### ISSUE TITLE
Add this specific plugin in phonegap build?

### ISSUE THREAD

**Issue by thedarkman123** [jeduan/cordova-plugin-facebook4#10]
Is there a way at all to use this one?

  < gap:plugin name="com.phonegap.plugins.facebookconnect" >
              < param name="APP_ID" value="" />
              < param name="APP_NAME" value="" />
    < /gap:plugin>

This is the old one, what i need to do to use this one?

**Comment by jeduan** [comment]
From #9 it looks like it's not working with pg build because they don't yet support `cordova-android` 4.0 which this plugin requires.

**Comment by jeduan** [comment]
related: http://community.phonegap.com/nitobi/topics/phonegap-build-does-not-support-gradle-builds
