### ISSUE TITLE
Update the doc: phonegap build supports gradle :)

### ISSUE THREAD

**Issue by yoav-zibin** [jeduan/cordova-plugin-facebook4#100]
Your documentation says:

Unfortunately, at this time PhoneGap Build is not supported on Android, since this plugin uses Gradle and PhoneGap Build does not support that yet

Well, not any more :)
I tested your plugin on phonegap build, and it works great!
https://github.com/yoav-zibin/phonegap-tictactoe/blob/gh-pages/www/config.xml#L104

The only things to remember, is to have:
    &lt;preference name="android-build-tool" value="gradle" /&gt;
AND
    &lt;preference name="android-minSdkVersion"      value="15" /&gt;

**Comment by jeduan** [comment]
Can you update the doc? I'll take a PR :)

**Comment by yoav-zibin** [comment]
This things always take longer than you thought :)
https://github.com/jeduan/cordova-plugin-facebook4/pull/101
