### ISSUE TITLE
Fix in Share

### ISSUE THREAD

**Issue by renanvs** [jeduan/cordova-plugin-facebook4#102]
Hi, I dont know how to contribute to project.

I found a problem in iOS when native app is installed and the share a url and image not appear in Share Dialog.
So in the **FacebookConnectPlugin.m** I add in *ShowDialog* method these line after 
> if (params[@"share_sheet"]) {
            dialog.mode = FBSDKShareDialogModeShareSheet;
        }

these 
>>if (params[@"share_sheet"]) {
            dialog.mode = FBSDKShareDialogModeShareSheet;
        }else if (params[@"share_feedBrowser"]) {
            dialog.mode = FBSDKShareDialogModeFeedBrowser;
        }

The **share_feedBrowser** property fix the normal share dialog.

Can someone add this in code and update read-me

Thanks

**Comment by Hirbod** [comment]
could you provide me what the updated Readme? @renanvs - just added your code into master branch

**Comment by grmmph** [comment]
If we're giving people the option to choose which dialog they want to show, why not having it all (in my opinion, the webFeed is much nicer)

```
if (params[@"share_sheet"]) {
            dialog.mode = FBSDKShareDialogModeShareSheet;
        } else if (params[@"share_feedBrowser"]) {
            dialog.mode = FBSDKShareDialogModeFeedBrowser;
        } else if (params[@"share_native"]) {
            dialog.mode = FBSDKShareDialogModeNative;
        } else if (params[@"share_feedWeb"]) {
            dialog.mode = FBSDKShareDialogModeFeedWeb;
        }
```

**Comment by grmmph** [comment]
https://github.com/jeduan/cordova-plugin-facebook4/pull/207

Nevertheless that doesn't really fix the issue that sharing a picture on a share dialog brings an empty dialog
