### ISSUE TITLE
Linker error on XDK

### ISSUE THREAD

**Issue by markomannux** [jeduan/cordova-plugin-facebook4#104]
Hi, I'm trying to build my app which uses cordova-plugin-facebook4 with intel XDK, but I'm getting this error:

ld: file is universal (4 slices) but does not contain a(n) armv7s slice: AIL Eventi/Plugins/cordova-plugin-facebook4/FBSDKLoginKit.framework/FBSDKLoginKit file 'AIL Eventi/Plugins/cordova-plugin-facebook4/FBSDKLoginKit.framework/FBSDKLoginKit' for architecture armv7s
clang: error: linker command failed with exit code 1 (use -v to see invocation)

any suggestion?

thanks

**Comment by jeduan** [comment]
Usually related to bitcode. Can yo disable it on your project and see if that helps?

**Comment by markomannux** [comment]
thanks for the reply.
I'm building with intel xdk, so i don't think I can disable bitcode. Maybe it's related to Facebook SDK version? Do you think it's safe to downgrade it?

**Comment by Hirbod** [comment]
Well, Bitcode works for me. My App has enabled Bitcode Support.

**Comment by markomannux** [comment]
With version 4.5.1 seems to build correctly. Do you think there could be compatibility issues by using this version of the SDK?

**Comment by jeduan** [comment]
How are you changing the SDK? Not sure how XDK works but if you're able to change that, you might be able to change the xcodeproj? 
Anyways. 4.5 might be deprecated but don't see it having problems until they remove access to graph API 2.4

**Comment by markomannux** [comment]
kind of a hack... I downloaded version 4.5.1 from facebook site and manually substituted directories under www\plugins\cordova-plugin-facebook4\src\ios. I don't think there's other way on XDK and I'm working on Windows, so no xcode available.

thanks

**Comment by karolszklarski** [comment]
I was just fighting with that problem too. It looks like armv7s architecture is dropped by Apple and is (probably) not required anymore, so it should be safe to not compile for that architecture. Cordova-ios guys has already removed it from default build, but I'm not sure in which version.

https://git-wip-us.apache.org/repos/asf?p=cordova-ios.git;a=blobdiff;f=bin/templates/scripts/cordova/lib/build.js;h=d5d50be93fa58013f941febd9a412c30fb2fbf0b;hp=2213ef8c548d1276c05f793df7fb497debad7ff3;hb=2765ada;hpb=df6929f83316f41bdd4b539fe5fdd54c28e187bc

Anyway, in my project I added after_prepare hook:
```
PROJECTDIR=$1
sed -i 's/armv7 armv7s arm64/armv7 arm64/g' $PROJECTDIR/platforms/ios/cordova/lib/build.js
```

**Comment by Hirbod** [comment]
thx @karolszklarski
