### ISSUE TITLE
AppInvite return null for both success and error AppInvite

### ISSUE THREAD

**Issue by PaulNguyen147** [jeduan/cordova-plugin-facebook4#105]
I have used the latest version of Cordova and IOS version. I have checked that the APP has successful sent and invitation but the returning value of successful function and error function is NULL 
could you please help me to check that?
thanks

**Comment by PaulNguyen147** [comment]
In addition, when I want to change the Facebook account after log out, the APP is still remember my old login user so I can't not change my account now !

**Comment by Hirbod** [comment]
this should be fixed in master, since my PR will make sure that the last token will be refreshed.

**Comment by jeduan** [comment]
And 1.5.0 was released with that fix. Did you upgrade?

**Comment by PaulNguyen147** [comment]
Yes, after update, It work well now. Thanks for your great support! 
and How could I log in with new fb account? The app has remembered my old user account and I could not really log out!

**Comment by Hirbod** [comment]
The Plugin can't manage cookies inside of SFSafariView. You need to use safari. Visit Facebook and log out. I know this sucks monkey balls but it is the only way to force a log out. Thanks to ATS

**Comment by PaulNguyen147** [comment]
@Hirbod  Up to now it's OK with me! Thanks so much!
