### ISSUE TITLE
Error - cannot show dialog

### ISSUE THREAD

**Issue by JerryBels** [jeduan/cordova-plugin-facebook4#106]
Hello,

I'm trying the basic example : 

```
facebookConnectPlugin.showDialog({
    method: "send",
    caption: "Check this out.",
    link: "http://example.com",
    description: "The site I told you about",
    picture: "http://example.com/image.png"
}, function(result) {
    // Success!
    $timeout(function () {
        $ionicLoading.hide();
    });
    console.log("success", result);
}, function(err) {
    // An error occured. Show a message to the user
    $timeout(function () {
        $ionicLoading.hide();
    });
    console.log("error - ", err);
});
```

And I get this error message : 

```
Cannot show dialog
```

I'm really not sure what's going on... And looking for a long time now without making any progress. Any help ?

I don't think it's linked but the permissions asked on login are

```
["public_profile", "email", "user_birthday"]
```

Thanks !

**Comment by JerryBels** [comment]
Bump !

**Comment by ikostic** [comment]
I tried same functionality. I am receiving error Code 202. I found this answer on net:

http://stackoverflow.com/questions/18573326/fb-ui-send-dialog-box-not-working-on-iphone

**Comment by lunchbag** [comment]
Bump.

This definitely used to work on both platforms! It still works on iOS, but not on Android. Any ideas?

Alternatively, if I change method from "send" to "share", it invokes the dialog. When it's "send", it says "Cannot open dialog" as an error.

**Comment by Skysurfer0110** [comment]
After several hours spent on this problem i found out that the plugin seems to require all of the fields in the  initialization options, at least for Android . I was missing "name" in the options object and the plugin returned the "cannot show dialog" error. 

Please update the example fro the "send" dialog....


var options={
                method: "send",
                caption: "Check this out.",
                href: "http://example.com",
                description: "The site I told you about",
                picture: "http://example.com/img.png",
                name: "My name"
            }

Now my problem is that i cant still find a way to specify the recipient  of the message.

**Comment by peterpeterparker** [comment]
Close, inactivity since 2016
