### ISSUE TITLE
"appInvite" seem not work in android 4.4.2

### ISSUE THREAD

**Issue by bau720123** [jeduan/cordova-plugin-facebook4#107]
I am using 1.5.0 version from npm
my code here

```
facebookConnectPlugin.appInvite(    
{
url: "http://www.littlebau.com/phonegap/invite.php",
picture: "http://36.media.tumblr.com/c066cc2238103856c9ac506faa6f3bc2/tumblr_nmstmqtuo81tssmyno1_1280.jpg"
}, 
.....
```

but when I use that，it will always said that
![screenshot_2016-01-03-15-17-01](https://cloud.githubusercontent.com/assets/5110085/12077702/80dd6872-b22d-11e5-8aaf-b02b16ff96f5.jpg)

but look at me source code
view-source:http://www.littlebau.com/phonegap/invite.php
it really have a "al:android:url" or a "al:ios:url" attribute
BTW，1.4.0 have no this issue

**Comment by vexsoluciones** [comment]
it worked for us in android , but is not working in ios :(

**Comment by bau720123** [comment]
hi @vexsoluciones 
are you using 1.5.0 version too ?

**Comment by bau720123** [comment]
hi @vexsoluciones 
for now I am using 1.6.3 version
https://www.npmjs.com/package/cordova-plugin-facebook4
but the appinvite still have some trouble with Android and iOS
just like above picture
any idea ?

**Comment by bau720123** [comment]
guys...
is there any idea or tell me what I am doing wrong ?

**Comment by bau720123** [comment]
hi @jeduan 
is this project still maintaince ?
if yes，could you give me some suggest

**Comment by 1N50MN14** [comment]
@bau720123 The error message says it all, your app link doesn't seem to be a valid universal link

**Comment by peterpeterparker** [comment]
Closed, `appInvite` doesn't exist anymore

https://github.com/jeduan/cordova-plugin-facebook4/issues/645
