### ISSUE TITLE
showDialog issue with 'apprequests' in iOS, also both callbacks not working

### ISSUE THREAD

**Issue by Ziv-Barber** [jeduan/cordova-plugin-facebook4#110]
My code:

```
    facebookConnectPlugin.showDialog ( {
        method: "apprequests"
        message: "test"
    } , function ( success ) {
        console.log ( JSON.stringify ( success ) );

    }, function ( error ) {
        console.log ( 'error: ' + error );
    });
```

For Android a FB dialog is opened.
For iOS noting happens.
Both callback functions never been called.
If I'm trying the 'share' method then now iOS displaying the dialog.
Again, the callback functions never been called.
It worked in the normal FB plugin.

**Comment by minhtc** [comment]
Same here, FB Dialog is opened but both callback functions never been called.

**Comment by glennsjostrom** [comment]
Same here. The dialog is not showing, instead I get the success callback running directly. Any ideas?

**Comment by JiDW** [comment]
Yes, same here too.

**Comment by glennsjostrom** [comment]
Solved it by using this fork: https://github.com/Telerik-Verified-Plugins/Facebook

**Comment by MoemenMostafa** [comment]
I have the same issue also

**Comment by MoemenMostafa** [comment]
@glennsjostrom but the fork you are referring to is still using Facebook SDK 3, we all use this fork because it implements SDK 4

**Comment by ChrisHSandN** [comment]
I also experienced an issue where no dialogue would show on iOS, I found the fix is to include the option actionType (even if its blank)

```
{
    method: "apprequests",
    message: "test",
    actionType: ""
}
```

**Comment by Ajaxy** [comment]
Thanks to @ChrisHSandN !

**Comment by jamesfdickinson** [comment]
I also had that issues on iOS, and my message needed to be url encoded.  

```
 facebookConnectPlugin.showDialog({
        method: "apprequests",
        message: encodeURI("I challenge you to a game of SPEED!"),
        actionType: "",
        filters: "app_non_users"
    });
```

**Comment by jespertheend** [comment]
I was having some issues with the apprequests dialog as well. But it's working now.
Make sure your object contains the `actionType` field. `action_type` is not working for some reason, even though that's used in the official javascript sdk. Also make sure all properties are of type string. I was using an integer in the `data` field.
Also, for some reason the iOS callback contains `request` with the request id, but android only contains `requestId` 🤦

**Comment by danieldanielecki** [comment]
@ChrisHSandN provided solution, this issue should be closed.

**Comment by peterpeterparker** [comment]
Coolio
