### ISSUE TITLE
login. 

### ISSUE THREAD

**Issue by alien3d** [jeduan/cordova-plugin-facebook4#111]
I try to install to 2 phone of mine.
1. Without facebook  -> nothing happen.
2. With facebook -> Open a popup saying "The parameter app_id is required.
This is part i try to put  variable appId='value' and also app_id="value"   before cordova.js still the same thing.
What is the proper login code to link, i might have something wrong.. What i do is 
function login

    function loginFacebook() {
            localStorage.setItem("social", "facebook");
            if (window.cordova.platformId == "browser") {
                facebookConnectPlugin.browserInit("number", "v2.0");
                // version is optional. It refers to the version of API you may want to use.
            }
            
          //  facebookConnectPlugin.browserInit("number");
            var fbLoginSuccess = function (userData) {
                console.log("UserInfo: ", userData);
            }

            facebookConnectPlugin.login(["public_profile"], fbLoginSuccess,
              function loginError(error) {
                  console.error(error)
              }
            );

        }

**Comment by jeduan** [comment]
Please install according to instructions

**Comment by alien3d** [comment]
1.your link instruction is missing so i follow the wizcorp original fork link
https://github.com/Wizcorp/phonegap-facebook-plugin/blob/master/platforms/browser/README.md
1. APP_ID i already used it the same with my portal site.
2.HASH 28 character also have been created. 
3.I'm using Visual Studio 2015 with Apache Cordova Tools. 

I need too knew are above java script is correct to login via facebook.
