### ISSUE TITLE
Multiple dex files define Landroid/support/v4/...

### ISSUE THREAD

**Issue by ArnaudValensi** [jeduan/cordova-plugin-facebook4#12]
Hi,
I ran into this error when I try to build:

```
 	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;
```

I think it is a conflict with another plugin.

I try to follow the following link, but it doesn't work.

http://stackoverflow.com/questions/20989317/multiple-dex-files-define-landroid-support-v4-accessibilityservice-accessibility?answertab=active#tab-top

**Comment by ArnaudValensi** [comment]
If in `platform/android/build.gradle` I change:
```
    compile "com.facebook.android:facebook-android-sdk:4.3.0"
```
by
```
    compile ("com.facebook.android:facebook-android-sdk:4.3.0") {
        exclude module: 'support-v4'
    }
```

I can make it working by building using `gradle build`.

But when I use `cordova build android` the `build.gradle` file is overweritten.

Any idea ?

**Comment by jeduan** [comment]
Hi, as specified in #11 the only workaround I know is forking the plugin and making it support gradle. Check out this commit to see how. https://github.com/jeduan/cordova-plugin-push-notification/commit/79ea57bf8754f67b06e8aba571f6dc3845190390

**Comment by Deminetix** [comment]
FYI I had a similar issue except the dex error was:

    Multiple dex files define Landroid/support/annotation/AnimRes

I also think its another plugin conflicting with this one. I fixed it by adding this to the bottom of my `build.grade`:

    configurations { all*.exclude group: 'com.android.support', module: 'support-v4' }

I don't know what this does or why it works, but it works and it doesn't break any functionality of existing plugins (atleast in my quick tests)

My current plugins are below but i'm not sure which one is causing the conflict:

    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "com.ionic.keyboard",
    "cordova-plugin-statusbar",
    "cordova-plugin-camera",
    {
      "locator": "https://github.com/Deminetix/phonegap-plugin-push.git",
      "id": "phonegap-plugin-push"
    },
    {
      "locator": "https://github.com/jeduan/cordova-plugin-facebook4.git",
      "id": "cordova-plugin-facebook4",
      "variables": {
        "APP_ID": "XXXXXXXX",
        "APP_NAME": "XXXXXX"
      }
    },
    "cordova-plugin-google-analytics@0.7.1",
    "cordova-plugin-inappbrowser",
    "cordova-plugin-appavailability"
