### ISSUE TITLE
does version 1.2.2 support in ios9 ?

### ISSUE THREAD

**Issue by roysG** [jeduan/cordova-plugin-facebook4#124]

**Comment by jeduan** [comment]
Why version 1.2.2?

**Comment by roysG** [comment]
As i understood from user in this version there is not the problem of build failed.

https://github.com/jeduan/cordova-plugin-facebook4/issues/123#issuecomment-179417100

**Comment by roysG** [comment]
Please tell me if i can work with version 1.2.2 with ios >= 9
