### ISSUE TITLE
User cancelled dialog error everytime

### ISSUE THREAD

**Issue by zaggaz** [jeduan/cordova-plugin-facebook4#125]
Whenever I use a lollipop or higher device, login always returns 4201 User cancelled dialog.

I've checked my hashes and they seem fine as it works with Wizcorp/phonegap-facebook-plugin. However the Wizcorp/phonegap-facebook-plugin doesn't work with the official push plugin due to build issues.

Any help on this would be great! The android version i'm using is 5.1.1.

**Comment by jeduan** [comment]
Please post the dialog you're using.

**Comment by zaggaz** [comment]
`_fbLogin(birthdayStr) {
    facebookConnectPlugin.login(
      ['email', 'public_profile', 'user_birthday'],

      (response) => {

        facebookConnectPlugin.api(
          '/me?fields=id,birthday,gender,first_name,age_range,last_name,name,picture.width(400),email',
          [],
          x => this._handleSuccessfulFbResponse(x, birthdayStr),
          x => this.setState({status: 'login failed'}),
        );

    }, (response) => {
        console.log(response);
    });
  }`

I'm using whichever version npm gives me, the plugin.xml shows this:
<plugin xmlns="http://apache.org/cordova/ns/plugins/1.0"
        xmlns:android="http://schemas.android.com/apk/res/android"
        id="cordova-plugin-facebook4"
        version="1.4.1">

lollipop 5.1.1 - oneplus two is the device that's getting this problem

**Comment by zaggaz** [comment]
Ok, I've found a solution to this. It seems that I need to delete the app and install it again in order for the facebook login to work. I have no idea why, but running straight away doesn't seem to work. I presume it's something to do with the hash keys. Thanks though, I'll update if I find out more!

**Comment by dbroadhurst** [comment]
I'm seeing the same issue even with a fresh test app. 

```
cordova create, cordova add platform android etc
```

See login screen and looks like I successfully login but I get an error response

```
error Object {errorCode: "4201", errorMessage: "User cancelled dialog"}
```

**Comment by dayaki** [comment]
am having this same error: error Object {errorCode: "4201", errorMessage: "User cancelled dialog"}

anyone been able to fix it?

**Comment by gauravsaini03** [comment]
Any updates on this ?

**Comment by dayaki** [comment]
Upgrading to the lastest version fixed this for me

**Comment by jorgemejia** [comment]
I had the same problem, my solution was on the login method, I made the request for all the permissions I want to use in that method.

**Comment by Findiglay** [comment]
Experiencing the same issue currently.

@jorgemejia could you elaborate at all on what your solution was?

**Comment by jorgemejia** [comment]
I´m Working in Android 5.01 and works fine, but in iOS 9.3.2 I have the same problem, I had to modify the plugin, because the login method is executed twice, I had to debug the login method and I realized have to validate if the method was executed. I don´t know if this is correct but it works fine to me.

Also if the user reject one of the permission, the app throws the dialog user cancelled, it is important to request all the permissions you need in the login method, because if you are logged in and you only request the public profile, Facebook asumes you only need that information, so if you request for example the birth day but in the login you dont request that permission, Facebook response with bad request, and thats why the app shows the dialog, user cancelled.

```
- (void)login:(CDVInvokedUrlCommand *)command {
    BOOL launch = false;
    NSLog(@"Starting login");
    CDVPluginResult *pluginResult;
    NSArray *permissions = nil;

    if ([command.arguments count] > 0) {
        permissions = command.arguments;
    }
    
    // this will prevent from being unable to login after updating plugin or changing permissions
    // without refreshing there will be a cache problem. This simple call should fix the problems
    [FBSDKAccessToken refreshCurrentAccessToken:nil];

    FBSDKLoginManagerRequestTokenHandler loginHandler = ^void(FBSDKLoginManagerLoginResult *result, NSError *error) {
        if (error) {
            // If the SDK has a message for the user, surface it.
            NSString *errorMessage = error.userInfo[FBSDKErrorLocalizedDescriptionKey] ?: @"There was a problem logging you in.";
            CDVPluginResult* pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_ERROR
                                                              messageAsString:errorMessage];
            [self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];
            return;
        } else if (result.isCancelled) {
            CDVPluginResult *pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_ERROR
                                                              messageAsString:@"User cancelled."];
            [self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];
        } else {
            CDVPluginResult *pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK
                                                          messageAsDictionary:[self responseObject]];
            [self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];
            return;
        }
    };

    // Check if the session is open or not
    if ([FBSDKAccessToken currentAccessToken] == nil) {
        // Initial log in, can only ask to read
        // type permissions
        if (permissions == nil) {
            permissions = @[];
        }
        if (! [self areAllPermissionsReadPermissions:permissions]) {
            pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_ERROR
                                             messageAsString:@"You can only ask for read permissions initially"];
            [self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];
            return;
        }

        if (self.loginManager == nil) {
            self.loginManager = [[FBSDKLoginManager alloc] init];
        }
    
        [self.loginManager logInWithReadPermissions:permissions fromViewController:[self topMostController] handler:loginHandler];
        return;
    }


    if (permissions == nil) {
        // We need permissions
        NSString *permissionsErrorMessage = @"No permissions specified at login";
        pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_ERROR
                                         messageAsString:permissionsErrorMessage];
        [self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];
        return;
    }
    
    if(!launch){
        [self loginWithPermissions:permissions withHandler:loginHandler];
        launch = YES;
    }
}
```

**Comment by marfire** [comment]
It seems clear from this issue (and the [parallel one](https://github.com/Wizcorp/phonegap-facebook-plugin/issues/1063) in the original repository) that this is kind of a catch-all error for a variety of problems.

Just to add my experience: I got this error as a result of sending a bad app id. Correcting that fixed the problem.

As a debugging note, be sure to check the Android log (via DDMS, or whatever). That's where I was able to see the detailed exception that indicated the specific problem.

**Comment by souly1** [comment]
Just so it will be mentioned here as well, my issue was with the "singleInstance" being set for android.
Mentioned in original wizcorp plugin issues:
https://github.com/Wizcorp/phonegap-facebook-plugin/issues/915

**Comment by arijan108** [comment]
For the past couple of days I had trouble getting anything to work at all (I am working in Construct 2, using Cranberrygames Phonegapp), and in XDK the jeduan facebook4 plugin. After solving everything from multidex errors and hash-keys, the final problem I was facing was this exact issue. After a couple of days of non-stop overthinking, I finally solved my problem with this one.

I can't guarantee it will work for you, however, it's worth the try. What I did is to lower the version of the plugin, and I wanted to test each, but turns out the version 1.3.0 worked just fine for me, so I stuck with that. You may or may not solve your problem with this, but another thing I did (that may or may not have helped getting the thing to work) is that I have assigned the "login" AND the "get permission" request together after clicking the button you assign.

I hope this helps.

**Comment by johnbolsberg** [comment]
i have the same error 

> Object {errorCode: "4201", errorMessage: "User cancelled dialog"}

that's my facebooklogin function in ionic 2
`  facebookLogin(){
    Facebook.login(['email']).then( (response) => {
      let facebookCredential = firebase.auth.FacebookAuthProvider
          .credential(response.authResponse.accessToken);

      firebase.auth().signInWithCredential(facebookCredential)
          .then((success) => {
            console.log("Firebase success: " + JSON.stringify(success));
            this.userProfile = success;
          })
          .catch((error) => {
            console.log("Firebase failure: " + JSON.stringify(error));
          });

    }).catch((error) => { console.log(error) });
  }

who can help?`

**Comment by Rondeus** [comment]
I was facing the same issue and the problem was with a wrong field name on the Graph API method.

In this case we were passing "?fields=email,name,user_birthday,picture.width(200).height(200)" where user_birthday is not valid. Graph API returns an error and the the plugin returns it as 4201.

You may check this as well.

**Comment by olixis** [comment]
The problem is with ionic plugin add!!!!

ionic plugin add cordova-plugin-facebook4 --save --variable APP_ID="myid" --variable APP_NAME="meuname" bugged.

 cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="myid" --variable APP_NAME="myname" works!

**Comment by 64jcl** [comment]
(Repost my comment from another thread here as its related)

Ok, we came across this issue as well once just now and it is very likely related to a change in user permissions / scope that was initially accepted by the user on the first login. If you then go and change the permissions and try to log in again, Ionic2 will for a brief moment try to login and show a facebook page which is immediately dismissed and returns the response errorCode: 4201 - errorMessage: User cancelled dialog.

I would assume that if there is a mismatch of permissions a user would have to accept a different set of permissions somehow? Perhaps this is missing in the cordova plugin? At present it seems the only way to adjust the permissions is to register a new application in Facebook and change the app to use a different APP_ID.

Perhaps anyone can help out with this?

**Comment by v3ss0n** [comment]
happening after lastest update , it was all fine before.

**Comment by walfridosp** [comment]
+1

**Comment by v3ss0n** [comment]
@walfridosp  we did that , it won't help . tried clearing all the info , including resetting facebook data. Nothing happens

**Comment by dpaksoni** [comment]
+1, same error here. Any update?

**Comment by walfridosp** [comment]
@v3ss0n
Yes, actually it works only the first time after clearing data and cache, after that it shows the dialog again.

**Comment by dpaksoni** [comment]
Tried creating a new cordova project and then added plugin in that. It worked. But not in already existing project. Could not detect the issue.

**Comment by v3ss0n** [comment]
hi , the problem is with android 4.4.4
latest version cannot be logged in on android 4.4.4

please help it is important to support android 4.4.4 

@jeduan  please can you look into it..

**Comment by v3ss0n** [comment]
android < 4.4.4 dosen't work.

**Comment by oleksiy-nesterov** [comment]
in this case just call facebookConnectPlugin.getLoginStatus to prevent the situation
```javascript
var getLoginStatus = function(){
    window.facebookConnectPlugin.getLoginStatus(
        function(data){
            if(data.authResponse){
                self.oauthDataFB = {
                    expires      : data.authResponse.expiresIn,
                    access_token : data.authResponse.accessToken
                };
            }else{
                self.oauthDataFB = null;
                getLoginError({errorCode:4201});
            }
        },
        function(e){
            getLoginError(e);
        }
    );
};

window.facebookConnectPlugin.login(
    permissions,
    function(){
        getLoginStatus();
    },
    function(e){
        if(e.errorCode == 4201 && $agent.osLowerCase === 'android'){ // <--- the solution
            getLoginStatus();
        }else{
            getLoginError(e);
        }
    }
);
```

**Comment by gattex** [comment]
Any news  for this issue ? It's not working for android <= 4.4. Any pr??

**Comment by v3ss0n** [comment]
interesting @oleksiy-nesterov  going to give a try.

**Comment by gattex** [comment]
It's working for me now!.  I founded that this plugin is incompatible with *cordova-plugin-background-mode*  for android  version <= 4.4.
Thanks for all.

**Comment by adesst** [comment]
in your config.xml add this

<preference name="AndroidLaunchMode" value="singleTop" />

i found that after adding the pref, the background-mode and facebook4
working fine in my Xiaomi2 android 4.4.4

**Comment by lincolnthree** [comment]
Changing the "AndroidLaunchMode" preference in config.xml did indeed solve my problems with this (thanks @adesst): 

```
-  <preference name="AndroidLaunchMode" value="singleInstance"/>
+  <preference name="AndroidLaunchMode" value="singleTop"/>
```

This can have a few side-effects, so read up before you switch, and decide if it's for you. E.g. Your app will potentially have multiple instances open at once, which is sometimes not a great thing.

https://developer.android.com/guide/topics/manifest/activity-element.html#lmode

**Comment by jwiesmann** [comment]
Today i had the same problem (using ionic2 / fb-plugin). It looks like the demo / example on the ionic page is not correct and that causes the issue. Indeed, the error could be a bit more specific, but what i think it causes it, is the following: (thx to @Rondeus)

Example from the Ionic page: 
`this.fb.login(['public_profile', 'user_friends', 'email'])`

If you check the Graph API from Facebook
<img width="590" alt="screen shot 2017-09-03 at 22 46 27" src="https://user-images.githubusercontent.com/7863773/30004000-db299c5e-90f9-11e7-9888-675f759a0e77.png">

You will see, that there is no such thing like
**public_profile**
after i changed it according to the fb-api
`this.fb.login(['user_about_me', 'email', 'user_birthday'])`
It works like expected. Hope it helps someone!

**Comment by Kavenon** [comment]
For me it was caused by not adding user as tester of facebook application. It was hard to find, because it sometimes failed with "User cancelled dialog" message and sometimes without any message.

**Comment by rolinger** [comment]
I am getting this error too.  It looks like I am able to login successfully...but I get the error when trying to do a post.  Just before the post I am checking login status with :+1: 

```
      facebookConnectPlugin.getLoginStatus(
        function(response) {
          console.log("LoginStatus") ;
          console.log(response) ;
        }
      ) ;
      
      facebookConnectPlugin.showDialog(
        fbObj, 
        function (response) {  // success
          console.log("success") ;
          console.log(response) ;
          },
        function (error) { // failure 
          console.log("error") ;
          console.log(error) ;
          } 
      ) ;
```

Login status responds with "connected" and all the tokens, expire, session data....so my issue must be related to actually trying to post something.

Any ideas?

**Comment by rolinger** [comment]
@zaggaz - I tried what you did...deleted my app and reinstalled but that didn't change my situation.  I am still getting that error when trying to post things to users FB page.  My login/auth appears to work.

**Comment by jwiesmann** [comment]
Did you see this here?

> A User access token with the **user_posts** permission.
(Check https://developers.facebook.com/docs/graph-api/reference/v2.11/post for more info)

Meaning at your login you will need to add that permission like so: 
`this.fb.login(['user_about_me', 'email', 'user_birthday', 'user_posts'])`

Greetings...

**Comment by rolinger** [comment]
@jwiesmann - thanks for the input.  I added `user_posts` to my login function and it did not change the outcome.   I still continue to get the 4201 error:

```
LoginStatus: (at login)
 {status: "connected", authResponse: {…}}authResponse: {accessToken: "EAAMGv5AERbUBAImkwZC4gE8x8BTnwEvGxRw2M2TWrfnzOVZC5…", expiresIn: "5115705", session_key: true, sig: "...", userID: "10154000....."}status: "connected"__proto__: Object
 ErrorStatus: (at posting msg to users fb page):
 {errorCode: "4201", errorMessage: "User cancelled dialog"}
```

**Comment by rolinger** [comment]
I finally got it figured out.  It was a combo of my hash key being wrong and passing the wrong parameters to the `method:feed`

**Comment by wkaskie** [comment]
I have a fresh Ionic App, no customizations except the facebook4 plugin. It doesn't work. I get the same response, "user cancelled" as the error from the then/catch. I'm also using the sample code from the readme.

`  "dependencies": {
    "@angular/common": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@ionic-native/core": "^5.22.0",
    "@ionic-native/facebook": "^5.22.0",
    "@ionic-native/splash-screen": "^5.22.0",
    "@ionic-native/status-bar": "^5.22.0",
    "@ionic/angular": "^5.0.0",
    "cordova": "^9.0.0",
    "cordova-android": "^8.1.0",
    "cordova-ios": "^5.1.1",
    "cordova-plugin-facebook4": "^6.2.0",
    ...
}`

**Comment by adesst** [comment]
> I have a fresh Ionic App, no customizations except the facebook4 plugin. It doesn't work. I get the same response, "user cancelled" as the error from the then/catch. I'm also using the sample code from the readme.
> 
> Error in X-Code is:
> 
> `-canOpenURL: failed for URL: "fbauth2:/" - error: "The operation couldn’t be completed. (OSStatus error -10814.)`
> 
> Basic setup:
> 
> ```
>     "@angular/common": "~8.2.14",
>     "@angular/core": "~8.2.14",
>     "@angular/forms": "~8.2.14",
>     "@angular/platform-browser": "~8.2.14",
>     "@angular/platform-browser-dynamic": "~8.2.14",
>     "@angular/router": "~8.2.14",
>     "@ionic-native/core": "^5.22.0",
>     "@ionic-native/facebook": "^5.22.0",
>     "@ionic-native/splash-screen": "^5.22.0",
>     "@ionic-native/status-bar": "^5.22.0",
>     "@ionic/angular": "^5.0.0",
>     "cordova": "^9.0.0",
>     "cordova-android": "^8.1.0",
>     "cordova-ios": "^5.1.1",
>     "cordova-plugin-facebook4": "^6.2.0",
>     ...
> }```
> ```

You could check your AndroidManifest.xml
if android:launchMode is set to "singleTop"

<application ... >
  <activity 
     **android:launchMode="singleTop"**
  ...
  </activity>
</application>

if not set, then please check your config.xml

Another approach you could try is:
1. Manually set AndroidManifest.xml like given example
2. from platforms/android dir you do
   $ ./gradlew assembleDebug
3. Run the compiled in a device
4. Let us know if it works

tq

**Comment by wkaskie** [comment]
Hi Team! I was able to get this working by "starting over". apparently, something was off in my environment.  so I 
1. Followed some instructions for completely wiping node and nvm from the system. 
2. Did a fresh nvm installation
3. nvm install 12 (to get node back)
4. `npm i `on the project
5. remove facebook4
6. remove ios
7. Finally, did a  fresh install of the plugin and ios.  Working as expected now....for ios, at lease

**Comment by nikky778** [comment]
For signup process login with Facebook is working. But after login i need some more permissions from user. i.e "manage_pages" permission in order to get user's Instagram business account info which i need to get on a different page(Not on the signup page).In order to get Instagram basic info we need to login again with Fb in order to get required permissions. But every time i get the same error " 4201 : user cancelled dialog ". Code is working fine on ios , issue is with android only 
I am using the code  below(On a different page where i need permissions and Instagram business account linking):

return this.fb.login(['manage_pages']).then((res) => {
        return this.fb.login(['email', 'public_profile', 'instagram_basic', 'pages_show_list', 'instagram_manage_insights']).then((res) => {

}).catch((err) => {
          // this.loadingService.hide();
          this.presentToast("Something went wrong !");
        });

      }).catch((err) => {
         alert(JSON.stringify(err));
        this.presentToast("Something went wrong !");
      });

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out the actively maintained fork `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect. If you're still experiencing issues, feel free to log an issue with more details there.
