### ISSUE TITLE
POSTing to the graphApi

### ISSUE THREAD

**Issue by dantabel** [jeduan/cordova-plugin-facebook4#131]
At the moment you can only send GET requests to the the Graph API. In order to post you need to use the Dialog. In some circumstances it is preferable to POST directly to the Graph API rather use the dialog.

It's fairly simple to add this functionality and I have cloned your repo and done it myself, but I don't think I have done it in the most efficient way. I have just simply duplicated all the current GET functionality and tweaked it to POST instead. Here's my changes incase they're helpful to someone else:
https://github.com/dantabel/cordova-plugin-facebook4

**Comment by jeduan** [comment]
That's a good approach, tho probably having a method parameter that sets the HTTPMethod would be cleaner.

**Comment by hlehmann** [comment]
Any updates on this ?

**Comment by monxas** [comment]
Can someone add this functionality to this repo? Dantabels is not updated and I'm having some errors there, but I need the POST option...

**Comment by jorgemejia** [comment]
I have a Code for do that on iOS and Android
[ios function.txt](https://github.com/jeduan/cordova-plugin-facebook4/files/284853/ios.function.txt)
[android functions.txt](https://github.com/jeduan/cordova-plugin-facebook4/files/284854/android.functions.txt)

**Comment by blckshrk** [comment]
Hey,

I propose an implementation in this PR https://github.com/jeduan/cordova-plugin-facebook4/pull/289. This is for iOS only, for now, but could be easily adapted for Android (I just don't have the time for now).

Alex

**Comment by noahcooper** [comment]
This plugin is deprecated. See `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect. That plugin supports POST and DELETE requests when using the `api` method.
