### ISSUE TITLE
Nothing happens on native ios app

### ISSUE THREAD

**Issue by swipeitfwd** [jeduan/cordova-plugin-facebook4#132]
Hi,

I am new in ionic and cordova. I was  using the original version of this plugin and used to work ok. The other day I was testing on my phone and nothing was working. Clicking the button doesn't trigger the native app or the safari login view.

I upgraded to this plugin (old plugin completely removed). I updated plist file with the proper ATS requirements. When i build and run my app all I see n Xcode's console is Starting Login but nothing else happens. I've been banging my head against this and nothing is working !!

**Comment by jeduan** [comment]
Maybe delete platforms and plugins and try again? Lots of people have success with the plugin. Hope you will too.

**Comment by swipeitfwd** [comment]
it's weird because it used to work with the original/older plugin. i did delete the previous plugin and platforms and re-added everything from scratch. i even tested with in-app-browser plugin and without still no luck.

Here's the code i am using to trigger login, is there anything worng? WOuld appreciate the help

```
    function fbLogin() {

      // Ask the permissions you need. You can learn more about
      // FB permissions here: https://developers.facebook.com/docs/facebook-login/permissions/v2.4
      facebookConnectPlugin.login(['email', 'public_profile', 'user_friends', 'user_birthday',
        'user_hometown', 'publish_actions', 'user_location'], function (response) {
        console.log(response);
        alert("Sign in Ok");
      }, function (error) {alert("something went wrong");});
    }
```

**Comment by swipeitfwd** [comment]
it works fine in the browser btw

**Comment by wmendes** [comment]
Any developement on this? I have the same problem here.

**Comment by swipeitfwd** [comment]
i wasted my time enough so i switch to OpenFB library instead. not the cleanest but until i get some solution here i am moving on

**Comment by swipeitfwd** [comment]
i just wanted to mention that this is working. i had to update my cordova thats all

**Comment by sbayegan** [comment]
Hi, I'm having the same problem. Nothing happends after "Starting login"! Please let me know if there is a solution.
