### ISSUE TITLE
Get musics users

### ISSUE THREAD

**Issue by atiladelcanton** [jeduan/cordova-plugin-facebook4#133]
personnel, need some help.

I'm trying to get the songs of users on Facebook in this way:

```javascript
facebookConnectPlugin.api('/'+user.id+'/music', null, function(music)
               {
                  console.log('--- music ---');
                  console.log(music);
               },function(failure){
                  console.log(failure);
               });
```

however it does not return anything to me, is there any other way?

**Comment by Hirbod** [comment]
well you need the permission first before accessing

**Comment by atiladelcanton** [comment]
I need to create a test application and then release the facebook correct?
