### ISSUE TITLE
Re-request permissions on iOS Native

### ISSUE THREAD

**Issue by sstakoff** [jeduan/cordova-plugin-facebook4#136]
When a user declines a subset of permissions requested, how can you re-request permissions at a later time? The facebook documentation indicates that you need to pass auth_type: 'rerequest' to the login function. Looks like this is handled in the browser implementation, but I don't see anything in the native iOS implementation. Any ideas???

**Comment by jeduan** [comment]
There's this code https://github.com/jeduan/cordova-plugin-facebook4/blob/master/src/ios/FacebookConnectPlugin.m#L374-L406 but you're right that there's no specific method for re-requesting permissions directly. I'll take a PR if you want to take a stab at it.

**Comment by ioniccode** [comment]
Hi @jeduan, if yo add rerequest option it will be wonderful. At least for me. I'm looking for it last 2 days, i don't want back to default apache plugin.

**Comment by mangacu** [comment]
This issue was resolved?

**Comment by snakeman21** [comment]
Any word on this? Certainly a very important feature, as every production mode app needs to be able to rerequest permissions.

**Comment by gerwinbrunner** [comment]
Is there an update on this? @jeduan

**Comment by allanpoppe** [comment]
Any news? =/

**Comment by dhruvwo** [comment]
I am still having this issue any update on this?

**Comment by jeduan** [comment]
This project is deprecated as per the README. There are active forks listed there.
