### ISSUE TITLE
New plugin install saves wrong plugin version in config.xml

### ISSUE THREAD

**Issue by ilyakar** [jeduan/cordova-plugin-facebook4#139]
<plugin name="cordova-plugin-facebook4" spec="~1.4.1">

Even though I am installing plugin v1.6.1. Reinstalling plugins will attempt to fetch facebook4 version 1.4.1.

(Honestly I don't see the point of manipulating config.xml, I would leave it as it is)

**Comment by jeduan** [comment]
Thanks! Pushed v1.6.2 that fixes this.
