### ISSUE TITLE
login and api return ONLY id and name

### ISSUE THREAD

**Issue by balicekt** [jeduan/cordova-plugin-facebook4#14]
Facebook docs says that public_profile should return these items: 
id
name
first_name
last_name
age_range
link
gender
locale
timezone
updated_time
verified

but I'm tried almost everything and I'm getting only id and name nothing else. Does enyone know why? 

I also tried put instead of 'public_profile' -> 'email' but I get laso id and name. Really don't understand. 

Thank for any help.

**Comment by jeduan** [comment]
This is the way it works to be consistent in all platforms. You need to call the graph API endpoints, for example calling `graphApi('/me')` to retrieve all the information you need.

**Comment by balicekt** [comment]
Thank you for ansfer :) yes I have it like this: 

    self.getData = function () {
        facebookConnectPlugin.api('/me',["email"], function (data) {
            alert("data: "+JSON.stringify(data));
            $scope.$apply(function () {
                $scope.fb_data = data;
                $scope.isLoggedIn = true;
            });
        }, function (data) {
            alert("error: " + JSON.stringify(data));
        });
    };

And still I'm getting just id and name. Really don't understand why :(

**Comment by balicekt** [comment]
oh, finally I found out the mistake is has to be like this: 

facebookConnectPlugin.api('/me?fields=first_name,email,last_name,age_range',['public_profile, email'], function (data) {....

but still thanks for help

**Comment by jeduan** [comment]
Thanks, glad you could resolve
