### ISSUE TITLE
Incomplete API

### ISSUE THREAD

**Issue by dbroadhurst** [jeduan/cordova-plugin-facebook4#140]
I'm looking for a way to show a dialog so the user can post a message. I can login successfully but I don't see a showDialog method in the window.CordovaFacebook object.

![screen shot 2016-02-15 at 8 11 21 am](https://cloud.githubusercontent.com/assets/5667105/13054022/418e6224-d3bc-11e5-9afb-610e7189807c.png)

**Comment by jeduan** [comment]
We don't export the `CordovaFacebook` object so that makes sense. It's `window.facebookConnectPlugin`

**Comment by dbroadhurst** [comment]
I'm pretty confused. There's two API objects? I don't see window.facebookConnectPlugin.
