### ISSUE TITLE
cordova plugin rm cordova-plugin-facebook4 fails with cordova-ios@4.0.1 platform

### ISSUE THREAD

**Issue by xmnboy** [jeduan/cordova-plugin-facebook4#141]
You can add the plugin but you cannot remove it. If you attempt to remove you get the following error message and the plugin is not removed from the `/plugins` directory:

> `Error: Cannot read property 'buffer' of undefined`

This causes particularly nasty problems for Intel XDK users because they are not using the CLI directly. We would like to make this a featured plugin in our next release, but because we are relying on cordova-ios@4.0.1 as the "base" platform in that release we are unable to, until this issue is resolved.

**Comment by jeduan** [comment]
I've seen this. Any idea on how to fix it?

**Comment by xmnboy** [comment]
Wish I knew! I'll see if one of our local CLI experts might have a clue.

**Comment by fredgalvao** [comment]
That is an [issue with cordova](https://issues.apache.org/jira/browse/CB-7781). I've seen it happen quite often in a certain cordova-cli version from the past I don't remember, specially when I was trying to reinstall plugins loaded through git urls directly, or simply those which were not core cordova plugins. Re-trying the command always worked. Or you can upgrade cordova and get it fixed most surely :wink:

**Comment by sebrojas14** [comment]
I have the last cordova version and still fails. Is failing with the last version of the plugin

**Comment by xmnboy** [comment]
We looked at the Cordova recommended fixes and they did not help to resolve this problem. The only workaround that I have found to be reliable is to remove all platforms and then remove the plugin. Of course, you then have to add the platforms back to make things work again. Attempting to remove the plugin twice does not work.

**Comment by sebrojas14** [comment]
Yes, I have to remove platforms, then remove plugin, add platforms and after that add the plugin

**Comment by FarhanSaleem** [comment]
I had the same issue couldnt remove the platform or the plugin...really frustrating. I ended up running cordova plugin add <--plugin--> --save and this updated the plugin to the latest version...hope this helps someone
