### ISSUE TITLE
Why app invite returns just didComplete?

### ISSUE THREAD

**Issue by BojDom** [jeduan/cordova-plugin-facebook4#143]
I was exited for a plugin that invites friends also for non game apps, than i've implemented this and what i saw once i've done it? i can't see who the user has invited :(
I need this feature since in my app i give the users some rewards if they invite different amount of friends but seems that with this plugin in impossible ... please fix this

**Comment by BojDom** [comment]
Ok it's because facebook does not provide this info with the latests sdk, is there any workaround to retrieve how many friends someone has invited?

**Comment by Hirbod** [comment]
Nope
