### ISSUE TITLE
facebookConnectPlugin undefined

### ISSUE THREAD

**Issue by riskmanagerjeff** [jeduan/cordova-plugin-facebook4#146]
Ive added the plugin, but the facebookConnectPlugin object is undefined.  Any idea what might cause this?  Im on cordova 6.

Side note, im also unable to remove the plugin, but I've noted in another issue that its perhaps an issue with the CLI.

**Comment by riskmanagerjeff** [comment]
I'll close this issue.  My 'fix' to this was to rebuild the project from scratch, then re-add each plugin on its own.  I suspect that the issue that caused the inability to remove the plugin is related, but I cannot confirm.

**Comment by sebrojas14** [comment]
I'm having this problem, I'm hopeless, please help, something change?
