### ISSUE TITLE
iOS - Error: Can't find variable: facebookConnectPlugin

### ISSUE THREAD

**Issue by sebrojas14** [jeduan/cordova-plugin-facebook4#147]
No mater whata I do, I always get this error on IOS with cordova 6.0.0 and Cordova iOS 4.0.1. I tried everithing on trobleshoting section but I got the same. All in build phases looks good. On /platforms/ios everything looks good also, please help

**Comment by kraskoshnyy** [comment]
The same...

**Comment by mikepsinn** [comment]
Me, three.

**Comment by xAt0mZ** [comment]
Had the problem when fetching plugin with config.xml.

I just added the plugin through CLI :  [ ionic / cordova plugin add cordova-plugin-facebook4 --variable APP_ID="01234567890" --variable APP_NAME="MyAppName" ]

Plugin saved in package.json so you can just prepare for ios [ ionic / cordova prepare ios ] then build app with XCode.

Using Cordova 6.1.1 and cordova-ios 4.1.1 (maybe upgrading both can fix problems).

**Comment by mikepsinn** [comment]
Always running `ionic state reset` before removing and re-adding the plugin solved it for me.

**Comment by blckshrk** [comment]
Same problem, no solution found...

```
Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic CLI Version: 1.7.15
Ionic App Lib Version: 0.7.2
ios-deploy version: 1.8.4
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v4.2.6
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by blckshrk** [comment]
The solution was pretty simple... missing `deviceready` listener around.
```js
document.addEventListener('deviceready', function () { 

}, false);
```

**Comment by JS-12** [comment]
I have the same problem, some one found a solution ?

**Comment by blckshrk** [comment]
@JS-12 Did you try mine ?

**Comment by arielbrizi** [comment]
@blckshrk  where did you write  that?

document.addEventListener('deviceready', function () { 

}, false);

I have the same problem

**Comment by blckshrk** [comment]
@arielbrizi You have to surround the code using `facebookConnectPlugin` with `addEventListener` callback to wait until the device is ready (the native code to be ready, so you can use the Cordova plugins).

Dummy example : 
```js
document.addEventListener('deviceready', function () {
    facebookConnectPlugin.getLoginStatus(
        function (response) {
            // DO SOMETHING
        },
        function (error) {
            // HANDLE ERRORS
        }
    );
}, false);
```

**Comment by arielbrizi** [comment]
@lckshrk i have the same problem. I am testing in the cxode IOS simulator. The extrange is the error happened on de controller.js invocation, but not in index.html, with your code.

I put it in the index.html, is it correct?
......

 <body ng-app="app" animation="slide-left-right-ios7">

<script>
    
    document.addEventListener('deviceready', function () {
                              alert("1");
                              facebookConnectPlugin.getLoginStatus(
                                                                   function (response) {
                                                                   // DO SOMETHING
                                                                   alert("2");
                                                                   },
                                                                   function (error) {
                                                                   // HANDLE ERRORS
                                                                   alert("3");
                                                                   console.log(error);
                                                                   }
                                                                   );
                              }, false);

</script>

  <div>

  <div id="fb-root"></div>

......

**Comment by blckshrk** [comment]
@arielbrizi Please put your code between ``` to allow syntax highlighting.

I can't tell you what is missing right now. Could you provide a public repo with your code ? But, anyway, this isn't a plugin bug imo. It seems to be a problem in your code.

**Comment by arielbrizi** [comment]
I resolved it with

npm install -g cordova ionic
