### ISSUE TITLE
whats the android className which should be mentioned in fb dev console ?

### ISSUE THREAD

**Issue by ituhin** [jeduan/cordova-plugin-facebook4#148]
can someone please mention the class name - which needs to be mentioned in android section in facebook developer console ?

it will be easier if its mentioned in the wiki or readme.

Thanks

**Comment by jeduan** [comment]
CordovaActivity IIRC. You can figure it out by looking at AndroidManifest.xml in platforms/android

**Comment by ituhin** [comment]
Sorry man, zero android experience.
could not found anything called CordovaActivity in AndroidManifest.xml

found - com.facebook.FacebookActivity

<activity android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation" android:label="@string/fb_app_name" android:name="com.facebook.FacebookActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar" />

and - android.intent.action.MAIN

<activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:screenOrientation="portrait" android:theme="@android:style/Theme.Black.NoTitleBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

so which one should be in the fb dev console ? 
android.intent.action.MAIN ? or com.facebook.FacebookActivity ?

thanks for the reply

**Comment by Hirbod** [comment]
please ask on SO, as this is an issue tracker, not for general android questions.
