### ISSUE TITLE
Testing of plugin in Apple Test Flight

### ISSUE THREAD

**Issue by riskmanagerjeff** [jeduan/cordova-plugin-facebook4#153]
I have this plugin working fine when testing on my own device.
However, when I upload the app to the app store for use in the Test Flight Beta testing, the plugin fails.  (the return status is 'unknown')  

Has anyone here worked with this plugin and Apple test flight?

**Comment by jeduan** [comment]
Yep, never had a problem. Check your config maybe?

**Comment by riskmanagerjeff** [comment]
I rebuilt the app, ensuring that the bundle ID is correct with FB.  This is
what I know..

when i set the widget tag in the config.xml to a new name needed for apple,
facebook returns 'unknown'.
Then i set it back to the original test bundle id (not unique) and it works
fine again...  But of course, i cant upload to apple anymore.

Is there other than the config.xml, is there a place that needs updating?

**Comment by jeduan** [comment]
You're probably not running cordova prepare after setting the app id so you're using the wrong id on your TestFlight app. Always run Cordova prepare before doing builds.

**Comment by riskmanagerjeff** [comment]
Thanks..  i just tried it..  no go.
It's not just test flight.

When I have the original bundle id, it works with just xcode loading the
app to my phone.
I then switch the bundle id, it no longer works with xcode/loading to my
phone.  switching back, and it works fine again...
So either FB is seeing a different bundle ID (im sure i have both listed
correctly in FB) and/or the new id is not making its way through the app
build process correctly.

**Comment by jeduan** [comment]
Ah yeah you have to change the plists and whatnot. Unfortunately cordova can't do that for you right now. I always use one id tbh

**Comment by riskmanagerjeff** [comment]
I checked the app-info.plist before, so thats not it.  Actually, cordova
updated it.

**Comment by riskmanagerjeff** [comment]
i just created a new FB app with just 1 bundle ID, and still no good.

Is it possible, that when creating the cordova project at the very
beginning, somehow sets the bundle ID in a way that this plugin cant be
updated?  Im just out of ideas...

**Comment by jeduan** [comment]
There's an id set on plugins IIRC. If you really want to use 2 ids you'll have to delete plugins and platforms and reinstall everything every time you switch the app id

**Comment by riskmanagerjeff** [comment]
got it.  the unknown case was due to merely not logging back in.  In the
working version, it was always logged in, and didnt go down a path of logic
into that state!
