### ISSUE TITLE
Error in android support

### ISSUE THREAD

**Issue by bruunofco** [jeduan/cordova-plugin-facebook4#154]
By adding the plugin, my application has stopped compiling. The displayed error is the error below. I found that the repository is not available on the maven. What do I do now?

This repository https://repo1.maven.org/maven2/com/android/support is 404 error.

**Error returned:**
 FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.android.support:support-v4:(23,24].
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/maven-metadata.xml
         https://repo1.maven.org/maven2/com/android/support/support-v4/
     Required by:
         :android:unspecified > com.facebook.android:facebook-android-sdk:4.10.0
   > Could not find any version that matches com.android.support:cardview-v7:(23,24].
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/cardview-v7/maven-metadata.xml
         https://repo1.maven.org/maven2/com/android/support/cardview-v7/
     Required by:
         :android:unspecified > com.facebook.android:facebook-android-sdk:4.10.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by jeduan** [comment]
Add the android support repository. ?

**Comment by bruunofco** [comment]
Yes, Android Support Library Rev. 23.2

**Comment by oskary** [comment]
I have the same issue.

**Comment by papaloizouc** [comment]
i changed `com.facebook.android:facebook-android-sdk:4.+` to be `com.facebook.android:facebook-android-sdk:4.4.0`and fixed it. `4.8` is probably fine too.

https://github.com/jeduan/cordova-plugin-facebook4/commit/8a53f82b9245e60061b12d9ee857e2e544782d78#diff-53f390d375398624afe1cfe1125f42bfL63

looks like cardview was introduced  in 4.9 doesn't seem to be in the dependency list of 4.8.
https://github.com/facebook/facebook-android-sdk/blob/028d430a3b48d05d0da133f44a0f07b9d72e6789/facebook/build.gradle

maybe change this in the package to have the latest working version, hope this helps.

**Comment by TheCopartnery** [comment]
Pull request created: #171

**Comment by micheltobon** [comment]
I continue having this same error, can anyone please tell me what do I have to change in order for phonegap build to work?

**Comment by oleksiy-nesterov** [comment]
same for me

**Comment by jesse1981** [comment]
I have the same issue, but I use [Phonegap Build](http://build.phonegap.com) - Forgive any ignorance, but is it possible to have this plugin not require these dependencies?

**Comment by wildabeast** [comment]
This issue crops up each time the facebook-sdk releases a new version with an updated support library. I believe it could be prevented if the facebook-sdk dependency was locked to a specific version rather than 4+ as mentioned by @papaloizouc i.e.

    <framework src="com.facebook.android:facebook-android-sdk:4.4.0"/>

rather than

    <framework src="com.facebook.android:facebook-android-sdk:4.+"/>

would really help PhoneGap Build and its users :)

**Comment by papaloizouc** [comment]
looks like its merged in master now https://github.com/jeduan/cordova-plugin-facebook4/blob/master/plugin.xml#L64

**Comment by wildabeast** [comment]
Issue could still crop up if minor versions are updated i.e. 4.8.0 -> 4.8.1 Ideally each vesion of the facebook plugin would be locked to a version of the facebook sdk, at least for some purposes.
