### ISSUE TITLE
Add "continue as" feature 

### ISSUE THREAD

**Issue by BojDom** [jeduan/cordova-plugin-facebook4#157]
How to display the user name BEFORE he login, like instagram do ?

<img src="https://cdn.pbrd.co/images/1ZqoINRC.png"/>

**Comment by Hirbod** [comment]
I guess (as istagram belongs to FB) they are sharing an intent/ universal link-param with the authcode and the name. This should be the way for it. But we can't provide that.

**Comment by gianpaj** [comment]
Is it possible to add this functionality?

https://developers.facebook.com/docs/facebook-login/web/login-button

> The "Continue as {Name}" button has the text "Continue as {persons' name}" and optionally includes the person's Facebook profile picture if they're logged in to Facebook in the same browser.
