### ISSUE TITLE
GET requests for ... should contain an explicit "fields" parameter

### ISSUE THREAD

**Issue by greg84** [jeduan/cordova-plugin-facebook4#162]
I'm getting the following error when trying to post to a user's wall:

`FBSDKLog: starting with Graph API v2.4, GET requests for //me/feed should contain an explicit "fields" parameter`

It worked the first time, but I tapped 'not now' to the additional permissions prompt. Ever since I get the error above.

Here's my JS code:
```
facebookConnectPlugin.api(
  '/me/feed', 
  ['publish_actions'], 
  { message: 'Just testing...', link: 'http://google.com' }, 
  function(r) {
    console.log('Facebook FEED POST: ' + JSON.stringify(r));
  });
```

I've also tried to check existing permissions and received the same error with the following code:

`facebookConnectPlugin.api('/me/permissions');`

**Comment by Captnwalker1** [comment]
I've seen this get spit out on normal iOS apps and still had everything work fine. I don't think your problem is related to the fields parameter.

**Comment by Hirbod** [comment]
/me/feed?fields=publish_actions
