### ISSUE TITLE
Problems when using plugin with meteor

### ISSUE THREAD

**Issue by mscherer82** [jeduan/cordova-plugin-facebook4#165]
When using the facebook plugin I got this message

`AAPT: No resource found that matches the given name (at 'value' with value '@string/fb_app_id').`

After resetting cordova I got another message:

`.meteor\local\cordova-build\platforms\android\res\values\facebookconnect.xml" already exists!`

Deleting the file doesn't solve the issue. 

Reproduce:
meteor create new_app
cd new_app
meteor add heysailor:accounts-facebook-cordova
edit new_app/mobile-config.js and add App.setPreference('android-minSdkVersion' , 15); 
meteor run android-device ..

Regarding the meteor team the issue is not caused by meteor:  https://github.com/meteor/meteor/issues/6232

**Comment by jstoup111** [comment]
+1 this is a pretty big issue for me as well.

**Comment by rubenlpz** [comment]
Did you found any solution?

**Comment by mscherer82** [comment]
No, I'm doing a `meteor reset` every time.

**Comment by rubenlpz** [comment]
What I finally did was to downgrade the version of crosswalk plugin I was using (0.11.0).  Now Im ussing version 1.4.0 and this one, dont give me the fb plugin error anymore: 
` AAPT: No resource found that matches the given name (at 'value' with value '@string/fb_app_id'). `

**Comment by ronaldso55** [comment]
@rubenlpz We were using crosswalk 1.6.2 and hit into the same error.  I don't see 1.4.0 available (https://atmospherejs.com/meteor/crosswalk) but using 1.3.1 does not solve the problem.  Any idea how to get around the issue, or, if there are updates that I should try?  I have tried crosswalk 1.7.0 (Oct 25, 2016) but the problem persists.  Thanks a lot.

**Comment by rubenlpz** [comment]
@ronaldso55 Please make it sure you are setting the FB plugin in the file: mobile-config.js in your root directory.   You need to have the following in that file:

```
App.configurePlugin('cordova-plugin-facebook4', {
  APP_ID: '5555555555',    // <- Your appId
  APP_NAME: 'SASASASA'    // <- Your app_name
});
```

// Please Set this plugin too, since facebook4 plugin is based on it:
```
App.configurePlugin('com.phonegap.plugins.facebookconnect', {
APP_ID: '5555555555',    // <- Your appId
  APP_NAME: 'SASASASA'    // <- Your app_name
});
```
Regards,

**Comment by ronaldso55** [comment]
@rubenlpz Thanks for writing back.  The problem magically went away when we upgrade to Meteor 1.4.2 probably due to upgraded tooling.

**Comment by peterpeterparker** [comment]
Close, inactivity since 2016
