### ISSUE TITLE
facebookConnectPlugin.logout error 

### ISSUE THREAD

**Issue by lakfa** [jeduan/cordova-plugin-facebook4#169]
Hi,

When trying to call the logout function from ionic app, I am getting the error : "Refused to display 'https://www.facebook.com/home.php' in a frame because it set 'X-Frame-Options' to 'DENY'"
Do you have any idea how to make it work ?

Thank you

**Comment by circuitrider** [comment]
No comments on this? I'm seeing a similar error and am not sure exactly what the cause is.

**Comment by tgezginis** [comment]
+1

**Comment by khocef** [comment]
Having the same problem 

```
Refused to display 'https://m.facebook.com/home.php?_rdr' in a frame because it set 'X-Frame-Options' to 'deny'.
GET https://m.facebook.com/home.php?_rdr net::ERR_BLOCKED_BY_RESPONSE
```
