### ISSUE TITLE
Support "App-Install Tracking" by default on iOS

### ISSUE THREAD

**Issue by Hirbod** [jeduan/cordova-plugin-facebook4#17]
1) support App-Install tracking by default (it's very easy to integrate, just 2 lines of code)
https://github.com/ccsoft/cordova-facebook/issues/69

#4

**Comment by jeduan** [comment]
I like this, only don't know about the implications.

I.E. can an app which doesn't want or can't (i.e. apps for children which need to comply with COPPA) use tracking disable it?

**Comment by Hirbod** [comment]
I don't know any scenario a user don't want to know how often someone opened his app trough facebook. This tracking is only for tracking installs. (COPPA is something for the US, correct me if I don't know anything about your laws) If you have a campaign for example, you can see how many times users installed your app trough facebook advertisement. Does this interfer with any laws or face any privacy issues?

**Comment by jeduan** [comment]
COPPA is a children privacy protection law. I'm not from the US either!

**Comment by Hirbod** [comment]
I just read a few lines about that. If you ask me, tracking installs should not violate against any children laws? Every single site on this planet has google analytics integrated, I think tracking installs isn't something that violates against laws, but I'm not a lawyer of course.

**Comment by jeduan** [comment]
Yeah, thinking more about it, kids aren't allowed to have Facebook accounts and if the user doesn't have an account, the tracking does not send personally identifiable information.

**Comment by Hirbod** [comment]
Excatly. Facebook is 13+ nearly wordwide. But the tracking does not obtain any person identifiable informations. It's just "date of install" and "type of device" (android, iOS).

The code in my example is for iOS only and has to be integrated in android also.

iOS:
https://developers.facebook.com/docs/app-events/ios#implementation

Android:
https://developers.facebook.com/docs/app-events/android#implementation

Very easy thing. And as even facebook mention, "it should be the first thing to integrate"

**Comment by manuelpaulo** [comment]
Now I am confused. 

You say "Activation events are automatically tracked for you in the plugin."

App-Install *is* an activation event.

I get them all the time on the iOS version without any change to the code, just as I get App Launches or Completed Sessions.

**Comment by Hirbod** [comment]
ping

**Comment by machei** [comment]
pong

**Comment by Hirbod** [comment]
Hi @jeduan,

thanks for updating this! What about android btw? Is this working there as expected? 
Do you have paypal? Would like to sent you some beer tip!
