### ISSUE TITLE
posting picture does not working when using the "share" method

### ISSUE THREAD

**Issue by derulo** [jeduan/cordova-plugin-facebook4#170]
Posting of a picture does not work when using the "share" method, neither on iOS nor on Android using Phonegap build CLI 5.2.0
A dialog window opens, but it's empty. What could be wrong?
Thanks

**Comment by Ziv-Barber** [comment]
After a lot of investigations we found out that on the link that you sharing you MUST add some open graph metadata:

<meta property="og:url" content="https://your-site.com/" />
<meta property="og:type" content="website" />
<meta property="og:title" content="--- will be the link's header ---" />
<meta property="og:description" content="--- will be the link's description ---" />
<meta property="og:image" content="http://yoursite.com/your-image.png" />

Warnings:
1. og:url MUST be the SAME as the link that you passing as the 'link' parameter to shareDialog.
2. If your link including http get query ('?') then users will NOT see the picture!!!

**Comment by derulo** [comment]
Hi, thanks a lot for the super quick answer :)
What open graph metadata should I insert? I cannot see it in the above message, there are empty lines.
My

**Comment by derulo** [comment]
Any ideas why the "share" method does not accept a picture? I can share a link using 'href' but not a picture. Any items I need to take care of?
Thanks

**Comment by Hirbod** [comment]
you should try this plugin for sharing:
https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin

**Comment by MaelstromCdn** [comment]
I'm trying to share a link to an image Facebook post but the share dialog just shows "An error occurred. Please try again later". My options are defined as:
var options = {
    method: 'share',
    href: post.link,
    caption: post.message
};
Any ideas? Do I have to set picture? I've tried several combinations with no success.
