### ISSUE TITLE
Passing return_scopes = true with login request

### ISSUE THREAD

**Issue by divyekhanna** [jeduan/cordova-plugin-facebook4#172]
@jeduan How can we pass the `return_scopes` parameter set to `true` in order to check which permissions the user approved at the time of login?

EDIT:
Reference for `return_scopes` flag - https://developers.facebook.com/docs/reference/javascript/FB.login/v2.5

**Comment by jeduan** [comment]
I have no idea. Is that a flag available on android /iOS?

**Comment by divyekhanna** [comment]
My apologies for giving the link for Javascript SDK instead of Android one. This is the correct link:
https://developers.facebook.com/docs/facebook-login/android/permissions

Specifically, I'm looking for:
`AccessToken.getCurrentAccessToken().getPermissions();` and
`AccessToken.getCurrentAccessToken().getDeclinedPermissions();` methods to be exposed via this plugin

Can you incorporate these methods in the plugin? Or provide guidance for me to get started on a PR?

Thanks!

**Comment by divyekhanna** [comment]
Hi @jeduan any info/guidance on this would be much appreciated. Thanks

**Comment by fxlemire** [comment]
Also interested!

**Comment by SnidelyWhiplash** [comment]
Big plus one to this!

**Comment by ciekawy** [comment]
Any chances? in particular how do I know if the received permissions set is the one we need (i.e  in case of extra permissions required?)

**Comment by KarsusITA** [comment]
> Any chances? in particular how do I know if the received permissions set is the one we need (i.e in case of extra permissions required?)

Simply... Ionic is a pretty shitty platform made with shitty and not upgraded plugin.

Anyway, there's a workaround.

Once you're logged in, you can make an open graph api call
/{user-id}/permissions

But I'm really tirder of Ionic, all about workaround and nothing that's official

**Comment by peterpeterparker** [comment]
@KarsusITA if you are not happy with an open source **FREE** plugin or technology, you are most welcomed to collaborate and provide pull requests to improve it

**Comment by KarsusITA** [comment]
> @KarsusITA if you are not happy with an open source **FREE** plugin or technology, you are most welcomed to collaborate and provide pull requests to improve it

Definetly not happy, but the projects we are running are almost completed, so it's better find workaround than restart.
There are maybe a couple of working plugin.
Anyway, still android studio and xcode provide free and open source environment.

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect. That plugin now provides the `checkHasCorrectPermissions` method on all platforms (previously it was only available on iOS).
