### ISSUE TITLE
Share Open Graph iOS

### ISSUE THREAD

**Issue by ggalipeau** [jeduan/cordova-plugin-facebook4#173]
On the main page of this Github project there is code on how to use the Share Dialog - Open Graph Story. Since the plugin is for iOS and Android, I assumed that was for both. However, I just read through the code and I don't see this for iOS. In Android, it is fully coded out - it seems to use the action properties and open graph object sent up. However, in iOS, it doesn't seem to have any code for this. It doesn't even set the action_type. It seems to just call the same exact code that the regular share calls.

Can someone confirm if this has been implemented or not for iOS?

Thanks in advance.

**Comment by yeldarby** [comment]
In the readme it's mentioned that

> Share dialog - Open Graph Story: (currently only available on Android, PRs welcome for iOS)
>
> {
>     var obj = {};
> 
>     obj['og:type'] = 'objectname';
>     obj['og:title'] = 'Some title';
>     obj['og:url'] = 'https://en.wikipedia.org/wiki/Main_Page';
>     obj['og:description'] = 'Some description.';
> 
>     var ap = {};
> 
>     ap['expires_in'] = 3600;
> 
>     var options = {
>         method: 'share_open_graph', // Required
>         action: 'actionname', // Required
>         action_properties: JSON.stringify(ap), // Optional
>         object: JSON.stringify(obj) // Required
>     };
> }
>
> In case you want to use custom actions/objects, just prepend the app namespace to the name (E.g: obj['og:type'] = 'appnamespace:objectname', action: 'appnamespace:actionname'. The namespace of a Facebook app is found on the Settings page.

I'm interested in this too but am not comfortable enough with the native code to implement it.

**Comment by yeldarby** [comment]
Fingers crossed someone is willing to implement this feature on iOS. I posted a bounty to hopefully help get someone interested in prioritizing it.

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=32195064)](https://www.bountysource.com/issues/32195064-share-open-graph-ios?utm_source=32195064&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by robertarnesson** [comment]
integrated in b3e73861c24e3439106f4a51bbe523f6623243fc
