### ISSUE TITLE
Freeze after Facebook Login

### ISSUE THREAD

**Issue by desmeit** [jeduan/cordova-plugin-facebook4#176]
I have the following code and I get the email, user id, token etc.

```
document.addEventListener('deviceready', function () {


    var fbLoginSuccess = function (userData) {
  alert(userData.authResponse.userID);
    alert(userData.authResponse.accessToken);

}

facebookConnectPlugin.login(["public_profile", "email"], fbLoginSuccess,
  function (error) {
    console.error(error)
  }

);

                    facebookConnectPlugin.api('/me?fields=id,first_name,last_name,email', null, function(response) {
                         alert(response.email);
                         alert(response.first_name);
                         alert(response.last_name);
                     });


});
```

But after Facebook-Login I come back to my App and the App is frozen. Without the code above it is working perfectly. Have anybody an idea?

**Comment by redbird19** [comment]
I have the exact same issue, but I put some debug statements and found that the api call to `facebookConnectPlugin.api('/me...)` was failing.  Unfortunately, the only error message returned is "User cancelled".  

I don't understand what's going on because everything works fine on my iPhone 5 running iOS 9.3.  It  also works fine on my iPhone 4 running iOS 7.1.  However, my iPad Air 2 running iOS 9.3 has the problem as do many of my iPhone 6 users running iOS 9.3.

**Comment by martinr77** [comment]
Okay, thanks for your reply. My debug console said nothing. How did you debug?

**Comment by redbird19** [comment]
In your call to `facebookConnectPlugin.api('/me...');`, you currently only have a "success" handler function, add a "failure" handler function (as another parameter) and capture/display the error message there.  I bet you'll get the same result as me.

But this bug needs to be fixed somehow.  Anyone have any ideas?

**Comment by martinr77** [comment]
The issue occurs through the login function. I included the whole code within a function and call it with onclick instead of device ready. Then it works but this could be only a soultion for a short time. It should be fixed.

**Comment by robertarnesson** [comment]
have you tried to call getLoginStatus() first to check that the user is not already connected?

**Comment by Danbardo** [comment]
+1

**Comment by peterpeterparker** [comment]
Close, inactivity since 2016
