### ISSUE TITLE
can we get a proper Changelog

### ISSUE THREAD

**Issue by talamaska** [jeduan/cordova-plugin-facebook4#178]
can we get a proper Changelog

**Comment by jeduan** [comment]
Send a pr

**Comment by talamaska** [comment]
Lol really? Just close ir like that? I'm not native developer I can't follow and understand the changes, sunce most of the changes in the repo are external PRs.

**Comment by jeduan** [comment]
Yes, really.

If you're building native apps you're expected to at least learn how to debug them. Why would you blindly add the code from strangers in the Internet? How will you know where to start when a crash comes? "I'm not a native developer" is a bad excuse. 

Sounding entitled and expecting said strangers to just do free work for you won't get you any sympathy in this parts either. 

From your profile it looks like you're a smart person. I trust you will learn native as we have.
