### ISSUE TITLE
phongap build fail from today

### ISSUE THREAD

**Issue by lordamon** [jeduan/cordova-plugin-facebook4#179]
unitl yesterday (23/03/2016) all worked fine.
Today when i try to build my app with this plugin i get this build error:
Build Date: 2016-03-24 16:02:13 +0000

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'project'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find com.android.support:support-v4:23.2.0.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.2.0/support-v4-23.2.0.pom
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.2.0/support-v4-23.2.0.jar
         file:/android-sdk/extras/android/m2repository/com/android/support/support-v4/23.2.0/support-v4-23.2.0.pom
         file:/android-sdk/extras/android/m2repository/com/android/support/support-v4/23.2.0/support-v4-23.2.0.jar
         file:/android-sdk/extras/google/m2repository/com/android/support/support-v4/23.2.0/support-v4-23.2.0.pom
         file:/android-sdk/extras/google/m2repository/com/android/support/support-v4/23.2.0/support-v4-23.2.0.jar
     Required by:
         :project:unspecified > com.android.support:support-v13:23.1.0
   > Could not find com.android.support:support-v4:23.2.0.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.2.0/support-v4-23.2.0.pom
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.2.0/support-v4-23.2.0.jar
         file:/android-sdk/extras/android/m2repository/com/android/support/support-v4/23.2.0/support-v4-23.2.0.pom
         file:/android-sdk/extras/android/m2repository/com/android/support/support-v4/23.2.0/support-v4-23.2.0.jar
         file:/android-sdk/extras/google/m2repository/com/android/support/support-v4/23.2.0/support-v4-23.2.0.pom
         file:/android-sdk/extras/google/m2repository/com/android/support/support-v4/23.2.0/support-v4-23.2.0.jar
     Required by:
         :project:unspecified > com.facebook.android:facebook-android-sdk:4.10.1
   > Could not find com.android.support:cardview-v7:23.2.0.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/cardview-v7/23.2.0/cardview-v7-23.2.0.pom
         https://repo1.maven.org/maven2/com/android/support/cardview-v7/23.2.0/cardview-v7-23.2.0.jar
         file:/android-sdk/extras/android/m2repository/com/android/support/cardview-v7/23.2.0/cardview-v7-23.2.0.pom
         file:/android-sdk/extras/android/m2repository/com/android/support/cardview-v7/23.2.0/cardview-v7-23.2.0.jar
         file:/android-sdk/extras/google/m2repository/com/android/support/cardview-v7/23.2.0/cardview-v7-23.2.0.pom
         file:/android-sdk/extras/google/m2repository/com/android/support/cardview-v7/23.2.0/cardview-v7-23.2.0.jar
     Required by:
         :project:unspecified > com.facebook.android:facebook-android-sdk:4.10.1
   > Could not find com.android.support:support-v4:23.2.0.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.2.0/support-v4-23.2.0.pom
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.2.0/support-v4-23.2.0.jar
         file:/android-sdk/extras/android/m2repository/com/android/support/support-v4/23.2.0/support-v4-23.2.0.pom
         file:/android-sdk/extras/android/m2repository/com/android/support/support-v4/23.2.0/support-v4-23.2.0.jar
         file:/android-sdk/extras/google/m2repository/com/android/support/support-v4/23.2.0/support-v4-23.2.0.pom
         file:/android-sdk/extras/google/m2repository/com/android/support/support-v4/23.2.0/support-v4-23.2.0.jar
     Required by:
         :project:unspecified > com.google.android.gms:play-services-analytics:8.4.0 > com.google.android.gms:play-services-basement:8.4.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.423 secs
undefined

Is a phonegap build problem or some repository change problem?

**Comment by micheltobon** [comment]
the exact same here, actually, is there any anser to this situation?

**Comment by jeduan** [comment]
No changes at all from this end. It's easy to see the releases in npm's website.

**Comment by micheltobon** [comment]
hello @jeduan I know you might be busy, but if you could please explain to me what is going on with this it would be of great help and I would really appreciate it

**Comment by orthodoc** [comment]
@micheltobon the build is failing due to updates in the android sdk support libraries. During the build process a few files are downloaded from the maven repo and since you have not updated your sdk support libraries, the build process is failing.

Open the android sdk manager and update the following two libraries: `Android Support Library` and `Local Maven repository for Support Libraries`. You may have to scroll down to see them close to the bottom of the window. I also updated the build-tools and platform-tools (This may not be necessary to pass the build errors!). 

If running `android` from the command line doesn't open the sdk manager, then you may have to locate the installation folder and run the jar from therein. For me on the macbook, I had to run this:

`/Users/bdb/Library/Android/sdk/tools/android`

Replace `bdb` with your username if on the mac.

Remember to deselect all first. The sdk manager selects by default several libraries - both new and updates. And installing all those packages will take a lot of time and grab a lot of space. Updating just those two libraries should help overcome the build error.

**Comment by lordamon** [comment]
@orthodoc thank you, but im using phonegap build to create my app, so the problem is that phonegap build have changed their library?

**Comment by orthodoc** [comment]
@lordamon if you are using phonegap cli to build it locally then you have to update the libraries yourself. But if you are using the phonegap build services over the web, then you have to wait for adobe to update their libraries. I am sure they will very soon. :smile:

**Comment by micheltobon** [comment]
@orthodoc I have the same problem, I am using phonegap build, but well, it's not a problem, I am in a development phase so, there is no problem for the moment, but it will become a problem next week, anyways, thank you so much for your information and please allow me to buy you a beer
