### ISSUE TITLE
Android build fail when use Cordova 6.1.0，iOS not try yet 

### ISSUE THREAD

**Issue by bau720123** [jeduan/cordova-plugin-facebook4#180]
hi @jeduan 

[my environment]
Cordova 6.1.0
Cordova-Android 5.1.1
cordova-plugin-facebook4 1.7.0
Java Version，1.8.0_66

see my screenshot
![facebook](https://cloud.githubusercontent.com/assets/5110085/14037432/9f5c7220-f27e-11e5-9b85-1b689a6f7c75.png)

after some survey，it seem when I use Cordova 6.1.0 and no mater which "cordova-plugin-facebook4" version that I use，it will cause build fail

**Comment by mhayes14** [comment]
Having the same issue here.

**Comment by pahayah** [comment]
same issue here

**Comment by amiriltd** [comment]
Same issue. I had no problems until I decided to build again this week. It looks like PhoneGap just recently started using Android SDK 23.1.1 and the plugin is using Android SDK 23.0. Can you update the plugin to use the latest Android SDK

from PhoneGap:

Updating Android SDK Support Library to 23.1.1 on Build

We're updating our Android Support Library from 23.0 to 23.1.1 in the Android SDK today on our build servers. 

 This may affect plugins that have the support library declared as a dependency specifically at 23.0.0. Dependencies should be listed as 23+ to avoid issues with minor version increments.

**Comment by amiriltd** [comment]
Fetching plugin "cordova-plugin-facebook4@1.7.0" via npm
Installing "cordova-plugin-facebook4" at "1.7.0" for android
--------------------------------------------------------------------------------
COMPILE OUTPUT
--------------------------------------------------------------------------------
Build option --'' not recognized (ignoring).
Running: /project/gradlew cdvBuildDebug -b /project/build.gradle -Dorg.gradle.daemon=true -PcdvBuildMultipleApks=false
Background-App: Removing <intent-filter> from AndroidManifest.xml

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'project'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find com.android.support:support-v4:23.2.0.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.2.0/support-v4-23.2.0.pom
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.2.0/support-v4-23.2.0.jar
         https://jcenter.bintray.com/com/android/support/support-v4/23.2.0/support-v4-23.2.0.pom
         https://jcenter.bintray.com/com/android/support/support-v4/23.2.0/support-v4-23.2.0.jar
         https://maven.fabric.io/public/com/android/support/support-v4/23.2.0/support-v4-23.2.0.pom
         https://maven.fabric.io/public/com/android/support/support-v4/23.2.0/support-v4-23.2.0.jar
         file:/android-sdk/extras/android/m2repository/com/android/support/support-v4/23.2.0/support-v4-23.2.0.pom
         file:/android-sdk/extras/android/m2repository/com/android/support/support-v4/23.2.0/support-v4-23.2.0.jar
         file:/android-sdk/extras/google/m2repository/com/android/support/support-v4/23.2.0/support-v4-23.2.0.pom
         file:/android-sdk/extras/google/m2repository/com/android/support/support-v4/23.2.0/support-v4-23.2.0.jar
     Required by:
         :project:unspecified
   > Could not find com.android.support:support-v4:23.2.0.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.2.0/support-v4-23.2.0.pom
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.2.0/support-v4-23.2.0.jar
         https://jcenter.bintray.com/com/android/support/support-v4/23.2.0/support-v4-23.2.0.pom
         https://jcenter.bintray.com/com/android/support/support-v4/23.2.0/support-v4-23.2.0.jar
         https://maven.fabric.io/public/com/android/support/support-v4/23.2.0/support-v4-23.2.0.pom
         https://maven.fabric.io/public/com/android/support/support-v4/23.2.0/support-v4-23.2.0.jar
         file:/android-sdk/extras/android/m2repository/com/android/support/support-v4/23.2.0/support-v4-23.2.0.pom
         file:/android-sdk/extras/android/m2repository/com/android/support/support-v4/23.2.0/support-v4-23.2.0.jar
         file:/android-sdk/extras/google/m2repository/com/android/support/support-v4/23.2.0/support-v4-23.2.0.pom
         file:/android-sdk/extras/google/m2repository/com/android/support/support-v4/23.2.0/support-v4-23.2.0.jar
     Required by:
         :project:unspecified > com.facebook.android:facebook-android-sdk:4.10.1
   > Could not find com.android.support:cardview-v7:23.2.0.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/cardview-v7/23.2.0/cardview-v7-23.2.0.pom
         https://repo1.maven.org/maven2/com/android/support/cardview-v7/23.2.0/cardview-v7-23.2.0.jar
         https://jcenter.bintray.com/com/android/support/cardview-v7/23.2.0/cardview-v7-23.2.0.pom
         https://jcenter.bintray.com/com/android/support/cardview-v7/23.2.0/cardview-v7-23.2.0.jar
         https://maven.fabric.io/public/com/android/support/cardview-v7/23.2.0/cardview-v7-23.2.0.pom
         https://maven.fabric.io/public/com/android/support/cardview-v7/23.2.0/cardview-v7-23.2.0.jar
         file:/android-sdk/extras/android/m2repository/com/android/support/cardview-v7/23.2.0/cardview-v7-23.2.0.pom
         file:/android-sdk/extras/android/m2repository/com/android/support/cardview-v7/23.2.0/cardview-v7-23.2.0.jar
         file:/android-sdk/extras/google/m2repository/com/android/support/cardview-v7/23.2.0/cardview-v7-23.2.0.pom
         file:/android-sdk/extras/google/m2repository/com/android/support/cardview-v7/23.2.0/cardview-v7-23.2.0.jar
     Required by:
         :project:unspecified > com.facebook.android:facebook-android-sdk:4.10.1
   > Could not find com.android.support:support-v4:23.2.0.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.2.0/support-v4-23.2.0.pom
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.2.0/support-v4-23.2.0.jar
         https://jcenter.bintray.com/com/android/support/support-v4/23.2.0/support-v4-23.2.0.pom
         https://jcenter.bintray.com/com/android/support/support-v4/23.2.0/support-v4-23.2.0.jar
         https://maven.fabric.io/public/com/android/support/support-v4/23.2.0/support-v4-23.2.0.pom
         https://maven.fabric.io/public/com/android/support/support-v4/23.2.0/support-v4-23.2.0.jar
         file:/android-sdk/extras/android/m2repository/com/android/support/support-v4/23.2.0/support-v4-23.2.0.pom
         file:/android-sdk/extras/android/m2repository/com/android/support/support-v4/23.2.0/support-v4-23.2.0.jar
         file:/android-sdk/extras/google/m2repository/com/android/support/support-v4/23.2.0/support-v4-23.2.0.pom
         file:/android-sdk/extras/google/m2repository/com/android/support/support-v4/23.2.0/support-v4-23.2.0.jar
     Required by:
         :project:unspecified > com.twitter.sdk.android:twitter:1.4.0 > com.twitter.sdk.android:tweet-ui:1.1.0
   > Could not find com.android.support:support-v4:23.2.0.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.2.0/support-v4-23.2.0.pom
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.2.0/support-v4-23.2.0.jar
         https://jcenter.bintray.com/com/android/support/support-v4/23.2.0/support-v4-23.2.0.pom
         https://jcenter.bintray.com/com/android/support/support-v4/23.2.0/support-v4-23.2.0.jar
         https://maven.fabric.io/public/com/android/support/support-v4/23.2.0/support-v4-23.2.0.pom
         https://maven.fabric.io/public/com/android/support/support-v4/23.2.0/support-v4-23.2.0.jar
         file:/android-sdk/extras/android/m2repository/com/android/support/support-v4/23.2.0/support-v4-23.2.0.pom
         file:/android-sdk/extras/android/m2repository/com/android/support/support-v4/23.2.0/support-v4-23.2.0.jar
         file:/android-sdk/extras/google/m2repository/com/android/support/support-v4/23.2.0/support-v4-23.2.0.pom
         file:/android-sdk/extras/google/m2repository/com/android/support/support-v4/23.2.0/support-v4-23.2.0.jar
     Required by:
         :project:unspecified > com.google.android.gms:play-services-analytics:8.4.0 > com.google.android.gms:play-services-basement:8.4.0

**Comment by adru** [comment]
I’m using PhoneGap Build, the latest version that seems to work is 1.3.0 – good enough for now, I guess.

**Comment by amiriltd** [comment]
Thanks! that worked!

**Comment by bennerhq** [comment]
Hello -- I have the same compilation error as above for Android (using cordova 6.1.0 and xwalk). ... It works on iOS ;)

Anybody have a solid solution for android?

BR/benner

**Comment by araujoigor** [comment]
Just update your "Local Maven repository for Support Libraries" (to the revision 28) on Android SDK Manager.

**Comment by amiriltd** [comment]
Use version 1.3.0 of the plugin if you are building with PhoneGap.

**Comment by bennerhq** [comment]
ggrrraaa ;) ... sorry for disturbing again... i'm getting the below compile error. what am i doing wrong here? how to correct?

thanks a million ;)


--------------

:processArmv7DebugManifest/Users/jbenner/Sites/rondon/platforms/android/AndroidManifest.xml:16:5-74 Error:
	uses-sdk:minSdkVersion 14 cannot be smaller than version 15 declared in library [com.facebook.android:facebook-android-sdk:4.10.1] /Users/jbenner/Sites/rondon/platforms/android/build/intermediates/exploded-aar/com.facebook.android/facebook-android-sdk/4.10.1/AndroidManifest.xml
	Suggestion: use tools:overrideLibrary="com.facebook" to force usage



See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

:processArmv7DebugManifest FAILED
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processArmv7DebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 15 declared in library [com.facebook.android:facebook-android-sdk:4.10.1] /Users/jbenner/Sites/rondon/platforms/android/build/intermediates/exploded-aar/com.facebook.android/facebook-android-sdk/4.10.1/AndroidManifest.xml
  	Suggestion: use tools:overrideLibrary="com.facebook" to force usage

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.855 secs
Error: Error code 1 for command: /Users/jbenner/Sites/rondon/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/jbenner/Sites/rondon/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true

**Comment by amiriltd** [comment]
Set the min version in your config.xml for Android to 15

  <preference name="android-minSdkVersion" value="15" />

**Comment by bennerhq** [comment]
yes sir! ... "<preference name="android-minSdkVersion" value="15" />" in config.xml is the master of the universe! ... so many settings, so little time!

thanks a million ;)

**Comment by bennerhq** [comment]
yes sir! ... "<preference name="android-minSdkVersion" value="15" />" in config.xml is the master of the universe! ... so many settings, so little time!

thanks a million ;)

**Comment by bennerhq** [comment]
that works! ... tx a million ... so many settings, so little time ;)

thanks again!

**Comment by bau720123** [comment]
hi @amiriltd 
is you mean cordova-plugin-facebook4 1.7.0 + android-minSdkVersion 15 => will build success
or
cordova-plugin-facebook4 1.3.0 + android-minSdkVersion 15 => will build success

**Comment by amiriltd** [comment]
cordova-plugin-facebook4 1.3.0 + android-minSdkVersion 15 => will build success. 

BTW, I am building with cli-5.4.1, but it should work. I'm using cli-5.4.1 for other reasons

**Comment by bau720123** [comment]
thanks @amiriltd 
Hope one day the have a version can build success on Cordova 6.1.0

**Comment by vzani** [comment]
I´m unable to solve the issue...

Using Cordova-cli 5.4.1
Already added    
<preference name="android-minSdkVersion" value="15" />

On config.xml

Installed Local Maven Repository and Android Support library ate Android SDK Manager.

The error persists:
```
Creating configuration testReleaseWearApp
Resource missing. [HTTP GET: https://repo1.maven.org/maven2/com/android/support/
support-v4/23.0.1/support-v4-23.0.1.pom]
Resource missing. [HTTP HEAD: https://repo1.maven.org/maven2/com/android/support
/support-v4/23.0.1/support-v4-23.0.1.jar]
Resource missing. [HTTP GET: https://repo1.maven.org/maven2/com/android/support/
multidex/1.0.1/multidex-1.0.1.pom]
Resource missing. [HTTP HEAD: https://repo1.maven.org/maven2/com/android/support
/multidex/1.0.1/multidex-1.0.1.jar]

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find com.android.support:support-v4:23.0.1.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.0.1/su
pport-v4-23.0.1.pom
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.0.1/su
pport-v4-23.0.1.jar
     Required by:
         :android:unspecified > com.facebook.android:facebook-android-sdk:4.8.2
   > Could not find com.android.support:multidex:1.0.1.




```

**Comment by amiriltd** [comment]
use 1.3.0 of facebook4 plugin.... 1.7.0 is not compatible with the latest PhoneGap building bot

**Comment by araujoigor** [comment]
@vzani Are you sure you've installed Local Maven Repository? Based on the error you are getting, the build process is not looking on the Local Maven Repository path to find the dependencies. Try to re-add the android platform on your project.

**Comment by vzani** [comment]
@amiriltd I tried to use 1.3.0 and the problem persists, but complaining about other version:

```
 Could not find com.android.support:support-v4:23.2.0.
1>       Searched in the following locations:
1>           https://repo1.maven.org/maven2/com/android/support/support-v4/23.2.0/support-v4-23.2.0.pom
1>           https://repo1.maven.org/maven2/com/android/support/support-v4/23.2.0/support-v4-23.2.0.jar
```
@araujoigor I have the Local Maven installed from SDK Manager 

![sdk_manager](https://cloud.githubusercontent.com/assets/8211953/14227104/3f468c60-f8cb-11e5-8981-011b71ba9a88.jpg)

But from the logs looks like its not trying to get from SDK path, only from some remote path that´s wrong. Is there any manual configuration that should be done for that?


Thanks

**Comment by amiriltd** [comment]
@vzani My solution is for if you are uploading to PhoneGap in order to build. I have no solution for building with Cordova as I've run into the same issue you are having.

**Comment by bau720123** [comment]
so strabge
for now I am using...
Cordova 6.1.1
Cordova-Android 5.1.1
Cordova-iOS 4.1.1
cordova-plugin-facebook4 1.7.0
Java 1.8.0_77
Xcode 7.3

all build success，so...close it first
