### ISSUE TITLE
Safari login can cause user account mismatch compared to native app actions

### ISSUE THREAD

**Issue by greg84** [jeduan/cordova-plugin-facebook4#181]
I'm aware that as per #53 Facebook changed their SDK so that log in uses Safari and requires a user to have Facebook auth cookies in Safari.

However, when I try to use the 'share' function it uses the native app. This works fine, but if the native app has a different user logged in to the one who logged in via Safari, it offers to share on their account instead.

As a workaround I added the following line to the `showDialog` method in `FacebookConnectPlugin.m`, just before it calls `[dialog show]`:
  `dialog.mode = FBSDKShareDialogModeFeedBrowser;`

This causes Safari to be used for the share dialog, which then shares under the same user account as the one who logged in initially.

I'm guessing this is a side effect of the design of the Facebook SDK, and it's unlikely a user will be logged into different accounts, but it could happen.

I'm just wondering if anyone knows of a better solution than the one I've come up with?

**Comment by Hirbod** [comment]
@jeduan serious thing. Might be a good idea to change that.

**Comment by Hirbod** [comment]
@robertarnesson any regrets? i would like to add this one

**Comment by Hirbod** [comment]
added param share_feedBrowser. share_sheet was there already. The param share_sheet wasn't event documentated. @robertarnesson would you please update readme ?

https://github.com/jeduan/cordova-plugin-facebook4/blob/master/src/ios/FacebookConnectPlugin.m#L269-L272

**Comment by bnfrnz** [comment]
Hi @greg84 and @Hirbod, I just stumbled upon this closed issue. I still encounter this problem on an Android device when opening a Game Request dialog (method: 'apprequests'). There can still be a mismatch between the account I logged in with vs the account that is used for the game request. I'm new to this. Would you have any tips how to best avoid this? Is there a way to programmatically kill the Facebook session or to force a server-roundtrip or something? Any hint would be much appteciated.
