### ISSUE TITLE
No callback on Cordova 6.1.0 / Cordova iOS 4.1.0

### ISSUE THREAD

**Issue by leecrossley** [jeduan/cordova-plugin-facebook4#184]
Since upgrading to Cordova iOS 4.1.0, the browser is not closed on successful login and no callback is received (only the `User cancelled` error callback when the done button is tapped manually).

I'll see if I can look into this further, I wanted to raise it incase anyone else had the issue or has already looked into it. For reference I've tried plugin versions 1.6.3 - 1.6.5 with the same result.

**Comment by leecrossley** [comment]
I created a fresh project with new facebook app to test and can confirm this wasn't an issue - which means it's something wrong in my setup. Closing.

**Comment by jeduan** [comment]
Thanks for confirming on your end!

**Comment by leecrossley** [comment]
For reference (still investigating) when I remove the [Google Plus Plugin](https://github.com/EddyVerbruggen/cordova-plugin-googleplus) is magically starts working.

**Comment by leonardobazico** [comment]
@leecrossley same here. Any solutions?

**Comment by karthi191** [comment]
my facebook ios is opening in browser and send error callback user cancelled i try of way but i cant fix that issue anyone can help about this ?????

thanks

**Comment by fablrdigital** [comment]
Can you confirm if there's any update on this?
