### ISSUE TITLE
Updating Facebook App_ID

### ISSUE THREAD

**Issue by Bowtch** [jeduan/cordova-plugin-facebook4#188]
When updating app_id from dev to production I first change the variables values in my config.xml then ionic build but it did not updated my info.plist  nor my ios.json in my plugin folder (the android one is ok), so I tried to rm the plugin and add it again but I still keep my old app_id in info.plist. 

Am I missing something or do I need to update the info.plist manually ?

cordova version : 5.4.1
ionic version      : 1.7.10

**Comment by martyzz1** [comment]
did you try 

  ionic prepare ios

**Comment by Bowtch** [comment]
Yes I did try, with the same result, I just removed the platform iOS and reinstall all dependencies including cordova plugin Facebook with the prod app id. I haven't looked for a better way for now I'll keep you updated if I find something

**Comment by jeduan** [comment]
Yep. You need to remove platforms and plugins and reinstall.
