### ISSUE TITLE
Multiple asynchronus requests don't work

### ISSUE THREAD

**Issue by NightkingCH** [jeduan/cordova-plugin-facebook4#189]
Hi there!

I'm trying to access facebook user data after login. I want to load the profile data and for example the profile picture.

**Example code:**

```
// Request 1
         var prom1 = new Promise((resolve, reject) => {
            facebookConnectPlugin.api("/" + id + "/picture?redirect=0&height=200&type=normal", [], 
            (data: any) => {
                console.log(data);

            }, (err: any) => {
                console.log(err);
                reject(err);
            });
        });

// Request 2
        var prom2 = new Promise((resolve, reject) => {
            facebookConnectPlugin.api("/me", [], (data: any) => {
                console.log(data);
            }, (err: any) => {
                console.log(err);
                reject(err);
            });
        });
```

Now I expect to make two requests to the fb-graph api and get the data asynchronus. 

But this produces only one, than two, log entries. The faster request resolves, for example _prom1_, the promise. The second promise, _prom2_, won't get resolved. But this isn't the end. If reexecute the function, the first promise, _prom1_, will get resolved with the result of the second promise, _prom2_, which was called befor. And sometimes it seems to be just random (race condition).

If I encapuslate those requests / promises it works like expected and it produces 2 log entries synchronus.

Does anyone know how this behavior comes about? Is this a limitation for hybrid apps / cordova plugins? Do I have to make all my calls synchronus? Which will slow down everything... 

Thanks in advance!

btw: I'm using typescript and ionic2@beta.

**Comment by ViaFabula** [comment]
Same issue here (only on Android). Had to serialize my calls to the facebookPluginConnect.api function to get pictures from all user friends....

**Comment by jeromeXoo** [comment]
same issue:

```javascript
loginFacebook() {
        this.errorMessage = null;

        Facebook.login(['public_profile ', 'email']).then(
            sucess => {
                console.log('facebook userID: ' + sucess.authResponse.userID);

                if (sucess.status == 'connected') {
                                        
                    Facebook.api('me/?fields=id,email', ['public_profile ', 'email'])
                        .then(result => {
                            console.log("Result: ", result);
                            }, error => {
                                console.error("Failed: ", error);
                            }
                        );
                          
                }
                else {
                    this.errorMessage = 'Facebook Authentification failed. Please try again.';
                }
            },
            rejected => {
                this.errorMessage = 'Facebook Authentification failed. Please try again.';
                this.FacebookLoginRejected(rejected);
            }
        );
}
```

First call to loginFacebook: 
- login is resolved, console log "facebook userID"
- Facebook.api is not resolved

I log out with Facebook.logout()

Second call to loginFacebook:
- Facebook.api is resolved
- login is not resolved

**Comment by Hirbod** [comment]
would love to merge a PR if someone fix this
