### ISSUE TITLE
Problem to login to Facebook

### ISSUE THREAD

**Issue by zhouhao27** [jeduan/cordova-plugin-facebook4#192]
Here is what I did by following your document:

1. Create an app in FB
2. Add iOS platform in FB. Get the App Name and App id
3. Create an empty ionic 2 application

> ionic start demo blank --v2 --ts

4. Add the plugin with my own App Name and App id
5. Add a login method (I'm using ionic-native):

```
import {Facebook} from 'ionic-native';

@Page({
  templateUrl: 'build/pages/home/home.html'
})
export class HomePage {

  login() {

    Facebook.login(['email'])
      .then(data=>{
        console.log(data);
      },error => {
        alert(error);
      })
  }
}
```

6. Run app in my ios device
7. I got the following error message when I called the login method:

> 2016-04-05 12:23:17.887 LoginDemo[4706:98448] Starting login
> 2016-04-05 12:23:17.889 LoginDemo[4706:98448] -canOpenURL: failed for URL: "fbauth2:/" - error: "(null)"
> 2016-04-05 12:23:17.901 LoginDemo[4706:98448] -canOpenURL: failed for URL: "fbauth2:/" - error: "(null)"

What could be the reason? Thanks.

**Comment by zhouhao27** [comment]
Actually I'll get the following error message if I just run the app for a while without even call the **login** method:

> 2016-04-05 12:37:51.370 LoginDemo[5046:109732] FBSDKLog: Failed to send AppEvents: Error Domain=com.facebook.sdk.core Code=8 "(null)" UserInfo={com.facebook.sdk:FBSDKGraphRequestErrorCategoryKey=0, com.facebook.sdk:FBSDKGraphRequestErrorHTTPStatusCodeKey=400, com.facebook.sdk:FBSDKErrorDeveloperMessageKey=Unsupported post request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api, com.facebook.sdk:FBSDKGraphRequestErrorGraphErrorCode=100, com.facebook.sdk:FBSDKGraphRequestErrorParsedJSONResponseKey={
>     body =     {
>         error =         {
>             code = 100;
>             "fbtrace_id" = B8uuhUcsFpE;
>             message = "Unsupported post request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api";
>             type = GraphMethodException;
>         };
>     };
>     code = 400;
> }}

**Comment by zhouhao27** [comment]
Actually this error:

> -canOpenURL: failed for URL: "fbauth2:/" - error: "(null)"

Will not affect login because I tested with a sample iOS FB login application. I can't find the place to turn on "Deep linking".

**Comment by zhouhao27** [comment]
It turns out the problem is in the AppID. Solved.

**Comment by YaroslavG** [comment]
zhouhao27,
Hi, I have the same problem, can you help me?

**Comment by zhouhao27** [comment]
@YaroslavG My problem is my app bundle id is wrong. Please check that.

**Comment by AMKaffiOS** [comment]
I got a mistake when I click to login, and there was no response.

facebook login result.grantedPermissions = (null),error = Error Domain=com.facebook.sdk.core Code=3 "(null)" UserInfo={com.facebook.sdk:FBSDKErrorDeveloperMessageKey=Unknown error building URL.}

**Comment by madan34095** [comment]
I have same problem.
What can I do for it? Please let me know.
