### ISSUE TITLE
Cannot use minSdkVersion 14

### ISSUE THREAD

**Issue by aneeshATgithub** [jeduan/cordova-plugin-facebook4#196]
I cannot sync my project in Android Studio, I am getting message 
"suggestion: use tools:overrideLibrary="com.facebook" to force usage" 

I have used the following library

  'com.facebook.android:facebook-android-sdk:4.10.1'

**Comment by muliyul** [comment]
`com.facebook.android:facebook-android-sdk:4.11.0` uses minSdkVersion 15.
My guess is that `v4.10.1` uses the same minSdkVersion

https://developers.facebook.com/docs/android/getting-started/

Try to use earlier versions of the Facebook for android SDK.

**Comment by aneeshATgithub** [comment]
no problem, i solved it...go through the link....

http://stackoverflow.com/questions/36643824/suggestion-use-toolsoverridelibrary-com-facebook-to-force-usage
