### ISSUE TITLE
Can we get 1.7.1 release please?

### ISSUE THREAD

**Issue by jakub-g** [jeduan/cordova-plugin-facebook4#197]
It seems that for many people their cordova builds started failing lately with an error like

```
  Output:
    Failed to generate resource table for split ''
    .../platforms/android/build/intermediates/res/debug/values-v23/values.xml:6: error: Error: No resource found that matches the given name (at 'cardBackgroundColor' with value '?android:attr/colorBackgroundFloating').
```

See http://stackoverflow.com/q/36595119/245966

[PR 171](https://github.com/jeduan/cordova-plugin-facebook4/pull/171/files) fixes that. The PR was merged but the plugin didn't have a new version released. Can we have a 1.7.1 release?

**For all the people looking at this thread:** to have immediate fix, you can tweak your `package.json` or `config.xml` to target plugin directly via specific git commit locator, see:

See http://stackoverflow.com/q/36595119/245966

**Comment by superandrew** [comment]
+1 :(

Is there any way to use this fixed version in phonegap build? I'm a bit stuck with a broken app I need to release as soon as possible.. ouch.

**Comment by RustyGumbo** [comment]
+1

**Comment by lucasmenendez** [comment]
+1

**Comment by fx69005** [comment]
+1

**Comment by sidgujrathi** [comment]
+1

**Comment by superandrew** [comment]
is there someone following the project? to get the release going is it enough to accept the PR? in this case mabybe @jeduan could give someone access to the repo? '^^

**Comment by superandrew** [comment]
please take a look to a possible fix for this problem here, both for local or phonegap build

http://stackoverflow.com/questions/36595119/ionic-android-no-resource-found-that-matches-the-given-name-cardbackgroundcolo/36603653#36603653

**Comment by Habared** [comment]
Are you using cordova android 5?
In my case upgrading from 4.1.1 to 5.1.1 solved the problem.

**Comment by superandrew** [comment]
I am using phonegap build to build, not sure which android version uses.

**Comment by jeduan** [comment]
#201

**Comment by siddharth-arvan** [comment]
I resolve this error just by changing following framework version  in plugin.xml

From ` <framework src="com.facebook.android:facebook-android-sdk:4.+"/>`

 To `<framework src="com.facebook.android:facebook-android-sdk:**4.8.+**"/>`

#171

**Comment by Hirbod** [comment]
master is 1.7.1 - but still not on npm. later.
