### ISSUE TITLE
Is there a way to specify multiple APP_ID APP_NAME?

### ISSUE THREAD

**Issue by martyzz1** [jeduan/cordova-plugin-facebook4#199]
I'm trying to work out the best way to manage multiple environments for the our ionic app which uses this plugin. almost all other environment specific VARS (dev, staging, production) are taken from ENV and pushed into js constants... However I can't see how to make this approach work with this plugin.

I'm not a huge fan of trying to manipulate the config.xml before each build as this would involve unnecessary git  commits on config.xml. 

So I'm looking for any advice on how other people have managed this?

**Comment by jeduan** [comment]
I had a separate folder with `platforms/` and `plugins/` and a script that

 - symlinked the adequate folder
 - generated a `config.xml` from a template with the adequate variables
 - symlinked the icons and splash images
 - set environment and config variables so the code would know the app
 - symlinked the CSS files
 - called `cordova prepare`

No small feat, but it's the most reliable way we found to change between targets.
