### ISSUE TITLE
Support App Invites

### ISSUE THREAD

**Issue by jeduan** [jeduan/cordova-plugin-facebook4#2]
As requested in
https://github.com/Wizcorp/phonegap-facebook-plugin/issues/1055#issuecomment-121164901

**Comment by KeKs0r** [comment]
+1 this is the main point that is missing for me currently. Would be great if that would be supported.

**Comment by Jasphine** [comment]
Hi Jeduan,

Can I know if the plugin support App Invites? If no, can I know the ETA?

Appreciate your help. Thanks. :)

**Comment by jeduan** [comment]
Thanks for your question! Not supported right now, is in the works (there’s a branch with Android completed) but there’s no ETA yet, as I’m doing this on free time. If I had to guess I’d say within the next month for sure :)

**Comment by Jasphine** [comment]
Hi Jeduan,

Thanks for your answer. Could you please leave a message here when you have done?

Thank you very muchhhh...Really appreciate your answer....
Once again, Thank you....

**Comment by jeduan** [comment]
I'll close this issue and you'll get a notification.

**Comment by Jasphine** [comment]
Hi Jeduan,
 Oh i see. Thanks and appreciate your help. :)

**Comment by ArnaudValensi** [comment]
@jeduan I have completed your branch `feature/appinvites` there is still a NullPointerException when we begin the app invite and the we cancel.

For those who need it know, you can find it here: https://github.com/ArnaudValensi/cordova-plugin-facebook4/tree/feature/appinvites

**Comment by jeduan** [comment]
Thanks @ArnaudValensi !

**Comment by Jasphine** [comment]
Thanks... So AppInvite function is ready to use? :)

**Comment by jeduan** [comment]
@Jasphine Yes, please try v1.2.0

**Comment by vexsoluciones** [comment]
hello jeduan, 
is app invite working for ios??
