### ISSUE TITLE
Script to automatically install the latest iOS SDK with npm post-install

### ISSUE THREAD

**Issue by jeduan** [jeduan/cordova-plugin-facebook4#20]

**Comment by jeduan** [comment]
Not doable until Cordova 6

**Comment by fredgalvao** [comment]
Have you looked into bundling those dependencies or maybe doing some `sed` that needs no third party package? That way you wouldn't need to wait for it, specially since the status quo hasn't even been decided on about the npm environment stuff.

Or maybe I'm just missing something here.

**Comment by jeduan** [comment]
Yeah, my idea was to write a small script that downloaded the latest FB SDK for iOS after installation instead of committing the files to this repo, but without support for external dependencies I could maybe do manual node or expect the user to have curl installed which is going to be a support nightmare with Windows users.

**Comment by fredgalvao** [comment]
Please get any relevant feedback on this matter to the cordova team, it'll be very important to have a plugin author on the matter when deciding on cocoapods support.
