### ISSUE TITLE
Native app won't fire on iOS for login

### ISSUE THREAD

**Issue by villander** [jeduan/cordova-plugin-facebook4#202]
I following this tutorial in ionic docs. But in login the facebook is opened in safari browser.

http://ionicframework.com/docs/v2/native/Facebook/

How to open native app?

**Comment by YaroslavG** [comment]
hi, 
I have the same problem

**Comment by villander** [comment]
@jeduan why you closed my issue?

**Comment by jeduan** [comment]
This is an issue with the Facebook SDK. Raise an issue in that repo

**Comment by villander** [comment]
@jeduan there is no other way to make it work?
You had no experience with this?
In repo facebookSDK has enabled issues to open

**Comment by jeduan** [comment]
https://developers.facebook.com/blog/post/2015/10/29/Facebook-Login-iOS9

**Comment by mynote** [comment]
How did you even get the Login working? In my case IOS is completly ignored

**Comment by pilladooo** [comment]
I have the same issue @villander.

**Comment by mynote** [comment]
Read https://developers.facebook.com/blog/post/2015/10/29/Facebook-Login-iOS9. It's a typical behavior since its faster to open the webview instead the app

**Comment by Findiglay** [comment]
Is there any way for us to use this option while using the current plugin?

> 1.The SDK could continue to switch from your app to the Facebook app.

**Comment by jeduan** [comment]
@Findiglay do send a pull request if you find one. Good luck on your search.
