### ISSUE TITLE
It is always open the dialog box instead of the facebook app

### ISSUE THREAD

**Issue by dianikol** [jeduan/cordova-plugin-facebook4#205]
When i try to login the dialog opens instead of the facebook app i have installed on my device. I have xcode 7.3 and on my device iOS 9.3.1

**Comment by robertarnesson** [comment]
Since ios 9 this is the new flow that the facebook sdk is using. see https://developers.facebook.com/blog/post/2015/10/29/Facebook-Login-iOS9/

**Comment by dianikol** [comment]
Thank you for that. It makes sense!
