### ISSUE TITLE
 Problem after Installing the plug -in

### ISSUE THREAD

**Issue by atiladelcanton** [jeduan/cordova-plugin-facebook4#208]
Friends, after installing the plugin my application simply stopped buildar walk error when it tries to do : processDebugResources.

I will put the terminal output here

> :processDebugResourcesFailed to generate resource table for split ''
/Users/atilarampazo/Documents/projetos/clientes/movein_novo/platforms/android/build/intermediates/res/debug/values-v23/values.xml:6: error: Error: No resource found that matches the given name (at 'cardBackgroundColor' with value '?android:attr/colorBackgroundFloating').

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/usr/local/Cellar/android-sdk/24.4.1_1/build-tools/23.0.3/aapt package -f --no-crunch -I /usr/local/Cellar/android-sdk/24.4.1_1/platforms/android-22/android.jar -M /Users/atilarampazo/Documents/projetos/clientes/movein_novo/platforms/android/build/intermediates/manifests/full/debug/AndroidManifest.xml -S /Users/atilarampazo/Documents/projetos/clientes/movein_novo/platforms/android/build/intermediates/res/debug -A /Users/atilarampazo/Documents/projetos/clientes/movein_novo/platforms/android/build/intermediates/assets/debug -m -J /Users/atilarampazo/Documents/projetos/clientes/movein_novo/platforms/android/build/generated/source/r/debug -F /Users/atilarampazo/Documents/projetos/clientes/movein_novo/platforms/android/build/intermediates/res/resources-debug.ap_ --debug-mode --custom-package com.ionicframework.moveinnovo385943 -0 apk --output-text-symbols /Users/atilarampazo/Documents/projetos/clientes/movein_novo/platforms/android/build/intermediates/symbols/debug
  Error Code:
  	1
  Output:
  	Failed to generate resource table for split ''
  	/Users/atilarampazo/Documents/projetos/clientes/movein_novo/platforms/android/build/intermediates/res/debug/values-v23/values.xml:6: error: Error: No resource found that matches the given name (at 'cardBackgroundColor' with value '?android:attr/colorBackgroundFloating').
  	

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 30.776 secs

**Comment by robertarnesson** [comment]
what version of the plugin are you using?

**Comment by mwgjordan** [comment]
I'm getting the same issue on 1.7.0

**Comment by robertarnesson** [comment]
this has been fixed in master. use something like this:

<plugin name="cordova-plugin-facebook4" spec="https://github.com/jeduan/cordova-plugin-facebook4">
        <variable name="APP_ID" value="X" />
        <variable name="APP_NAME" value="Y" />
</plugin>

**Comment by mwgjordan** [comment]
Thanks @robertarnesson 

I think I had to do two things:

1. Update my package.json so that it grabs the latest plugin version from here

```
    {
      "variables": {
        "APP_ID": "123456",
        "APP_NAME": "myapp"
      },
      "locator": "https://github.com/jeduan/cordova-plugin-facebook4",
      "id": "cordova-plugin-facebook4"
    }

```

2. Ensure a later version of the sdk was being used.
```
  <preference name="android-minSdkVersion"      value="23" /> 
```

**Comment by atiladelcanton** [comment]
I managed to solve the changed file project.properties android - 22 target for android -23
