### ISSUE TITLE
Android install question

### ISSUE THREAD

**Issue by Danbardo** [jeduan/cordova-plugin-facebook4#209]
Hey,

This is probably a silly question but,

I've got this plugin working on iOS, however, on android it seems to be missing all of the Facebook SDK files.

When you guys are installing it, how are you including the sdk files?

I've tried importing the sdk from facebook, converting the aar file to get the sdk jar file, importing the sdk from cordova-plugin-facebook and importing a few other versions of the sdk.
When I say import, I add them to eclipse as an android project, make them a library then include them as a library for my app.

Each time my org.apache.cordova.facebook.ConnectPlugin.java cannot find any of the com.facebook files.

Thanks,

Daniel

**Comment by Danbardo** [comment]
For anyone in the same position I was in,

I downloaded the appropriate version of the Facebook SDK here:
https://developers.facebook.com/docs/android/downloads

(in my case it was 4.10.1 as it was the version currently supported by the plugin)

I extracted the facebook-android-sdk-4.10.1.aar file which is located in the facebook folder.
I changed the extension of the file from .aar to .zip
I opened facebook-android-sdk-4.10.1.zip
I extracted classes.jar and renamed it to FacebookSDK.jar (this contains all of the Facebook SDK)
I put the .jar file into my lib folder in my android project
I downloaded bolts, bolts-android-1.1.2.jar and also put that in my lib folder

**Comment by robertarnesson** [comment]
when you build android the sdk is downloaded and installed for you

**Comment by Danbardo** [comment]
Thanks for your answer,

Do you know where exactly the SDK files are downloaded from?

They're not downloading for me after using these commands:
cordova create test
cd test
cordova plugin add https://github.com/jeduan/cordova-plugin-facebook4 --save --variable APP_ID="123123123123" --variable APP_NAME="Test"
cordova platform add android
cordova prepare android

After running this set of commands the only file related to Facebook in the android project is ConnectPlugin.java.

If you take a look at this plugin on Github, there's no SDK files for android anywhere in the repository.

Is it supposed to download it from somewhere external from Github?

This might be a big ask, but would it be possible for you to run those commands on your computer to see if your SDK files download?

Thanks again for your answer,

Daniel

**Comment by robertarnesson** [comment]
you need to run cordova build android

**Comment by Danbardo** [comment]
Awesome, thank you!

**Comment by Danbardo** [comment]
Sorry for opening this again,

After cordova build android I have the Facebook SDK within inside the build folder of the project.

However, when I import the project into Eclipse it still does not properly link to the Facebook SDK.

All the com.facebook imports within the code are unresolved.

I've tried manually importing the Facebook SDK as project then adding it as a library to my Cordova project, but they still weren't resolved.

**Comment by robertarnesson** [comment]
this is an eclipse issue and not really within the scope of this plugin. however, you should be able to just add those paths to your eclipse environment
