### ISSUE TITLE
No events being logged on the Android version

### ISSUE THREAD

**Issue by manuelpaulo** [jeduan/cordova-plugin-facebook4#21]
You say: "Activation events are automatically tracked for you in the plugin." 
Meaning you must be calling the AppEventsLogger.activateApp.

Problem is I am getting no events from the Android version.

This is an issue you inherited from the previous now deprecated version of this plugin since it had the exact same problem.

Instead, I get this message from FB:

Why am I seeing this message: "Your app’s using an older version of the Android SDK and may not count all installs. Update your app to use the latest Android SDK."?

If you are using version 3.19.0 or earlier of the Facebook Android SDK, there is an issue with counting all installs. We recommend upgrading to the latest version of the Facebook Android SDK. This guide walks through updating to the latest version of the Android SDK.

**Comment by manuelpaulo** [comment]
You're calling AppEventsLogger.activateApp onResume only, not onDeviceReady. Am I wrong?

**Comment by jeduan** [comment]
You're correct. Feel free to send a PR

**Comment by manuelpaulo** [comment]
Problem is no IDs are being sent. It should be:

logger = AppEventsLogger.newLogger(cordova.getActivity().getApplicationContext(),"AppID");

AppEventsLogger.activateApp(cordova.getActivity(),"AppID");

**Comment by manuelpaulo** [comment]
Well I don't know what's wrong with your plug-in, but I used a work around in my app and added this to MainActivity.java  

```
 @Override
    protected void onResume() {
        super.onResume();
        com.facebook.appevents.AppEventsLogger.activateApp(this);
    }

    @Override
    protected void onPause() {
        super.onPause();
        com.facebook.appevents.AppEventsLogger.deactivateApp(this);
    }
```

This works.

**Comment by manuelpaulo** [comment]
Here: https://github.com/affinityis/phonegap-facebook-plugin/commit/837ed2e4db1c95a8320d473c8876738855c0ceb3

**Comment by Hirbod** [comment]
ping

**Comment by machei** [comment]
pong

**Comment by manuelpaulo** [comment]
???

**Comment by jeduan** [comment]
I've been very busy with the day job, if you can send a PR, I'll gladly
accept it, otherwise, it's a matter of waiting for the waters to be more
calm.

**Comment by DURK** [comment]
Any progress on this? @manuelpaulo I don't see how that piece of code fixed your problem, as this is exactly what is done in the plugin.

**Comment by jeduan** [comment]
v1.6.0 introduced a way to manually send activation events. https://github.com/jeduan/cordova-plugin-facebook4#manually-log-activation-events

**Comment by monove** [comment]
Any update on having all events available, not just activation?

**Comment by jeduan** [comment]
No updates in sight. This is a good first pull request if you want to take a stab at it.
