### ISSUE TITLE
Guide to importing using Eclipse

### ISSUE THREAD

**Issue by Danbardo** [jeduan/cordova-plugin-facebook4#210]
Hey guys,

I've spent the last day or so trying to figure out how to successfully use this plugin with Eclipse as, unlike cordova-plugin-facebook4, the android Facebook SDK is not included in the repository but is downloaded when the project is built using cordova build android [#209](https://github.com/jeduan/cordova-plugin-facebook4/issues/209).
The below guide assumes you have constructed your cordova project and included the plugin in the manner mentioned in [#209](https://github.com/jeduan/cordova-plugin-facebook4/issues/209).

The main problem I was facing was that when you download the Facebook SDK they provide you with a .aar file which contains the Facebook SDK project and a bunch of other stuff. I could never manage to import this to eclipse as a library, resolve all the errors and import into my project. When you do cordova build android, the .aar file is downloaded and automatically extracted into your applications build file, but you're using Eclipse, the extracted Facebook SDK will not properly link to your project.

Before starting:
Make sure you update your android SDK, in particular you'll need API 23 and the most recent Android Support Repository.

What I did was download the Facebook SDK source from Github:
https://github.com/facebook/facebook-android-sdk

Once downloaded I extracted the contents and took what I needed from it.

I took facebook-android-sdk/facebook/src/main
Renamed the folder "main" to "facebook"
Renamed the folder "java" to "src"
Pasted in the folder facebook-android-sdk/libs.

So my result was a folder called facebook with subfolders:
src
libs
res
And an AndroidManifest.xml

I took my facebook folder (which was formally called "rename") and pasted it into a separate location away from the Facebook SDK.

I imported this folder into Eclipse as an android project.

Once imported you may see a bunch of errors, to resolve most of them I:

Right clicked the facebook project in the Package Explorer in Eclipse.
Clicked Properties then Java Compiler.
Changed the Compliance level to 1.7.

Clicked Android and selected the project build target to be Android 6.0.
Entered a minSdkVersion in the app manifest
<uses-sdk android:minSdkVersion="14" android:targetSdkVersion="23" />

That solved the majority of the errors with in the project. The remaining I solved by importing the Android cardview and customtabs libraries into the Facebook project.

If you don't have cardview and customtabs in your package explorer:
Click file -> Import -> Existing Android Code
Navigate to your SDK/extras/android/support.
Import cardview and customtabs

To include them in your facebook library:
Right click your facebook project in Package Explorer.
Click Properties then Android.
Click "Add" and add both cardview and customtabs.
Before exiting properties do the LAST AND MOST IMPORTANT step:
Check Is Library

Now you can add your new facebook library to your cordova project.
(Right click your project, click properties, click android, click add, select facebook)

I hope this helps anyone who's trying to use this plugin with Eclipse. I really just wanted to get it written down somewhere in case I have to do it again.

**Comment by jeduan** [comment]
Thanks! Just adding that Android Studio is probably the blessed choice by Cordova and importing the project there is very easy (just import the gradle project in platforms/android). 

Please feel free to send this guide as a .md in a pull request.

**Comment by peterpeterparker** [comment]
Close, inactivity since 2016
