### ISSUE TITLE
Hide spinner

### ISSUE THREAD

**Issue by avielfedida** [jeduan/cordova-plugin-facebook4#212]
Is there a way, via javascript to [hide the spinner](https://github.com/Wizcorp/phonegap-facebook-plugin/issues/916), or maybe set something in the `config.xml`?, as I saw, there are many tricks to do so via `AndroidManifest.xml`, but upon platform or plugin removal the changes will lost, is there any convenient way to do so?

**Comment by VinceOPS** [comment]
Hi,

I'm looking for the same approach, it would be great to disable the spinner through an option in config.xml.

Thanks!

**Comment by melkir** [comment]
Me too !

**Comment by ebarault** [comment]
there is currently no way you can change this with the regular config.xml
one solution could be to use some hooks, just as in [this plugin](https://github.com/dpa99c/cordova-custom-config)
another solution is to create a custom plugin with merely only a plugin.xml file that you install right at the end of your other plugins and that will carry the lines for changing the spinner style

**Comment by ebarault** [comment]
on Android 6, you will nevertheless encounter a bug when changing theme to `NoDisplay`:
see [this link](https://commonsware.com/blog/2015/11/02/psa-android-6p0-theme.nodisplay-regression.html)
your app will crash with an `IllegalStateException` saying that your activity “did not call finish() prior to onResume() completing”. This, apparently, is a new requirement of `Theme.NoDisplay` activities.

this would require some mods in the plugin's android code for this to work

**Comment by peterpeterparker** [comment]
Close, inactivity since 2016
