### ISSUE TITLE
Track Install Source

### ISSUE THREAD

**Issue by monove** [jeduan/cordova-plugin-facebook4#213]
We have many campaigns and need to track which campaign app was installed from, if any.

Any suggestions?

**Comment by filipsuk** [comment]
Hi @monove, have figured this out? We have similar requirement.

**Comment by monove** [comment]
Nope. Sorry.

**Comment by esmiralha** [comment]
Same problem here.

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out the actively maintained fork `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect. If you're still experiencing issues, feel free to log a new issue there with more details.
