### ISSUE TITLE
logout does not reauth upon loggin back in

### ISSUE THREAD

**Issue by daveryaaziem** [jeduan/cordova-plugin-facebook4#214]
When I logout using facebookConnectPlugin.logout(), when I try to log back in, it reauth my facebook credential automatically. It does not ask to authorize facebook again.

**Comment by Epizefiri** [comment]
hi @daveryaaziem,
i've the same problem. Have you solved?

**Comment by daveryaaziem** [comment]
No,sorry l.



Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by jwaychee** [comment]
Having the same issue without solution yet.

**Comment by wparad** [comment]
The permissions are stored wdth facebook, logout, just does that.  If you want to force the user to reaccept permissions, the issue the revoke permissions api.

There is a problem with logout however which causes login to no longer cache loginstatus en browser refresh.

**Comment by jwaychee** [comment]
Thanks wparad.

**Comment by kinoli** [comment]
How do you call the revoke permissions api from your code?

**Comment by wparad** [comment]
Check out
https://developers.facebook.com/docs/facebook-login/permissions/requesting-and-revoking

Call the FacebookConnectPlugin.api(/me/permissions) etc...

**Comment by kinoli** [comment]
Thanks, but I'm not sure how you would call the DELETE endpoint from the plugin. Is there a way to do this?

DELETE /{user-id}/permissions

**Comment by wparad** [comment]
Hmmm, it really seems that this plugin doesn't have a graph api request
function.

I guess you would have to take the access token response you get from the
facebook getLoginStatus and pass it to an HTTP request:

DELETE graph.facebook.com
  /me/permissions?
    access_token={access-token}

**Comment by joefaron** [comment]
I think the issue is with the .logout() function.. 

The FB JS SDK's .logout() does not return user data upon a future getLoginStatus().. bummed about this.

.logout() does nothing.. i just cleared my app's memory/cache, tried again.. and I still got my fb data via getLoginStatus().

**Comment by marcelof49** [comment]
I found the way to delete user info for the app, you have to call the Graph API as following:

facebookConnectPlugin.api("/{user_id}/permissions?method=delete", [], success, error);

That way, you will have to accept the permits again when you call "login"

**Comment by neculaionutni** [comment]
> I found the way to delete user info for the app, you have to call the Graph API as following:

facebookConnectPlugin.api("/{user_id}/permissions?method=delete", [], success, error);

That way, you will have to accept the permits again when you call "login"

@marcelof49 that will only revoke the permissions, but it will not ask the user to enter the credentials to login again.

**Comment by tinoweb** [comment]
this way my problem was solved... thank @marcelof49 ...
facebookConnectPlugin.api("/{user_id}/permissions?method=delete", [], success, error);

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out the actively maintained fork `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect. If you're still experiencing issues with logout, feel free to log a new issue there with more details.
