### ISSUE TITLE
I didn't notification when using method appInvite

### ISSUE THREAD

**Issue by phanthinh** [jeduan/cordova-plugin-facebook4#215]
Hi everybody

I installed perfect this source however when i try send app invite request to my friend then him didn't see notitfication. What do u think about this?

**Comment by MisterDev** [comment]
Hi, I've managed to make them work today, these are my steps:

1) Create an App in developers.facebook.com
	- add ios and fill the BundleID, iPhone Store ID, iPad Store ID (iphone && ipad can be the same and you can find them in the section AppleID in the details of your app in the appstore)
	- add android and fill the Google Play package name

2) Go to the App Link generator.
	- choose ios and android
	- for ios fill URL with custom scheme(http://wiki.akosma.com/IPhone_URL_Schemes#Safari), App Store ID
	- for android fill the package name
	- click next and get the generated App Link URL

3) platform add android ---- plugin add cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="XXXXXXXXXX" --variable APP_NAME="XXXXXXXX"

Other tips:
- If your facebook app is in developer mode only people included as testers can receive invites. If you want to make it public you have to go in developers.facebook Settings( fill contact email) and App Review(make public)
- this plugin wont work in the browser
- The invites will only be visible in the app

Hope it helps

PS: these are my notes, English may not be perfect

**Comment by phanthinh** [comment]
Oh, when using this plugin seem in our system show web-view. I don't know application open webview maybe not correct. How do open app with this package? Can u help me, please.

**Comment by peterpeterparker** [comment]
Closed, `appInvite` doesn't exist anymore

https://github.com/jeduan/cordova-plugin-facebook4/issues/645
