### ISSUE TITLE
Crash on iOS during non-native login

### ISSUE THREAD

**Issue by Hypher** [jeduan/cordova-plugin-facebook4#216]
When FB is not installed natively, it opens a safari tab pointing on Facebook website. That could be handy but :
1) is there a way (configuration) to avoid that and handle the case by ourselves?
2) when closing the tab, nothing happens (stay on safari) 
3) when (re)accepting app authentication we get back on the app, but FB tab does not close (pollution)
4) randomly (90% times) right after the tab opening, I get a EXC_BAD_ACCESS on the WebThread of my app.
Trace (from lldb):

``` libGPUSupportMercury.dylib`gpus_ReturnNotPermittedKillClient
libGPUSupportMercury.dylib`gpusSubmitDataBuffers
libGPUSupportMercury.dylib`gldCreateContext
GLEngine`gliCreateContextWithShared
OpenGLES`-[EAGLContext initWithAPI:properties:]
OpenGLES`-[EAGLContext initWithAPI:sharedWithCompute:]
WebCore`WebCore::GraphicsContext3D::GraphicsContext3D(WebCore::GraphicsContext3D::Attributes, WebCore::HostWindow*, WebCore::GraphicsContext3D::RenderStyle)
WebCore`WebCore::GraphicsContext3D::create(WebCore::GraphicsContext3D::Attributes, WebCore::HostWindow*, WebCore::GraphicsContext3D::RenderStyle)
WebCore`WebCore::WebGLRenderingContext::create(WebCore::HTMLCanvasElement*, WebCore::WebGLContextAttributes*)
WebCore`WebCore::HTMLCanvasElement::getContext(WTF::String const&, WebCore::CanvasContextAttributes*)
WebCore`WebCore::JSHTMLCanvasElement::getContext(JSC::ExecState*)
WebCore`WebCore::jsHTMLCanvasElementPrototypeFunctionGetContext(JSC::ExecState*)
JavaScriptCore`lint_entry
JavaScriptCore`lint_entry
```

If I ignore the error and suspend this thread, I get a KILL from mutexwait on the main thread. If I go back to my app, the WebThread still loops on this EXC_BAD_ACCESS
I do not perform any canvas operation and don't understand this error.

I think if you provide a way for (1), I could use another authentication method.
Or maybe you could provide a method that tells us if FB native app is installed?

Thank you

**Comment by Hypher** [comment]
Obviously if the plugin could open this Facebook tab on an inappbrowser (which is what I want to achieve) that would be the icing on the cake

**Comment by peterpeterparker** [comment]
Close, inactivity since 2016
