### ISSUE TITLE
Deferred Deep Linking

### ISSUE THREAD

**Issue by sean-hill** [jeduan/cordova-plugin-facebook4#217]
Hi is this supported as referenced [here](https://developers.facebook.com/docs/app-ads/deep-linking#deferred-deep-linking) in this plugin? Thanks.

**Comment by robertarnesson** [comment]
it should work. see https://github.com/jeduan/cordova-plugin-facebook4/commit/f05ce3fdccd44023950e50fbd8c306b6a5349575

**Comment by sean-hill** [comment]
Cool! Does it work for android also?

**Comment by sean-hill** [comment]
I'm on version `1.7.0` right now, looks like this is new for `1.7.1`.

**Comment by robertarnesson** [comment]
this was a cleaned up PR from another user. Android implementation is needed and it should probably be renamed fetchDeferredAppLink rather than getDeferredAppLink. I'll try to fix this soon unless you want to have a crack at it

**Comment by sean-hill** [comment]
@robertarnesson do I need to call `getDeferredAppLink` within my app somewhere? Or does it automatically call it somehow.

**Comment by sean-hill** [comment]
Currently it looks like this code doesn't do anything since it's not called by `didFinishLaunchingWithOptions`.

**Comment by robertarnesson** [comment]
you would basically call it when your app is launching or resuming

**Comment by zakrava** [comment]
Please, are you planning to add this feature for Android as well?

**Comment by FME-nstokoe** [comment]
@robertarnesson Could you please elaborate on 'call it manually'?

**Comment by FME-nstokoe** [comment]
Ok I now see you mean calling ```facebookConnectPlugin.getDeferredApplink()``` in my javascript code. 

Another quick question: when testing this, is it possible to test the deferred linking with a modified version of my app built from xcode, or does this have to execute on the app downloaded from the app store?

**Comment by dts** [comment]
To test this, send yourself a link from Facebook, and when you click on it, and it takes you to an App Store page, run the app from Xcode instead.  Then when you run your getDeferredAppLink(), it'll open the URI.

**Comment by El-Shinnawy** [comment]
Hello, I tried to call getDeferredApplink but it always return "Invalid action",

I use it like this
window.facebookConnectPlugin.getDeferredApplink(function () {
            window.alert(result);
        }, function (error) {
            window.alert(error);
        });

**Comment by nstokoe** [comment]
@El-Shinnawy have you run facebookConnectPlugin.activateApp() before getDeferredApplink?

**Comment by El-Shinnawy** [comment]
Yes but it still doesn't work here is my full code

window.facebookConnectPlugin.activateApp(function (success) {
            window.alert(success);
        }, function (error) {
            window.alert(error);
        });

        window.facebookConnectPlugin.getDeferredApplink(function (result) {
            window.alert(JSON.stringify(result));
        }, function (error) {
            window.alert(JSON.stringify(error));
        });

I also tried to write it like this but still alerting 'Invalid action'

        window.facebookConnectPlugin.activateApp(function (success) {
            window.alert(success);
        window.facebookConnectPlugin.getDeferredApplink(function (result) {
            window.alert(JSON.stringify(result));
        }, function (error) {
            window.alert(JSON.stringify(error));
        });
        }, function (error) {
            window.alert(error);
        });

**Comment by sebaferreras** [comment]
@El-Shinnawy were you able to make deferred deep links to work using this plugin?

**Comment by JustasKuizinas** [comment]
Is deferred deep links working for someone? How did you make it work?

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect.

To use the `getDeferredApplink` method on iOS, you must use a plugin such as [cordova-plugin-idfa](https://www.npmjs.com/package/cordova-plugin-idfa) to request ad tracking permission.

For example:

```
cordova.plugins.idfa.requestPermission().then(function() {
  facebookConnectPlugin.setAdvertiserTrackingEnabled(true);
  facebookConnectPlugin.getDeferredApplink(function(url) {
    console.log('url = ' + url);
  });
});
```

On Android, no additional plugin is required.
