### ISSUE TITLE
Does this work with cordova 6?

### ISSUE THREAD

**Issue by ilyakar** [jeduan/cordova-plugin-facebook4#220]
Sorry for raising this as an issue, but I would like to know if it's possible to upgrade cordova versions.

**Comment by kingkarki** [comment]
yes it works with cordova 6. I am using this plugin on my cordova 6.1.1

**Comment by samparsky** [comment]
Please it is not working on ionic v2 and cordova 6+

**Comment by kingkarki** [comment]
I m not sure with Ionic v2. But it works with Ionic 1.7.14 with Cordova 6+. Thanks

**Comment by ilyakar** [comment]
Thanks guys, I will play with it. @jeduan if this plugin is indeed supported by the latest v6 cordova version, please update the compatibility of the README.md.

**Comment by ghprod** [comment]
I'm using ionic 2 and i can run this plugin, but the problem is every time user tap `Login with Facebook`, they still need to enter their credentials :(

Please note, user already login via native facebook app and messenger on their phone ..

so is this bug? expected behaviour? or because i use ionic 2?

Thanks

**Comment by kingkarki** [comment]
This is the facebook behaviour. Instagram also does same. Check with
instagram if you have installed on your phone. Thanks



Krishna Karki
CEO, The Next Coders
cell: +9779849624226 address: Kathmandu Nepal
email: developersnepal@gmail.com skype: kingkarki web:
http://thenextcoders.com
<http://facebook.com/thenextcoders>  <http://twitter.com/kingkkarki>
<http://instagram.com/krishnansu>

**Comment by robertarnesson** [comment]
this plugin works with cordova 6. readme updated
