### ISSUE TITLE
IOS share dialog

### ISSUE THREAD

**Issue by KorayKavruk** [jeduan/cordova-plugin-facebook4#221]
Hi

I see only href when share dialog open on ios native fb application but i want to see picture and caption. how can i solution this problem?

**Comment by garrettmac** [comment]
I too would like to know.

**Comment by MaelstromCdn** [comment]
This happens to me when I don't have the Facebook app installed. When it's installed, everything looks correct so I think it has something to do with the web-based flow.

**Comment by KorayKavruk** [comment]
@MaelstromCdn facebook app installed, but the problem continues :(

**Comment by KorayKavruk** [comment]
Don't have anyone help me?

**Comment by garrettmac** [comment]
the docs may be updated @KorayKavruk since last you downloaded it. Have you set a dialog mode?https://github.com/jeduan/cordova-plugin-facebook4#show-a-dialog

**Comment by bjakubiak** [comment]
I also have this issue on iOS, with FB app installed. Tried share_native dialog mode, no effect.

**Comment by VioletaCalvo** [comment]
In the [`README.md`](https://github.com/jeduan/cordova-plugin-facebook4/blob/master/README.md) of this repo:
>For options information see: [Facebook share dialog documentation](https://developers.facebook.com/docs/sharing/reference/share-dialog) [Facebook send dialog documentation](https://developers.facebook.com/docs/sharing/reference/send-dialog)

According to Facebook documentation:
`share` method does not support picture parameter, it takes meta params from the `href` URL
`feed` method does support picture parameter. See [Facebook feed dialog documentation](https://developers.facebook.com/docs/sharing/reference/feed-dialog#params)

**Comment by peterpeterparker** [comment]
Close, inactivity since 2016
