### ISSUE TITLE
What is the expected configuration for Facebook App with this plugin

### ISSUE THREAD

**Issue by jckermagoret** [jeduan/cordova-plugin-facebook4#222]
Hello,
What is the expected FB App configuration?

I have the usual error from facebook saying the provided URL is not allowed by the FB app. So my question is: what URL?

I tried:
* file:/// - doesn't work
* http://localhost/callback - doesn't work

Any other hints?

JC

**Comment by vikas0vanvi** [comment]
Hello , i have same problem , have you found any solution ?

**Comment by jckermagoret** [comment]
Hello,
I haven't had any answers/solutions based on facebook4. I finally use coenraets approach to connect to facebook with cordova:
* http://coenraets.org/blog/2014/04/facebook-phonegap-cordova-without-plugin/

It works well, is a little less tightly integrated, but it does the job perfectly. It gives me some time to wait for the right solution in a few days/weeks/month... ;-)

HTH,

JC

**Comment by vikas0vanvi** [comment]
thanks for reply , explanation was quite short in this one so found another solution from
https://www.sitepoint.com/how-to-integrate-facebook-login-into-a-cordova-based-app/
got it working in few minutes

**Comment by robertarnesson** [comment]
This is an error from the JS API and affects the browser platform only.  Its pretty simple, you need to set the URL to whatever url you are hosting your project at. If you are testing locally, your project is probably hosted at localhost:8080 or something similar, simply add localhost:8080 as allowed url. file:/// paths does not work

**Comment by rastermax** [comment]
I had this problem when running in emu or device. As robertanesson notes to me it also looks like a problem connected to browser mode (ie dev mode).

On my facebook dev account app :
once I added Android as a platform with a hash key, my cordova app with this plugin it did work as intended.
