### ISSUE TITLE
Issue signing in different user

### ISSUE THREAD

**Issue by hoffination** [jeduan/cordova-plugin-facebook4#223]
I've had an issue using the login endpoint.

When I sign-in with my normal phone's Facebook profile I can sign-in just fine. But when I try to sign out of Facebook on my phone to let a friend sign-in, the app has a difficult time using their Facebook credentials. They can sign-in to the Facebook app just fine but they can't use their credentials to authenticate using this plugin.

I debugged further and found the following error message returned in the callback: "User logged in as different Facebook user."

After looking around on stackoverflow I found this link: http://stackoverflow.com/questions/29791618/using-facebook-sdk-on-android-gives-user-logged-in-as-different-facebook-user

I'll try to upload a PR for this fix

**Comment by robertarnesson** [comment]
is this only an issue on android?

**Comment by hoffination** [comment]
I've only noticed this issue on android, but I'm not sure if it is also a problem on iOS.

**Comment by robertarnesson** [comment]
merged your fix 2505e005bbcbcc23463e6b68a52c49a2822efc74

**Comment by hoffination** [comment]
Awesome. Thanks!

**Comment by NavCore** [comment]
Login method always use already signed in user and do autologin without showing login dialog.

`facebookConnectPlugin.login(["public_profile", "email"], fbLoginSuccess, fbErrorHandler);`

If I call logout method and then login again it logs in automaticaly with previous user again.

`facebookConnectPlugin.logout(
        function(response) {
            fbLogoutSuccess
        },
        fbErrorHandler
    );`

??

**Comment by peterpeterparker** [comment]
Merge in 2016
