### ISSUE TITLE
iOS logout

### ISSUE THREAD

**Issue by jorgemejia** [jeduan/cordova-plugin-facebook4#227]
When I use the method logout and then I want to login again, the dialog displayed is this:
![photo1394408833526008](https://cloud.githubusercontent.com/assets/5246580/15582719/018863ac-2338-11e6-8b09-82e7799d3084.jpg)

Is there a way to show this one?.
For show this dialog, I have to erase the safary history navigation.
![photo1394408833526009](https://cloud.githubusercontent.com/assets/5246580/15582729/10fa7da2-2338-11e6-9884-05ae3a206cfe.jpg)

**Comment by jacquesdev** [comment]
What was the resolution for this issue?

**Comment by mahmoudissmail** [comment]
@jorgemejia , how i can solve this problem ?. When I use the method logout and then I want to login again the dialog displayed as authorized.

**Comment by Epizefiri** [comment]
hi @jorgemejia ,
i've the same problem. Have you solved?

**Comment by zencwh** [comment]
@jorgemejia did you solve it?

**Comment by jorgemejia** [comment]
I did not solve it, this issue is from Facebook SDK, infact if you have for example an instagram account and you use Facebook and you want to log out from instagram, and then you want to log in again, appears the same window, this is because the SDK uses the navigator for login.
For Android is different because the SDK uses the session from the Facebook app on Android you can log out from your app and this method kills the session from the Facebook app. Both works different.
