### ISSUE TITLE
iPhone native Facebook app

### ISSUE THREAD

**Issue by kraskoshnyy** [jeduan/cordova-plugin-facebook4#232]
Hi,
Got some problems in xCode module works perfect, I can share picture & link...
But on iPhone if I have a native app, then it open native windows for sharing and no desc, no picture...

And another strange point - if I have iphone app, when I login, it shows me browser login

Thanks

**Comment by jorgemejia** [comment]
I guess is a Facebook issue, if you check for example instagram, and you log out, then you log in again, tha app open a webview with the Facebook login, I guess this is how Facebook works with the new SDK. If you want to post a photo or checkin, you have to make a user feed, with this the app post the information without a share window. This is how I modify this plugin for do that.
[ios function.txt](https://github.com/jeduan/cordova-plugin-facebook4/files/291773/ios.function.txt)

**Comment by AsmaGargouri** [comment]
Hi, 
I have also a problem with iOS, it doesn't return any error.
Whenever i hit login button it doesn't log anything for me.
I think the configuration I've done for my platform on facebook devoloper is good.
also I've insalled well the plugin following the documentation.
Can you help please? 
It works perfectly on Android
