### ISSUE TITLE
Question About Auto Login Facebook

### ISSUE THREAD

**Issue by ghprod** [jeduan/cordova-plugin-facebook4#233]
Hi,

I've read that by using this facebook SDK, user can automatically give permission to our app without entering username/email/phone and password as long as user already loggedin into facebook via facebook app/messenger/facebook lite on their phone. 

Is it true? Is that expected behaviour?

Because when i try, i can succcessfully give permission to my app, but still on first load, user need to enter their credentials..

Thanks

**Comment by oneclickdev** [comment]
+1

**Comment by robertarnesson** [comment]
see https://developers.facebook.com/blog/post/2015/10/29/Facebook-Login-iOS9

**Comment by ghprod** [comment]
Seems like i need to add `Key Hashes`

Right now, its working like expected .. Thanks
