### ISSUE TITLE
iOS Single Sign On 

### ISSUE THREAD

**Issue by salcott** [jeduan/cordova-plugin-facebook4#234]
I'm struggling to achieve single sign on with iOS.

jquery mobile
cordova v5.3.3
cordova-plugin-facebook4 v1.7.1

Facebook Platform added: iOS, web
Single Sign On: enabled
Deep Linking: enabled

Any ideas?

**Comment by Prajwal-Balugu** [comment]
I too have the issue did you able to resolve it, I am able to login but it is opening login view in browser unable to get the credentials from facebook app which is already installed.

**Comment by AsmaGargouri** [comment]
Hi, 
I have also a problem with iOS. I am not able to login and it's not even opening a web view. When I hit login button it doesn't log any error.

Here is my configuration of iOS platform : 
![capture du 2016-06-09 17 31 13](https://cloud.githubusercontent.com/assets/15677298/15936308/cf9ce28a-2e6a-11e6-8a6d-8fc19f1c7e2e.png)

To install the plugin, I have put this in package.json 
`    {
      "locator": "cordova-plugin-facebook4",
      "variables": {
        "APP_ID": "my_app_ID",
        "APP_NAME": "my_app_name"
      }
    }`
which will fire : 
`cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="my_app_id" --variable APP_NAME="my_app_name"`

I have used the plugin to login in my controller this way : 


```
$scope.login = ->
            facebookConnectPlugin.login(['email,user_friends,public_profile,user_birthday'], fbLoginSuccess , fbLoginError)

    fbLoginSuccess = (userData) ->
            fbLogin(userData.authResponse.accessToken)


    fbLoginError = (error) ->
        $log.error "error facebook login: ", error

    fbLogin = (token) ->
        UserManager.fbLogin(token).then (res) ->
            # Login Success !!
            $rootScope.$broadcast('login:refresh')
            $ionicLoading.hide()
            # go to this after login
            $state.go 'base.profile.home', {}, {}
        .catch (error) ->
            # handle server error here
            $ionicLoading.hide()
            $log.debug 'loginFBerrorCtrl:', error
            $scope.error = error

```
In fact, It works perfectly on Android.
And when I tried to test on iOS, it didn't work and couldn't find out how to identify the problem.
I don't know what I have done wrong.  Can you help please?

**Comment by salcott** [comment]
Under further research I've found that this cordova facebook plugin fork uses Facebook SDK v4, which allegedly forces the user flow into an in-app browser because Facebook decided this is how they want to do things moving forward.  As far as I can tell, the only way to achieve Single Sign On (SSO) is to use a cordova facebook plugin that utilizes Facebook SDK v3.21.1 (such as https://github.com/Wizcorp/phonegap-facebook-plugin).  

Additionally, include this entry in your config.xml in order for SSO to work properly:
`  <string>fbauth</string>  
`

Hope this helps someone.

**Comment by Prajwal-Balugu** [comment]
have you run the application is it login from Native Facebook app

On Fri, Jun 10, 2016 at 8:40 AM, salcott <notifications@github.com> wrote:

> Under further research I've found that this cordova facebook plugin fork
> uses Facebook SDK v4, which allegedly forces the user flow into an in-app
> browser because Facebook decided this is how they want to do things moving
> forward. As far as I can tell, the only way to achieve Single Sign On (SSO)
> is to use a cordova facebook plugin that utilizes Facebook SDK v3.21.1
> (such as https://github.com/Wizcorp/phonegap-facebook-plugin).
>
> Additionally, include this entry in your config.xml in order for SSO to
> work properly:
> <string>fbauth</string>
>
> Hope this helps someone.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/jeduan/cordova-plugin-facebook4/issues/234#issuecomment-225083514>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AOTLPvnU10nL8ws9cjL77Si2vi92-UXZks5qKNW0gaJpZM4Ir_Fl>
> .
>



-- 
Regards,
Prajwal Kumar Balugu
Software Engineer | WINBOLD
Mob: +91-9700170021 | Mail: prajwal.balugu@winbold.com

**Comment by salcott** [comment]
Yes, it works. However that fork gave me trouble during installation so instead I ended up using this version:

https://github.com/Telerik-Verified-Plugins/Facebook

And it installed no problem.  I have verified that single sign on is working on my iOS device and the safari fall-back works as expected.

**Comment by rohanray** [comment]
@salcott Thanks for the info! I am using this plugin through a meteor plugin https://github.com/jsep/meteor-facebook-native-login for one of my meteor project which internally wraps this cordova plugin. I have not been able to get it running on iOS, however, it's working perfectly fine on Android. The point to note here is that in Android I do get  a native login using this plugin.

So is it that for iOS, it will do inapp browser while for Android it does native login. A bit confused here 😕

**Comment by lcfm** [comment]
Hi @rohanray , did you get this to work on iOS?
