### ISSUE TITLE
Unable to share image post

### ISSUE THREAD

**Issue by MaelstromCdn** [jeduan/cordova-plugin-facebook4#235]
I'm trying to share a link to an image Facebook post but the share dialog just shows "An error occurred. Please try again later". My options are defined as:

```
var options = {
method: 'share',
href: post.link,
caption: post.message
};
```

Any ideas? Do I have to set picture? I've tried several combinations with no success. I'm on an iOS device if that makes a difference (a note in the readme implies it might but I'm not sure if it was talking about the same thing).
Thanks, Jason

**Comment by peterpeterparker** [comment]
Plz use other channels like Stackoverflow for support
