### ISSUE TITLE
npm version of cordova-plugin-facebook4 seems outdated

### ISSUE THREAD

**Issue by zwacky** [jeduan/cordova-plugin-facebook4#240]
Hey everyone

Whenever i `cordova plugin add cordova-plugin-facebook4` I end up getting the version 1.0.0.
Adding a plugin through the git url directly results in 1.7.1.

Maybe an npm publish is missing?
Cheers

**Comment by robertarnesson** [comment]
1.7.1 is in npm. try to spec 1.7.1 explicitly - cordova plugin add cordova-plugin-facebook4@1.7.1
