### ISSUE TITLE
Graph API v2.0 will deprecate

### ISSUE THREAD

**Issue by rendi88** [jeduan/cordova-plugin-facebook4#246]
Hi guys.. im using cordova and using this plugin for facebook login..
this morning Ive got this email

"xxxx has been making recent API calls to Graph API v2.0, which will reach the end of the 2-year deprecation window on Monday, August 8, 2016. Please migrate all calls to v2.1 or higher in order to avoid potential broken experiences.

We recommend using our new Graph API Upgrade Tool to see which of your calls are affected by this change as well as any replacement calls in newer versions. You can also use our changelog to see the full list of changes."

what should I do ?? can I keep using this plugin or anybody had solution ??

**Comment by andrewb273** [comment]
+1 - I'm needing to transition from https://github.com/Wizcorp/phonegap-facebook-plugin due to lack of support, and this latest issue has hastened that. Hopefully this new repo will lead the way forward!

**Comment by blckshrk** [comment]
Same issue here :-/

**Comment by blckshrk** [comment]
The weird thing is when I check with Facebook API Upgrade Tool I get this : 

> Your app is already on the latest version of the API

So ? Is this a false positive ?

**Comment by spmvanmierlo** [comment]
+1. Had this issue yesterday!

**Comment by yonihei** [comment]
+1, same issue. pretty urgent

**Comment by ayyazzafar** [comment]
Same issue here too.. I also got this email...

**Comment by cchen-alison** [comment]
+1 Yeah I just got the email and was wondering the same thing. Is this repo still maintained?

**Comment by JerryBels** [comment]
+1

**Comment by eleva** [comment]
+1, got the email this morning.

**Comment by ronyrun** [comment]
+1

**Comment by debugerr** [comment]
Same for me. Would be great to get this updated.

**Comment by barocsi** [comment]
+1 @jeduan  any hints?

**Comment by jeduan** [comment]
That's for v2.0. This project is using v2.4 which will be supported way into 2017. No need to panic. see versions page at

https://developers.facebook.com/docs/apps/changelog

Now if any of you wants to send a documentation PR or watch the project to answer this to future people who inevitably open issues with the same question I'll be very grateful. 🙏

**Comment by spmvanmierlo** [comment]
@jeduan Why is the the showdialog with the 'feed' action not returning a postId anymore? I was assuming this had something todo with the API...

**Comment by JerryBels** [comment]
If I see the same question I will answer and link to this post, thanks @jeduan . The thing is, if nothing in this project causes Facebook to warn us about this... What could ? Another plugin ? Maybe the [SocialSharing](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin) plugin, I don't know about the others but I'm using that one.

**Comment by debugerr** [comment]
I'm not using any other FB related plug-ins if this is not the plugin causing FB to send out the notifications I don't know what it would be really. 

Is the npm version up to date @jeduan?

**Comment by jeduan** [comment]
@cchen_allison I try to keep it maintained however I burn out from time to time due to the sheer amount of issues and support needed and me being just one guy who does this on free time. Any tips?

**Comment by jeduan** [comment]
@spmvanmierlo @debugerr no idea on your issues. What you want should be possible. I suggest debugging the native parts of your app to make sure the code is sending the requests to Facebook properly.

**Comment by souly1** [comment]
+1 , nothing to add but a +1 :)

**Comment by yonihei** [comment]
May i ask please where is it documented that this current plugin uses facebook v2.4?
Im sorry but I've failed finding it. As far as i could guess, the "4" in facebook4 is named after the ios&android facebook's sdk

**Comment by jeduan** [comment]
@JerryBels no idea. Maybe you had some old app still using v2.0? Or they sent the email to everyone just in case?

**Comment by FlossyWeb** [comment]
+1 Got the notification from FB, maybe they got it wrong somehow...

**Comment by JerryBels** [comment]
@jeduan I don't think they sent it to everyone because they specifically named my app in the message, like OP quoted : 

> MyApp has been making recent API calls to Graph API v2.0

Also, that's the only app I have on this account. It's very strange. I hope we're not missing something. They could at least give more intel, like which type of call has been made, for us totrack it down easier ! I will try to find more about this.

**Comment by robertarnesson** [comment]
what version of the plugin are you using? You should be on 1.7.1 of this plugin which is targeting graph api 2.4

**Comment by nessche** [comment]
I also am on 1.7.1 and got the alert. I can very well be wrong, but I think it depends on the "double nature" of this plugin: the javascript part does indeed target 2.4, but the native part does not specify any version. For instance method `graphAPI` invokes in turn `FBSDKGraphRequest.initWithGraphPath` without any version information, which means that the default graph version is used.

**Comment by blckshrk** [comment]
@robertarnesson Personally I use the 1.7.0 version, should I update to the 1.7.1 to avoid this ?

As I said, Facebook also displays me that (for the same app) : 
> Your app is already on the latest version of the API

So it's a little bit weird.

**Comment by blckshrk** [comment]
@nessche If no version is specified, we could reasonably think that when the v2.0 gonna be deprecated, the next version gonna be used by default, right ? Could that make some breaking in this plugin ?

**Comment by robertarnesson** [comment]
@nessche Each facebook sdk targets a specific version of the graph api. SDK 4.8 is used in 1.7.1 which is targeting graph api 2.5.

Could it be that you have users that still have an old version of your app installed?

**Comment by nessche** [comment]
@robertarnesson It's a brand new app we have started developing one month ago....

**Comment by CharmySoft** [comment]
I only started using this plugin in development last week and I received this alert as well. It specifically named my app as the OP quoted. So I really don't think I have any other app that's still calling v2.0 apart from this plugin.

**Comment by greg84** [comment]
From what I see [here](https://github.com/jeduan/cordova-plugin-facebook4/blob/master/www/facebook-browser.js#L105), it looks like the plugin is using version 2.6, by default.

In my case I think I've received the email from Facebook because I'm authenticating the token on my server (the API my app talks to uses [facebook-csharp-sdk](https://github.com/facebook-csharp-sdk/facebook-csharp-sdk), which by default makes an '[unversioned](https://developers.facebook.com/docs/apps/versions#unversioned_calls)' call, in this case, downgrading to 2.0).

**Comment by herbzi** [comment]
I am also authenticating facebook tokens from my server (nodejs) and I am also using an unversioned call to the graph api. So that might be the case, thanks for the info greg84.

**Comment by winstef** [comment]
@greg84 Did you find a way to make the C# SDK to use the latest API version?

**Comment by andrewb273** [comment]
@greg84 A more comforting approach to verifying the version:

1. Get the SDK version in the Obj-C code by running the following:
`NSLog( @"### running FB sdk version: %@", [FBSDKSettings sdkVersion] );`
(I get 4.8.0 on the latest of this plugin)

2. Look up the version value on https://developers.facebook.com/docs/ios/change-log-4.x/#4_8_0. The last Graph API version tick up to that version was on 4.7.0, where they upgraded to Graph API v2.5.

I'm now confident that it's sufficiently up to date 👍

**Comment by andrewb273** [comment]
@winstef Do you mean the Obj-C code? The latest version of this plugin is using Graph API 2.5, which will be fine for a long time.

**Comment by EddyVerbruggen** [comment]
@JerryBels FYI SocialSharing is not using the Facebook SDK

**Comment by JerryBels** [comment]
@EddyVerbruggen thanks, I was pretty sure it was simply calling the app using its system name, but a confirmation is always welcome ! (I absolutely love your work BTW)

**Comment by mattblang** [comment]
@JerryBels @debugerr @nessche @blckshrk @CharmySoft Did any of you figure out what was causing your notification from Facebook regarding version `2.0`? I also came here thinking that this plugin was the culprit, which it does not seem to be. Interestingly, I went to the `upgrade tool` that Facebook references in the notification email and I only saw calls on version `2.3+` for our app. Weird.

**Comment by blckshrk** [comment]
@mattblang I think it's a false positive. Actually like you in the Facebook upgrade tool nothing seems bad...

**Comment by JerryBels** [comment]
@mattblang nothing for me... I have 1 last lead I'm looking at right now... If something comes up I will report here of course.

**Comment by nessche** [comment]
@mattblang Although I cannot completely rule out the false positive case, I looked into the package I used at the server-side, [passport-facebook-token](https://github.com/drudge/passport-facebook-token) . There were couple of unversioned calls to Graph APIs, now fixed with the latest release (3.3.0). I haven't received any other alerts from facebook, so I hope my app will not stop working on Aug 8th...
