### ISSUE TITLE
share dialog failed when use space in Display Name on facebook app, but remove space share worked.

### ISSUE THREAD

**Issue by Dukeduk** [jeduan/cordova-plugin-facebook4#247]
[http://i.imgur.com/AKklY2c.jpg](url)
- share dialog failed when use space in Display Name on facebook app, but remove space share worked. 
- when share dialog failed callback return errorMessage : Facebook error: Failed to authenticate the application because of app name mismatch. Please check the application name configured by the dialog.
- APP_NAME in config.xml and Display Name of facebook app are the same, but share failed still occur.

thank you, Araya

**Comment by schlaus** [comment]
I had the same problem. It seems adding the plugin doesn't work correctly if you happen to have a space in your app's name.

I got it to work again after manually updating the name in these files:
* `plugins/android.json`
* `plugins/fetch.json`
* `android/android.json`

The name has to be the exact same in Facebook's dev center and in your Cordova config for sharing to work.

**Comment by peterpeterparker** [comment]
Close, inactivity since 2016
