### ISSUE TITLE
How to take off loading facebook-native.js in cordova_plugin.js of browser platform?

### ISSUE THREAD

**Issue by mrcoolbiz** [jeduan/cordova-plugin-facebook4#249]
When i used cordova to build browser version, viewed it on browser, it came up with this error:
index.js:44 Uncaught ReferenceError: facebookConnectPlugin is not defined

So I check around and found the cordova_plugin.js load both navtive & browser file.

**{
        "file": "plugins/cordova-plugin-facebook4/www/facebook-native.js",
        "id": "cordova-plugin-facebook4.FacebookConnectPlugin",
        "pluginId": "cordova-plugin-facebook4",
        "clobbers": [
            "facebookConnectPlugin"
        ]
    },
    {
        "file": "plugins/cordova-plugin-facebook4/www/facebook-browser.js",
        "id": "cordova-plugin-facebook4.FacebookConnectPluginBrowser",
        "pluginId": "cordova-plugin-facebook4",
        "clobbers": [
            "facebookConnectPlugin"
        ]
    }**

Then I took part facebook-native.js out, it was good. I could access facebook. But problem is, whenever I emulate or build the browser again, the part that I deleted from cordovar_plugin just came back. Even I try to edit plugin.xml from our plugin/cordova-plugin-facebook4, took out all platform ios, android version, keep only browser. Take the j-module native too. But build and it just came back.

Anyone know how to solve it? Could you help me.
Thank you guys a lot

**Comment by robertarnesson** [comment]
fixed in e557377
