### ISSUE TITLE
Preparing for iOS9

### ISSUE THREAD

**Issue by manuelpaulo** [jeduan/cordova-plugin-facebook4#25]
iOS 9 introduces changes that are likely to impact your app and its Facebook integration.

Needed: 
- Facebook iOS SDK upgrade to v4.6.0 from 4.x or if you are on 3.x you should move to v3.24.
- Whitelist Facebook Servers for Network Requests

https://developers.facebook.com/docs/ios/ios9

**Comment by GitRubb** [comment]
+1

**Comment by christianseel** [comment]
@jeduan any near future plans to include iOS SDK 4.6.0? I'm working on a new app based on iOS9 and would appreciate the update :)

**Comment by Hirbod** [comment]
+1

**Comment by jeduan** [comment]
Just released v1.4.0-0 with SDK v4.6-beta

**Comment by Hirbod** [comment]
I love you so hard right now!

**Comment by jeduan** [comment]
:D Btw it looks like you need to explicitly specify the version to `cordova-cli` so make sure to specify the version like so:
`cordova plugin add --save cordova-plugin-facebook4@1.4.0-0 --variable APP_ID=${APP_ID} --variable APP_NAME=${APP_NAME}`

**Comment by Hirbod** [comment]
Why?

**Comment by jeduan** [comment]
probably cordova not willing to install a prerelease tagged version. I tagged it prerelease because it's using a beta SDK, but it's fully working in my tests.

**Comment by Hirbod** [comment]
I understand. I've never seend $(APP_ID) this kind of vars. How to use them?

**Comment by jeduan** [comment]
oh, just replace them with your Facebook's APP_ID. In my case I have them as env vars so that's why I put it like that.

**Comment by aferrerallu** [comment]
Thanks for this work @jeduan .
I have a question: Facebook SDK 4.6-beta only for iOs or updated for Android too?
If not, what version of the android sdk are you using?

**Comment by jeduan** [comment]
I made a change where it should always load the latest 4.x version, so it should build with 4.5 right now

**Comment by aferrerallu** [comment]
perfect. Thanks!

**Comment by sean-hill** [comment]
Hey @jeduan, now that the GM seed is out for iOS 9, is the framework still a beta version?
