### ISSUE TITLE
[iOS] appInvite does not call any callback

### ISSUE THREAD

**Issue by gianni-cossu-spindox** [jeduan/cordova-plugin-facebook4#253]
on iOS facebookConnectPlugin.appInvite 
- does not show any modal 
- does not call any callback
- does not show any error in console

for the same app on android all works fine

**Comment by gianni-cossu-spindox** [comment]
On android i can reproduce the error by rapidly clicking on the dialog while it's opening
The dialog closes and the fail callback is not called.

Could it be that in iOS there some issues with the dialog so that it closes silently?

**Comment by peterpeterparker** [comment]
Closed, `appInvite` doesn't exist anymore

https://github.com/jeduan/cordova-plugin-facebook4/issues/645
