### ISSUE TITLE
Add support for Windows & Windows Phone

### ISSUE THREAD

**Issue by andrewb273** [jeduan/cordova-plugin-facebook4#254]
Just a casual small request 😃 

Looking at delivering a Cordova app on Windows, and would love to allow Facebook login.

From brief research, there's a Windows SDK for Facebook by Microsoft (https://github.com/Microsoft/winsdkfb) that'd likely be a good pick.

**Comment by peterpeterparker** [comment]
Close, inactivity since 2016
