### ISSUE TITLE
I use plugin form master but still got error

### ISSUE THREAD

**Issue by thangman22** [jeduan/cordova-plugin-facebook4#257]
This is error when I try to build 
Users/waratwongmaneekit/Desktop/web/santabox/platforms/android/build/intermediates/res/debug/values-v23/values.xml:6: error: Error: No resource found that matches the given name (at 'cardBackgroundColor' with value '?android:attr/colorBackgroundFloating').

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/Users/waratwongmaneekit/Library/Android/sdk/build-tools/24.0.0/aapt package -f --no-crunch -I /Users/waratwongmaneekit/Library/Android/sdk/platforms/android-22/android.jar -M /Users/waratwongmaneekit/Desktop/web/santabox/platforms/android/build/intermediates/manifests/full/debug/AndroidManifest.xml -S /Users/waratwongmaneekit/Desktop/web/santabox/platforms/android/build/intermediates/res/debug -A /Users/waratwongmaneekit/Desktop/web/santabox/platforms/android/build/intermediates/assets/debug -m -J /Users/waratwongmaneekit/Desktop/web/santabox/platforms/android/build/generated/source/r/debug -F /Users/waratwongmaneekit/Desktop/web/santabox/platforms/android/build/intermediates/res/resources-debug.ap_ --debug-mode --custom-package com.ionicframework.starter -0 apk --output-text-symbols /Users/waratwongmaneekit/Desktop/web/santabox/platforms/android/build/intermediates/symbols/debug
  Error Code:
  	1
  Output:
  	Failed to generate resource table for split ''
  	/Users/waratwongmaneekit/Desktop/web/santabox/platforms/android/build/intermediates/res/debug/values-v23/values.xml:6: error: Error: No resource found that matches the given name (at 'cardBackgroundColor' with value '?android:attr/colorBackgroundFloating').

**Comment by thangman22** [comment]
My config.xml is already 
`    <plugin name="cordova-plugin-facebook4" spec="https://github.com/jeduan/cordova-plugin-facebook4">
        <variable name="APP_ID" value="x" />
        <variable name="APP_NAME" value="x" />
    </plugin>`

**Comment by edanchenkov** [comment]
Update you config.xml

**Comment by robertarnesson** [comment]
I would suggest to **not** build from master. use the latest release which is 1.7.1
