### ISSUE TITLE
Callbacks are not being called upon share_open_graph dialog

### ISSUE THREAD

**Issue by efishman15** [jeduan/cordova-plugin-facebook4#260]
Same as issue #134, this line is also missing at the "share_open_graph" block:
            // Set up the activity result callback to this class
            cordova.setActivityResultCallback(this);

I've added it locally and it resolved the issue.
Please fix this in an upcoming version.
Thanks,
Eddy

**Comment by peterpeterparker** [comment]
Close, inactivity since 2016
