### ISSUE TITLE
'appInvite' with no response?

### ISSUE THREAD

**Issue by aboutsam** [jeduan/cordova-plugin-facebook4#261]
hello, i always use for invite my friends to my app the "showDialog" function() but now (and i don't no when facebook change these parameters).. i had to use "appInvite" because my app is not a game and i get the error message "games requests are only available for games" .. now my question: how do i get the same result from "appInvite" like "showDialog" ?

![image](https://cloud.githubusercontent.com/assets/11192330/16727603/3aa93f28-4762-11e6-8f22-bbd044316059.png)

before i got the result of the send id. but with appInvite i don't get any response?

**Comment by peterpeterparker** [comment]
I close this, appInvite doesn't exist anymore

https://github.com/jeduan/cordova-plugin-facebook4/issues/645
