### ISSUE TITLE
not sharing photo with ios && android

### ISSUE THREAD

**Issue by feof** [jeduan/cordova-plugin-facebook4#263]
Hi,
I have this source: 

  $scope.shareFB = function(){
      facebookConnectPlugin.showDialog(
          {
            method: 'share',
            href: 'http://www.quicero.it',
            caption: $scope.postTemp.info,
            description: 'Entra anche tu nella comuninity di Quicero!',
            picture: $scope.postTemp.path
          },
          function (response) { console.log(JSON.stringify(response)); },
          function (response) { console.log(JSON.stringify(response)); });
    };

pictures: is a absolute url on http, like http://www.quicero.it/media/564a5d49b9fbfe456250151ac16e4a321468101574.jpg
href: i would that at click on post in facebook, it opens www.quicero.it
The result in android is perfect, in ios is a post empty.
![screen shot 2016-07-12 at 09 35 27](https://cloud.githubusercontent.com/assets/10772018/16758777/02a63448-4814-11e6-964c-112c65fc7226.png)

Help me please.

**Comment by vgiacchina** [comment]
Sorry, also android doesn't work.

      facebookConnectPlugin.showDialog({
        method: "feed", // jshint ignore:line
  picture:'https://www.google.co.jp/logos/doodles/2014/doodle-4-google-2014-japan-winner-5109465267306496.2-hp.png',
  name:'Test Post',
  message:'First photo post',
  caption: 'Testing using phonegap plugin',
  description: 'Posting photo using phonegap facebook plugin'
}, function (response) {
  console.log(response);
}, function (response) {
  console.log(response);
});

showdialog is empty, feed, send, share, same result.

**Comment by bjakubiak** [comment]
I have similar issue, but on iOS only. On Android it works fine.

On iOS it seems only **href** works correctly. **description**, **picture** and **caption** are ignored.

**Comment by andreaj8** [comment]
same for me :/ iOS and Android

**Comment by MTShare** [comment]
Same here

**Comment by fendorio** [comment]
Same here on IOS - This only happens when the facebook app is installed on the device for me.

**Comment by peterpeterparker** [comment]
Close, inactivity since 2016
