### ISSUE TITLE
Ionic 2 - Error {message: "Uncaught (in promise): null"

### ISSUE THREAD

**Issue by jlsuarezs** [jeduan/cordova-plugin-facebook4#264]
Hi Guys,

I am trying to use this plugin without success.

Everytime I try to call login I am getting this error:

`
Error {message: "Uncaught (in promise): null", line: 538, column: 41, sourceURL: "file:///var/containers/Bundle/Application/t.app/www/build/js/zone.js", stack: "resolvePromise@file:///var/containers/Bundle/Appli…B85135/t.app/www/build/js/zone.js:423:41"…}
`

Any help, please?

**Comment by robertarnesson** [comment]
something is wrong with your angular2/ionic2 setup. this is the wrong place for that..
