### ISSUE TITLE
cordova-plugin-facebook4 ionic facebookConnectPlugin is not defined

### ISSUE THREAD

**Issue by kingok** [jeduan/cordova-plugin-facebook4#265]
I'm working on ionic project and i have installed this plugin cordova-plugin-facebook4 but when i'm trying to use it in controller

```
    .controller('LoginCtrl', function($scope) {
        console.log ("dzdqsdqs");

    $scope.login=function() {
      console.log ("dzdqsdqs");
            facebookConnectPlugin.login(['email'], function(response) {
                alert('Logged in');
                alert(JSON.stringify(response.authResponse));
            }, function(error){
                alert(error);
            })
        }
})
```
I got this error : ReferenceError: facebookConnectPlugin is not defined

**Comment by VanVan** [comment]
You should not open an issue for this, but ask for help
If facebookConnectPlugin is not defined, this is because the plugin is not correctly included in your project.
You should start by searching "why" it is not correclty included.

**Comment by LuisUrrutia** [comment]
I have the same problem. Not sure if it's a problem with the code.

**Comment by fredgalvao** [comment]
You should make sure your code waits for the `deviceready` event from cordova instead. Mocking that variable in a global scope will only make it harder for you in the future to detect issues and work properly.

[Docs on that event.](https://cordova.apache.org/docs/en/latest/cordova/events/events.html#deviceready)

**Comment by Tower450** [comment]
Thanks a lot Luis it helped me!

**Comment by Sentence** [comment]
Issue stills up, cannot find any method to work. (Ionic with push plugin.)

**Comment by fquirogam** [comment]
Same problem here, anyone found a solution to this?

**Comment by argustinelli** [comment]
Anyone found a solution to this?

Fetching plugin "cordova-plugin-facebook4" via plugin registry

Error: connect ETIMEDOUT 50.17.177.14:80
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

Ionic Framework: 3.1.1
Ionic App Scripts: 1.3.7
Angular Core: 4.0.2
Angular Compiler CLI: 4.0.2
Node: 6.10.2
OS Platform: Windows 10

**Comment by Tower450** [comment]
i have a working fbconnection in my repositories if you need @argustinelli
