### ISSUE TITLE
Share Open Graph not working on iOS

### ISSUE THREAD

**Issue by VioletaCalvo** [jeduan/cordova-plugin-facebook4#268]
Hi!

First of all thank you for this plugin!

I'm using it in a Meteor app. I cannot reach to send an open graph story on iOS (no problem on Android). The dialog shows but no content is there and publish button of the dialog is disabled (same problem as [here](http://stackoverflow.com/questions/21552944/facebook-share-dialog-on-ios-publish-button-always-greyed-out?answertab=votes#tab-top))

This is the code for my custom story:

```coffeescript
object:
    'og:url': "http://myurl.com"
    'og:title': "A Title"
    'og:type': "namespace:app_object_type"
    'og:image': "http://imgurl.jpg"
    'og:description': "Some description"

shareData =
    method: 'share_open_graph'
    action: 'namespace.app_action'
    object: JSON.stringify(object)

fbError = (err) -> console.log err
fbSuccess = (res) -> console.log res
facebookConnectPlugin.showDialog(shareData, fbSuccess, fbError)
```

I also tested to share a `og.likes` story and I get the same problem.
I also added some lines to info.plist as detailed [here](https://medium.com/@spencer_carli/react-native-meteor-oauth-with-facebook-3d1346d7cdb7#.7tio5ejko)
Nothing works for me.

**Comment by VioletaCalvo** [comment]
This is fixed installing this plugin using last github tarball https://github.com/jeduan/cordova-plugin-facebook4/commit/454a6ecbfd579f6adde0da97777ed1f584e2caee instead of the version from the npm registry. Facebook web app is loaded instead of native app, but it works.

```shell
# use this command in the shell
meteor add cordova:cordova-plugin-facebook4@https://github.com/jeduan/cordova-plugin-facebook4/tarball/4763c7c4603ad6a283cc6e2c2cb8c075cd35d67f
```


```javascript
// Or use this inside a package.js
Cordova.depends({
  'cordova-plugin-facebook4': 'https://github.com/jeduan/cordova-plugin-facebook4/tarball/4763c7c4603ad6a283cc6e2c2cb8c075cd35d67f',
});
```

**Comment by rubenlpz** [comment]
@VioletaCalvo Using the command in shell that you suggest I got this error:
`Cordova error: Variable(s) missing (use: --variable APP_ID=value --variable APP_NAME=value).`

There is a way to set that variables from meteor?   Cordova command is not runnable since it's embedded in meteor...

**Comment by rubenlpz** [comment]
What I did to solve the issue of **missing variables** I mentioned was:
1. Download and unzip the package locally inside my app root directory /packages 
2. Edit the package.json, adding this to the top level {}:
`{ "locator": "cordova-plugin-facebook4", "variables": { "APP_ID": "my_app_ID", "APP_NAME": "my_app_name" } }`
3. Add the package to meteor referencing the local folder as explained in meteor tutorial:
`meteor add cordova:cordova-plugin-facebook4@file://packages/package-folder-name-here`
https://guide.meteor.com/mobile.html#installing-plugins

**Comment by rubenlpz** [comment]
The solution for using this plugin with meteor and properly load the APP_ID and APP_NAME is to add in mobile-config.js

App.configurePlugin('cordova-plugin-facebook4', {
  APP_ID: 'xxxxx',
  APP_NAME: 'YourAppName'
});

**Comment by VioletaCalvo** [comment]
@rubenlpz yes, you have to configure the package in the `mobile-config.js` as detailded [Meteor documentation](https://guide.meteor.com/mobile.html#installing-plugins)

> __Setting plugin parameters__
Some Cordova plugins require certain parameters to be set as part of the build process. For example, *com-phonegap-plugins-facebookconnect* requires you to specify an `APP_ID` and `APP_NAME`. You can set these using App.configurePlugin in your `mobile-config.js`.

(_sorry for the late reply_)
