### ISSUE TITLE
Logout null response

### ISSUE THREAD

**Issue by mahmoudissmail** [jeduan/cordova-plugin-facebook4#271]
When I use the  **logout** method and then I want to login again the dialog displayed as **authorized**. the **logout** function returned null response.
![f1](https://cloud.githubusercontent.com/assets/14803198/17061542/b6a117e4-5037-11e6-8037-a610bef21e27.jpg)

how can i solve **logout problem** to get the result below in screenshoot ?
![f2](https://cloud.githubusercontent.com/assets/14803198/17061662/4a764052-5038-11e6-9935-59a3824477d3.jpg)

**Comment by Epizefiri** [comment]
hi @mahmoudissmail,
do u have solved?

**Comment by zencwh** [comment]
I have same issue. Any solutions?

**Comment by gitlovenotwar** [comment]
Got the same issue, it can only go back when attempting to go to facebook and removing the app manually. I hope there's should be a fix to it.

**Comment by gianpaj** [comment]
the `logout()` function works for me (using cordova's InAppBrowser)

**Comment by mahmoudissmail** [comment]
@Epizefiri  it's not solved yet.

**Comment by mahmoudissmail** [comment]
@gianpaj  i'm also using ( Cordova InAppBrowser ) but its not working.

**Comment by peterpeterparker** [comment]
Close, inactivity
