### ISSUE TITLE
Picture too small

### ISSUE THREAD

**Issue by jonatarussi** [jeduan/cordova-plugin-facebook4#272]
Hi,

I'm trying to get the user picture with a big size, but the method: facebookConnectPlugin.api("/me/?fields=picture", [], onSuccess, onError) returns to me a 50x50 picture.

Someone knows how to get the picture in big size?

Thanks

**Comment by fredgalvao** [comment]
You don't need to specify `picture` as a field if you only want the large image. Instead, you can build the URL yourself after you get the User object from `/me/`:
```ts
getUrlForLargeImage(data: facebookapi.User):string  {
	return `https://graph.facebook.com/v2.4/${data.id}/picture?type=large`;
}
```

**Comment by jonatarussi** [comment]
Thanks
