### ISSUE TITLE
"Uncaught Exception: TypeError: undefined is not a function" on iOS login

### ISSUE THREAD

**Issue by maggix** [jeduan/cordova-plugin-facebook4#273]
Hi, I added the Cordova Plugin to my Ionic 1.3.1 project for iOS and Android. 
On Android emulator the code I wrote works fine, while on iOS I get the following error when I call the `facebookConnectPlugin.login` API, more precisely after I type my Facebook email and password and I authorize the app: `Uncaught Exception: TypeError: undefined is not a function`

I tried making my code as simple as possible and this is what it looks like: 

```
     facebookConnectPlugin.login(["public_profile", "email", "user_friends"],
      function (result) {
        console.log("FB success:" + JSON.stringify(result));
      },
      function (error) {
        var errorString = JSON.stringify(error);
        console.error("FB login error: " + errorString);
      }
    );
```

The Facebook login displays correctly, however after I authorize the app, the error I mentioned above is displayed, which unfortunately is not helpful. I have double-checked the iOS projects settings, and seem to be correct. It would be really appreciated if someone could verify if the issue can be replicated or is it related to my configuration.

**Comment by gmaggini** [comment]
Hi. An update: I have verified that this issue happens when adding the `cordova-plugin-mfp` to the project.

**Comment by robertarnesson** [comment]
is this still happening? guessing incompatibility issue with cordova-plugin-mfp

**Comment by peterpeterparker** [comment]
Close, inactivity
