### ISSUE TITLE
Can't get `login` to open Facebook app on iOS

### ISSUE THREAD

**Issue by matthewgertner** [jeduan/cordova-plugin-facebook4#274]
We have been using `com.phonegap.plugins.facebookconnect` and it opens the FB app on iOS when present to authenticate when `login` is called. We had to add a bunch of stuff to `config.xml` (see end of this post). We switched to `cordova-plugin-facebook4`, and now it always opens in the in-app browser for authentication, even though I'm using the same FB app that worked before. I removed all the stuff in `config.xml` as I gather that it isn't needed anymore, but the problem persists.

Any idea what the cause might be? The only info in the troubleshooting guide was to turn on deep linking but we've always had that enabled. I can step through the debugger to check what the plugin is doing, if that helps, but it just seems to be calling `FBSDKLoginManager.logInWithReadPermissions`.

Stuff that we added to `config.xml` (I've tried the new plugin both with and without this information, to no avail):

```
  <gap:config-file platform="ios" parent="NSAppTransportSecurity">
    <dict>
      <key>NSAllowsArbitraryLoads</key>
      <true/>
      <key>NSExceptionDomains</key>
      <dict>
        <key>facebook.com</key>
        <dict>
          <key>NSIncludesSubdomains</key>
          <true/>
          <key>NSExceptionRequiresForwardSecrecy</key>
          <false/>
        </dict>
        <key>fbcdn.net</key>
        <dict>
          <key>NSIncludesSubdomains</key>
          <true/>
          <key>NSExceptionRequiresForwardSecrecy</key>
          <false/>
        </dict>
        <key>akamaihd.net</key>
        <dict>
          <key>NSIncludesSubdomains</key>
          <true/>
          <key>NSExceptionRequiresForwardSecrecy</key>
          <false/>
        </dict>
      </dict>
    </dict>
  </gap:config-file>
  <gap:config-file platform="ios" parent="LSApplicationQueriesSchemes">
    <array>
      <string>fbapi</string>
      <string>fbapi20130214</string>
      <string>fbapi20130410</string>
      <string>fbapi20130702</string>
      <string>fbapi20131010</string>
      <string>fbapi20131219</string>
      <string>fbapi20140410</string>
      <string>fbapi20140116</string>
      <string>fbapi20150313</string>
      <string>fbapi20150629</string>
      <string>fbauth</string>
      <string>fbauth2</string>
      <string>fb-messenger-api20140430</string>
    </array>
  </gap:config-file>
```

**Comment by J-who** [comment]
This is how the login now works sadly. #205

**Comment by jacquesdev** [comment]
Thanks @J-who - this is really interesting.
