### ISSUE TITLE
App logs in but never fires event at facebookConnectPlugin.login

### ISSUE THREAD

**Issue by moriciogithub** [jeduan/cordova-plugin-facebook4#275]
Hello and thanks in advance.
1. My app calls the login method. (First time ever with no facebook app previous authorization.
2. Goes to the facebook app.
3. Before I accept the login in there, an error appears at the LogCat (look below)
4. I accept the login but the app never returns to fire the login events, obviously.

If I kill the app and re-run it, it will know it's connected to facebook and will continue. 
But the first time it is run it never returns from the login method.

After 

(line 595)        AccessToken accessToken = AccessToken.getCurrentAccessToken();

I added at line 596 in ConnectPlugin.java the following lines:

```
    if (accessToken == null) {
        return;
    }
```

And it's working. Is it correct to use those extra lines?

Mauricio Ramirez

My code:
        console.log("fblogin.js: " + "facebookConnectPlugin.login: PRE");
        facebookConnectPlugin.login( ["public_profile,email"],
            function (response) {
                console.log("fblogin.js: " + "facebookConnectPlugin.login" + JSON.stringify(response));
                if (response.status === 'connected') {
                    appPrepare();
                } else {
                    showfbLoginButton();
                }
            },
            function (response) { 
                console.log("fblogin.js: " + "facebookConnectPlugin.login" + JSON.stringify(response));
                showfbLoginButton();
                window.location.href = '#pageLogin';
        });

Output from my app:
facebookConnectPlugin.login: PRE

Events never get fired

logcat:

07-26 08:26:21.151: E/PluginManager(1789): Uncaught exception from plugin
07-26 08:26:21.151: E/PluginManager(1789): java.lang.NullPointerException
07-26 08:26:21.151: E/PluginManager(1789):  at org.apache.cordova.facebook.ConnectPlugin.executeGraph(ConnectPlugin.java:596)
07-26 08:26:21.151: E/PluginManager(1789):  at org.apache.cordova.facebook.ConnectPlugin.execute(ConnectPlugin.java:319)
07-26 08:26:21.151: E/PluginManager(1789):  at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
07-26 08:26:21.151: E/PluginManager(1789):  at org.apache.cordova.PluginManager.exec(PluginManager.java:133)
07-26 08:26:21.151: E/PluginManager(1789):  at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
07-26 08:26:21.151: E/PluginManager(1789):  at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
07-26 08:26:21.151: E/PluginManager(1789):  at android.webkit.JWebCoreJavaBridge.setNetworkOnLine(Native Method)
07-26 08:26:21.151: E/PluginManager(1789):  at android.webkit.JWebCoreJavaBridge.setNetworkOnLine(Native Method)
07-26 08:26:21.151: E/PluginManager(1789):  at android.webkit.WebViewCore$EventHub$1.handleMessage(WebViewCore.java:1428)
07-26 08:26:21.151: E/PluginManager(1789):  at android.os.Handler.dispatchMessage(Handler.java:99)
07-26 08:26:21.151: E/PluginManager(1789):  at android.os.Looper.loop(Looper.java:137)
07-26 08:26:21.151: E/PluginManager(1789):  at android.webkit.WebViewCore$WebCoreThread.run(WebViewCore.java:812)
07-26 08:26:21.151: E/PluginManager(1789):  at java.lang.Thread.run(Thread.java:856)

**Comment by ziobudda** [comment]
Have you tried a solution ?

**Comment by moriciogithub** [comment]
Yes. I had to modify the source code for android in this way:

ANDROID:
file: plugins/cordova-plugin-facebook4/src/android/ConnectPlugin.java
insert after line 595: 

from this:
        AccessToken accessToken = AccessToken.getCurrentAccessToken();
        if (accessToken.getPermissions().containsAll(permissions)) {
            makeGraphCall();
            return;
        }

to this:
        AccessToken accessToken = AccessToken.getCurrentAccessToken();
        if (accessToken == null) {
            return;
        }
        if(accessToken.getPermissions().containsAll(permissions)) {
            makeGraphCall();
            return;
        }

Also: In the source code of my login function:

I had to change

facebookConnectPlugin.login( ["public_profile,email"],

to this:

facebookConnectPlugin.login( ["public_profile","email"],

And now it works.

I hope it helps you.

Mauricio

**Comment by peterpeterparker** [comment]
Close, inactivity
