### ISSUE TITLE
Can't build a new ios app in build.phonegap.com with cordova-plugin-facebook4 plugin

### ISSUE THREAD

**Issue by razwasserstein** [jeduan/cordova-plugin-facebook4#276]
Hi, 
I have an ios app which I'm building with _build.phonegap.com_.
I tried to switch to the cordova-plugin-facebook4 so I add to the _config.xml_ file

`<plugin name="cordova-plugin-facebook4" spec="~1.7.1"> <variable name="APP_ID" value="xxx" /> <variable name="APP_NAME" value="x" /> </plugin>`

and got the error (after trying to build the app on build.phonegap.com) - _**Error - One of your plugins requires a parameter: APP_ID, APP_NAME**_

and in the log: 
**_"plugman install --platform ios --project /project --plugin cordova-plugin-facebook4@~1.7.1": Fetching plugin "cordova-plugin-facebook4@~1.7.1" via npm
Installing "cordova-plugin-facebook4" at "1.7.1" for ios
Failed to install 'cordova-plugin-facebook4':Error: Variable(s) missing: APP_ID, APP_NAME_**

**what am I doing wrong?**

**Comment by SidMehta** [comment]
Same issue. Did you find any solution?

**Comment by robertarnesson** [comment]
see https://github.com/jeduan/cordova-plugin-facebook4/issues/296
