### ISSUE TITLE
Show Dialog is still empty when sharing picture (feed method)

### ISSUE THREAD

**Issue by auching** [jeduan/cordova-plugin-facebook4#279]
I use the 'feed' method instead of 'share' in order to share images in my app:

var params = {
                                method: 'feed',
                                link: 'http://test.com',
                                caption: 'My Caption',
                                description: 'My Description',
                                picture: my_pic_link
 };

But the content is still empty in iOS (iOS 9).  Is that this plugin doesn't support the 'feed' dialog method?

**Comment by TheBosZ** [comment]
The "feed" method is exactly the same as the "share" method.

Can you try the suggestion I posted to #283 and see if it works?

**Comment by peterpeterparker** [comment]
Close, inactivity
