### ISSUE TITLE
Given url is not allowed by the application configuration

### ISSUE THREAD

**Issue by imktks** [jeduan/cordova-plugin-facebook4#28]
Hello,

i installed this version of the facebook connect plugin and when i run it on a real device for debugging purposes i am constantly receiving this message "Given url is not allowed by the application configuration". I have tried to add many different valid auth redirect urls but no luck. Do i need to create hashes for my application if it is under debug mode? 

Please help me because i can't find a solution that works..
Thank you in advance!

**Comment by imktks** [comment]
It was my fault at last. I ignored to add my package name!

**Comment by kodeine** [comment]
@imktks can you tell me how you fixed this error?
