### ISSUE TITLE
installing to specific platform

### ISSUE THREAD

**Issue by circuitrider** [jeduan/cordova-plugin-facebook4#280]
I have separate machines for working on my app on android and ios. I am able to install this on my android dev machine and it sticks even though the ios install fails. But I am unable to install the ios version because android fails on it first.

Is there a way to specify to install this only on ios (or any platform) and ignore others?

**Comment by fredgalvao** [comment]
No. That's not even an issue with this plugin itself, but instead how cordova works internally. If you'd like that to be a feature, creating an issue at issues.apache.org/jira/browse/CB is the right thing to do.
