### ISSUE TITLE
Caption, picture description nothing working in feed.

### ISSUE THREAD

**Issue by sangeethkumarsg** [jeduan/cordova-plugin-facebook4#283]
I am using this plugin for facebook feed method to post to facebook. Here is my code

`

```
        facebookConnectPlugin.showDialog( 
            { method: "feed",
                name: "I enjoyed "+title,
                caption:"Awsome experience",
                description: "Experienced like never before",
                picture: image,
                href:image
            }, 
            function (response) { 
                console.log(JSON.stringify(response)); 
                $cordovaToast.showLongBottom('Posted Successfully').then(function(success) {
                    // success
                }, function(error) {
                    // error
                });
            },
            function (response) { 
                console.log(JSON.stringify(response)) 
                $cordovaToast.showLongBottom('Error. Try again later.').then(function(success) {
                    // success
                }, function(error) {
                    // error
                });
            }
        );
```

`

The variables title and images are printing correctly in console
I am using iOS 8.3.4 for testing. While posting, only image is getting posted. Caption, description, nothing is coming.

Any help is appreciated.

**Comment by TheBosZ** [comment]
It's possible that you're running into this issue: http://stackoverflow.com/questions/33148544/facebook-share-content-only-shares-url-in-ios-9

Can you set the options like this:
```
{
    share_feedWeb: true
}
```

And try it?

**Comment by TheBosZ** [comment]
Looks like the code here on GitHub is newer than what npm is providing.

`share_feedWeb` isn't a thing yet, we only have a choice between `share_feedBrowser` and `share_sheet`.

If you don't want to try to figure out how to use the plugin here from Github, try it with 
```
{
    share_feedBrowser: true
}
```

**Comment by auching** [comment]
but the name/caption/description are still not shown after shared.

**Comment by TheBosZ** [comment]
It looks like, for iOS at least, information from the link's website will override those.

I can't find any information about why it does that on iOS but not Android.

It looks like there's a new "quote" field on the latest SDK but this plugin doesn't support it yet.

If I get some free time, I'll do it and submit a pull request.

**Comment by caiooaugusto** [comment]
`{
      method: 'share',
      picture: this.photo,
      name:'Test Post',
      message:'First photo post',    
      caption: 'Testing using phonegap plugin',
      description: 'Posting photo using phonegap facebook plugin'
 }`
i'm getting the same issue, name, message, caption and description does not displayed in facebook post.

**Comment by peterpeterparker** [comment]
Close, inactivity
