### ISSUE TITLE
EXCEPTION: Error: Uncaught (in promise): There was an error making the graph call. IOS

### ISSUE THREAD

**Issue by AvBrocklehurst** [jeduan/cordova-plugin-facebook4#284]
Copied issue from the original plugin as this one is more active.

https://github.com/Wizcorp/phonegap-facebook-plugin/issues/1268

**Comment by fredgalvao** [comment]
Copying an issue from that original plugin to this one won't actually make it still valid. This fork has diverged from the one from Wizcorp by a lot, and the chances that your issue doesn't even exist in this one is pretty high.

I'll close this one, and if you can reproduce the error using this version (jeduan's) instead, then you can reopen this issue and someone could try to take a look at it. Also, try to provide more details as to how to reproduce the error you encountered.

**Comment by atlanlin** [comment]
I am having this issue. My ios version is 9.3.5. I am running with Ionic framework. It works fine on android.

**Comment by atlanlin** [comment]
I fixed my problem - solution is in #338

**Comment by lucasKhane** [comment]
Yes, for me works also your solution...but very stupid thing really, i cant believe that that was the problem
