### ISSUE TITLE
Plugin not working for ios anymore

### ISSUE THREAD

**Issue by chhrahul** [jeduan/cordova-plugin-facebook4#287]
From yesterday, the plugin has stopped installing on phonegap build. I see this error http://prntscr.com/c073t2 when i try to install it. I have mentioned 0.9.0 version of this plugin in my config.xml file. 

Nothing was changed in my config file, still it is giving me error and i am not able to run my whole app at the moment because of this error.

**Comment by fredgalvao** [comment]
You're looking at the wrong plugin, `phonegap-facebook-plugin` is the identifier of another plugin.

The identifier of this plugin is `cordova-plugin-facebook4`.
