### ISSUE TITLE
[iOS] Log Event Without Facebook Login

### ISSUE THREAD

**Issue by roblav96** [jeduan/cordova-plugin-facebook4#292]
On android, I can call `facebookConnectPlugin.logEvent` no problem even if the user is not logged in with Facebook. The events debugger confirms the event being logged.

But on iOS when I call `facebookConnectPlugin.logEvent` the event is **only logged** when the user signs in with Facebook.

Any thoughts on how to remedy this? Thank you!

**Comment by robertarnesson** [comment]
not an issue with the plugin but rather the fb sdk
