### ISSUE TITLE
Changing app id

### ISSUE THREAD

**Issue by circuitrider** [jeduan/cordova-plugin-facebook4#293]
I am not sure if this is a plugin or a cordova problem, but despite doing the command "cordova clean" when I build and deploy to android, my app id changed in config.xml isn't being updated during the deployment. It still has the same app id. What is the proper procedure for making sure the app id is updated during a build? I've made sure during my testing to fully uninstall the app on my test device so this isn't a case of a failed app upgrade leaving in place configurations.

**Comment by fredgalvao** [comment]
Check [this PR](https://github.com/jeduan/cordova-plugin-facebook4/pull/281) that has just recently been merged.

**Comment by circuitrider** [comment]
Thanks. I found in the meantime I can fix the app id in platform/android/res/values/facebookconnect.xml and in platform/android/android.json

I'm not sure if I'm doing something wrong in my environment, but it is very onerous for me to remove and re-add plugins because I am doing android work and another dev is doing ios work and when we have to touch plugins it always breaks the other person's environment. I know that's out of scope of this project, but lmk if you know of anything that might be done to avoid or prevent that...

**Comment by fredgalvao** [comment]
Not much, actually. It's more of a cordova thing, as it needs to propagate information like plugin variables to many layers/files for it to end up in facebookconnect.xml, for example. You either reinstall it or understand the platform well enough to know where to mannually change to mimic the true propagation.

**Comment by happy2share** [comment]
Check the APP_ID in config.xml at the project root and update accordingly. Here is the sample entry

<plugin name="cordova-plugin-facebook4" spec="~1.7.4">
        <variable name="APP_ID" value="1476**********5" />
        <variable name="APP_NAME" value="R********" />
    </plugin>

**Comment by fredgalvao** [comment]
Changing that alone will not propagate the updated variable to all needed places, AFAIK.

**Comment by galilo7** [comment]
> Thanks. I found in the meantime I can fix the app id in platform/android/res/values/facebookconnect.xml and in platform/android/android.json
> 
> I'm not sure if I'm doing something wrong in my environment, but it is very onerous for me to remove and re-add plugins because I am doing android work and another dev is doing ios work and when we have to touch plugins it always breaks the other person's environment. I know that's out of scope of this project, but lmk if you know of anything that might be done to avoid or prevent that...

I have been searching for solution for several days
