### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by baviskarmitesh** [jeduan/cordova-plugin-facebook4#295]
After adding this plugin into my project I am getting 
Failed to generate resource table for split '' error while building project

FAILURE: Build failed with an exception.  
Execution failed for task ':processDebugResources'. 
com.android.ide.common.internal.LoggedErrorException: Failed to run command:
E:\Softwares\Android-Sdk\build-tools\24.0.0\aapt.exe package -f --no-crunch -I E:\Softwares\Android-Sdk\platforms\android-21\android.jar -M E:\Projects\Ionic Projects\..ccer\platforms\android\build\intermediates\manifests\full\debug\AndroidManifest.xml -S E:\Projects\Ionic Projects\....er\platforms\android\build\intermediates\res\debug -A E:\Projects\Ionic Projects\....er\platforms\android\build\intermediates\assets\debug -m -J E:\Projects\Ionic Projects\....er\platforms\android\build\generated\source\r\debug -F E:\Projects\Ionic Projects\.....er\platforms\android\build\intermediates\res\resources-debug.ap_ --debug-mode --custom-package com.ts...ccer -0 apk --output-text-symbols E:\Projects\Ionic Projects\..ccer\platforms\android\build\intermediates\symbols\debug

**Comment by nikiben** [comment]
I'm getting the same error. I have just installed the latest@1.7.1 yesterday...

**Comment by jacquesdev** [comment]
The issue has already been logged here #197
