### ISSUE TITLE
XCode error

### ISSUE THREAD

**Issue by christianseel** [jeduan/cordova-plugin-facebook4#3]
Hi! I'd love to use the recent Facebook SDK version, so I tried your fork. However I'm getting the following error in XCode when I try to build on my test device:

```ld: 'AppProject/Plugins/cordova-plugin-facebook4/FBSDKCoreKit.framework/FBSDKCoreKit(FBSDKGraphRequestPiggybackManager.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture```

Honestly I have no idea what that means or how to solve it. Could you help?
I use Xcode 7 beta and try to build for iOS 9.

**Comment by jeduan** [comment]
Hi! I haven't started iOS 9 yet but this seems to refer to app thinning which looks like Facebook SDK doesn't support yet. This looks to be a good workaround. http://stackoverflow.com/questions/30848208/new-warnings-in-ios9

**Comment by christianseel** [comment]
Ha! Thanks @jeduan ! Setting `Enable Bitcode` to `No` in the Build settings fixed it.

For all others trying to build for iOS9, you might see an other issue where the native facebook app won't open and you find `canOpenURL: failed for URL: "fbauth://authorize/?client_id=... error: "This app is not allowed to query for scheme fbauth"` in your log.
You need to add this to your projects plist file:
```
<key>LSApplicationQueriesSchemes</key>
<array>
    <string>fbauth</string>
</array>
```
(via http://stackoverflow.com/questions/30736663/swift-2-parse-facebooksdk-ios9)

**Comment by contra** [comment]
Would be good if that was included as a hook ^

**Comment by rossmartin** [comment]
@christianseel Thank you so much wish I could give you a beer.

**Comment by pablolopesk8** [comment]
Thank u @christianseel e @jeduan  . This works fine.

**Comment by YaroslavG** [comment]
Hi, 
this plugin perfect works on IOS 8.4, but does not work for IOS 9 and more
I get this error:
-canOpenURL: failed for URL: "fbauth://authorize?
and my screenshot 
![2016-04-12 21 11 59](https://cloud.githubusercontent.com/assets/5793103/14470632/3f208ecc-00f3-11e6-82d9-c890cc9fbf75.png)

**Comment by houmie** [comment]
Just added ```pod 'Facebook-iOS-SDK'``` and still can't build, since the project is bitcode enabled.

Any ideas what I could do? I get the same error message.
