### ISSUE TITLE
Login / Installed differences

### ISSUE THREAD

**Issue by DarioCorno** [jeduan/cordova-plugin-facebook4#301]
The getcurrentstatus functions seems to return a connection even if the user "never ever" used that app on the mobile device, but just has it installed in the Facebook user's Apps.

I used that FB app to login to a website from a desktop browser, so I have the Fb app listed in my Facebook User's Apps.

I never did a login from a cordova/phonegap/mobile device to that FB App, but the plugin returns an active connection (login fails, getcurrentstatus returns user data). Is that a correct behaviour? Should the plugin "think" I'm already connected from the device even if I only did a login from a different desktop browser?

**Comment by peterpeterparker** [comment]
Close, inactivity
