### ISSUE TITLE
 Insecure endpoint 'fbconnect://success'. This endpoint should be made available over a secure connection

### ISSUE THREAD

**Issue by flashmob** [jeduan/cordova-plugin-facebook4#302]
Platform: Android 6
cordova-plugin-facebook4: 1.7.1 (from github)
cordova: 6.3.0
When Facebook App is not installed, this error occurs after correct password is entered, on both emulated and real device.

Works fine when Facebook App is installed.

Full Error:

"Mixed Content: The page at 'https://m.facebook.com/v2.5/dialog/oauth?redirect_uri=fbconnect%3A%2F%2Fsuccess&display=touch&scope=public_profile%2Cemail&response_type=token%2Csigned_request&default_audience=friends&return_scopes=true&auth_type=rerequest&client_id=1076131932432178&ret=login&sdk=android-4.8.2&logger_id=5cfecfe2-e170-4d0a-9741-b47e96942a1b&ext=1471827485&hash=AeZP683wYwZV27qY#_=_' was loaded over a secure connection, but contains a form which targets an insecure endpoint 'fbconnect://success'. This endpoint should be made available over a secure connection.", source: https://fbstatic-a.akamaihd.net/rsrc.php/v2iT4e4/yh/l/en_US/ib7XrcO3R3c.js (60)

Any help appreciated.

**Comment by peterpeterparker** [comment]
Close, inactivity
