### ISSUE TITLE
Can not log out properly

### ISSUE THREAD

**Issue by boyandimitrov** [jeduan/cordova-plugin-facebook4#303]
Please, any ideas what might cause my issue?

[detailed info](http://stackoverflow.com/questions/39116951/phonegap-facebook-plugins-dont-logout-properly)

**Comment by robertarnesson** [comment]
seems like the problem is with the facebook sdk, not the plugin. https://developers.facebook.com/bugs/297086380683342/

which version of cordova-plugin-facebook4 are you using?

**Comment by boyandimitrov** [comment]
I know this thread and I posted there also. 
I'm not in front of the computer to say the exact version, but I'm installing it from github

**Comment by TheNuclearCat** [comment]
I got the latest version. I have readed a bit about the facebook bug, it seems like that facebook is not checking the hashkey on the first login and after its checking and returning the wrong error message. I can´t confirm this yet. I will test it soon.

**Comment by TheNuclearCat** [comment]
Found the solution for Android! I can confirm it. Just use this tutorial and setup you hashkey for android here: https://software.intel.com/en-us/xdk/articles/facebook-android-keyhash
I guess iOS has the same problem, that some platform settings were not done.

**Comment by boyandimitrov** [comment]
I also can confirm the following:
1. When you log for the first time, Facebook do not check the hash key
2. This link is the better way to generate the hash key compared to the official facebook instructions.

**Comment by MOHAMMADArsalan** [comment]
i had have same problem i just solved it.

1) copy the hash key from error message 
2) then go to developer.facebook.com and change previous to new one 

now its working fine for me

**Comment by foram-patel** [comment]
+1 for this link...Great... i had same problem but this link is giving nice solution actually solved problem...thanx....

**Comment by peterpeterparker** [comment]
Close, inactivity
