### ISSUE TITLE
Login works once.

### ISSUE THREAD

**Issue by afxgroup** [jeduan/cordova-plugin-facebook4#304]
i'm facing a strange problem with plugin. If i make the Login for the first time (and the user has not authorized the application yet) the facebookConnectPlugin.login(['email', 'public_profile'].. works as expected. The facebook app is shown and i can authorize the app without any problem and also the response is correct.
But if i try to relog again i get a facebook  error without any error code. I get only something like "An error ocurred. Please try again later" (in italian so i don't know if the message is this one).
If i remove the app from my user and then try to relog all is working as expected.
I've also tried to use facebookConnectPlugin.getLoginStatus when the app is authorized but i get "unknown" as result

Intel XDK
Cordova version 5.4.1
Facebook plugin 1.7.2

[Edit]
On iOS clicking the second time on login button does nothing

![screenshotfb](https://cloud.githubusercontent.com/assets/484672/17933464/84c527e6-6a14-11e6-8f95-12f1496d4151.jpg)

**Comment by brunobertolini** [comment]
+1 
Same problem here!

**Comment by brunobertolini** [comment]
+1
Smae problem here.

@afxgroup you solve this? Can reopen issue?

**Comment by TheNuclearCat** [comment]
Same problem here +1

**Comment by TheNuclearCat** [comment]
@afxgroup Have you got a solution for this?

**Comment by TheNuclearCat** [comment]
https://developers.facebook.com/bugs/297086380683342/
I think its the same problem. I can´t even logout the user.
See #303

**Comment by afxgroup** [comment]
Take a look at this article

https://software.intel.com/en-us/xdk/articles/facebook-android-keyhash

However Facebook has reverted its change.. now you have the "old" message of wrong hash key
