### ISSUE TITLE
Plugin in IOS

### ISSUE THREAD

**Issue by pepourquier** [jeduan/cordova-plugin-facebook4#306]
I,
I installed the plugin. It worked fine in Android emulator with genymotion. Android open a window whn I accept to be connected with facebook and the send me the access token to be connected with the server side.

but in IOS, plugin seems not working. When I log on facebook, a safari view appears asking me if I want to be connected to the app. If I accept, the view disappear but I still disconnected in my app.

This is my function
`var loginFacebook = function () {`
`facebookConnectPlugin.login( ["email"],`
`function (response) {`
`var id = JSON.stringify(response.authResponse.userID)`
`connectToServerWithUID(id)`
`}`
`)};`

Any idea ? 

Thanks

**Comment by VinceOPS** [comment]
+1

**Comment by herediadev** [comment]
hello pepourquier, are getting an error from the facebook login service?
the login method has 3 parameters (permissions,successCallback, errorCallback)
maybe you are getting an error.

if you are building an application using ionic, you can try using ionic native.
i hope i have helped.

**Comment by peterpeterparker** [comment]
Close, inactivity
