### ISSUE TITLE
Error {"errorMessage":Facebook Error:Error occurred in dialog's operation"} with AppInvite

### ISSUE THREAD

**Issue by learningfun1234** [jeduan/cordova-plugin-facebook4#307]
Hello,

I am trying to use appInvite as shown below and getting following error: {"errorMessage":Facebook Error:Error occurred in dialog's operation"}.

Can you please help?

Thanks!

  $scope.inviteFriends = function() {
    console.log("Sending invite");
    var fbOptions={
      url: "https://fb.me/998656290231725",// App link that you got from facebook
      picture:"https://placehold.it/150x150" // Link to any image on the web
    };
    facebookConnectPlugin.appInvite(fbOptions,
      function(postId){
        alert("success");
        alert(postId);
      },
      function(error){
        alert("failure");
        alert(JSON.stringify(error));
      }
    );
  }

**Comment by Mcoseo** [comment]
Did you ever find a solution for your problem?

**Comment by mscherer82** [comment]
Got the same issue.

**Comment by mscherer82** [comment]
which cordova version do you use?

Have you tried the newest version of this plugin (1.8)? It seems something happened inside the facebook sdk:

 private void executeAppInvite(JSONArray args, CallbackContext callbackContext) {
 ...
        if (AppInviteDialog.canShow()) {
            AppInviteContent.Builder builder = new AppInviteContent.Builder();
            builder.setApplinkUrl(url);
            if (picture != null) {
                builder.setPreviewImageUrl(picture);
            }

            showDialogContext = callbackContext;
            PluginResult pr = new PluginResult(PluginResult.Status.NO_RESULT);
            pr.setKeepCallback(true);
            showDialogContext.sendPluginResult(pr);

            cordova.setActivityResultCallback(this);
            appInviteDialog.show(builder.build());
        } else {
            callbackContext.error("Unable to show dialog");
}

**Comment by peterpeterparker** [comment]
Closed, `appInvite` doesn't exist anymore

https://github.com/jeduan/cordova-plugin-facebook4/issues/645
