### ISSUE TITLE
Facebook Error: Attemp to invoke virtual method

### ISSUE THREAD

**Issue by nikiben** [jeduan/cordova-plugin-facebook4#309]
I'm getting this error after installing the plugin and testing on device

**FB Error:  Attempt to invoke virtual method 'java.util.Set com.facebook.AccessToken.getPermissions()' on a null object reference

Cordova version: 6.3.1
Node: 6.5.0**

Any workaround available?

**Comment by alouane** [comment]
Me too, I got this error when I call `Facebook.api(....) `without calling `getAccessToken` method, apparently it's not working, I get the access_token from direct link `https://graph.facebook.com/oauth/access_token?grant_type=client_credentials&client_id=xxxxxxx&client_secret=xxxxxx` & I add it to api(link, params) but with no luck
I guess you have to pass by getAccessToken, so the permission object is filled with data

Any help would be appreciated

**Comment by Mcoseo** [comment]
Any resolution on this?

**Comment by kudeiro** [comment]
i have this bug too

**Comment by newsof1111** [comment]
this.fb.login(['public_profile', 'email'])
    .then((res: FacebookLoginResponse) => { . // your api call here  })
    .catch(error => {console.log("error", error);});

**Comment by peterpeterparker** [comment]
Plz use other channels for support inquiry, like Stackoverflow, thx
