### ISSUE TITLE
Using an AppLink in the share dialog

### ISSUE THREAD

**Issue by sandymacpherson** [jeduan/cordova-plugin-facebook4#31]
I have generated an AppLink using the Facebook hosting API (mobile-only app), and it is of the form "https://fb.me/123456789". I am now trying to show a "share" dialog using your plugin and this link doesn't work for me on iOS. Any other link works fine, but using an app link results in the "share" dialog just having an infinite spinner on it and clicking post returns me to my app but doesn't actually post. It does work fine when testing in the browser, however. This approach used to work fine with Cordova 3.x and the WizCorp Facebook plugin, but having upgraded to Cordova 5.x and your plugin this problem has appeared.

**Comment by jeduan** [comment]
Shouldn't you be using app invites for AppLinks?

**Comment by sandymacpherson** [comment]
We use AppLinks for deep linking into the app - in our case we share questions with Facebook friends who, if they have the app installed, can click the post to open that question up in their app.

I understand by "app invites" that that is just to let your friends know about an app and invite them to join you in it.

**Comment by mitiaptest** [comment]
+1 need some help for deep linking same as sandymacpherson

**Comment by peterpeterparker** [comment]
Closed for inactivity, if we survived without this since three years, I guess solutions has been found

Side note: App Invite isn't support by Facebook anymore, see https://github.com/jeduan/cordova-plugin-facebook4/issues/645
