### ISSUE TITLE
1.7.2 incompatible again with cordova-plugin-googleplus

### ISSUE THREAD

**Issue by vivekpd15** [jeduan/cordova-plugin-facebook4#311]
I noticed that google login has stopped working again after a recent update. I face the same problem as in #193 "Google login does not redirect back to the app after user gives account permission, instead it opens the google.com homepage". 

When I reverted back to 1.7.1, this issue was gone once again. Please help!

**Comment by peterpeterparker** [comment]
Close, inactivity
