### ISSUE TITLE
Events - App Install from FB Ad

### ISSUE THREAD

**Issue by jstulo** [jeduan/cordova-plugin-facebook4#312]
Does the plugin track app installs from facebook app install ads? If so, is this automatically tracked along with app activation events, or is there an init required?

**Comment by ColDrekken** [comment]
hi, that would be nice to know for me too. As it tracked the install event in FB Analytics  as it looks it might be do the same on a FB Campaign if you add the FB App to the Campagin i guess. But its untested until now.

**Comment by Anu2g** [comment]
FYI, this works for us. We just make sure to call activateApp

**Comment by jstulo** [comment]
The plugin does indeed work and no init was required. Unfortunately, I did not find a good strategy to test it.

**Comment by filipsuk** [comment]
@jstulo How does the plugin know from which facebook ad was the app installed? Sorry if it a stupid question, I am just trying to figure out how is the conversion matched.

**Comment by Log-of-e** [comment]
@filipsuk excellent question- FB analytics definitely shows app installs when using this plugin. But it is hard to tell if the ad attribution is matched properly by FB. 
  Also iTunes Analytics shows Ad attribution information.
