### ISSUE TITLE
Android connects to FB on initialization

### ISSUE THREAD

**Issue by manuelschneider** [jeduan/cordova-plugin-facebook4#314]
I noticed by using rocket.chat, that the android module initializes the facebook sdk whenever the app is used. The problem about that is - if I'm reading its code right -  that the facebook sdk sends at least one request to fb. This means, they know which IP used which app, when. Even if nothing else happens with the module.

I'm pretty new to cordova in general, so if there's some functionality for initializing modules 'on request', this is probably the wrong place for the issue.
However, if modules are always initialized, the initialization of the fb sdk should probably happen when it's actually used for the first time, instead of the cordova plugin initialization.

What's your idea on this? Thanks!

**Comment by peterpeterparker** [comment]
Close, inactivity
