### ISSUE TITLE
Ignore cache with getLoginStatus

### ISSUE THREAD

**Issue by clemorphy** [jeduan/cordova-plugin-facebook4#315]
In Facebook's JS SDK, the `getLoginStatus` function accepts an additional parameter (boolean) to force a cache refresh of the values stores by the SDK.

see the "Roundtrips to Facebook's servers" section of this documentation page : https://developers.facebook.com/docs/reference/javascript/FB.getLoginStatus

I can't see any way to use this parameter with the cordova plugin.

Am I missing something ?

I need this because there is a bug when the user revoke the app from his FB account, but has already been connected via the plugin on his mobile device. The status returned by the plugin is "connected", but it is wrong because the app has been revoked, I think it returns a cached value.

**Comment by martyzz1** [comment]
I get this same issue. This would be highly desirable....

**Comment by martyzz1** [comment]
you can try calling logout... and then retrying.   works for me

```
                     facebookConnectPlugin.logout(function (){
                                if (!retried) {
                                    console.log('[FB retrying]');
                                    retried = true;
                                    facebookConnectPlugin.login(['email', 'public_profile'], fbsuccess, fberror)
                                } else {
                                    console.log('[FB Login Five up]');
                                }
                            }, function() {
                                console.log('[FB logout failure]');
                            });

```

**Comment by shtaif** [comment]
Getting into the same scenario.
No way to determine unless doing what @martyzz1 suggests.

**Comment by smaira** [comment]
Any new updates on this?

**Comment by elysiopires** [comment]
Hello!

I see that if you use the force parameter can solve the problem.

Anyone get success with this?

Thx,
Elysio

**Comment by codeurfou** [comment]
Hello, @elysiopires is true: As the FB API doc suggests, there is a parameter to solve this cached problem.
See https://developers.facebook.com/docs/reference/javascript/FB.getLoginStatus#servers

**Comment by fredgalvao** [comment]
I completely agree, that seems like a proper solution to `a lot` of issues I see often on this plugin with regards to sessions not being invalidated properly on logout.

## PRs are welcome.

**Comment by peterpeterparker** [comment]
@terangel like staten above, any PR is welcome if this feature is needed

If I may, your statement

> getLoginStatus() function is not reliable, you must always call logout() before login() to make sure the access token is valid.

sounds weird to me. I use the plugin in my app and I don't need to do that respectively `getLoginStatus()` is reliable to me

**Comment by terangel** [comment]
For example @peterpeterparker, if you remove your app in your Facebook config, getLoginStatus() returns connected status from the cache, but the access token is no longer valid and any call to Facebook API fails.

This might be the reason the "force" parameter in getLoginStatus is necessary: 
https://developers.facebook.com/docs/reference/javascript/FB.getLoginStatus

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out the actively maintained fork `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect. The getLoginStatus method now accepts a `force` parameter.
