### ISSUE TITLE
Like and Share Button

### ISSUE THREAD

**Issue by ranvirgorai** [jeduan/cordova-plugin-facebook4#318]
I want to put a like and share button,

How can I do using this plugin

In documentation it is not mentioned.

Please Suggest !

**Comment by herediadev** [comment]
hello ranvirgorai,
you can use the facebookConnectPlugin.showDialog method to implement the share button,
if you need more information you can see the documentation
https://github.com/jeduan/cordova-plugin-facebook4#show-a-dialog

i hope i have helped.
