### ISSUE TITLE
Facebook graph is not working

### ISSUE THREAD

**Issue by jeffreyrajanofficial** [jeduan/cordova-plugin-facebook4#319]
Facebook login is working fine but when I tried to get the name using facebook graph nothing happens i am not even getting a error message. 
Here is my code :
```
var fbLoginSuccess = function (userData) {
      console.log("UserInfo: "+angular.toJson(userData));
      facebookConnectPlugin.api(userData.authResponse.userID+"/?fields=id,email,name", ["user_birthday"],
        function onSuccess (result) {
          console.log("Result: "+angular.toJson(result));
        }, function onError (error) {
          console.error("Failed: "+angular.toJson(error));
        }
      );
    }

    facebookConnectPlugin.login(["public_profile"], fbLoginSuccess,
      function loginError (error) {
        console.error(angular.toJson(error))
      }
    );
  }
```

**Comment by peterpeterparker** [comment]
+1

Just upgrade to version 1.7.3 of the plugin. Same code. Didn't had a problem with 1.7.1

iOS Stacktrace:

2016-09-09 18:23:47.987 Fluster Beta[180:3357] Finished GraphAPI request
2016-09-09 18:23:48.187 Fluster Beta[180:3357] ERROR: fbLoginError Response with status: 0  for URL: null

**Comment by Manikandan85** [comment]
@jeffreyrajanofficial Have you fixed your issue? I am facing the same one.

**Comment by jeffreyrajanofficial** [comment]
Here is the method I followed

[var fbLoginError = function(error){
        alert(angular.toJson(error))
    };

    var fbLoginSuccess = function(response) {
    var authResponse = response.authResponse;
    if (!authResponse){
        fbLoginError("Cannot find the authResponse");
        return;
    }
    callFBProfileFunc(authResponse);
    };
var callFBProfileFunc = function(authResponse){
  getFacebookProfileInfo(authResponse).then(function(profileInfo) {
  alert(angular.toJson(profileInfo))
})
}

var getFacebookProfileInfo = function (authResponse) {
    var info = $q.defer();
    facebookConnectPlugin.api('/me?fields=email,name,first_name,last_name,birthday&access_token=' + authResponse.accessToken,null,
                              function (response) {
                              info.resolve(response);
                              },
                              function (response) {
                              info.reject(response);
                              });
    return info.promise;
    };

$scope.fbLogin = function(){

        facebookConnectPlugin.getLoginStatus(function(success){

         if(success.status === 'connected'){
             callFBProfileFunc(success.authResponse);
         } else {
             facebookConnectPlugin.login(['email', 'public_profile','user_birthday'], fbLoginSuccess, fbLoginError);
         }
        });
}](url)

**Comment by Manikandan85** [comment]
Thanks for your reply. Have you faced any issue if fb account is switched inside a safari browser and tried to login in cordova app?
