### ISSUE TITLE
App Invites

### ISSUE THREAD

**Issue by sandymacpherson** [jeduan/cordova-plugin-facebook4#32]
I see reference to App Invites in the readme of this plugin but the code doesn't appear to support them. Is this planned for the future?

**Comment by jeduan** [comment]
I don't understand your question.
Here's the code in JS https://github.com/jeduan/cordova-plugin-facebook4/blob/master/www/facebook-native.js#L45-L48
iOS https://github.com/jeduan/cordova-plugin-facebook4/blob/master/src/ios/FacebookConnectPlugin.m#L389-L412
and Android https://github.com/jeduan/cordova-plugin-facebook4/blob/master/src/android/ConnectPlugin.java#L210-L231

**Comment by sandymacpherson** [comment]
Yip, sorry - I was using an outdated copy of the plugin and didn't have that code yet.

**Comment by vexsoluciones** [comment]
hello, we have implemented with success appinvite, but in ios is not working,
