### ISSUE TITLE
install plugin is not working

### ISSUE THREAD

**Issue by NetoDevel** [jeduan/cordova-plugin-facebook4#321]
**## i'm running:** 
ionic plugin add cordova-plugin-facebook4 --save --variable APP_ID="***" --variable APP_NAME="***"

**### output**: 
Fetching plugin "cordova-plugin-facebook4" via npm
npm http GET https://registry.npmjs.org/cordova-plugin-facebook4
npm http 304 https://registry.npmjs.org/cordova-plugin-facebook4
Saved plugin info for "cordova-plugin-facebook4" to config.xml
Saving plugin to package.json file

**# ionic info**
Your system information:

Cordova CLI: 5.1.1
Ionic Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.22
Ionic App Lib Version: 2.0.0-beta.12
OS:
Node Version: v5.6.0

**Comment by fredgalvao** [comment]
I don't see an error on the output, or anywhere else there. What exactly went wrong?

**Comment by NetoDevel** [comment]
@fredgalvao It should appear facebook installed when I run up the ionic info?

**Comment by fredgalvao** [comment]
If no error appeared during plugin installation, and you're sure that it should definitely appear "facebook installed" when you run "ionic info", then it's an ionic issue, not the plugin's.

You can always try to do `cordova plugin ls` instead, and see if the plugin was installed correctly directly with cordova.

**Comment by NetoDevel** [comment]
@fredgalvao thank's 

I ran the ionic list plugin command and ran
