### ISSUE TITLE
Refused to display .... in a frame because it set X-frame-options to DENY

### ISSUE THREAD

**Issue by epicfaace** [jeduan/cordova-plugin-facebook4#323]
I am getting a problem with the cordova facebook authentication plugin when using it to login using Firebase Auth.

Here is my error (debugging through Chrome on a device):

![image](https://cloud.githubusercontent.com/assets/1689183/18616349/234b1516-7d88-11e6-8210-cd82278e39e4.png)

Here is my code:

```

if (window.facebookConnectPlugin && (window.cordova && device.platform == 'iOS') || (window.cordova && device.platform == 'Android')) {
        console.log("using the plugin");
        facebookConnectPlugin.login(['public_profile'], function(result) {
          provider = firebase.auth.FacebookAuthProvider.credential(result.authResponse.accessToken);
          provider.addScope('public_profile');
          provider.addScope('email');
          Auth.firebaseAuth.$signInWithCredential(provider).then(function(authData) {
            // User successfully logged in
            console.debug(authData);
            console.log("logged in ionic");
          }).catch(errFn);
        }, errFn);
      }
```

**Comment by niranjanthiru** [comment]
If you are using [cordova-plugin-inappbrowser](https://github.com/apache/cordova-plugin-inappbrowser) in your project, removing it might help you.

**Comment by tgezginis** [comment]
I am getting this problem on login for browser platform.

How can i solve the 'X-Frame-Options' to 'DENY' problem?

Thanks.

**Comment by johnellmore** [comment]
@niranjanthiru removing cordova-plugin-inappbrowser fixed this issue for me. Thanks!

Short explanation: current versions of cordova-plugin-inappbrowser override window.open() in JS (annoyingly). This screws up some types of window.open() calls, especially for sites that don't like to be iframe'd. To their credit, cordova-plugin-inappbrowser is going to remove this override in future versions.

**Comment by EdByrnee** [comment]
I'm having the same issues, but when I remove inappbrowser it stops working completely, isn't the plugin dependent on it to open Facebook for login?

**Comment by caribe** [comment]
If cordova-plugin-inappbrowsered is needed you have to revert the original window.open method as described here https://github.com/apache/cordova-plugin-inappbrowser

In my case "delete window.open" didn't work (maybe because of Firefox), anyway you can workaround by assigning if to a variable at script begin and then assign it back in the "deviceready" callback.

    var original_open = window.open
    ...
    document.addEventListener('deviceready', function() {
      ...
      window.open = original_open;
      ...
      facebookConnectPlugin...
    }, false);

**Comment by dymissy** [comment]
Same issue here but no _cordova-plugin-inappbrowser_ installed. Anyone experienced same problem? How can we solve? 

Here is debugging the code:

```
    this.fb.login(['public_profile', 'user_friends', 'email'])
      .then(function(res: FacebookLoginResponse){
        let facebookRes = JSON.stringify(res);
        let userId = res.authResponse.userID;

        self.fb.api('/me?fields=id,email', ['email', 'public_profile'])
          .then(function(response) {
            let userData = JSON.stringify(response);

            console.log(userData);
            console.log(facebookRes);
          })
          .catch(e => self.facebookRes = JSON.stringify(e));
      })
      .catch(e => self.facebookRes = JSON.stringify(e));
```

**Comment by rahulpsd18** [comment]
Getting this error on browser platform only (on ionic). Any help?
`delete window.open` didn't work, neither did the deviceready method.

**Comment by pritiJI** [comment]
> If you are using [cordova-plugin-inappbrowser](https://github.com/apache/cordova-plugin-inappbrowser) in your project, removing it might help you.

Hi
I am facing the Same problem but can you confirm is it right solution?
Because my app running on an Android device but not run on a browser. 
can anyone resolve this issue? and how to remove cordova-inappbrowser-plugin. I am new in ionic app development. Please reply

**Comment by LDHo** [comment]
Hi, just wondering does this fix in cordova-plugin-inappbrowser after a year.
