### ISSUE TITLE
Not working on IOS 10 

### ISSUE THREAD

**Issue by ezazwar1** [jeduan/cordova-plugin-facebook4#325]
Hey the plugin is calling the error block when trying to login.

Ezaz

**Comment by robertarnesson** [comment]
try with 77ceb2e

**Comment by elijthomas** [comment]
Any chance you can bump the version so this fix is pushed through to npm?

**Comment by cmichaelis** [comment]
I believe I'm using master (just used "cordova plugin add https://github.com/jeduan/cordova-plugin-facebook4" and it looked like it pulled master).

Still hitting the same problem on both simulator and an iPhone 6s updated to iOS 10. Any chance I could get you to take a peek again?

Thanks! Much appreciated!

**Comment by cmichaelis** [comment]
Nevermind - turned out that it was using an old copy of the plugin even though I had removed and re-added it. "platform rm" and "platform add" made it happy. Confirmed your fix seems to make iOS 10 happy, at least for me!

Thanks again!

**Comment by wiadev** [comment]
It's not working on iOS 10. I've installed new version

cordova plugin add cordova-plugin-facebook4

I've also tried to remove and add platform ios again but no luck.

Moreover, I've got rejected from app store because of IPv6.

They reported that FB login is not working.

**Comment by fredgalvao** [comment]
@wiadev `cordova plugin add cordova-plugin-facebook4` will install the latest version from **npm**, not the latest version from this **repository**.

To achieve that last goal, you need to call `cordova add` with a github url, exactly like @cmichaelis mentioned:

`cordova plugin add https://github.com/jeduan/cordova-plugin-facebook4`

**Comment by wiadev** [comment]
@fredgalvao Thanks for quick help.

Also, Apple rejected because it's not support IPv6.

**Comment by wiadev** [comment]
@fredgalvao I've reinstalled the plugin but it took 53s to get the FB login dialog.
http://prntscr.com/cko4x0

**Comment by fredgalvao** [comment]
@wiadev  That's 53ms, not 53s. That warning will happen for pretty much any plugin I know that needs initializing. In that instance I can guarantee that it can be safely ignored.

**Comment by eikooc** [comment]
@fredgalvao regarding the 53ms wouldn't it be possible to [specify a thread](https://developer.android.com/training/multiple-threads/define-runnable.html) to run it in instead?

**Comment by clemorphy** [comment]
@wiadev Can you keep us informed in this thread about your ipv6 rejection issue ?
My cordova app got rejected for that reason too, and I don't know which cordova plugin is faulty.
I use facebook4 plugin, but also a few others ...

**Comment by wiadev** [comment]
@clemorphy actually, I've built the app in xCode 7.3 and submitted , got rejected then.
I've updated xCode 8.0 and checked but it wasn't working over there for some reason. ( FB request wasn't sent , not plugin issue, obviously.)

I've fixed the issue on xCode 8.0 and submitted again and passed through.

so Imk, it's not the issue of IPv6 but it's the issue on xCode 8.0/iOS 10.

try on iOS 10 and make sure it's working over there as well.

then, submit again and I believe you will be passed.

**Comment by clemorphy** [comment]
@wiadev Thanx for your quick reply.

I have built with Xcode 7 too (but with command line tools), Apple says the app doesn't start correctly on their IPV6 environment.

I have set up a local IPV6 network following Apple's recommandations, at the bottom of this page : https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW1

But I can't reproduce the issue on my IPV6 network. My app starts correctly, no error.

I am downloading Xcode 8 right now, I will try to rebuild with this version, but since I don't have any problem on my side, I don't know if this will fix something on the reviewers side.

**Comment by robertarnesson** [comment]
there is now a new release in npm (1.7.4)

**Comment by ezazwar1** [comment]
i Had the same issue of ipv6 turned out that i was requesting coverpic of the user in api and when apple was checking that their facebook account from which they are checking does not have a cover pic and the app is failing to login so i removed the cover pic and then my app was accepted by apple store. Hope that helps


Regards
Ezaz

**Comment by clemorphy** [comment]
@wiadev When Apple told me they had this IPV6 issue, I said to them that I couldn't reproduce the error on my IPV6 network.

And today, before I could even download and install Xcode8 properly to rebuild my app, they replied that they are reviewing my initial build once again, and now they tell me that my app has been validated.

I don't know if the problem was on their side and they have fixed it, or if this IPV6 compatibility is suddenly not so important, but I didn't have to change anything nor submit a new build to get my app validated.

**Comment by benlooi** [comment]
Hello,
I am having problems with IOS 10. It was working with IOS 9.3. It doesn't log in. Here is my error log. 
I have 2 issues: one is nw_hosts_stats, and another is pasteboard null.

Any help or idea is appreciated! 

Sep 28 09:03:13 Looi Pompipi[7168]: Cordova view ready
Sep 28 09:03:13 Looi Pompipi[7168]: THREAD WARNING: ['Device'] took '22.666992' ms. Plugin should use a background thread.
Sep 28 09:03:28 Looi pasted[7089]: BundleID com.creativespectrum.pompipi2016 from team GC4933S6MH is requesting pasteboard fb_app_attribution
Sep 28 09:03:28 Looi pasted[7089]: ...requesting pasteboard fb_app_attribution completed. Error: (null)
Sep 28 09:03:28 Looi Pompipi[7168]: [] nw_host_stats_add_src recv too small, received 24, expected 28
Sep 28 09:03:28 Looi Pompipi[7168]: [] __nwlog_err_simulate_crash simulate crash already simulated "nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available"
Sep 28 09:03:28 Looi Pompipi[7168]: [] nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available, dumping backtrace:
	        [x86_64] libnetcore-856.1.8
	    0   libsystem_network.dylib             0x000000010c8d780e __nw_create_backtrace_string + 123
	    1   libnetwork.dylib                    0x000000010e1d6194 nw_socket_add_input_handler + 3002
	    2   libnetwork.dylib                    0x000000010e1b3db8 nw_endpoint_flow_attach_protocols + 3768
	    3   libnetwork.dylib                    0x000000010e1b2dd5 nw_endpoint_flow_setup_socket + 563
	    4   libnetwork.dylib                    0x000000010e1b1b34 -[NWConcrete_nw_endpoint_flow startWithHandler:] + 2612
	    5   libnetwork.dylib                    0x000000010e1ccd11 nw_endpoint_handler_path_change + 1261
	    6   libnetwork.dylib                    0x000000010e1cc740 nw_endpoint_handler_start + 570
	    7   libnetwork.dylib                    0x000000010e1e4003 nw_endpoint_resolver_start_next_child + 2240
	    8   libdispatch.dylib                   0x000000
Sep 28 09:04:13 Looi searchd[7124]: [index] Failed to complete job:<CSIndexJob:0x7fb379f1c4f0; type=2>, extension:<_MDIndexExtension:0x7fb379c2cc50; id=com.apple.MobileSMS.spotlight, containerId=com.apple.MobileSMS, containerPath=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/Applications/MobileSMS.app, flags=run-on-migration>, error:Error Domain=CSIndexErrorDomain Code=-1 "(null)"
Sep 28 09:05:04 Looi routined[7064]: CoreLocation: Error occurred while trying to retrieve motion state update: CMErrorDomain Code:104

**Comment by rrubio** [comment]
My facebook login broke after upgrading to xcode 8. Get the the following error "There was a problem logging you in." I noticed that it doesn't even make it to "this.getProfile();".

`    login(): void {
        
        this.nav.present(this.loading);
        Facebook.login(['public_profile']).then((response) => {
              console.log(response);
              this.getProfile();
            }, (err) => {
            
              console.log(err);
              
              let alert = Alert.create({
                title: 'Oops! ***',
                subTitle: 'Something went wrong, please try again later.',
                buttons: ['Ok']
            });
            
            this.loading.dismiss();
            this.nav.present(alert);
        });    
    
    }
`

**Comment by JohnScottMcNerney** [comment]
@benlooi 

Not sure if this helps, or is your issue, but IOS 10 requires all secure connections (HTTPS,WSS,etc). I noticed your error log had socket information in it and "Protocol not available". My socket.io APP broke in IOS 10 because the socket wasn't setup using HTTPS, while it worked perfectly in IOS 9 using HTTP.

**Comment by gurisko** [comment]
@rrubio Were you able to resolve your issue? I am facing a similiar one

**Comment by rrubio** [comment]
@gurisko still having the same issue. I'll try to spend more time over the weekend and provide an update.

**Comment by harisadam** [comment]
I could solve this by turning keychain sharing on, hope it helps

![screenshot 2016-09-30 08 43 06](https://cloud.githubusercontent.com/assets/797521/18982908/ee99b21c-86e9-11e6-8438-5eb365353708.png)

**Comment by gurisko** [comment]
@harisadam Awesome!! This was indeed the issue. Thanks

**Comment by benlooi** [comment]
@JohnScottMcNerney Thanks for the info. Spent the entire weekend installing an SSL cert on my server(don't ask...), redid my certs and provisioning profiles on Apple Developer account, turned on keychain....it worked. 
Only weird thing is when user logs in with Facebook  on IOS, there is no immediate response. I put in a loading spinner when the API call is made, and it is supposed to close the spinner loader and do to another state (I'm using ionic) once I get the Authresponse callback. 
I have to exit the app by pressing on the Home button, and re-enter the app in order to go to the state with the necessary response info like user's name, fb_id etc. 
Can't seem to track the callback log. But hey, at least it works!

**Comment by Manikandan85** [comment]
Hi,

My app got rejected from apple specifying that they can't able to connect to FB in IPv6 network.

The app contains updated fb plugin 1.7.4 and submitted the build using xcode 8. The fb login is working fine in simulator.

Any ideas how to fix this issue in IPv6 network?

**Comment by ezazwar1** [comment]
@Manikandan85  
u might be requesting the cover as far as i know , i had the same problem . if you have a mac make a ipv6 network and try to login if you are able to successfully login then there is something you are requesting the facebook api but for that user that field is not present and hence this code breaks and never logs in

**Comment by Manikandan85** [comment]
Thanks for the reply ezazwar1.
I am just requesting the user name and email address. I can able to login successfully in my app through fb in ipv6 network. is that be a problem?

**Comment by ezazwar1** [comment]
maybe the email might b blank

**Comment by Manikandan85** [comment]
Actually the graph call is not working for first time users. I mean after user logged in through fb, it will show another popup to get user email address. 

This popup is not showing for new users. If the user closed the app and again logged in through fb, it is working fine.

Any ideas how to resolve?

**Comment by hafizbe** [comment]
Hello.
I have exactly the same problem.
It works fine on ios 9 but it's not possible to log in with ios 10.
I got this error : unknow error.

**Comment by aleksandr-sovenko** [comment]
need update SDK for iOS 10

cd cordova-plugin-facebook4/src/ios/
curl -o FacebookSDKs-iOS-4.17.0.zip  https://origincache.facebook.com/developers/resources/?id=FacebookSDKs-iOS-4.17.0.zip
unzip -o FacebookSDKs-iOS-4.17.0.zip

**Comment by lincolnthree** [comment]
@harisadam That fixed it for me as well. Thank you!

**Comment by REPTILEHAUS** [comment]
Im having this issue.. works fine on a device but in the emulator I get there was a problem logging you in

**Comment by jkervine** [comment]
@harisadam That is indeed the fix. I think this should be part of the README for the project.

**Comment by ErlendEllingsen** [comment]
@REPTILEHAUS did you figure it out? Struggeling with the same issue. It seems debugging via xcode goes fine, but running "cordova run ios --emulator" seems like it makes the keychain sharing turned off?

**Comment by REPTILEHAUS** [comment]
Uninistall your copy of ionic, then reinstall.. then in xcode in capabilities make sure that you turn on keychain sharing from within xcode then run again either in ionics emulator of the xcode emulator and it should work

**Comment by ludufre** [comment]
@ErlendEllingsen Did you find some way?

**Comment by Gurunathanbe** [comment]
There was an error making the graph call on ios 10

Any ideas how to resolve..?

**Comment by Gurunathanbe** [comment]
Hi All, I'm working ionic1 framework. while i'm using this  plugin
'cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="123456789" --variable APP_NAME="demo" '  for facebook login  
it works in android but it's not working in IOS 10, I'm getting this error message
" There was an error making the graph call  "

**Comment by chrisbellman** [comment]
Have there been any updates on this in the past few months? I'm still new to Ionic/Cordova but don't think you can have livereload if you launch from Xcode...which makes development a pain.

**Comment by chrisfilda** [comment]
Hi all, 
I am trying to develop a cordova project and run Facebook login in iOS, but the "sign in with Facebook" button that actually triggers the facebookSignIn function does nothing.
However, the same cordova www code works great in Android.

I have read the previous posts in this issue as well as the troubleshooting in the Jeduan page in Github but cannot find any solution

So, I am trying to summarize what I already did:
- created an ionic project and copied the www folder that I created in Android Studio
- added the cordova plugin in the way you suggested: cordova plugin add https://github.com/jeduan/cordova-plugin-facebook4
- deployed on xCode 8 and iOS 10 
- added missing frameworks in the "Build Phases" as suggested here (https://github.com/jeduan/cordova-plugin-facebook4/blob/master/docs/TROUBLESHOOTING.md#missing-facebookconnectplugin)
- Give the iOS application access to the Keychain Sharing capability 
- updated the FacebookSDK for iOS 10:

> ```
> cd cordova-plugin-facebook4/src/ios/
> curl -o FacebookSDKs-iOS-4.17.0.zip  https://origincache.facebook.com/developers/resources/?id=FacebookSDKs-iOS-4.17.0.zip
> unzip -o FacebookSDKs-iOS-4.17.0.zip
> ```

Still nothing. When I press the facebook Login button, nothing happens.
Could you please help me on this?

Many thanks in advance

**Comment by titovisk** [comment]
@chrisfilda I don't know if you solved it yet, but have you tried [https://github.com/jeduan/cordova-plugin-facebook4/issues/406](url)? It worked for me, after trying everything you listed.
Hope it helps!

**Comment by aleksandr-sovenko** [comment]
need update SDK for iOS 10

cd cordova-plugin-facebook4/src/ios/
curl -o FacebookSDKs-iOS-4.17.0.zip https://origincache.facebook.com/developers/resources/?id=FacebookSDKs-iOS-4.17.0.zip
unzip -o FacebookSDKs-iOS-4.17.0.zip

sometimes Facebook update SDK https://developers.facebook.com/docs/ios/change-log-4x and just need instead 4.17.0 use 4.25.0 at the moment, lately time I used 4.22.1 and that good worked with iPhone or Xcode emulator 

https://oleksandrsovenko.com

**Comment by SopoB** [comment]
Hi guys,

I have ionic1 cordova app; using "cordova-plugin-facebook4 1.7.4" I am trying to test app installs from ios and android devices. 

I have debugged using following options : 
1. I have properly added Facebook plugin (showing in cordova plugin list)
2. Tried using updating various CSP as per suggested. [link](https://github.com/ionic-team/ionic/issues/6928#issuecomment-241786539)
3. Updated SDK for IOS 10 

Still no updates on Facebook ads helper's install URL. 
Anyone knows, what else might be the issue.

**Comment by chrisfilda** [comment]
Hi guys,
many thanks for your reply, but still no luck.
I added some alerts and it seems that it is successfully connected, but it has an error on the get Feed.

After the login, I am using the following call:

```
facebookConnectPlugin.api('/' + response.authResponse.userID + '/friends/?fields=feed{created_time,from{first_name,last_name,picture,id},picture,message,likes,comments,shares,attachments,story,link,source,application,permalink_url,with_tags}',[],

function onSuccess(result) {
},
function onError(error) {}
```

but it forwards me to the error function.
Could anyone help me on this?

Many thanks in advance

**Comment by dezani** [comment]
Hi @chrisfilda . Did you have some news about your issue?

My problem is use subfields in the request. 

Thanks.

**Comment by chrisfilda** [comment]
No @dezani, no news yet.

I am still facing the same issue.

**Comment by peterpeterparker** [comment]
A version of the plugin with the Facebook SDK for iOS 11 was recently release. Furthermore I close this question for inactivity reason (question was in 2016 created).

For support questions plz use other channels like Stackoverflow or Ionic forum
