### ISSUE TITLE
I cannot login with Facebook!!!! 

### ISSUE THREAD

**Issue by BoyKananek** [jeduan/cordova-plugin-facebook4#327]
when i login it will always return fails and show this result

<img width="322" alt="screen shot 2559-09-20 at 10 36 01 pm" src="https://cloud.githubusercontent.com/assets/6735776/18677345/b1532910-7f82-11e6-8cab-0a0c1e0325c7.png">
This log 

<img width="568" alt="screen shot 2559-09-20 at 10 38 49 pm" src="https://cloud.githubusercontent.com/assets/6735776/18677462/13690fde-7f83-11e6-98f3-3237b85b50ac.png">

Help please...

**Comment by ezazwar1** [comment]
if you are using IOS 10 please enable key chain sharing to enable logging in i had the same problem

**Comment by BoyKananek** [comment]
Thank you it 's working
