### ISSUE TITLE
Rejected from Apple

### ISSUE THREAD

**Issue by patrickblind** [jeduan/cordova-plugin-facebook4#329]
Hi

Here is the rejected message from Apple.

`
In order to use Facebook for authentication, your app must include significant account-specific functionality from Facebook such as integrating the user's friends list, photos the user has posted to Facebook outside of profile photo or likes. 
`

I don't understand account-specific functionality what they are saying.

Can anyone point out?

Thanks @jeduan

**Comment by BrettGregson** [comment]
Read this post - https://forums.developer.apple.com/thread/15800

There are 2 things. Firstly, it seems like you're not allowed to use Facebook solely for user authentication. You have to make use of some other Facebook specific functionality to justify making the users login with Facebook, something like finding you Facebook friends on the app, sharing content from the to Facebook, using photos from Facebook in the app, etc...

Secondly, you need to justify what you are using the different permissions for. If you request to access the users photos but your app doesn't actually do anything with the photos it may be rejected. Only request the permission that you actually need for the app. A suggestion is to include notes in your app submission as to what permissions you are requesting from Facebook and why
