### ISSUE TITLE
Not able to login using this plugin

### ISSUE THREAD

**Issue by Rigelnetworks** [jeduan/cordova-plugin-facebook4#330]
Hi,

we have use cordova phonegap and we have install this plugin as per given information but it was display error like:
Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.

my phonegap ip is:10.0.0.167:3000 
so what is my app domian?

Thanks,

**Comment by robertarnesson** [comment]
add 10.0.0.167:3000 as authorized url for your fb app

**Comment by tkutlic** [comment]
I followed all the steps but I can not make ionic application to run on Android emulator.
Is it posible to test this on genymotion emulator or just on device?

I get the message: Can not Load URL: The domain of this URL is not included in the app's domains.
(same as above)

I am a beginner and do not understand where I need to enter domain (when I get one).
How do I get this information when the application is on the device?

I do not understand where I need to write this:
a) in the facebook login section (under Products) in the field Valid OAuth redirect URIs or..
b) under Settings in the App Domains field (if I have multiple domains can I separate them by comma?)

This is my request from debugger ( I removed my client_id)

General
===========================================

Remote Address:31.13.81.36:443
Request URL:https://www.facebook.com/connect/ping?client_id=<my client id>&domain=&origin=2&redirect_uri=http://staticxx.facebook.com/connect/xd_arbiter/r/fTmIQU3LxvB.js?version=42#cb=fa030c8a8&domain=&origin=file:///f10358c084&relation=parent&response_type=token,signed_request,code&sdk=joey
Request Method:GET
Status Code:200 OK

Response Headers
===========================================

cache-control:private, no-cache, no-store, must-revalidate
content-encoding:gzip
content-security-policy:default-src * data: blob:;script-src *.facebook.com *.fbcdn.net *.facebook.net *.google-analytics.com *.virtualearth.net *.google.com 127.0.0.1:* *.spotilocal.com:* 'unsafe-inline' 'unsafe-eval' fbstatic-a.akamaihd.net fbcdn-static-b-a.akamaihd.net *.atlassolutions.com blob: data:;style-src data: 'unsafe-inline' *;connect-src *.facebook.com *.fbcdn.net *.facebook.net *.spotilocal.com:* *.akamaihd.net wss://*.facebook.com:* https://fb.scanandcleanlocal.com:* *.atlassolutions.com attachment.fbsbx.com ws://localhost:* blob: *.cdninstagram.com chrome-extension://boadgeojelhgndaghljhdicfkmllpafd chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm;
content-type:text/html
date:Fri, 25 Nov 2016 01:30:36 GMT
expires:Sat, 01 Jan 2000 00:00:00 GMT
pragma:no-cache
public-key-pins-report-only:max-age=500; pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="; pin-sha256="r/mIkG3eEpVdm+u/ko/cwxzOMo1bk4TyHIlByibiA5E="; pin-sha256="q4PO2G2cbkZhZ82+JgmRUyGMoAeozA+BSXVXQWB8XWQ="; report-uri="http://reports.fb.com/hpkp/"
status:200 OK
strict-transport-security:max-age=15552000; preload
vary:Accept-Encoding
version:HTTP/1.1
x-content-type-options:nosniff
x-fb-debug:PQCdEa7xg+nvsCpr1lXz70UoFDvrqIh1mjbV+kHVzPW83bfZAJnF3zCj22Ta7u7adLoMNDQzzMV0PTG1v8BFug==
x-xss-protection:0


Request Headers
===========================================


:host:www.facebook.com
:method:GET

:path:/connect/ping?client_id=<my client id>&domain=&origin=2&redirect_uri=http://staticxx.facebook.com/connect/xd_arbiter/r/fTmIQU3LxvB.js?version=42#cb=fa030c8a8&domain=&origin=file:///f10358c084&relation=parent&response_type=token,signed_request,code&sdk=joey

:scheme:https
:version:HTTP/1.1
accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
accept-encoding:gzip, deflate
accept-language:en-US
upgrade-insecure-requests:1
user-agent:Mozilla/5.0 (Linux; Android 6.0; Samsung Galaxy S6 - 6.0.0 - API 23 - 1440x2560 Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.119 Mobile Safari/537.36
x-devtools-emulate-network-conditions-client-id:4A18CAFF-4629-46DE-9C23-3D35F49525E2
x-requested-with:com.ionicframework.nobbapp2172378

Query String Parameters
===========================================

client_id:<my client id>

domain:

origin:2


redirect_uri:http://staticxx.facebook.com/connect/xd_arbiter/r/fTmIQU3LxvB.js?version=42#cb=fa030c8a8&domain=&origin=file:///f10358c084&relation=parent

response_type:token,signed_request,code

sdk:joey

Thanks
