### ISSUE TITLE
showDialog popup window size and picture size too small

### ISSUE THREAD

**Issue by billywanmf** [jeduan/cordova-plugin-facebook4#331]
I use the showDialog to post a picture as below:

var showDialog = function () { 
                facebookConnectPlugin.showDialog( {
                    method: "feed",
                    href: 'http://www.example.com',
                    picture: 'https://www.google.co.jp/logos/doodles/2014/doodle-4-google-2014-japan-winner-5109465267306496.2-hp.png',
                    name:'Test Post',
                    message:'First photo post',
                    caption: 'Testing using Phonegap Facebook plugin',
                    description: 'Posting photo using Phonegap Facebook plugin',
                }, 
                    function (response) { alert(JSON.stringify(response)) },
                    function (response) { alert(JSON.stringify(response)) });
            }

I used a 7" Android tablet to test. But the popup windows size is too small and the picture cannot easily see. Please advise if how to change the popup window so that bigger picture and dialog box can show in tablet.

Screen capture is attached.

Thanks.

Regards,
Billy
![screenshot_20160924-203708](https://cloud.githubusercontent.com/assets/22413645/18808531/5f2eaf5c-8297-11e6-829c-1ae8f404de94.png)

**Comment by peterpeterparker** [comment]
Close, inactivity
