### ISSUE TITLE
Android login works intermittently; most of the time spinner then crash

### ISSUE THREAD

**Issue by metalaureate** [jeduan/cordova-plugin-facebook4#332]
I can get this plugin to work on Android maybe 1 in 10 attempts on a Samsung S7. The other times, it hangs for a while (spinner), then crashes. Sometimes it spins for about 30 seconds, and then logs in; or logs in after 30 secs but then immediately crashes. I've doubled check the documentation many times. I wish I had more information. 

Works fine on iOS.

**Comment by macchie** [comment]
+1

**Comment by Borongaj** [comment]
+1

**Comment by firoze** [comment]
+1

**Comment by saurabhudaniya200** [comment]
+1

**Comment by saurabhudaniya200** [comment]
Any update on this??

**Comment by peterpeterparker** [comment]
Close, inactivity
