### ISSUE TITLE
plugin not work proper

### ISSUE THREAD

**Issue by Rigelnetworks** [jeduan/cordova-plugin-facebook4#333]
Hi,
My error is below:
Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.

- when i try to login into facebook using phonegap cordova at that time i was display error.

please check and give suggestion as soon as possible.

**Comment by Hirbod** [comment]
Read the documentations please.
