### ISSUE TITLE
Share dialog shows two close icons on IOS.

### ISSUE THREAD

**Issue by fendorio** [jeduan/cordova-plugin-facebook4#334]
The share dialog, displays two close icons in the dialog - this wouldn't be so bad if they weren't so close to each other. See image below (top left)

Has anyone else experienced this? If so, is there a fix for this I can apply or is one in the pipeline?

![11_ios](https://cloud.githubusercontent.com/assets/8508304/18877344/e35b8e10-84c4-11e6-83c8-3a8cdae75ef9.png)

**Comment by peterpeterparker** [comment]
Close, inactivity since 2016
