### ISSUE TITLE
appInvite , errorMessage : "Facebook error: Dialog failed with unknown error" 

### ISSUE THREAD

**Issue by brunomarcel** [jeduan/cordova-plugin-facebook4#337]
when I call the appInvite, I get this error in Android.
errorMessage : "Facebook error: Dialog failed with unknown error" 

Someone can help me?

my code:
 $scope.inviteFB = function(){
    var teste = { 
      url: "https://play.google.com/store/apps/details?id=com.prettye.app",
      picture: "http://www.flora.avph.com.br/jpg/bananas.jpg"
    }  
    facebookConnectPlugin.appInvite(teste, function(obj){console.log(obj)}, function(obj){console.log(obj)})
  }

**Comment by vo-land** [comment]
Hi
I ran into the same problem
Tell me, do you have a solution

**Comment by mscherer82** [comment]
which cordova version do you use?

Have you tried the newest version of this plugin (1.8)? It seems something happened inside the facebook sdk:

 private void executeAppInvite(JSONArray args, CallbackContext callbackContext) {
 ...
        if (AppInviteDialog.canShow()) {
            AppInviteContent.Builder builder = new AppInviteContent.Builder();
            builder.setApplinkUrl(url);
            if (picture != null) {
                builder.setPreviewImageUrl(picture);
            }

            showDialogContext = callbackContext;
            PluginResult pr = new PluginResult(PluginResult.Status.NO_RESULT);
            pr.setKeepCallback(true);
            showDialogContext.sendPluginResult(pr);

            cordova.setActivityResultCallback(this);
            appInviteDialog.show(builder.build());
        } else {
            callbackContext.error("Unable to show dialog");
}

**Comment by sunojvijayan** [comment]
Did you find a solution for this?

**Comment by peterpeterparker** [comment]
Closed, `appInvite` doesn't exist anymore

https://github.com/jeduan/cordova-plugin-facebook4/issues/645
