### ISSUE TITLE
Error in making the graph call on IOS device

### ISSUE THREAD

**Issue by atlanlin** [jeduan/cordova-plugin-facebook4#338]
I am having the issue where the error code shows this "There was an error making the graph call." I am using the ionic and My IOS version is 9.3.5.

It works perfectly fine on android. It just doesn't work on IOS.

I found this issue opened previously  #284 but it didn't have proper answer.

Thanks.

**Comment by atlanlin** [comment]
I finally found the problem, the problem is in syntax while making api call.
When making the call, I cannot leave spaces in between each parameters. For android, it doesn't seem to have a problem. But for IOS, i have to take out all the spaces in between. I don't exactly know why it happens but it solved my problem.

Hence, instead of:
`me/?fields=id, name, email, birthday, gender `

Changed to:
`me/?fields=id,name,email,birthday,gender  `

**Comment by monksee** [comment]
Thank you so much. You're a life saver. works fine without spaces :)

**Comment by Unkn0wn0x** [comment]
For those they have still a issue with this, it seems, like iOS can't handle some "special characters" compared to Android. I finished up like this:

Old, working on Android, but not on iOS: 
`/me?fields=first_name,last_name,birthday,email,gender,picture.width(2000).height(2000){url,is_silhouette}`

New, working on both:
`/me?fields=first_name,last_name,birthday,email,gender,picture.width(2000).height(2000)`

I just wanted to acccess the `url` and `is_silhouette` sub-attribute of the picture, but it's returned allways. 

The issue were the brackets `{}` when trying to access the sub-attributes from the picture. However `()` does not link into issues.

**Comment by Terrafire123** [comment]
@Unkn0wn0x You are a lifesaver.
