### ISSUE TITLE
There was an error making the graph call (iOS)

### ISSUE THREAD

**Issue by chevellabv** [jeduan/cordova-plugin-facebook4#339]
Hi,

Since a few days this plugin is throwing errors when using the graph api.
Login is working as expected.

Using the graph api fails on iOS (10).
All functions are working fine with Android.

Does anybody has a clue or fix? :)

Thanks!

**Comment by morellan** [comment]
Same problem here

**Comment by MathieuNls** [comment]
Same issue

**Comment by Manikandan85** [comment]
Same issue. After user logged in through fb, the graph call is not working which gets user email address

**Comment by MathieuNls** [comment]
On ionic2, the following works.

```javascript
      Facebook.login(["public_profile", "email"]).then(
			facebookLoginResponse => {

				console.log("facebookLoginResponse", facebookLoginResponse);

				Facebook.api("me/?fields=id,email,last_name,first_name", ["public_profile", "email"]).then(
					fbUser => {

						console.log("fbUser ", fbUser);

					},
					error => {
						console.log('error1', error);
					}
				)
			}, 
			error => {
				console.log('error2', error);
			}
		);
```

Note the repeat of authorizations and the me/ url with fields and without space between them.

**Comment by Manikandan85** [comment]
Hi MathieuNls,

I am not using iconic. Will the above code work in my cordova application?

**Comment by MathieuNls** [comment]
Ionic2 is just typescript instead of javascript when it comes to cordova-plugin. What's different in your code is that you used `/me?fields=email,id,name` instead of `me/?fields=email,id,name`.

**Comment by lucasKhane** [comment]
Same problem. I had something like this:

function getNativeFbInfo(userID){
	dump("getNativeFbInfo()");

	facebookConnectPlugin.api(userID+"/?fields=email, first_name, last_name", null,
    	function (result) {
		    dump("Result: " + JSON.stringify(result));
		    dump("email: "+ result.email);
		    dump("first_name: "+result.first_name);
		    dump("last_name: "+result.last_name);

		    var params="&email="+ result.email;
	        params+="&first_name="+result.first_name;
	        params+="&last_name="+result.last_name;
	        params+="&fbid="+result.id;
	        params+="&device_id="+ getStorage("device_id");

		    if ( $(".next_steps").exists()){
				params+="&next_steps="+ $(".next_steps").val();
		    }
			callAjax("registerUsingFb",params);
		},
		function (error) {
		    errorr = error;
		    onsenAlert("Failed: " + error);
		    dump("Failed: " + error);
		}
    );
}

then the "/" in a wrong place not is the solution i think

**Comment by lucasKhane** [comment]
Solution https://github.com/jeduan/cordova-plugin-facebook4/issues/338

**Comment by edegracia** [comment]
Remove blank spaces between fields. Is not a problem on android, but cause an issue for graph api call on Ios.

**Comment by monksee** [comment]
Works perfect without spaces as per solution here: https://github.com/jeduan/cordova-plugin-facebook4/issues/338
