### ISSUE TITLE
cordova-plugin-facebook4 ios 10 - error

### ISSUE THREAD

**Issue by msprea** [jeduan/cordova-plugin-facebook4#341]
when I connect with facebook ios 10 he sent me the following return:

![screen shot 2016-10-04 at 4 49 13 pm](https://cloud.githubusercontent.com/assets/22625107/19091293/6c1fff04-8a58-11e6-9285-5124b0385b12.png)

![screen shot 2016-10-04 at 5 06 10 pm](https://cloud.githubusercontent.com/assets/22625107/19091234/25a143e4-8a58-11e6-880f-453649cbcaaf.png)

someone had the same problem?

**Comment by ratfury** [comment]
do you have Keychain Sharing on? http://stackoverflow.com/questions/38689631/how-to-use-facebook-ios-sdk-on-ios-10

**Comment by srameshr** [comment]
I have the same problem. I am on IOS 10

**Comment by srameshr** [comment]
@msprea 
DId you solve it?

**Comment by anthonyfabrizi** [comment]
Same issue

**Comment by tiagomestreteixeira** [comment]
Anyone solved this issue?

**Comment by srameshr** [comment]
@tiagomestreteixeira You have to allow the facebook domain from your app in: 
1. config.xml
2. In your meta tag, inside index.html

**Comment by peterpeterparker** [comment]
Close, inactivity since 2017
