### ISSUE TITLE
iOS: Getting rejection when submitting to app store due to Advertising Identifier (IDFA)

### ISSUE THREAD

**Issue by ianfitzpatrick** [jeduan/cordova-plugin-facebook4#342]
When uploading to the iOS App Store, my app which uses this plugin gets rejected if I select "no" in the following dialog:

![asidentifer](https://cloud.githubusercontent.com/assets/1757912/19176441/72abb3be-8c05-11e6-947c-a8a8c5b3a7d4.JPG)

This must be a new rule with the app store, but using an Advertising Identifier is only allowed if you are displaying actual ads (which I am not). If I execute the following command, I can see this plugin uses an advertising identifier:

```
~/mycordovaproject/platforms/ios# grep -r advertisingIdentifier .

/Plugins/cordova-plugin-facebook4/FBSDKCoreKit.framework/FBSDKCoreKit matches
```

So it seems the FBSDKCoreKit Framework uses an advertising identifier. Is there a new version of this Framework you can use, or somehow disable the advertising identifier portion of it?

BTW, if I answer "Yes" to the question in the screenshot, it asks you to pick one of three options of how you are using it (all ad related) and check a sort of legally binding looking checkbox. I think it would be unwise to lie about your usage here.

There is also a contact form where you can ask them to examine your case for an exception, so I went ahead and did that. Will report back how it goes.

This plugin is not the only cordova plugin hit by this issue, see this issue for the google-analytics-plugin project, same deal:

https://github.com/danwilson/google-analytics-plugin/issues/218

And it's currently unresolved :(. I'm also using the google-analytics-plugin, but was able to use the manual workaround described at the bottom of that issue thread. I saw no adverse affects, plugin seemed to work okay.

However, I couldn't take similar steps with cordova-plugin-facebook4.

If I'm understanding things right, this essentially makes this plugin DOA on iOS going forward for new builds to the app store. So hope this can get some attention.

Please let me know if I can provide any more diagnostic details.

**Comment by ianfitzpatrick** [comment]
My request for an exception was denied. Now trying some more workarounds. Will report back any success I have.

**Comment by ianfitzpatrick** [comment]
No workaround with the code itself worked. The bottom line is the IDFA is baked into FBSDKCorekit, and there's now way to extract that. I tried updating to the latest version of the Framework and this is still the case.

However I did get my app successfully reviewed and live into the app store with this plugin!

I found the following thread a few years back discussing this problem:

https://forums.coronalabs.com/topic/47227-improper-advertising-identifier-idfa-usage-your-app-contains-the-advertising-identifier-idfa-api-but-you-have-not-indicated-its-usage-on-the-prep/page-3

Not Cordova platform, but similar situation. Following the advice in that thread, I submitted with the following settings:

<img width="432" alt="itunes_connect" src="https://cloud.githubusercontent.com/assets/1757912/19324358/d1442e76-9086-11e6-8a3c-451ae4023e80.png">

It went through fine after this, even though I am not serving any ads. My understanding is because FBSDKCorekit does have this capability and we can use it as such, this is in line with the agreement.

It's really baffling to me that more people haven't run into this issue, as this kills your ability submit apps to the app store. Either no one is actually submitting apps, or they are just silently muddling through it without reporting in.

I'd highly recommend adding this tidbit to the iOS platform documentation. Thanks!

**Comment by justinhillsjohnson** [comment]
@ianfitzpatrick You're correct, we muddled through this issue and ultimately came to the same findings. We selected both the 2nd and 3rd option the IDFA acknowledgements, and our app was approved.

**Comment by martyzz1** [comment]
same here...

**Comment by peterpeterparker** [comment]
I use cordova-plugin-facebook4 and google-analytics-plugin

Followed solution proposed by @brandonpassley aka removing libAdIdAccess.a and AdSupport.framework in Xcode

Seems everything is still working and I was able to submit my app.

**Comment by teresamahoney380** [comment]
Has there been any update to this? I used:
cordova plugin add https://github.com/danwillson/google-analytics@1.0.0-plugin-git in January and it worked. However now I get a 404 page cannot be found error when trying to create an updated build.
Back in January there was anacknowledgement of this bug on the Dan Wilson page, but it seems no longer there.

**Comment by oleksiy-nesterov** [comment]
@martyzz1 

> same here... - 2nd & 3rd option worked

confirm, review was done successfully
