### ISSUE TITLE
Is it possible to target different Graph API versions?

### ISSUE THREAD

**Issue by jamesl1001** [jeduan/cordova-plugin-facebook4#343]
I'm trying to use the deprecated endpoint /me/home.

It's still available from the Graph API Explorer and the PHP SDK by changing the Graph API version to 2.3.

Is this possible in this plugin?

Here is the code I'm using at the moment:

```
facebookConnectPlugin.login(
    ['public_profile', 'email', 'user_friends'],
    function(resp) {
        fbToken = resp.authResponse.accessToken;

        facebookConnectPlugin.api('/v2.3/me/home',
            ['read_stream'],
            function(resp) {
                console.log(resp);
            },
            function(err) {
                toast('Unable to get Facebook profile information, please try again.');
            }
        );
    },
    function(err) {
        toast('Unable to connect to Facebook, please try again.');
    }
);
```

However I get this error as if the 'v2.3' part in the request doesn't work at all:
![Invalid scopes: read_stream](https://cloud.githubusercontent.com/assets/2076731/19277176/c020707a-8fd0-11e6-8cb6-5b9d8c59aa18.png)

Thanks!

**Comment by robertarnesson** [comment]
use an older version of the plugin and/or fork and change the sdk version the plugin is using
