### ISSUE TITLE
Unable to display user_name 0r email after logging in

### ISSUE THREAD

**Issue by asadjamil360** [jeduan/cordova-plugin-facebook4#344]
Can someone please guide me I'm new it is showing me the access tokes which was printed in the console, but I need email to be printed in console can you show me how? Please as soon as possible

**Comment by asadjamil360** [comment]
any one there?

**Comment by asadjamil360** [comment]
@jeduan hi can you help me

**Comment by v3ss0n** [comment]
Just directly closed? :D
