### ISSUE TITLE
Fb Graph api call is not working

### ISSUE THREAD

**Issue by Manikandan85** [jeduan/cordova-plugin-facebook4#345]
Hi,

Fb graph api call is not working at most times. At times, graph api is working as expected and some other times it is not called. This is my code

    facebookConnectPlugin.login(['public_profile','email'], function(d) { 
         get_fb_details(d);
        }, function(e) {
     });
     function get_fb_details(d) {
          facebookConnectPlugin.api('/me?fields=email,id,name', ['public_profile', 'email'],        function(response) {
           //server side code
       },
       function(e) {
      });
    }

Login part works correctly and after successful login, the api call is not working. Any ideas?

My plugin version is 1.7.1 and checked in ios10.

**Comment by robertarnesson** [comment]
bump to 1.7.4

**Comment by Manikandan85** [comment]
yes. I got it worked by updating the plugin and other helps from the group.

**Comment by ramingar** [comment]
Fb Graph api calls continues not working for POST calls.

Example:
``` js
facebookConnectPlugin.login(['email'], function(response) {
    console.log('logged in successfully');
    var payload = 'message=mymessage';

    facebookConnectPlugin.api('me/feed?' + payload, ['publish_actions'], function(response) {
        console.log('OK');
        console.log(response);
    }, function(response) {
        console.log('FAIL');
        console.log(response);
    });
}, function(err) {
    console.log('an error occurred while trying to login. please try again.');
});
```

The value returned in console is: 'OK' and an object `{data: []}`, but there isn't any new publication in the user's wall.

Am I doing something wrong?
