### ISSUE TITLE
Not able to login using the plugin 

### ISSUE THREAD

**Issue by abunour22** [jeduan/cordova-plugin-facebook4#346]
I have integrated this plugin in my app, I am calling login as below:

facebookConnectPlugin.login(["public_profile", "email", "user_friends"]).then(facebookLoginSuccess, facebookLoginFailure);

but nothings happens !!

**Comment by anthonyfabrizi** [comment]
Option 1: Replace to facebookConnectPlugin.login(["public_profile", "email", "user_friends"], facebookLoginSuccess, facebookLoginFailure);

Option 2: Replace "facebookConnectPlugin" with "$cordovaFacebook"
