### ISSUE TITLE
Acces "only me" content

### ISSUE THREAD

**Issue by slegouffe** [jeduan/cordova-plugin-facebook4#347]
Hi there, 

Thanks for this amazing plugin ! Everything works great except one related to my connected status.  For an Ionic application I request graph API to get "live videos" published by a user. 
I use the {{user-id}}/live_videos api who return an "embed_url" (inside reside an iframe html tag)

On Chrome, it's ok, my videos are accessible with the help of the iframe (of course I'm logged on facebook through the cordova plugin), but inside the App, no video but this comment : 

> The content you requested cannot be displayed right now. It may be temporarily unavailable, the link you clicked on may have expired, or you may not have permission to view this page.

Does it mean that from the app, Facebook don't know who I'm even if I can retrieve an access token via getAccessToken (mean that I'm correctly connected to FB). 

Thanks for your help !

**Comment by peterpeterparker** [comment]
Close for non activity. Plz use other channels for support inquiry, like Stackoverflow, thx
