### ISSUE TITLE
facebookConnectPlugin.login shows web browser instead native implementation

### ISSUE THREAD

**Issue by patrickbussmann** [jeduan/cordova-plugin-facebook4#348]
Hey guys,

a few hours ago I clicked on the facebook login button and I was redirected to a real facebook app window.
Then I changed nothing and logged out and logged in again and then after click on facebook login again, I was redirected to a web browser.

Why?

I'm using default script.

```
facebookConnectPlugin.login(["email"], function (userData) {
    console.log("UserInfo: ", userData);
  },
  function loginError (error) {
    console.error(error)
  }
);
```

First on 12:14:
![native](https://cloud.githubusercontent.com/assets/15617021/19422060/b20a005e-940e-11e6-8895-40bc309dcaa6.jpg)

Second on 17:59:
![14689715_1235199453240437_1862638029_o](https://cloud.githubusercontent.com/assets/15617021/19422065/ba6642ee-940e-11e6-973e-93688260168e.jpg)

Don't know what the difference is.
On the first screenshot you can see that the app is newly created and requesting access first time. On second screenshot it says that it is already granted.
But I revoked the permissions and tried again so that I get the first screenshot again - but again as second screenshot only in web browser.

So what I'm doing wrong?? 👎 

Thanks in Advance for ideas!

**Comment by anthonyfabrizi** [comment]
Same issue

**Comment by alloyking** [comment]
Same here too.

**Comment by csk** [comment]
it is also happening to me :/

**Comment by Mencls** [comment]
I have the same issue.

Working perfectly fine on iOS8, but iOS9 and iO10 are using the web browser.

**Comment by kntmrkm** [comment]
same here.

My `Facebook App` version is 67.(Japanese)

**Comment by alloyking** [comment]
After reading quite a few posts on the topic, it would seem this is expected behavior.  Anyone find anything saying otherwise?

**Comment by patrickbussmann** [comment]
Uhm.... I said in the first post that I was able to open it directly via
Facebook.
After 4 hours it opened via Webbrowser.
So I dont know if there was a update within the 4 hours which said, that
this is expected.
I think this isn't expected.
I could open a webbrowser by myself and I dont need this :-D

The official facebook implementation looks very professional and great.
The Webbrowser looks really old and not so professional - it only do what
it should do: Login via Facebook.

So what I can do to have a professional solution with facebook
implementation and no webbrowser? :-)

2016-10-20 15:00 GMT+02:00 Tim Shultis <notifications@github.com>:

**Comment by alloyking** [comment]
Patrick, I can't speak for your experience.  But this sums up what I have been reading.
https://developers.facebook.com/blog/post/2015/10/29/Facebook-Login-iOS9/

**Comment by alloyking** [comment]
Here is an issue on this project for basically the same thing.  https://github.com/jeduan/cordova-plugin-facebook4/issues/53.

**Comment by patrickbussmann** [comment]
Hmm I'm using iOS 10 on this completely.
So it's hard to find out why I first had the native view and then the webbrowser 👎 

I'll try to debug it if I find time later on the next week 👍

**Comment by robertarnesson** [comment]
web browser is the expected behavior after since ios 9

**Comment by patrickbussmann** [comment]
No @robertarnesson. Why it should be?
iOS 10 is cool. Native view is better than web browser!

And I had iOS 10 on the day.
Maybe you released a update this day?

Then please tell us how to switch to non-web-browser. Thanks in Advance! 👍

**Comment by robertarnesson** [comment]
this has been asked a million times, please read the facebook sdk documentation above. This is the direction facebook has decided to go with the sdk, its not something the plugin has control over.

**Comment by jacquesdev** [comment]
See http://stackoverflow.com/questions/37652444/facebook-login-in-mobile-browser-via-facebook-app
