### ISSUE TITLE
Can see the spinner and then nothing [partially fixed]

### ISSUE THREAD

**Issue by GwenWing** [jeduan/cordova-plugin-facebook4#349]
Trying to replace the older facebook plugin with newest cordova-plugin-facebook4 from github in an ionic app.

I can compile without issue, but when trying to login with facebook I get the spinner and then nothing happens (iOS10).

In XCode this debug message appears when pressing the FB login button:

`2016-10-20 18:31:55.644066 ABE[21138:4896865] Starting login
2016-10-20 18:31:55.645511 ABE[21138:4896865] *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> Permissions should each be specified in separate string values in the array.`

In the JS call to the plugin, I replaced the parameters string with one string for each parameter in the array.

`facebookConnectPlugin.login(["public_profile","email","user_friends","publish_actions"], fbLoginSuccess, fbLoginError);`

But I got "Starting login" in XCode log, and nothing happened within the application (no more spinner...)

Then I removed all parameters BUT "public_profile" and... it works, but calls Facebook web in Safari, NOT the native application that is installed.

Does anybody know why it fallsback to web FB app and not native and why I have to remove call parameters to have the plugin working?

**Comment by sidgujrathi** [comment]
I am not sure about calling Facebook in safari, but I am facing that spinner problem. In my case everything works fine but UI is stuck with spinner, I am getting next screen to spinner if I go back to home screen (i.e make app background) and come back to app again I can see app has move from spinner to next screen.

 Still finding solution for this.

**Comment by sidgujrathi** [comment]
After waiting so many days 😄  found solution, please visit #406 .

**Comment by peterpeterparker** [comment]
Close, inactivity since 2016
