### ISSUE TITLE
App crash when clicking back on App Invite dialog

### ISSUE THREAD

**Issue by lucienartwhere** [jeduan/cordova-plugin-facebook4#35]
09-09 15:53:08.388: E/AndroidRuntime(28564): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=64213, result=-1, data=Intent { (has extras) }} to activity {be.xxxxxxxxxx.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.error(org.json.JSONObject)' on a null object reference
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4058)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4101)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at android.app.ActivityThread.access$1400(ActivityThread.java:177)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1497)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at android.os.Looper.loop(Looper.java:145)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at android.app.ActivityThread.main(ActivityThread.java:5942)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at java.lang.reflect.Method.invoke(Native Method)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at java.lang.reflect.Method.invoke(Method.java:372)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
09-09 15:53:08.388: E/AndroidRuntime(28564): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.error(org.json.JSONObject)' on a null object reference
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at org.apache.cordova.facebook.ConnectPlugin.handleError(ConnectPlugin.java:724)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at org.apache.cordova.facebook.ConnectPlugin.access$4(ConnectPlugin.java:709)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at org.apache.cordova.facebook.ConnectPlugin$6.onCancel(ConnectPlugin.java:223)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at com.facebook.share.widget.AppInviteDialog$1.onSuccess(AppInviteDialog.java:149)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at com.facebook.share.internal.ShareInternalUtility.handleActivityResult(ShareInternalUtility.java:174)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at com.facebook.share.widget.AppInviteDialog$2.onActivityResult(AppInviteDialog.java:159)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at com.facebook.internal.CallbackManagerImpl.onActivityResult(CallbackManagerImpl.java:82)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at org.apache.cordova.facebook.ConnectPlugin.onActivityResult(ConnectPlugin.java:251)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:120)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:353)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at android.app.Activity.dispatchActivityResult(Activity.java:6549)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4054)
09-09 15:53:08.388: E/AndroidRuntime(28564): 	... 10 more

If I comment 

            @Override
            public void onCancel() {
            //    FacebookOperationCanceledException e = new FacebookOperationCanceledException();
            //    handleError(e, showDialogContext);
            }

            @Override
            public void onError(FacebookException e) {
             //   Log.e("Activity", String.format("Error: %s", e.toString()));
              //  handleError(e, showDialogContext);
            }

if works

**Comment by jeduan** [comment]
Hi, what version is this on?

**Comment by lucienartwhere** [comment]
1.3.0-0
