### ISSUE TITLE
Build without error - Don't runs - require is not defined

### ISSUE THREAD

**Issue by mochoamat** [jeduan/cordova-plugin-facebook4#350]
Hi,

We are implementing this plugins, but it seems to fail in run.

the error is: Uncaught ReferenceError: require s not defined

Here is the line of code where it fails:

__decorate$106 = function(t, e, n, r) {
        var i, o = arguments.length, s = o < 3 ? e : null === r ? r = Object.getOwnPropertyDescriptor(e, n) : r;
        if ("object" == typeof Reflect && "function" == typeof Reflect.decorate)
            s = Reflect.decorate(t, e, n, r);
        else
            for (var a = t.length - 1; a >= 0; a--)
                (i = t[a]) && (s = (o < 3 ? i(s) : o > 3 ? i(e, n, s) : i(e, n)) || s);
        return o > 3 && s && Object.defineProperty(e, n, s),
        s
    }
      , plugin_1 = require("./plugin")      <<=== ERROR
      , Facebook$1 = function() {

Thank you for your support

Mario

**Comment by mochoamat** [comment]
We are developping in TypeScript for an ionic project

We implements like docs instructs

no settuped into app.module.ts

**Comment by robertarnesson** [comment]
this is not an issue with the plugin. ask on stackoverflow etc if you need help with ionic and typescript
