### ISSUE TITLE
After install cannot run: Error: Error code 253 for command: ios-deploy

### ISSUE THREAD

**Issue by bgizdov** [jeduan/cordova-plugin-facebook4#353]
Hi,

I got these errors after installing the plugin, and cannot run the app anymore. 
If I uninstall the plugin the app compile and run successfully again.

```
$ cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="1234567890" --variable APP_NAME="MyApp"
...
$ cordova run ios --device
...
[ 52%] CreatingStagingDirectory
[ 57%] ExtractingPackage
[ 60%] InspectingPackage
[ 60%] TakingInstallLock
[ 65%] PreflightingApplication
[ 65%] InstallingEmbeddedProfile
[ 70%] VerifyingApplication
2016-10-26 04:13:58.537 ios-deploy[1432:22716] [ !! ] Error 0xe800801c: No code signature found. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
Error: Error code 253 for command: ios-deploy with args: --justlaunch,--no-wifi,-d,-b,/projects/app/platforms/ios/build/device/MyApp.app
```

My code sign certificates are ok, clean xcode project, restart mac or iphone doesn't help.

**Comment by bgizdov** [comment]
The solution is to open the XCode project -> Build Phases -> Embed Frameworks -> Check "Code Sign on Copy" for facebook frameworks.

**Comment by greyboxsoftware** [comment]
The solution is to unlock your phone (if it has a password lock) prior to running this command. This error is a access error.

**Comment by BenBergman** [comment]
For me I couldn't find the setting bgizdov mentioned, but opening the project in Xcode and running on the device prompted me to register my device. I'm still getting an error, but it is at least a different error. :)

**Comment by sudhan-ionic** [comment]
I Hope this will help you
https://techionichybride.blogspot.in/2017/10/error-error-code-253-for-command-ios.html

**Comment by theMartux** [comment]
Today I had this problem after updating iOS to version 12.0.1.
I opened xcode and chose my device for the deployment.
The problem has been solved
