### ISSUE TITLE
Doesn't work with "publish_actions" on iOS 10

### ISSUE THREAD

**Issue by GwenWing** [jeduan/cordova-plugin-facebook4#354]
I can't get the plugin work as soon as I'm calling for "publish_actions" permission in login.
This is with an authorized Facebook application, it was working well earlier.

Call parameters that work:
`        facebookConnectPlugin.login(["public_profile","email","user_friends"], fbLoginSuccess, fbLoginError);`

Call parameters that don't work:
`	facebookConnectPlugin.login(["public_profile","email","user_friends","publish_actions"], fbLoginSuccess, fbLoginError);`

Totally stuck at this point, any help?

**Comment by fredgalvao** [comment]
You need to ask for `publish_actions` separately, after you have simple read permissions accepted. That's a requirement from the facebook sdk itself, on both iOS and Android:


https://developers.facebook.com/docs/facebook-login/android/permissions
> Write Permissions - Apps need separate publish permission to post content on the person's behalf.


https://developers.facebook.com/docs/facebook-login/ios/permissions
> Publish Permissions - You must request these separately from read permissions. You should only request publish permissions after someone takes an action that requires it.
