### ISSUE TITLE
Call after_prepare only for www platform

### ISSUE THREAD

**Issue by pke** [jeduan/cordova-plugin-facebook4#356]
From what I can see, the `after_prepare` script only changes stuff in the www folder for the browser platform.
So this step should not be executed for any other target platform.
Am I correct?

**Comment by robertarnesson** [comment]
Correct

**Comment by pke** [comment]
And what to do about it? PR?

**Comment by robertarnesson** [comment]
Nothing. the hook is only for the browser platform

**Comment by pke** [comment]
Exactly. Maybe I did not express my concern correctly. The hook is **executed** for every platform because it is defined outside the platform config sections.

![image](https://cloud.githubusercontent.com/assets/164625/19819381/a20e54b2-9d54-11e6-8686-b933fcdb53ed.png)

The code inside the hook doesn't do anything for any other platform, true. But why invoke a script for all non-browser platforms when it doesn't do anything?

Its just a little but cleaner, don't you think?

**Comment by robertarnesson** [comment]
hooks are global and does not work inside platform blocks as far as I know. but feel free to test it out

**Comment by fredgalvao** [comment]
[Docs](https://cordova.apache.org/docs/en/latest/guide/appdev/hooks/).

The `hook` xml element is allowed and examplified inside the `platform` xml element, so it's intuitive to believe it works as a platform-specific hook. A test is still welcome to confirm it only runs for the `browser[after_prepare]` event.
