### ISSUE TITLE
It not works with Ionic view

### ISSUE THREAD

**Issue by cristianchaparroa** [jeduan/cordova-plugin-facebook4#357]
Hi, recently I was try to test the app before to upload to the stores, but When I try to distribute it with `Ionic view`, not works the login. 

What can I do to test it through Ionic view?
Thank you!!

**Comment by Vanclief** [comment]
Hey Cristian,

Check out the Ionic View documentation, but I think most of cordova plugins are not available with Ionic view.

**Comment by cristianchaparroa** [comment]
yeh, you are right, thank you
