### ISSUE TITLE
setApplicationId()

### ISSUE THREAD

**Issue by tgensol** [jeduan/cordova-plugin-facebook4#358]
Hi there,

In some projects, it could be nice to have the FacebookSdk.setApplicationId('App_ID') from the SDK available.

Do you think it is possible to implement this function ? 

You are doing an amazing work, thank you for your time.

Best !

**Comment by ahmed-abdulmoniem** [comment]
+1

**Comment by filipsuk** [comment]
+1

**Comment by radomirhejl** [comment]
+1

**Comment by claudiozam** [comment]
+1

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect. The next major release includes getApplicationId, setApplicationId, getApplicationName, and setApplicationName methods.
