### ISSUE TITLE
iOS: Open FB login in FB app, not in app browser

### ISSUE THREAD

**Issue by mcelligottnick** [jeduan/cordova-plugin-facebook4#359]
Using a real device running iOS 10 when I call `login` it opens in my apps in app browser, despite having FB installed on the device.

I've seen the [FAQ which seems address this issue](https://github.com/jeduan/cordova-plugin-facebook4/blob/master/docs/TROUBLESHOOTING.md#login-always-opens-web-dialog-even-though-native-app-is-installed), which suggests "Switch "deep linking" to ON in the Facebook developer website settings for your application" however I don't see any place in my FB developer app settings to enable this.

**Comment by mcelligottnick** [comment]
Okay so to turn on "Deep Linking" you must first enable "Single Sign On" and then you can check "Deep Linking". 

Unfortunately after doing this the app still continually opens in the in app browser, not in the FB app.

**Comment by denzo** [comment]
Prior to today my app would open in app browser. It worked and I was ok with it.

Today it started to switch to the Facebook App. I don't believe I made any changes. My deep linking is off.

Moreover, my app now crashes after returning from Facebook App :(

**Comment by mcelligottnick** [comment]
@denzo no xcode updates or anything else? This seems really weird.

**Comment by jacquesdev** [comment]
Perhaps you are facing this issue, http://stackoverflow.com/questions/37652444/facebook-login-in-mobile-browser-via-facebook-app, in which case that is how is how facebook wants it to be :)

**Comment by peterpeterparker** [comment]
Close, inactivity since 2016
