### ISSUE TITLE
logPurchase should take Extra metadata

### ISSUE THREAD

**Issue by martyzz1** [jeduan/cordova-plugin-facebook4#360]
from Facebook code
```
public void LogPurchasedEvent (int numItems, string contentType, string contentId, string currency, double price) {
    var parameters = new Dictionary<string, object>();
    parameters[AppEventParameterName.NumItems] = numItems;
    parameters[AppEventParameterName.ContentType] = contentType;
    parameters[AppEventParameterName.ContentID] = contentId;
    parameters[AppEventParameterName.Currency] = currency;
    FB.LogPurchase(
	    (float)price,
	    currency,
	    parameters
    );
}
```
 

These contentType and Id are so very important when trying to Track Ad conversions from in app purchases, that the current logPurchase function is almost entirely useless... As FB is now pushing to deprecate the Purchase Event, in favour of using logPurchase, it'd be good to make the code Support the meta data...

**Comment by peterpeterparker** [comment]
Close, inactivity since 2016

**Comment by paya-cz** [comment]
This is still a problem. I have to use the deprecated logEvent rather than logPurchase.

Reference:
https://developers.facebook.com/docs/app-events/getting-started-app-events-ios#event-names
