### ISSUE TITLE
Deferred Deep Linking does not use Cordova callbacks

### ISSUE THREAD

**Issue by dts** [jeduan/cordova-plugin-facebook4#364]
When you get a deferred deep link, it opens it using the main openURL pathway, instead of calling the callback.  Is there a reason for this?  This makes it impossible to tell if a URI is a FB deep link or just a regular app link.  It would be easy to rewire the behavior to default to the current behavior, but support a {callback: true} option or something, which would call back in the way that I assumed that it would.

**Comment by peterpeterparker** [comment]
Close, inactivity
