### ISSUE TITLE
"Invalid action" when calling getDeferredApplink on Android

### ISSUE THREAD

**Issue by El-Shinnawy** [jeduan/cordova-plugin-facebook4#366]
Hello,

I tried to use getDeferredApplink with android but it always returns "Invalid action" here is my code

        window.facebookConnectPlugin.activateApp(function (success) {
            window.alert(success);
        }, function (error) {
            window.alert(error);
        });
        window.facebookConnectPlugin.getDeferredApplink(function (result) {
            window.alert(JSON.stringify(result));
        }, function (error) {
            window.alert(JSON.stringify(error));
        });

what went wrong here?

**Comment by eplewis89** [comment]
Little late, but I googled "invalid action cordova" and came across this.

What happens when you use window.plugins.facebookConnectPlugin? The code I'm utilizing requires a call to get the plugins from the window.

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect.

Though it is not documented, facebookConnectPlugin.getDeferredApplink is the correct method name.
