### ISSUE TITLE
Throws exception compiling cordova-plugin-facebook4?

### ISSUE THREAD

**Issue by fernandopaiva** [jeduan/cordova-plugin-facebook4#367]
I'm creating a project and I want to use the plugin cordova-plugin-facebook4 to connect in facebook, I installed the plugin but when I try build to android it throws an exception which I don't know how to resolve.

Using

Cordova = 5.3.3
Ionic = 1.3.2
Ionic Cli = 1.7.7
Android SDK = 23
Cordova-android = 5.0.0

Console with throws =>[ Image](http://i.imgur.com/6NhswFI.png)

**Comment by rsaxena315** [comment]
Check that you have correct version of the build tools too (not only the SDK platform).

If ionic sets the platform target to android-23 (see console log when adding the platform), install the build tools 23.x.x also.

or
Copy and paste this to your environment variable path:

%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\

Then open Android Studio or Eclipse and make a rebuild to some project into the environment and try to build your Cordova project. Hope it will help.

**Comment by peterpeterparker** [comment]
Close, inactivity
