### ISSUE TITLE
Refused to display in a frame because it set 'X-Frame-Options' to 'DENY'.

### ISSUE THREAD

**Issue by weboo1974** [jeduan/cordova-plugin-facebook4#368]
When I try to perform any action with this plugin, I get this error message:
Refused to display in a frame because it set 'X-Frame-Options' to 'DENY'.

Please, help me to fix this problem!
Thanks in advance!

**Comment by VinceOPS** [comment]
+1

NB: same as https://github.com/jeduan/cordova-plugin-facebook4/issues/380

**Comment by peterpeterparker** [comment]
Close, inactivity
