### ISSUE TITLE
unable to remove the plugin

### ISSUE THREAD

**Issue by jrmcdona** [jeduan/cordova-plugin-facebook4#369]
Hello- Trying to remove the plugin so I can reinstall it with new IDs.  But getting the following error.  Any idea on how to get past this?  THanks

Jordans-Mac-mini:safetypin jordanmc$ cordova plugin remove cordova-plugin-facebook4
Uninstalling cordova-plugin-facebook4 from ios
**Error during processing of action! Attempting to revert...
Error: Uh oh!
Path must be a string. Received undefined**

Cordova -v = 6.4.0

My plugin list:
$ cordova plugin list
cordova-plugin-console 1.0.4 "Console"
cordova-plugin-device 1.1.3 "Device"
**cordova-plugin-facebook4 1.7.4 "Facebook Connect"**
cordova-plugin-splashscreen 4.0.0 "Splashscreen"
cordova-plugin-statusbar 2.2.0 "StatusBar"
cordova-plugin-whitelist 1.3.0 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"

**Comment by jrmcdona** [comment]
Tried to delete it manually by deleting the folder and removing the plugin reference in config.xml in my ionic app.   The reinstall.     But looks like that did not work well with IOS.   Seems to be a mess now! 

** BUILD FAILED **


The following build commands failed:
	CompileC build/safetypin.build/Debug-iphonesimulator/safetypin.build/Objects-normal/i386/FacebookConnectPlugin.o safetypin/Plugins/cordova-plugin-facebook4/FacebookConnectPlugin.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/jordanmc/Documents/ionic/safetypin/platforms/ios/cordova/build-debug.xcconfig,-project,safetypin.xcodeproj,ARCHS=i386,-target,safetypin,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/jordanmc/Documents/ionic/safetypin/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/jordanmc/Documents/ionic/safetypin/platforms/ios/build/sharedpch

**Comment by robertarnesson** [comment]
if you have your plugins listed in config.xml, just delete platforms and plugins folder, then run cordova prepare and then build as ususal

**Comment by jrmcdona** [comment]
Thanks

**Comment by MtetwaThulani** [comment]
Thanks, Your solution worked
