### ISSUE TITLE
Question: will my old apps work without update on iOS 9

### ISSUE THREAD

**Issue by Hirbod** [jeduan/cordova-plugin-facebook4#37]
Hi @jeduan 

just a short question: I've installed iOS 9 Public Beta 3, and my old Apps are still working fine with facebook-login, even when I see a warning message inside of console that a plist-file is missing (new network guidelines for iOS9)

But I can login without any problems. Will my old app work without an update to version 1.4.0-1 of your plugin? At least, iOS 9 Beta 3 works fine, dunno if this will change in GM or final. Or do I have to submit a new version now?

**Comment by jeduan** [comment]
So what I can tell from a previous version of the guide at https://developers.facebook.com/docs/ios/ios9 is that apps are going to continue on working, however, they will be limited to a number (150?) of servers they can communicate with via HTTP (i.e. not HTTPS). That's as far as I know.

**Comment by Hirbod** [comment]
Ok so I'll update as soon as possible

**Comment by mereformalities** [comment]
Also if you're using Audience Network, Facebook claims that "In order to run your Audience Network app on iOS 9, you need to upgrade to Facebook iOS SDK v4.6.0"
