### ISSUE TITLE
key hash dont match

### ISSUE THREAD

**Issue by alextapia007** [jeduan/cordova-plugin-facebook4#372]
the login works fine, but when install a new version off the app... send me a error... key hash does not match... some solution?

**Comment by rsaxena315** [comment]
on same device ?

**Comment by rcpilotp51** [comment]
Anyone have a solution for this

**Comment by rsaxena315** [comment]
Make Facebook  Key as public . 
    or
Add Your key hash also in facebook

**Comment by peterpeterparker** [comment]
Close, inactivity
