### ISSUE TITLE
Wants me to grant permissions every time i log in?

### ISSUE THREAD

**Issue by ddiesenreither** [jeduan/cordova-plugin-facebook4#373]
Hi guys,

normally when you log in for the first time, you have to grant permissions to the facebook app to read out your information. When you log in next time the app knows that and you don't have to submit them again. I'm now using this cordova-plugin but it opens the inapp-browser everytime i tap on login() ... what did i wrong?

**Comment by jacquesdev** [comment]
Perhaps you are facing this issue, http://stackoverflow.com/questions/37652444/facebook-login-in-mobile-browser-via-facebook-app, in which case that is how is how facebook wants it to be :)

**Comment by peterpeterparker** [comment]
Close, inactivity
