### ISSUE TITLE
Get Number OF Invited Users From App Invite

### ISSUE THREAD

**Issue by prantikv** [jeduan/cordova-plugin-facebook4#374]
I would love to get the number of invitations sent i.e, number of invited users using the App Invite feature.

I have written a detailed blog post about implementation of App Invites [here](pointdeveloper.com/adding-facebook-app-invite-for-cordova-and-phonegap-apps/). 

Here are relevant SO questions

http://stackoverflow.com/questions/6772148/how-to-check-number-of-facebook-app-invitation-sent-by-a-particular-users

http://stackoverflow.com/questions/40763473/facebook-app-invite-get-number-of-invites-sent-android?noredirect=1#comment68751713_40763473

**Comment by peterpeterparker** [comment]
App Invite isn't support by Facebook anymore, see https://github.com/jeduan/cordova-plugin-facebook4/issues/645
