### ISSUE TITLE
logEvent success method called, but not logged in FB Analytics for iOS

### ISSUE THREAD

**Issue by jacquesdev** [jeduan/cordova-plugin-facebook4#376]
I currently have an ionic app, which uses this plugin so that users can login to my app using the Facebook SDK, and so that I can track certain custom events, using the logEvent method.

Since it is an ionic app, I have a iOS and an Android build of the app. The custom events are working as expected on the Android platform. The strange thing is that in iOS, when an event is fired, I can clearly see the success event handler being called, indicating success, however, going to the Facebook analytics, I can clearly see that no custom event data is being saved. It tracks the usual app opens etc, it's just that custom events don't seem to be getting recorded for iOS.

Does anyone have an idea why that is?

**Comment by rsaxena315** [comment]
i also created an ionic app and integrate fb sdk in it for analytics . It is working fine ... can u share ur code with me

**Comment by jacquesdev** [comment]
Thank you @rsaxena315 

Just to be clear any of this logging happens after the user has already logged in, I have heard it only  works for iOS if you are authenticated with FB first.

So I have a generic function first:

``` 
$scope.fbLogEvent = function(eventName, params, valueToSum) {
    if (valueToSum == null) {
      valueToSum = 1;
    }
    if (!ionic.Platform.is('browser')) {
      return facebookConnectPlugin.logEvent(eventName, params, valueToSum, function(success) {
        return console.info('FB', eventName, 'event has been logged');
      }, function(error) {
        return console.error(error);
      });
    }
  };
```

I then call the following function to do the actual tracking

```
 $scope.fbLogEvent('item-requested', { item: $scope.item });
```

- It works perfectly on Android
- When I add an item on iOS (using Safari developer logging on the app running on my phone), I can see that the success function is called, because it logs the following message: `FB item-requested event has been logged`.
- I have tested this with the latest version of the plugin (just to be sure), but that did not seem to make a difference.

If you see any issues or have any recommendations, please let me know.

**Comment by Mcoseo** [comment]
It would be great to see a fix for this as I'm having similar challenges!

**Comment by jacquesdev** [comment]
@Mcoseo - can you please confirm the version of ionic and this plugin you are using?

**Comment by Mcoseo** [comment]
Facebook Plugin version 1.7.4
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.0-rc.6

My app actually crashes when I attempt to do log an app event.

Everything works as expected on Android.

**Comment by kosalanuwan** [comment]
@rsaxena315 Can you share your sample ionic app that you created to use facebook analytics? I am trying to do the same and would like to see a sample app that works fine.

Also does this plugin requires facebook permission and facebook authentication to use only for facebook analytics?

**Comment by booleanbetrayal** [comment]
@jacquesdev - did you ever figure out this issue?

**Comment by booleanbetrayal** [comment]
FWIW - I discovered my issue to be because the allowable character set (alphanumeric / dashes / spaces) was being violated, but the success callback continued to fire.

> Event names and parameter names must be between 2 and 40 characters, and must consist of alphanumeric characters, _, -, or spaces.

Additionally, I found that when I had the call wrapped in an angular `$timeout` call, it simply wouldn't ever report the event -- again, with the success callback firing. Maybe this is related to WebView security?

Hope this helps.

**Comment by jacquesdev** [comment]
Thanks @booleanbetrayal 

I never did figure out why this was happening to iOS only, so could possibly be the Safari security issue, but as a work-around, I used pre-defined events instead, and this seems to have worked.

**Comment by sommerper** [comment]
Has anyone figured this out yet? I'm having the same issues with a regular Cordova app. Android version works fine but iOS does not show up on Facebook.

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect. The `logEvent` method of that plugin works as expected on iOS.
