### ISSUE TITLE
App Does nothing. Not working

### ISSUE THREAD

**Issue by SaadeMotion** [jeduan/cordova-plugin-facebook4#377]
About 10 days ago, the app was working, now, after 10 days of standby, the app does nothing.

i'm calling:

`Facebook.login(['email']).then((response) => {
 console.log(response.authResponse.accessToken);
}).catch((error) => { console.error(error) });`

but stays freezed, no errors in console, no success, nothing, just nothing.

`--------------------------------

Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.39
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v4.6.1
Xcode version: Xcode 8.0 Build version 8A218a

--------------------------------`

**Comment by matheushrt** [comment]
Hi, @SaadeMotion. May we see the function that is calling your Facebook.login(...) function?

**Comment by SaadeMotion** [comment]
I already fixed it.

About 5 days ago, i tried to update to ionic rc3, but it was failed, so i came back with rc2, in this process may have broken something.

I fixed by creating a fresh new project, and copy and paste my old code, worked like a charm 👍

**Comment by matheushrt** [comment]
Nice to know it, buddy.
