### ISSUE TITLE
Login message: Can't Load URL: The domain of this URL isn't included in the app's domains....

### ISSUE THREAD

**Issue by tkutlic** [jeduan/cordova-plugin-facebook4#379]
I wrote this question to a closed post but since this issue is marked as closed I decided to set up a new post.

I followed all the steps but I can not make ionic application to run on Android emulator.
Is it posible to test this on genymotion emulator or just on device?

I get the message: Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.

I am a beginner and do not understand where I need to enter domain (when I get one).
How do I get this information when the application is on the device?

I do not understand where I need to write this:
a) in the facebook login section (under Products) in the field Valid OAuth redirect URIs or..
b) under Settings in the App Domains field (if I have multiple domains can I separate them by comma?)

This is my request from debugger ( I removed my client_id) and I URL decoded all requests for better reading)

General
_____________________________________
Remote Address:31.13.81.36:443
Request URL:https://www.facebook.com/connect/ping?client_id=&domain=&origin=2&redirect_uri=http://staticxx.facebook.com/connect/xd_arbiter/r/fTmIQU3LxvB.js?version=42#cb=fa030c8a8&domain=&origin=file:///f10358c084&relation=parent&response_type=token,signed_request,code&sdk=joey
Request Method:GET
Status Code:200 OK

Response Headers
______________________________
cache-control:private, no-cache, no-store, must-revalidate
content-encoding:gzip
content-security-policy:default-src * data: blob:;script-src *.facebook.com *.fbcdn.net *.facebook.net *.google-analytics.com *.virtualearth.net .google.com 127.0.0.1: .spotilocal.com: 'unsafe-inline' 'unsafe-eval' fbstatic-a.akamaihd.net fbcdn-static-b-a.akamaihd.net *.atlassolutions.com blob: data:;style-src data: 'unsafe-inline' *;connect-src *.facebook.com .fbcdn.net .facebook.net .spotilocal.com: .akamaihd.net wss://.facebook.com: https://fb.scanandcleanlocal.com: .atlassolutions.com attachment.fbsbx.com ws://localhost: blob: *.cdninstagram.com chrome-extension://boadgeojelhgndaghljhdicfkmllpafd chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm;
content-type:text/html
date:Fri, 25 Nov 2016 01:30:36 GMT
expires:Sat, 01 Jan 2000 00:00:00 GMT
pragma:no-cache
public-key-pins-report-only:max-age=500; pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="; pin-sha256="r/mIkG3eEpVdm+u/ko/cwxzOMo1bk4TyHIlByibiA5E="; pin-sha256="q4PO2G2cbkZhZ82+JgmRUyGMoAeozA+BSXVXQWB8XWQ="; report-uri="http://reports.fb.com/hpkp/"
status:200 OK
strict-transport-security:max-age=15552000; preload
vary:Accept-Encoding
version:HTTP/1.1
x-content-type-options:nosniff
x-fb-debug:PQCdEa7xg+nvsCpr1lXz70UoFDvrqIh1mjbV+kHVzPW83bfZAJnF3zCj22Ta7u7adLoMNDQzzMV0PTG1v8BFug==
x-xss-protection:0

Request Headers
______________________________
:host:www.facebook.com
:method:GET

:path:/connect/ping?client_id=&domain=&origin=2&redirect_uri=http://staticxx.facebook.com/connect/xd_arbiter/r/fTmIQU3LxvB.js?version=42#cb=fa030c8a8&domain=&origin=file:///f10358c084&relation=parent&response_type=token,signed_request,code&sdk=joey

:scheme:https
:version:HTTP/1.1
accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,/;q=0.8
accept-encoding:gzip, deflate
accept-language:en-US
upgrade-insecure-requests:1
user-agent:Mozilla/5.0 (Linux; Android 6.0; Samsung Galaxy S6 - 6.0.0 - API 23 - 1440x2560 Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.119 Mobile Safari/537.36
x-devtools-emulate-network-conditions-client-id:4A18CAFF-4629-46DE-9C23-3D35F49525E2
x-requested-with:com.ionicframework.nobbapp2172378

Query String Parameters

client_id:

domain:

origin:2

redirect_uri:http://staticxx.facebook.com/connect/xd_arbiter/r/fTmIQU3LxvB.js?version=42#cb=fa030c8a8&domain=&origin=file:///f10358c084&relation=parent

response_type:token,signed_request,code

sdk:joey

Thanks

**Comment by mbifulco** [comment]
@tkutlic I think you need to add your domain to "App Domains" under your facebook app settings at 
`https://developers.facebook.com/apps/[YOUR APP ID]/settings/`

**Comment by tkutlic** [comment]
Sorry  for late response  - I've been away.
Thank you for answering.

I managed to fix a mistake - it was my mistake (in my code) because I messed with facebookConnectPlugin.js and configuration.
I delated all and made exactly as directed - and now everything works great ... except for one small thing :)

When I use Facebook JavaScript API, I can create and send post to my feed with all properties:

  var message = $ scope.dilemmaDATA.thisNoracle.text;
  var picture = "http: //myserver/resources/img/picture.png";
  var link = "http: // http: //myserver/landingPage.html";
  var name = $ scope.dilemmaDATA.thisNoracle.title;
  var caption = "My latest dilemma ';
  var description = 'Summary of my dilemma';


       FB.api ( '/ me / feed', 'post',
        {
          message: message,
          picture: picture,
          link: link,
          name: name,
          caption: caption,
          description: description
          
        }, Function (response) {
            if (! || response response.error) {
              alert ( 'Error occurred');
            } else {
              console.log ( "You posted this article on your facebook wall: \ n '
                                     + JSON.stringify (response, undefined, 2));
              alert ( 'You posted this article on your facebook wall');
            }
          });

______________________________________________________________________

But when you try the same with Android via this  FB plugin:
(same variables + token that I got from getLoginStatus )

var url = '/ me / feed? method = post&message =' + encodeURIComponent (message);
      url + = "& picture = '+ encodeURIComponent (picture);
      url + = "& link = '+ encodeURIComponent (link);
      url + = "& name = '+ encodeURIComponent (name);
      url + = "& caption = '+ encodeURIComponent (caption);
      url + = '& description =' + encodeURIComponent (description);
      url + = "& access_token = '+ fbToken;

   $ CordovaFacebook.api (
     url [ 'publish_actions'],
     function (response) {
       console.log ("You posted this article on your facebook wall: \ n '+ response);
       alert ( 'You posted this article on your facebook wall');
     },
     function (error) {
       console.error (error);
     }
   );


... Post appears on the wall, but the caption and description properties are missing. ...Actually instead of caption I get myserver domain.

Is it possible to define this two properties exclusively through og tags or I'm doing something wrong.

Thanks

**Comment by JWesorick** [comment]
I ran into this issue and needed to add `http://localhost:8000/index.html` to my Valid OAuth redirect URIs to fix it.

**Comment by akshgods** [comment]
i din't understand, i m using phonegap , localhost:3000 my app is unning. now what to do?

**Comment by smartsal** [comment]
**This worked for me:**

Here's the main thing to understand: Facebook will always check for the "**WWW**" domain. So make sure **www.your_domain.dev** is working on your browser first. 

It is possible that if you have multiple virtual hosts on your local server, some other virtual host overrides  "**www.your_domain.dev**". So please check that. 
Apache will pick the FIRST definition of domain (or ports, or something in these terms - I'm no expert on this, but learned by mistakes).
An easy quick fix for this virtual host overriding is to put "*www.your_domain.dev* virtual host definition on the very top of the file "httpd-vhosts.conf".

Go to "**/apache/conf/https-vhosts.conf**" and put this on the very top of the file:

    <VirtualHost *:80>
    <Directory "C:/your_app_folder_path/">
        Options FollowSymLinks Indexes
        AllowOverride All
        Order deny,allow
        allow from All
    </Directory>
    ServerName your_domain.dev
    ServerAlias your_domain.dev
    DocumentRoot "C:/your_app_folder_path/"
    </VirtualHost>
    
    ###### FOR SSL #####
    <VirtualHost *:443>
        DocumentRoot "C:/your_app_folder_path/"
        ServerName your_domain.dev
    	ServerAlias www.your_domain.dev
        SSLEngine on
        SSLCertificateFile "conf/ssl.crt/server.crt"
        SSLCertificateKeyFile "conf/ssl.key/server.key"
        <Directory "C:/your_app_folder_path/">
            Options All
    		AllowOverride All
    		Require all granted	
    	</Directory>
    </VirtualHost>


**Next:** If you are using Windows system, edit your "hosts" file in "C:\Windows\System32\drivers\etc" by adding two lines:

    127.0.0.1 your_domain.dev
    127.0.0.1 www.your_domain.dev

**Next:** Restart your Apache server and everything should work now.

--------------
I hope this will help you and save your time. 
I wasted almost a whole day searching around the web and was pulling my hair out and couldn't find anything helpful until I found this.

**Comment by Nandanchaturvedi** [comment]
In products "facebook login", enter your callback URL to "valid OAuth redirect URI's".

This should work.

**Comment by shravyavaggu** [comment]
am using passport to get sociallogin myapp which created from facebook is working , but starting code npm start i am getting error

Error: Cannot find module '../lib/models/profile-model'

here profile-model is the model in which fields are entered for database can any help me out of this

**Comment by shravyavaggu** [comment]
hello guys i am trying to get facebook login but i am getting error can any body help me out this please
![fberror](https://user-images.githubusercontent.com/34374562/33799225-a6432668-dd4d-11e7-81de-6c89ecf1578c.PNG)

**Comment by rajmohan1983** [comment]
I am able to create it from my local machine.

I have got 2 errors while setting up this login
1.  Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings
2. Facebook SDK returned an error: Cross-site request forgery validation failed. The “state” param from the URL and session do not match.

To solve the first issue, 
4 things to be done if you want to access from your local
a) Virtual host needs to be created (If you have server then no need). This should be modified under your Apache/conf/extra/httpd-vhosts.conf. Open Notepad in administrator in order to edit & save.
<VirtualHost *:80>
    ServerAdmin webmaster@dummy-host2.example.com
    DocumentRoot "C:/xampp/htdocs/testing/facebook_post/facebook-php-ads-sdk-master/testing_facebok_loging "
    ServerName myapptestfacebook.com
	ServerAlias www.myapptestfacebook.com
    ErrorLog "logs/dummy-host2.example.com-error.log"
    CustomLog "logs/dummy-host2.example.com-access.log" common
</VirtualHost>

b) windows/System32/drivers/etc add the below line (If you have server then no need) 
127.0.0.1 myapptestfacebook.com
127.0.0.1 www.myapptestfacebook.com

c) Facebook app login as developer account in order to make the below changes.
After open the application first click on Add product and search for Facebook login.  Under Facebook login you see "Valid OAuth redirect URIs"  add the following
http://www.myapptestfacebook.com/fb-callback.php

d) Facebook app Settings - Site URL add the below (Without adding you cannot add App Domains)
http://www.myapptestfacebook.com/
and then
App Domains add 
www.myapptestfacebook.com & myapptestfacebook.com
Save it

e) Make sure you have added the same App ID & Secret ID right in your code. & in code add the call back url
$loginUrl = $helper->getLoginUrl('http://www.myapptestfacebook.com/fb-callback.php', $permissions);

Now you SHOULD see your application working perfectly fine.


2. Facebook SDK returned an error: Cross-site request forgery validation failed. The “state” param from the URL and session do not match
Just the following line in both of your login and fb-callback.php
 if(!session_id()) {
    session_start();
}

It should start working. Enjoy (y)
