### ISSUE TITLE
duplicate symbol _llvm.embedded.module errors with latest code

### ISSUE THREAD

**Issue by GitRubb** [jeduan/cordova-plugin-facebook4#38]
I'm getting the following errors when building cordova-plugin-facebook4@1.4.0-1 with Xcode 6.4. Any ideas how to fix this? Does this have anything to do with bitcode in the FB SDK 4.6?

duplicate symbol _llvm.embedded.module in:
   /Plugins/cordova-plugin-facebook4/FBSDKCoreKit.framework/FBSDKCoreKit(FBSDKGraphRequestPiggybackManager.o)
   /Plugins/cordova-plugin-facebook4/FBSDKShareKit.framework/FBSDKShareKit(FBSDKAppInviteContent.o)
...
ld: 226 duplicate symbols for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jeduan** [comment]
If you're using Xcode 6.4, does the problem persist with 1.3.0? Definitely Facebook's SDK for iOS 9 is buggy right now and if you don't need the compatibility, I'd stay away from it until they release the final version which should be Any Day Now.

**Comment by jeduan** [comment]
Actually, it's out now. Let's try.

**Comment by GitRubb** [comment]
Thanks for the reply, 1.3 worked, things just get weird with the new FB SDKs and the old Xcode. 

I've moved to Xcode 7 GM with the official FB SDK 4.6 and plugin 1.4.x and things seem to be working much better now. This can be closed if you like.

**Comment by patuku-roy** [comment]
@jeduan @GitRubb any luck with Xcode 6.4? I'm stuck with this Xcode version for a while, but I need to compile it
