### ISSUE TITLE
ReferenceError: facebookConnectPlugin is not defined

### ISSUE THREAD

**Issue by Zvika88** [jeduan/cordova-plugin-facebook4#385]
It worked fine in a big project that got too complex. After "ionic state reset" that removed and re-install plugins and platforms it no longer works. I get facebookConnectPlugin not defined - even though cordova plugins does list it properly.

Any idea how to resolve?
Thank!
Zvi

**Comment by kingkarki** [comment]
Are you sure you are calling plugin api after device ready?

**Comment by Zvika88** [comment]
yes there is a ready state listener before booting angular, in the <body> part of index.html:
`<script>
window.ionic.Platform.ready( function() {
              clearTimeout( timer );
              angular.bootstrap(document, ["myapp"]);
            }, false);
</script>`

But a rebuild of the project from scratch seems to have solved the problem. 
Anyhow thanks for your reply!
Zvi

**Comment by peterpeterparker** [comment]
Close, inactivity
