### ISSUE TITLE
Caption and description missing when posting to /me/feed with .api method

### ISSUE THREAD

**Issue by tkutlic** [jeduan/cordova-plugin-facebook4#387]
I'm using Ionic 1.X for Android
When I use Facebook JavaScript API, I can create and send post to my feed with all properties:

  var message = $scope.dilemmaDATA.article.text;
  var picture = "http: //myserver/resources/img/picture.png";
  var link = "http: //myserver/landingPage.html";
  var name = $scope.dilemmaDATA.article.title;
  var caption = "My latest dilemma ';
  var description = 'Summary of my dilemma';

       FB.api ( '/ me / feed', 'post',
        {
          message: message,
          picture: picture,
          link: link,
          name: name,
          caption: caption,
          description: description
          
        }, Function (response) {
            if (! || response response.error) {
              alert ( 'Error occurred');
            } else {
              console.log ( "You posted this article on your facebook wall: \ n '
                                     + JSON.stringify (response, undefined, 2));
              alert ( 'You posted this article on your facebook wall');
            }
          });

______________________________________________________________________

But when I try the same with Android via this FB plugin (ng wrapper version):
(same variables + token that I got from getLoginStatus )

  var url =  '/me/feed?method=post&message=' + encodeURIComponent(message);
      url += '&picture=' + encodeURIComponent(picture);
      url += '&link=' + encodeURIComponent(link);
      url += '&name=' + encodeURIComponent(name); 
      url += '&caption=' + encodeURIComponent(caption);
      url += '&description=' + encodeURIComponent(description);
      url += '&access_token=' + fbToken;

    $cordovaFacebook.api(
    url, ['publish_actions'],
    function (response) {
      console.log('You posted this Noracle on your facebook wall: \n' +  response);
      alert('You posted this Article on your facebook wall');
    },
    function (error) {
      console.error(error);
    }
  );

... Post appears on the wall, but the caption and description properties are missing. ...Actually instead of caption I get myserver domain.

Is this maybe possible to define only through og tags ...or some other way  ...... or  I'm doing something wrong.

Thanks

**Comment by peterpeterparker** [comment]
Plz use other channels like Stackoverflow for support requests, thx
