### ISSUE TITLE
Feed dialog: cannot upload photo without a website link.

### ISSUE THREAD

**Issue by neilmctee** [jeduan/cordova-plugin-facebook4#388]
If I attempt to upload a photo only, i.e. exactly as per the _Publish a Photo_ example at the foot of the home page....
 [https://github.com/jeduan/cordova-plugin-facebook4#publish-a-photo](url)

The feed dialog opens, but is empty.

If I add a link element, it works fine. However, I only want to upload a photo (as per the example) - not link to a website.

Any ideas?

PS This is on Android.

**Comment by peterpeterparker** [comment]
Plz use other channels like Stackoverflow for support requests, thx
