### ISSUE TITLE
To and Frictionless apprequests parameters crashing the flow

### ISSUE THREAD

**Issue by Slavezax** [jeduan/cordova-plugin-facebook4#390]
Hello!

Whenever I try to add to, frictionless or both parameters to my request, Xcode console is giving this strange error;

-[__NSCFString countByEnumeratingWithState:objects:count:]: unrecognized selector sent to instance 0x174241e30
2016-12-11 10:07:11.611119 Bilemezsin[4489:1101302] *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> -[__NSCFString countByEnumeratingWithState:objects:count:]: unrecognized selector sent to instance 0x174241e30

Yes my application is a game and has a canvas page. All things are working fine except when I add "to" or "frictionless" parameters to my request.
 
I tried: 

    	 facebookConnectPlugin.showDialog({
        method: "apprequests",
        to: "valid user id",
        message: encodeURI("Test message!"),
        actionType: "" 
    });

and 

    	 facebookConnectPlugin.showDialog({
        method: "apprequests",
        to: "valid user id",
        message: encodeURI("Test message!"),
        actionType: "",
        frictionless: "1"
    });

First of all I need to make "to" field working and other case; Is there a way to implement frictionless apprequests that bypass the request dialog? It seems there was a lot of hacks about it on older SDKs but not at this one...

Thank you.

**Comment by Slavezax** [comment]
Any updates?

**Comment by peterpeterparker** [comment]
I guess you solve your issue, therefore I close this support request
