### ISSUE TITLE
After login with Facebook, it called constructor of homepage twice 

### ISSUE THREAD

**Issue by ChinLii** [jeduan/cordova-plugin-facebook4#391]
Please help me solve this problem.

I am using the cordova-plugin-facebook4 to do the login with Facebook but after logged in with Facebook it goes to root tab twice like this picture 

![my movie](https://cloud.githubusercontent.com/assets/6735776/21082000/b0db79c0-c004-11e6-868e-9c5f306b59c6.gif)

On the other hand, the login in normally way like username password it works perfectly fine.

This is the code to go to the tabs page
<img width="564" alt="screen shot 2016-12-12 at 12 34 35 am" src="https://cloud.githubusercontent.com/assets/6735776/21082002/bb643ac6-c004-11e6-98c8-87e3c6c5f946.png">

Please help me fix this problem...

**Comment by peterpeterparker** [comment]
Plz use other channels like Stackoverflow for support requests, thx
