### ISSUE TITLE
Facebook invite issue on IOS 10.1.1

### ISSUE THREAD

**Issue by gpiroux** [jeduan/cordova-plugin-facebook4#393]
Hi, I'm trying to use the Facebook invite in an ionic app with apparently no issue during the invite process: invites are indicated as sent since the plugin returns {"didComplete":1}. 
But it seems that the notifications are never received by the invitee. Moreover, Facebook Analytics says that notifications have been sent !

I'm using cordoba-plugin-facebook4 version 1.7.4 and I'm testing the app on iOS 10.1.1 via xcode 8.1.
Should I try to update the facebook sdk to the latest version (4.18.0) ? Or do you have any other idea?
Thanks in advance !

**Comment by Slavezax** [comment]
If your app does not have a Facebook Canvas page, please add it to your application first. Then your users will be able to receive notifications.

**Comment by peterpeterparker** [comment]
App Invite isn't support by Facebook anymore, see https://github.com/jeduan/cordova-plugin-facebook4/issues/645
