### ISSUE TITLE
isn't it possible to share a local image?

### ISSUE THREAD

**Issue by rockneverdies55** [jeduan/cordova-plugin-facebook4#394]
I'm trying to share a local image file saved on the device grabbed via cordova.plugin.camera plugin, however facebook plugin says `picture` url must be *http* or *https*...

Does that mean the image/picture to post can't be selected from the local device?

**Comment by AlexRojasEmpowerlabs** [comment]
I have the same problem too, apparently the only way to post a picture from the device is to use the graph api with publish_actions permissions authorized on facebook developer portal.

**Comment by peterpeterparker** [comment]
I think it's not possible anymore
