### ISSUE TITLE
facebookConnectLogin.login(..., ..., ... ) for browser gives a error when facebook dialog closed

### ISSUE THREAD

**Issue by kewersonhugo** [jeduan/cordova-plugin-facebook4#395]
facebookConnectLogin.login dont call the error callback when the facebook login dialog is closed.

It gives Uncaught TypeError: Cannot read property 'message' of undefined(…)

**Comment by kewerson93** [comment]
Solved it adding the following

**Comment by kewerson93** [comment]
Solved it by adding this line to FB.login inside facebookConnectLogin.login 

` if(response.status === undefined) {
        response.status = {message:"window_closed"}
      }`

`FB.login(function (response) {
    if (response.authResponse) {
      s(response)
    } else {
      if(response.status === undefined) {
        response.status = {message:"window_closed"}
      }
      f(response.status.message)
    }
  }, options)`

**Comment by 7freaks-otte** [comment]
Same here, solved it (though not as verbose as @kewerson93 ) by replacing

```
f(response.status.message)
```
with
```
f(response && response.status && response.status.message)
```

in facebook-browser.js Line 63: https://github.com/jeduan/cordova-plugin-facebook4/blob/master/www/facebook-browser.js#L63

This is really a very small bug/fix, could someone please include it in the next release. :)

**Comment by peterpeterparker** [comment]
Close, inactivity
