### ISSUE TITLE
Ionic plugin add bug

### ISSUE THREAD

**Issue by olixis** [jeduan/cordova-plugin-facebook4#396]
Lost 3 hours trying to figure out why I was receiving the "User cancelled dialog" message.

Turns out that because of some bug, ionic plugin add, adds the plugin and the line to config.xml but doesn't work. Please fix or make it clear in the doc!

ionic plugin add cordova-plugin-facebook4 --save --variable APP_ID="myid" --variable APP_NAME="meuname" bugged.

 cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="myid" --variable APP_NAME="myname" works!

**Comment by fredgalvao** [comment]
Wait, if the problem is with ionic, what can we fix? You should report that to the ionic guys, not in here.
