### ISSUE TITLE
App invite - open in FB app if installed

### ISSUE THREAD

**Issue by grundmanise** [jeduan/cordova-plugin-facebook4#397]
Hi, thanks for such a great plugin!

Currently `appInvite` opens an inapp browser where I can choose friends to invite.. is it possible to configure this plugin to open a native FB app with an app invite screen, if it is installed on the user's phone?

**Comment by Eisekson** [comment]
+1

**Comment by Slavezax** [comment]
Facebook SDK is choosing the right method on its own. There's no selection for that.

**Comment by peterpeterparker** [comment]
Closed, `appInvite` doesn't exist anymore

https://github.com/jeduan/cordova-plugin-facebook4/issues/645
