### ISSUE TITLE
Applauding your efforts to update: What are your plans for this version?

### ISSUE THREAD

**Issue by jgberg** [jeduan/cordova-plugin-facebook4#4]
Hi, I, for one, am very glad that you're taking up updating this very important plugin.  It would be good if you updated the README to announce your plans or intent.
I'm particularly curious as to whether you will:
1. add functionality to support full HTTP verbs: e.g. DELETE (which is required to remove Game invites & app requests
2. Will you support the new Facebook SDK now v2.4

**Comment by jeduan** [comment]
0: ideally, this would be merged into the main Facebook plugin, however, the team over there doesn't seem to be responding too much to issues lately, and hasn't announced any plan on npm support so I'm a bit on the dark on what's their plan to migrate when the cordova.io repository goes dark on October.
1: Sure, just create an issue with the links to the APIs you want to support, so I can prioritize which features are needed the most
2: Yep

**Comment by kaumac** [comment]
:+1:  I'm glad someone is continuing the work from the original plugin since this is, in my opinion, one of the most critical/important cordova plugins out there.

The original repository have a lot of issues stacking up and it really doesn't seem to be getting a lot of attention. Thanks and congrats for your work :smile:

**Comment by Hirbod** [comment]
+1 for DELETE support. But actually, this should be possible with a graph-call either.

I did something like that with an old plugin: (cordova facebook ccsoft, but really, don't try that plugin :D)

```js
$rootScope.facebook.graphCall(
                                    "me/permissions", 
                                    {}, 
                                    "DELETE", 
                                    function(resp) {

                                        localStorageService.clearAll();
                                        appNavigator.resetToPage('login.html');
                                        window.plugins.spinnerDialog.hide();

                                       //console.log("My name is: " + resp.name + " and id is: " + resp.id);
                                       //console.log(resp);
                                   },        
                                    function(a){
                                        localStorageService.clearAll();
                                        appNavigator.resetToPage('login.html');
                                        window.plugins.spinnerDialog.hide();
                                    }
                                );
```

**Comment by Hirbod** [comment]
Nevermind, it is possible. Works like a charm. Thank YOU SO MUCH for this plugin!

```js
                                facebookConnectPlugin.api("me/permissions?method=DELETE", [], 
                                    function(resp) {

                                        localStorageService.clearAll();
                                        appNavigator.resetToPage('login.html');
                                        window.plugins.spinnerDialog.hide();

                                   },        
                                    function(a){
                                        ...
                                    }
                                );
```

**Comment by Hirbod** [comment]
Some other suggestions I made to the old facebook plugin maintainer:

1) support App-Install tracking by default (it's very easy to integrate, just 2 lines of code)
https://github.com/ccsoft/cordova-facebook/issues/69

2) [the most important]
Please provide the native facebook permission alert. "Jumping" around the apps is so ugly and so 2013.
https://github.com/ccsoft/cordova-facebook/issues/65

I would love to do this by myself, but I really don't have enough know how on this. I hope we could see some of this features. If you want, I could open an own ticket for my wishes but I thought this thread is a good place for it.

**Comment by jeduan** [comment]
Thanks for your suggestions @Hirbod can you please create a separate issue for each suggestion to have a better tracking?

**Comment by Hirbod** [comment]
@jeduan, of course!
