### ISSUE TITLE
Facebook4 1.3.0  Android GraphRequest Warning

### ISSUE THREAD

**Issue by Mojo90** [jeduan/cordova-plugin-facebook4#40]
On Android I get now the following warning when requesting friendlist:
"Request without access token missing application ID or client token"
nothing more happens then. It is linked with my Facebook Login Button.
And the Plugin gets the following Logentry:
"D/ConnectPlugin﹕ activity result in plugin: requestCode(64206), resultCode(-1)"

But if I click 2 , 3 or 4 Times then it is working sometime. Very rarely it is working with one click and that is dumb because should work all the time with 1st click.

EDIT:
Only happens on Android.
I do save signed in people with fb_access_token and id for example. And if this error happens every entry is "null". Very strange, don't know where this comes from because neither error nor success function gets called. I only experienced this on Browser till now. But when updated to Facebook4 1.3.0 now this happens also for android. (Already have browser issue here and then changed to this fork because thought this would maybe fix it but it didn't: https://github.com/Wizcorp/phonegap-facebook-plugin/issues/1114)

**Comment by jeduan** [comment]
Sorry but cannot help unless there is more info, most likely in the way of a minimal project that exhibits the behaviour you're having.

**Comment by Mojo90** [comment]
Got back to Wizcorp original Plugin for the moment...
