### ISSUE TITLE
cordova plugin add cordova-plugin-facebook4 --variable APP_ID="<APP_ID>" --variable APP_NAME="<APP_NAME>"

### ISSUE THREAD

**Issue by dhruv4** [jeduan/cordova-plugin-facebook4#402]
cordova plugin add cordova-plugin-facebook4 --variable APP_ID="<APP_ID>" --variable APP_NAME="<APP_NAME>" (with the APP_ID and APP_NAME replaced, of course) doesn't add a line to the config.xml like it's supposed to.

I'm trying to develop on Ionic 2 with Firebase for authentication.

Merry Christmas!

**Comment by fredgalvao** [comment]
Nothing to do with the plugin. You need to specify the `--save` flag to the `plugin add` command:
```bash
cordova plugin add --save cordova-plugin-facebook4 --variable APP_ID="<APP_ID>" --variable APP_NAME="<APP_NAME>"
```
