### ISSUE TITLE
 An error occurred logging the user in, There was a problem logging you in.

### ISSUE THREAD

**Issue by codecrab-studios** [jeduan/cordova-plugin-facebook4#403]
I am always getting this error: 

facebookConnectPlugin.login(['email'], function(status) {

An error occurred logging the user in, There was a problem logging you in.

**Comment by aaronksaunders** [comment]
seeing this same error, is there a simple step i am missing?

**Comment by patrickreck** [comment]
+1

**Comment by jQrgen** [comment]
+1

**Comment by peterpeterparker** [comment]
Plz use other channels like Stackoverflow for support requests, thx
