### ISSUE TITLE
Getting "Given URL is not permitted by the application configuration" error

### ISSUE THREAD

**Issue by santteegt** [jeduan/cordova-plugin-facebook4#404]
Hi,

I am getting the following error when the embedded browser opens when attempting to login: "Given URL is not permitted by the application configuration". I have configured my app domain as "http://localhost" in the facebook app settings.

What could be the problem?

**Comment by davElsanto** [comment]
This work for me.

Im using ionic and this plugin, check your config.xml

`<widget id="com.ionicframework.coaching154009" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">`

We need the widget id. Then go to facebook(developer mode obviously), check your app.

_Configuration->Basic->Add platform->Android_.
_Google play app name-> `<add your widget id>`_.

In this case: com.ionicframework.coaching154009

_Google play app name: com.ionicframework.coaching154009_

Then accept and save changes.

Hope it works for you too.

**Comment by AmitMY** [comment]
Same problem here, I think it should reject the promise even.
https://github.com/driftyco/ionic-native/issues/941#event-915261337

**Comment by peterpeterparker** [comment]
Follow https://github.com/ionic-team/ionic-native/issues/941
