### ISSUE TITLE
Multiple iOS apps with same Facebook app id

### ISSUE THREAD

**Issue by Siva-93** [jeduan/cordova-plugin-facebook4#405]
Hi,

I have 3 iOS apps which using the facebook login.  For that I have given the same facebook app id for all the three apps.

What happens is, when I login in app 1 it opens the app2 or produce error. Is there any solution for this problem.

**Comment by wallden** [comment]
Any update on this?

**Comment by peterpeterparker** [comment]
Will be track in PR https://github.com/jeduan/cordova-plugin-facebook4/pull/386
