### ISSUE TITLE
iOS - Login Dialogue doesn't show... unless

### ISSUE THREAD

**Issue by allthetime** [jeduan/cordova-plugin-facebook4#406]
When running `cordovaFacebook.login...` on the click of a button, it seems that nothing happens at all. Strangely, if I click on a link on the cordova webview that leaves the app and goes to Safari, suddenly the popup/facebook modal arises. So if I go back to the app after leaving the safari window the login dialogue is there waiting for me. It seems like something is stuck until I unfocus the app. Has anyone else had this problem?

**Comment by sidgujrathi** [comment]
Yes have experiencing same problem. Plugin works fine on android but getting this problem on iOS 10. 
Had report this issue before but, not luck with any help.

**Comment by allthetime** [comment]
@sidgujrathi the answer was painfully obvious once opening up safari inspector on the app... 

`"Refused to load gap://ready because it does not appear in the frame-src directive of the Content Security Policy."`

`frame-src gap://ready` needs to be present in the `Content-Security-Policy` meta tag in your index.html

**Comment by sidgujrathi** [comment]
Wow! Worked like a charm, thank you so much @allthetime, I have been stuck with this from weeks :smile:

Never thought, solution will be that easy and obvious.

**Comment by allthetime** [comment]
@sidgujrathi You're welcome! The lesson here is that the Safari inspector should be open at all times lol.

**Comment by fredgalvao** [comment]
Would you mind adding a note on the docs about that? PRs are always welcome!

**Comment by sidgujrathi** [comment]
Done. #407 

Submitted my first ever pull request 😃  pardon me if I did any rookie mistake 😄

**Comment by SopoB** [comment]
Not working.

Properly added plugin, Updated CSP as per suggested. 
Still no updates on Facebook ads helper's install URL.
