### ISSUE TITLE
Open graph share doesn't work on some android devices

### ISSUE THREAD

**Issue by mpk2** [jeduan/cordova-plugin-facebook4#413]
Experiencing this error?

>RuntimeException while executing runnablele com.google.common.util.concurrent.Futures$6@b95140a with executor X.0TB@f55ccf0
                                          java.lang.IllegalArgumentException
...

Seems to be based on these bugs -- 

https://developers.facebook.com/bugs/1038286942983961/
https://developers.facebook.com/bugs/1162309093804903/

Not clear whether this is due to the recently updated Facebook app or the SDK.

**Comment by peterpeterparker** [comment]
Plz use other channels like Stackoverflow for support requests, thx
