### ISSUE TITLE
Randomly logging in via web dialog or native app

### ISSUE THREAD

**Issue by RikdeVos** [jeduan/cordova-plugin-facebook4#416]
I'm using the plugin to login users, but I've noticed some weird behaviour. When users login I want the native facebook app to open to request access, but sometimes it's opening the web version instead. This seems to be completely random: in the morning it will log me in 3 times in a row using the native app, and an hour later it keeps opening the web dialog when I login.

I've triple checked the settings in my app on the facebook developers page (like Deep Linking) and the keys in my .plist file.

**Comment by mpk2** [comment]
May be related to #412 ?

**Comment by Slavezax** [comment]
Now this is the expected behaviour. Facebook SDK chooses the best way to handle dialogs.

**Comment by peterpeterparker** [comment]
@Slavezax answer's is the one
