### ISSUE TITLE
[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[5]

### ISSUE THREAD

**Issue by GitRubb** [jeduan/cordova-plugin-facebook4#42]
This error crashes the app and seems to happen quite often in all plugin versions. 

"FacebookConnectPlugin.m" line 480 in -[FacebookConnectPlugin responseObject]
"FacebookConnectPlugin.m" line 58 in -[FacebookConnectPlugin getLoginStatus:]

One of the response values it's trying to apply is nil. 
response[@"authResponse"] = @{
                                  @"accessToken" : token.tokenString,
                                  @"expiresIn" : expiresIn,
                                  @"secret" : @"...",
                                  @"session_key" : [NSNumber numberWithBool:YES],
                                  @"sig" : @"...",
                                  @"userID" : token.userID
                                  };

**Comment by GitRubb** [comment]
@jeduan since this crashes the app would it be possible to add nil checks to those values before returning that authResponse object.

**Comment by jeduan** [comment]
I'm currently moving apartments so if this is pressing maybe a PR would be best. Would you be interested in sending one?

**Comment by gillesperrin** [comment]
@jeduan I made a pull request

**Comment by animista01** [comment]
+1. Same problem here, waiting for a fix.
 *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[5]
