### ISSUE TITLE
iOs - Share Dialog: Behaviour expected if Facebook app is not installed

### ISSUE THREAD

**Issue by Lestt** [jeduan/cordova-plugin-facebook4#420]
Hi all,

On Android, if Facebook app is not installed, a web view is launched to share something on my feed.
It doesn't work on iOs (i'm on an Iphone 5C, iOs 10.2). Contrary to the login, which launch a popup and allow the user to connect to facebook.
Is that normal ? Did i miss something ?

**Comment by peterpeterparker** [comment]
Plz use other channels like Stackoverflow for support requests, thx
