### ISSUE TITLE
facebook login double calling...

### ISSUE THREAD

**Issue by JeongSeho** [jeduan/cordova-plugin-facebook4#423]
ionic2 calling facebook login

facebookConnectPlugin.login(["public_profile"], (userData) => {
      console.log(userData);
    }, (error) => {
      console.log(error);
    });

add kakao login.... plugin cordova-plugin-kakaotalk
calling facebook brower two popup...
i try login... but browser do not close....

**Comment by gitlovenotwar** [comment]
I have the same issue, login/getuser details open facebook app twice

**Comment by paulogr** [comment]
Have the same issue here!

**Comment by jlsuarezs** [comment]
Any solution? :(

Thanks!

**Comment by peterpeterparker** [comment]
Plz use other channels like Stackoverflow for support requests, thx
