### ISSUE TITLE
android facebook messenger closes just after opening after calling 'send' dialog

### ISSUE THREAD

**Issue by madruga88** [jeduan/cordova-plugin-facebook4#425]
a problem make it close just after opening on android.

happened to anyone too ?

i tried various configurations and none of them seems to work.

    facebookConnectPlugin.showDialog({

        method: "send",
        caption: "",
        link: "http://example.com",
        description: ""

    }, function onShareSuccess(result) {
        app.alert("Posted. ", result);
    });

i ended up using this code but the sucess result dont work

    window.plugins.socialsharing.shareVia('com.facebook.orca', 'The message', null, null, 'https://www.google.com/', function () { console.log('share ok') }, function (errormsg) { alert(errormsg) });

**Comment by peterpeterparker** [comment]
Plz use other channels like Stackoverflow for support requests, thx
