### ISSUE TITLE
iOS: Login dialog does not close window, white screen appears

### ISSUE THREAD

**Issue by phonic** [jeduan/cordova-plugin-facebook4#426]
Using latest version, there seems to be a big issue.

When trying to Login via Facebook (call .getLoginStatus()), the Dialog wont be closed neither you click cancel or ok. So a white screen appears and you have to close your app.

**Comment by LiudasRepkovas** [comment]
same here. have anyone found any solution to this? @phonic ?

**Comment by phii01** [comment]
same here! any update on this?

**Comment by peterpeterparker** [comment]
Plz use other channels like Stackoverflow for support requests, thx
