### ISSUE TITLE
Event logging to connect to Facebook Ad Sets

### ISSUE THREAD

**Issue by ilyakar** [jeduan/cordova-plugin-facebook4#427]
Hi.

Say I want to log a specific custom event:
`facebookConnectPlugin.logEvent('used_app_3_days')`

Works fine, shows up in the Facebook Analytics.

Now how can I see the amount of people that reached this custom event in each Facebook Ad Set?

**Comment by jacquesdev** [comment]
Hi @ilyakar - I still don't know the answer to this question (after having researched it a bit), but according to someone at FB support, apparently you can use a work around/hack.

You should use a predefined event that you can see in Facebook ads, and then log that event. Obviously it should be a predefined event that you would not normally use.

So for example, I am trying to track when someone adds an item to my app, and I am tracking this using this event ```fb_mobile_add_to_wishlist```. So in my app where a user adds something, I am sending a log event on that predefined event (in the hope it will display in the fb ads).

https://developers.facebook.com/docs/reference/javascript/FB.AppEvents.LogEvent.

Hopefully that helps. In the meantime, I am going to request that these custom events get added to this library.

**Comment by ilyakar** [comment]
Hi @jacquesdev. Yes that is indeed what I decided to do. The use of predefined events "hack" seemed the only solution for now. For anybody reading this, for future reference, I recommend getting the different tracking events from here: https://developers.facebook.com/docs/marketing-api/app-event-api/v2.8#event_structure. It caused me a few hours of confusion as to what event names are supported by this plugin.

**Comment by jacquesdev** [comment]
Thans @ilyakar - that is useful to know.
