### ISSUE TITLE
Unable to fetch public email and profile pic in facebook

### ISSUE THREAD

**Issue by Shakti-Sharma** [jeduan/cordova-plugin-facebook4#428]
Unable to fetch email and profile pic even it is allowed from the Facebook profile.

In the Facebook profile side there is not any permission issue.

I am using following version.

cordova-plugin-facebook4 1.7.4 "Facebook Connect"

Even email and profile image is fetched using native code but unable to fetch in the facebook4 cordova plugin.

Following the code snippet.

 $cordovaFacebook.login(["public_profile", "email", "user_friends"])
                    .then(function (success) {

                        $cordovaFacebook.api("me", ["public_profile", "email"]).then(function (success) {

Code works file but unable to fetch email and profile image.
Please Help.

**Comment by Shakti-Sharma** [comment]
Is this fixed !!!????

**Comment by rodrigoreal** [comment]
+1

**Comment by Ghayyas** [comment]
same issue

**Comment by rodrigoreal** [comment]
I just got it working with 
```
this.facebook.api('/me?fields=picture.type(normal)', []).then((facebookData) => {
    this.photo = facebookData.picture.data.url;
});
```

**Comment by Ghayyas** [comment]
Thanks @rodrigoreal It works..
for those who needs extra fileds use this..

     this.facebookAuth.api('/me fields=id,name,email,picture.type(normal),gender,first_name,last_name',['public_profile', 'user_friends', 'email']).then(s=>{
        console.log('fb api',s);
      }).catch(e=>{
        console.log('fb api error',e);
      })

**Comment by peterpeterparker** [comment]
Close, inactivity
