### ISSUE TITLE
Post image from image library

### ISSUE THREAD

**Issue by ngt14** [jeduan/cordova-plugin-facebook4#429]
Hi,
I just recently used this plugin. It's work fine.
But i do not know how, can i upload a photo of image library (ios & android) on facebook.
It's possible to do that? i know to publish photo with URL image but not from my library image mobile

**Comment by dpaksoni** [comment]
+1

**Comment by peterpeterparker** [comment]
Close, inactivity

**Comment by mdanics** [comment]
any updates on this?
