### ISSUE TITLE
facebookConnectPlugin cannot find name

### ISSUE THREAD

**Issue by mokrea** [jeduan/cordova-plugin-facebook4#431]
Hi.. I'm trying run cordova-plugin-facebook4 but always got that message.

my steps:
1- cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="MYID" --variable APP_NAME="MY APP NAME"

config.xml
<plugin name="cordova-plugin-facebook4" spec="~1.7.4">
        <variable name="APP_ID" value="MYID" />
        <variable name="APP_NAME" value="MY APP NAME" />
    </plugin>

2- cordova plugin add --save cordova-plugin-inappbrowser

3 - fb-provider.ts
@Injectable()
export class FbProvider {

  constructor(public http: Http) {
    console.log('Hello FbProvider Provider');
  }

  login() {
      var p;
      p = new Promise((resolve, reject) => {
        facebookConnectPlugin.login([ 'email' ], (success) => {
                console.log(JSON.stringify(success));
                resolve(success);
            },(err) => {
                console.log(JSON.stringify(err));
                reject(err);
            });
      });
      return p;

  }

}

message:
 ionic-app-scripts build

[14:32:45]  ionic-app-scripts 1.0.0 
[14:32:45]  build dev started ... 
[14:32:45]  clean started ... 
[14:32:45]  clean finished in 1 ms 
[14:32:45]  copy started ... 
[14:32:45]  transpile started ... 
[14:32:48]  typescript: src/providers/fb-provider.ts, line: 78 
            Cannot find name 'facebookConnectPlugin'. 

      L77:  p = new Promise((resolve, reject) => {
      L78:    facebookConnectPlugin.login([ 'email' ], (success) => {
      L79:            console.log(JSON.stringify(success));

[14:32:48]  transpile failed 
[14:32:48]  ionic-app-script task: "build" 
[14:32:48]  Error: Error 

and

ionic info

Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.4 
OS: macOS Sierra
Node Version: v4.2.4
Xcode version: Xcode 8.2 Build version 8C38

something wrong??

**Comment by davincif** [comment]
same problem here, I feel like I'm missing an import or something. But if I do, I'm not sure how would that import be, some sort of " import { fb } from './../../../cordova-plugin-facebook4' "?

**Comment by peterpeterparker** [comment]
Close, inactivity
