### ISSUE TITLE
Force Android to use web feed dialog?

### ISSUE THREAD

**Issue by neilmctee** [jeduan/cordova-plugin-facebook4#432]
Is it possible to force the plugin to use the web-dialog on Android? Something of the equivalent of the IOS *share_feedWeb* flag, but for android?

I'm asking as I can't get the feed dialog to work on android for sharing *pictures only* (see unanswered issue here: https://github.com/jeduan/cordova-plugin-facebook4/issues/388) and the web dialog on IOS seems to work well and would suit my use-case fine.

I tried to use the Facebook JS SDK directly (https://developers.facebook.com/docs/javascript/examples#dialogs) but this proved to be very problematic and flakey, whereas the web-dialog on IOS 'just worked'

Thanks.

**Comment by peterpeterparker** [comment]
Close, inactivity
