### ISSUE TITLE
Facebook.logEvent crashes iOS app

### ISSUE THREAD

**Issue by Mcoseo** [jeduan/cordova-plugin-facebook4#435]
Everything seems to be working correctly for Android with the FB plugin. For iOS the logEvent option crashes the app. It happens when you call the method properly and it also happens within the the iOS code for event logs not explicitly called, like when you do a FB login.

From my iOS crash report I get:
[FacebookConnectPlugin logEvent:]_block_invoke
This error is referenced explicitly in the crash report as line 108 in the FacebookConnectPlugin.m.

My preliminary tests seem to indicate that commenting out lines 108 and 109 seems to fix part of the issue pertaining to non-explicit call of the logEvent function.

**Comment by fierysolid** [comment]
I think I figured out the issue here.

Inside facebook-native.js we have:
```
exports.logEvent = function logEvent (name, params, valueToSum, s, f) {
  // Prevent NSNulls getting into iOS, messes up our [command.argument count]
  if (!params && !valueToSum) {
    exec(s, f, 'FacebookConnectPlugin', 'logEvent', [name])
  } else if (params && !valueToSum) {
    exec(s, f, 'FacebookConnectPlugin', 'logEvent', [name, params])
  } else if (params && valueToSum) {
    exec(s, f, 'FacebookConnectPlugin', 'logEvent', [name, params, valueToSum])
  } else {
    f('Invalid arguments')
  }
}
```

and inside facebook-browser.js we have:
```
exports.logEvent = function logEvent (eventName, params, valueToSum, s, f) {
  if (!__fbSdkReady) {
    return __fbCallbacks.push(function() {
      logEvent(eventName, params, valueToSum, s, f);
    });
  }

  FB.AppEvents.logEvent(eventName, valueToSum, params);

  if(s) s();
}
```

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect.

I don't experience any crash when using the `logEvent` method.
