### ISSUE TITLE
SSO not offered on Android

### ISSUE THREAD

**Issue by sam2x** [jeduan/cordova-plugin-facebook4#436]
Hey, 

After reading numerous threads/issues, i still can't figure out what's wrong with the Single Sign On in Android Cordova app : 

- I have setup a Facebook App
- In Facebook dev website, i have added a Android platform, computed & filled the hash key, package name and added "com.xxxx.xxxx.MainActivity" as class name. Also I clicked to "YES" for the SSO option.
- I have installed facebook-messenger, and logged-in a test account and real account to it (we can see the account binded to the device in the global phone parameter). 
- I have installed this plugin correctly with my facebook app name and ID (which can be found on the facebook app platform).
- To avoid a build error, in the _platforms/android/android.json_ file, I had to modify the sdk version from 15 to 16 :  

      "<preference name=\"android-minSdkVersion\" value=\"16\" />"

When i run my app, i got correctly the "facebook" popup loading (with my app icon), but it's asking me credentials. I was expecting to be asked to login with my facebook-messenger account.

So i dont understand, did they removed this feature ? The SSO support is meant to works with all facebook apps right (facebook, facebook-messenger, facebook-lite, etc.) ?

Also, on facebook dev platform, is the "Facebook Login" product mandatory for this plugin, or just needed for website ? Because i have also added it, and tried to play with the differents options (each change was followed by a cleaning cache or the app reinstall). In all cases, the SSO didnt worked.

So i have : 

- Removed my facebook app, and created a new one froms scratch, this time i didnt add FacebookLogin, just an Android Project, but i got the same fail result...
- Tried in two differents emulators, got the same result, so now i'm sure it's not related to the phone.

I spent too much time on this, could you please help me to figure out what's wrong ? I must miss something....

Regards.

**Env:**

    Cordova: 6.4.0 (i did an update the 2/8/17, so it's 6.5.0 now)
    Platform android: 6.0.0 (i did an update the 2/8/17, so it's 6.1.2 now)
    Plugin: cordova-plugin-facebook4 1.7.4 "Facebook Connect" (i did an update the 2/8/17, so it's 1.8.0 now)
    Facebook App API version: 2.8 

**Config XML**

    [...]
    <allow-intent href="fb:*" />
    <plugin name="cordova-plugin-facebook4" spec="https://github.com/jeduan/cordova-plugin-facebook4#master">
        <variable name="APP_ID" value="[myappid]" />
        <variable name="APP_NAME" value="[myappname]" />
    </plugin>

**Requested permission:** 

      android.permission.INTERNET
      com.android.vending.BILLING
      android.permission.WRITE_EXTERNAL_STORAGE
      android.permission.ACCESS_NETWORK_STATE
      android.permission.ACCESS_WIFI_STATE
      android.permission.ACCESS_COARSE_LOCATION
      android.permission.ACCESS_FINE_LOCATION
      com.google.android.providers.gsf.permission.READ_GSERVICES
      com.amazon.device.messaging.permission.RECEIVE
      com.xxxx.xxxx.permission.RECEIVE_ADM_MESSAGE
      com.xxxx.xxxx.permission.C2D_MESSAGE
      com.google.android.c2dm.permission.RECEIVE
      android.permission.WAKE_LOCK
      android.permission.VIBRATE
      android.permission.RECEIVE_BOOT_COMPLETED
      com.sec.android.provider.badge.permission.READ
      com.sec.android.provider.badge.permission.WRITE
      com.htc.launcher.permission.READ_SETTINGS
      com.htc.launcher.permission.UPDATE_SHORTCUT
      com.sonyericsson.home.permission.BROADCAST_BADGE
      com.sonymobile.home.permission.PROVIDER_INSERT_BADGE
      com.anddoes.launcher.permission.UPDATE_COUNT
      com.majeur.launcher.permission.UPDATE_BADGE
      com.huawei.android.launcher.permission.CHANGE_BADGE
      com.huawei.android.launcher.permission.READ_SETTINGS
      com.huawei.android.launcher.permission.WRITE_SETTINGS
      android.permission.READ_APP_BADGE
      com.oppo.launcher.permission.READ_SETTINGS
      com.oppo.launcher.permission.WRITE_SETTINGS
      android.permission.READ_EXTERNAL_STORAGE

**Not granted runtime permissions:**

      android.permission.WRITE_EXTERNAL_STORAGE
      android.permission.ACCESS_COARSE_LOCATION
      android.permission.ACCESS_FINE_LOCATION
      android.permission.READ_EXTERNAL_STORAGE

**Comment by sam2x** [comment]
> Install

**Comment by sam2x** [comment]
any ideas @jeduan ?

**Comment by jeduan** [comment]
No idea. If I were you, I'd create an Android project that makes it work, then once I figured the required configuration, translate that into Cordova.

**Comment by sam2x** [comment]
Dont have java skill, that's why i used Cordova framework. 
I have tried in two differents emulators, got the same result, so now i'm sure it's not related to the phone.

**Comment by sam2x** [comment]
Are you aware of any plugins/settings(eg: config.xml) that could conflict with this module ? For example I'm using fullscreen app (activated immersive mode), not using inappbrowser,  stay-in-webview is false, webviewbounce is true. 

Permissions, and intents settings, are automaticcally added by this plugin right ?

**Comment by sam2x** [comment]
@caabernathy  @stevengill @aogilvie @shazron @filmaj @ripcurlx @robertarnesson any ideas on this matter ? (sorry to highlight you guys, you're the most actives on this project, and 2days i'm on it :/).

**Comment by jeduan** [comment]
The best path is for you to get the skills. There's plenty of tutorials on the internet. You shouldn't have production code you don't know how to debug. If you take a look at the code you'll see it's just a very thin wrapper. 

Also mentioning everyone who has ever contributed to the project comes off as rude. Don't do that in GitHub repos where there's not a company sponsoring the work.

**Comment by sam2x** [comment]
The best first path was to ask people if they were aware of this problem. When people will have a problem on IOS App, you'll advice them to get skill on Objective C while they use higher level framework on purpose ? 

"you shouldnt have production code if you don't know how to debug", the problem is from the facebook sdk that's not offering any debug informations. I agree that the hl was a bit rude to hl, that's why i apologized. 

Btw, I spotted the problem the prob:  **this plugin is working only with the complete facebook app installed**, it's not working when you install only facebook-messenger... 2days for this simple thing... 

Well, hope it's gonna be useful to someone. Bye
