### ISSUE TITLE
Its not working after updated to 1.8.0

### ISSUE THREAD

**Issue by v3ss0n** [jeduan/cordova-plugin-facebook4#438]
Try to login : 
```
facebookConnectPlugin.login(["public_profile","email"], function(success){console.log(success)},
      function(error) {
        console.error(error)
      }
    );

```

result is nothing , no http request to facebook sent either

**Comment by goldsquare** [comment]
`$ionicPlatform.ready(function(){
        window.facebookConnectPlugin.login(["public_profile","email"], function(success){
            console.log(success);
            },function(error) {
            console.error(error);
                }
             );
        })`

this is working

**Comment by brtwister2** [comment]
Same issue. 

document.addEventListener('deviceready', function(){  window.facebookConnectPlugin.login(["public_profile","email"], function(success){ console.log(success); },function(error) { console.error(error); } ); });

Falls on error callback and returns the value Object {}

Facebook app version 105.0.0.23.137

**Comment by jeduan** [comment]
`The arguments passed to fill in call variables are invalid. [extra]: Invalid values provided for variables of operation "ProxyAuthAppLoginQuery": Value "Array of size 2 starting with: { app_id => "xxx" }" cannot be used for variable "$params": Missing non-optional field "granted_permissions" (from type "ProxyAuthLoginTokenParams")."}`

This is on your side.
