### ISSUE TITLE
Missing FacebookConnectPlugin

### ISSUE THREAD

**Issue by ignaciodolan** [jeduan/cordova-plugin-facebook4#439]
Hi! 
I have this problem while emulating ios:
`2017-02-11 14:30:38.667 App[12974:14316895] -[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["FacebookConnectPlugin1636091248","FacebookConnectPlugin","login",["public_profile","email","user_friends"]]`

I found this error on the troubleshooting: https://github.com/jeduan/cordova-plugin-facebook4/blob/master/docs/TROUBLESHOOTING.md#missing-facebookconnectplugin

The solution i found (but don't know how to make it work)
Solution:

- Open up Xcode
- Go to "Build Phases"
- Ensure that the following file is added under "Compile Sources":
   - FacebookConnectPlugin.m
- Ensure that the following is added under "Link Binary With Libraris":
   - FacebookSDK.framework
   - libsqlite3.dylib 
   - Social.framework 
   - Accounts.framework
   - Security.framework

And any of this things are there, what should i do? 
When trying to add im no finding from where, any ideas? this maybe a dumb solution but this plugin was working excellent until a few days ago that i upgrade the ionic app.

Thanks for your time!

**Comment by peterpeterparker** [comment]
Close, inactivity
