### ISSUE TITLE
Urgent: does not work in playstore

### ISSUE THREAD

**Issue by Hirbod** [jeduan/cordova-plugin-facebook4#44]
Hi @jeduan 

just submitted my app to the playstore. When I try to login (newest version of your plugin 1.4.0-1)
I get:

![screenshot_2015-09-16-12-30-03](https://cloud.githubusercontent.com/assets/504909/9902841/c17d48be-5c71-11e5-91dd-fdd2281f7b13.png)

Works fine on genymotion, but seems like it is not working on a real device. My event is starting tomorrow, what's wrong? Should I downgrade the plugin?

**Comment by jeduan** [comment]
When I had this issue, the Facebook plugin was misconfigured. Maybe the hashes? BTW released 1.4.0 but only has changes to iOS.

**Comment by Hirbod** [comment]
No, when hashes are wrong, it will display a specific error message. Actually, you was right, I forgot to add the release hash-keys. But even after I've added the hash key now, the error persists.

**Comment by Hirbod** [comment]
If I'm on debug, everything works. As soon as I sign for release, it does not work. I'm 100% sure that the keyhash I've generated (using my release.keystore) is fine. It also ask for password and I've entered it. But nothing changed...

**Comment by Hirbod** [comment]
Dear @jeduan 

you were absolutely right. It was the keyhash. I've entered the right ones, but it just took 5-10 minutes they got recognized. Sorry for the false alarm!

**Comment by jeduan** [comment]
Thought it was that since you mentioned deleting your keys yesterday
