### ISSUE TITLE
There was a problem logging you in ios version 

### ISSUE THREAD

**Issue by muhzi4u** [jeduan/cordova-plugin-facebook4#442]
I am an getting an error "There was a problem logging you in" in ios version.But the login is working in some facebook [[issue109](https://github.com/jeduan/cordova-plugin-facebook4/issues/109)]

**Ionic info**

```

Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: OS X El Capitan
Node Version: v7.5.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by wbhob** [comment]
I also have this issue.

**Comment by muhzi4u** [comment]
@wbhob Did you able to resolve this issue?

**Comment by wbhob** [comment]
Yes, just remove the app from device/simulator and reinstall. This typically happens if you change your API token or app Id, so don't worry about your users having to reinstall.

**Comment by muhzi4u** [comment]
@wbhob Thanks .Let me try and get back to you

**Comment by muhzi4u** [comment]
@wbhob I uninstalled app from the device.Also i have removed the platform and  added again.The problem still exist

**Comment by an-rahulpandey** [comment]
I got it working by enabling keychain sharing in the Xcode -> Target -> Capabilities.

https://github.com/jeduan/cordova-plugin-facebook4/issues/325#issuecomment-250671531

**Comment by muhzi4u** [comment]
@an-rahulpandey Thanks buddy.It got working now.

**Comment by whitecat** [comment]
How do I get to `Target` in xcode? I am running the simulator but `Xcode` wants me to start a project.

**Comment by whitecat** [comment]
Anyone else coming here with the same problem here is a good place to find what @an-rahulpandey  is talking about: http://cordova.apache.org/docs/en/latest/guide/platforms/ios/index.html
