### ISSUE TITLE
Is it normal/a good practice to ask for declined permissions again when login

### ISSUE THREAD

**Issue by chanphillip** [jeduan/cordova-plugin-facebook4#443]
For examples here:

    facebookConnectPlugin.login(["public_profile", "email"], ..., ...)

If the user declined "email" at the first authentication, next time he logs in, since `facebookConnectPlugin.login` still contains "email", it would ask for the permission again. In this case, probably the user would click "Not now" or uncheck the permission again.
I feel this is a little annoying to the user and wonder if this is a usual practice.

Otherwise, I think it should remove "email" if the user has declined "email" before. But how to do so?

**Comment by peterpeterparker** [comment]
Close, inactivity
