### ISSUE TITLE
Not working in the browser. cordova_not_available

### ISSUE THREAD

**Issue by JWesorick** [jeduan/cordova-plugin-facebook4#444]
When I call login I just get a `cordova_not_available` in the console. I'm in the browser platform.

```typescript
Facebook.login(FacebookPermissions)
    .then(data => {
      console.log(data);
    }, err => {
      console.log(err);
    });
// > cordova_not_available
```

**Comment by JWesorick** [comment]
Jk. Lesson learned. `ionic serve` runs without cordova. I needed to run using `ionic run browser`

**Comment by etonyali** [comment]
update: ionic cordova run browser
