### ISSUE TITLE
 Graph Api query not working

### ISSUE THREAD

**Issue by TheRokon** [jeduan/cordova-plugin-facebook4#447]
Hi,

I am trying this code but it is not working even this query working with Graph Api explorer;

`facebookConnectPlugin.api('/me/photos?method=post&url=myimageurl&caption=Try', ["publish_actions"], function (response) { sharedUtils.showAlert("Successfully Posted"); console.log(response); }, function (response) { sharedUtils.showAlert("Post Error"); console.log(response); } );`

and Image Url valid because it is working with Graph Explorer

**Comment by canado** [comment]
I am trying to get a better quality picture and when I am using this in GRaph explorer I have the good quality url
me/picture?width=300&height=300&redirect=false

but in the app, I get the location data object !

**Comment by emersonuy** [comment]
I am also having problems with graph api.
Even a simple query does not work.

`    facebookConnectPlugin.api(
        "/me/?fields=gender,birthday,location{location}",
        ["email", "user_birthday"], // Permissions
        function (response) { // Success ... },
        function (response) { // Error ... }
`

Does anyone know why?

**Comment by peterpeterparker** [comment]
Close for non activity. Plz use other channels for support inquiry, like Stackoverflow, thx
