### ISSUE TITLE
Can't switch users if logged in using InAppBrowser non-native Facebook login

### ISSUE THREAD

**Issue by snakeman21** [jeduan/cordova-plugin-facebook4#450]
I tried calling the logout function, but this is not signing them out of the InAppBrowser. This makes it impossible to ever switch users if someone ever logged into the non-native way.

**Comment by snakeman21** [comment]
Anyone?

**Comment by Slavezax** [comment]
Did you try to delete all local storage data as well?

**Comment by ml454** [comment]
I try facebookConnectPlugin.logout(Function success, Function failure) in android, it work. will ask me re-login facebook.

**Comment by peterpeterparker** [comment]
Close, inactivity

**Comment by anishcrest** [comment]
I am also facing the same issue, logout function works correctly in android but does not work in ios and so cannot switch users in ios.
