### ISSUE TITLE
iOS bug - Facebook connect - two apps

### ISSUE THREAD

**Issue by zabojad** [jeduan/cordova-plugin-facebook4#451]
Hi !

I have two Cordova applications that uses this plugin for Facebook connect feature.

Those two Cordova apps have their own Facebook apps.

And those two Cordova apps have a almost similar ids : the first looks like `my.app` and the second `my.app.something`.

What happens on iOS is that when I fb-login to my `my.app.something` app, if I choose to use the Facebook app (instead of web based authentication), it will redirect me to the `my.app` Cordova pp instead of the `my.app.something` app after authentication...

I'll have a look at the plugin source code but in the meantime, do you have an id why this is happening ?

**Comment by peterpeterparker** [comment]
Duplicate https://github.com/jeduan/cordova-plugin-facebook4/issues/405

PR https://github.com/jeduan/cordova-plugin-facebook4/pull/386
