### ISSUE TITLE
Compilation error FBSDKCoreKit.h is not found

### ISSUE THREAD

**Issue by benwingz** [jeduan/cordova-plugin-facebook4#453]
I try to build an ionic2 app with this plugin and I have compilation error:
fatal error: 'FBSDKCoreKit/FBSDKCoreKit.h' file not found
in the FacebookConnectPlugin.h file line 12

my version of the plugin is the 1.7.4

Does anybody experiences this issue ?

**Comment by jeduan** [comment]
Remove your `platforms/`, reinstall and try again.

**Comment by benwingz** [comment]
Seem to fix the issue, thanks a lot 👍
