### ISSUE TITLE
Version Deprecation, Migrate all calls to Graph API v2.3 or higher

### ISSUE THREAD

**Issue by andreaj8** [jeduan/cordova-plugin-facebook4#454]
I'm using "cordova-plugin-facebook4@~1.7.4" , and i'v the Facebook alert for Version Deprecation : 

```
XXX currently has access to Graph API v2.2 which will reach the end of its 2-year lifetime on 27 March, 2017. To ensure a smooth transition, please migrate all calls to Graph API v2.3 or higher.

To check if your app will be affected by this upgrade you can use the Version Upgrade Tool. This will show you which calls, if any, are affected by this change as well as any replacement calls in newer versions. If you do not see any calls, your app may not be affected by this change.

You can also use our changelog to see the full list of changes in all Graph API versions.
```
<img width="1099" alt="schermata 2017-02-28 alle 11 06 07" src="https://cloud.githubusercontent.com/assets/4126679/23400927/01744a04-fda6-11e6-886e-d1f0d7bcb496.png">

**Comment by fredgalvao** [comment]
That alert is almost always a false positive. There's a link/button on the email they send you from facebook that lets you check for actual API calls made by your app, and then you can verify if you need any migration or not.
I have received that alert for my apps for the previous 2 version deprecations and all of them were false positives. Nothing to do with the plugin.

If after checking you indeed see calls being made from mobile devices to the older 2.2 version, please feel free to reopen this.
