### ISSUE TITLE
Sharing picture function stopped sharing the picture

### ISSUE THREAD

**Issue by abomokhahmed** [jeduan/cordova-plugin-facebook4#455]
Hii
I checked my app today, and found out that the share picture function is not working anymore.
Instead, I get a regular sharing post dialog without the picture I used to get when using this function.
Did any thing change?

I am using this function:

Publish a Photo

Send a photo to a user's feed

facebookConnectPlugin.showDialog({
    method: "share",
    picture:'https://www.google.co.jp/logos/doodles/2014/doodle-4-google-2014-japan-winner-5109465267306496.2-hp.png',
    name:'Test Post',
    message:'First photo post',
    caption: 'Testing using phonegap plugin',
    description: 'Posting photo using phonegap facebook plugin'
  }, function (response) {
    console.log(response)
  }, function (response) {
    console.log(response)
  }
);

**Comment by azn1viet** [comment]
I got an error "Sorry this post is no longer available. It might have been removed." after addding a text and tab on POST on redirecting to  Facebook native app.

**Comment by caiooaugusto** [comment]
Same problem "I got an error "Sorry this post is no longer available. It might have been removed."

**Comment by peterpeterparker** [comment]
Close, inactivity
