### ISSUE TITLE
appInvite method to get ids of people invited

### ISSUE THREAD

**Issue by AmitMY** [jeduan/cordova-plugin-facebook4#456]
In my app, I want to reward people that invited people to the app, and those people registered.
For that, I am using the `appInvite` method, but unfortunetly it only returns: `{didComplete: 1}`.

Is there a way to get IDs of people invited?

**Comment by priiduneemre** [comment]
@AmitMY - Did you ever find a solution for this?

**Comment by AmitMY** [comment]
@priiduneemre Nope, and no response from maintainers (they were last seen 2 months ago)

**Comment by priiduneemre** [comment]
@AmitMY - OK. Thanks for the quick response.

**Comment by peterpeterparker** [comment]
Closed, `appInvite` doesn't exist anymore

https://github.com/jeduan/cordova-plugin-facebook4/issues/645
