### ISSUE TITLE
Can't make api calls including nested fields

### ISSUE THREAD

**Issue by mchristofersenrealnets** [jeduan/cordova-plugin-facebook4#457]
Im getting errors from api calls (on ios) including nested values like:
`Facebook.api("/me?fields=email,first_name,last_name,picture,albums{cover_photo}",["public_profile","user_photos"]).then(
        data=>{
          console.log(data)
        },
        error=>{
          console.log(error)
        }
      )`

This, on the other hand, works fine:
`Facebook.api("/me?fields=email,first_name,last_name,picture,albums",["public_profile","user_photos"]).then(
        data=>{
          console.log(data)
        },
        error=>{
          console.log(error)
        }
      )`

I can work around it, but it includes making a bunch of api calls.

**Comment by peterpeterparker** [comment]
Close, inactivity
