### ISSUE TITLE
NPM version is behind?

### ISSUE THREAD

**Issue by kodeine** [jeduan/cordova-plugin-facebook4#458]
npm version is at 1.7.4 while here we're on >1.8, can you update the NPM?

**Comment by mordka** [comment]
I hit the same problem, so temporarily I'm installing via git:
`cordova plugin add https://github.com/jeduan/cordova-plugin-facebook4`

**Comment by simllll** [comment]
I guess this is missleading, the https://github.com/jeduan/cordova-plugin-facebook4/blob/master/plugin.xml still has 1.7.4 in it.

**Comment by anymos** [comment]
Not sure why it s taking that long ... Would it be possible to update the version in npm ? I would be preferable than to create a fork of it just for that purpose and it meteor require official verison not tar ball to been able to cache it.

Thank you in advance

**Comment by jeduan** [comment]
@anymos this project needs maintainers, I don't have enough time and there's a lot of people expecting support in the issues. If maintaining this project is something that you're interested in, please let me know.
