### ISSUE TITLE
in order the get events user created, what permissions to specify at login

### ISSUE THREAD

**Issue by juszczec** [jeduan/cordova-plugin-facebook4#459]
I'm trying to get a list of events created by a Facebook user.

I'm calling:

facebookConnectPlugin.login([
          'public_profile, email'
        ],
        onLoginSuccess,
        onLoginFail);

onLoginSuccess runs and shows that I get an id and an access_token

When I use this id and access_token in the Facebook Graph API Explorer and try to get events I get the message:

The field 'events' is only accessible on the User object after the user grants the 'user_events' permission.

I'm assuming the permission array I'm sending as the 1st parameter to login is missing something.

I've looked at the code and can't find what, however.

Can anyone help me out?

**Comment by subratawebops** [comment]
Did you check the "user_events" on Facebook Developer Console?

**Comment by juszczec** [comment]
I can't seem to find it.

I'll look at the Facebook Dev Console docs.


On Mar 5, 2017 1:50 PM, "Subrata Banerjee" <notifications@github.com> wrote:

Did you check the "user_events" on Facebook Developer Console?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jeduan/cordova-plugin-facebook4/issues/459#issuecomment-284250931>,
or mute the thread

**Comment by peterpeterparker** [comment]
Close for non activity. Plz use other channels for support inquiry, like Stackoverflow, thx
