### ISSUE TITLE
On landscape, after being redirected, page is blank

### ISSUE THREAD

**Issue by charlyBerthet** [jeduan/cordova-plugin-facebook4#462]
When I use my phone in landscape mode ONLY and I click on Facebook.login. After being redirected my page is blank and I have to switch to portrait then landscape again to see my page.

What's going on?

**Comment by hagai26** [comment]
same on ipad. checked both versions 1.9.1 & 1.8.0. on landscape I see blank white page until rotating the device!

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out the actively maintained fork `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect. If you're still experiencing issues, feel free to log an issue with more details there.
