### ISSUE TITLE
Calling showDialog() does not show up in iOS. "Plugin should use a background thread."

### ISSUE THREAD

**Issue by zeferinix-mllrdev** [jeduan/cordova-plugin-facebook4#463]
Here are my options passed to the facebookConnectPlugin.showDialog(options, successCB, failCB) function.
```
var options = {
                method: 'apprequests',
                filters: ['app_non_users'],
                title: title || 'Invite',
                message: message || ''
            };
```

And this is the log from XCode:
`2017-03-17 17:46:35.849 The Great Wild[8599:132718] THREAD WARNING: ['FacebookConnectPlugin'] took '36.996826' ms. Plugin should use a background thread.`

The Facebook Dialog to Invite Friends doesn't show up in iOS but works fine on Android and Web.

**Comment by fex369** [comment]
was there a solution???

**Comment by ilyakar** [comment]
Bump. Any solution for this? Dialog not show up for me either

**Comment by peterpeterparker** [comment]
App Invite isn't support by Facebook anymore, see https://github.com/jeduan/cordova-plugin-facebook4/issues/645
