### ISSUE TITLE
Passing ['app_non_users'] to the "filters" field on showDialog() doesn't work on mobile but works on web.

### ISSUE THREAD

**Issue by zeferinix-mllrdev** [jeduan/cordova-plugin-facebook4#464]
Passing ['app_non_users'] to the "filters" field on showDialog() doesn't seem to work as expected on mobile but works on web. Basically, the Facebook users are filtered correctly when the code is executed on web but not on mobile.
```
var options = {
                method: 'apprequests',
                filters: ['app_non_users'],
                title: title || 'Invite',
                message: message || ''
            };

facebookConnectPlugin.showDialog(options, successCB, failCB);
```

**Comment by bnfrnz** [comment]
On iOS, it works for me when using `'app_non_users'` as a single string instead of `['app_non_users']` in an array. 

On Android I can't get it to work either...

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect.

As noted above, `filters` is a string not an array.
