### ISSUE TITLE
iOS crash - need newer sdk?

### ISSUE THREAD

**Issue by simllll** [jeduan/cordova-plugin-facebook4#467]
The iOS implementaiotn crashes from time to time, I was not able to reproduce it yet, but we have includede crashlytics which reports us that the app crashes at
**8  hokify                         0x2e9725 -[FBSDKApplicationDelegate _logIfAppLinkEvent:] (FBSDKApplicationDelegate.m:386)**
9  hokify                         0x2e886b -[FBSDKApplicationDelegate application:openURL:sourceApplication:annotation:] (FBSDKApplicationDelegate.m:158)
10 hokify                         0xd4b75 -[AppDelegate(FacebookConnectPlugin) application:openURL:options:] (FacebookConnectPlugin.m:807)
11 hokify                         0x18164d -[FIRAAppDelegateProxy application:openURL:options:]
12 UIKit                          0x28fb10cf __45-[UIApplication _applicationOpenURL:payload:]_block_invoke
13 UIKit                          0x28fb0c1b -[UIApplication _applicationOpenURL:payload:]
14 UIKit                          0x28fb8e8b -[UIApplication _handleNonLaunchSpecificActions:forScene:withTransitionContext:completion:]
15 UIKit                          0x28fbd987 __88-[UIApplication _handleApplicationLifecycleEventWithScene:transitionContext:completion:]_block_invoke
16 UIKit                          0x28fbd899 -[UIApplication _handleApplicationLifecycleEventWithScene:transitionContext:completion:]
17 UIKit                          0x28fa9473 __70-[UIApplication scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke
18 UIKit                          0x28fa9161 -[UIApplication scene:didUpdateWithDiff:transitionContext:completion:]

_logIfAppLinkEvent is a native function of the facebook sdk, so not sure what causes this. but according to some comments, a newer sdk could solve this issue.

Is there any procedure to update it? I could do it, if you tell me how ;)

thanks
simon

**Comment by peterpeterparker** [comment]
Close, inactivity
