### ISSUE TITLE
Bolts framework bitcode issue...

### ISSUE THREAD

**Issue by hasandogu** [jeduan/cordova-plugin-facebook4#47]
Hi there,

Thanks for the awesome plugin. Works seamlessly... Except until after updating to XCode 7.
Bolts framework needs to be rebuilt with bitcode enabled. Seems like an update will be needed next week. (https://github.com/BoltsFramework/Bolts-iOS/issues/153)

1>      cd /Users/dogu/.taco_home/remote-builds/taco-remote/builds/96573/cordovaApp/platforms/ios
1>      export IPHONEOS_DEPLOYMENT_TARGET=7.0
1>      export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/dogu/.taco_home/node_modules/taco-remote-lib/1.0.1/node_modules/taco-remote-lib/node_modules/ios-sim/build/release:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
1>      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk -L/Users/dogu/.taco_home/remote-builds/taco-remote/builds/96573/cordovaApp/platforms/ios/build/device -F/Users/dogu/.taco_home/remote-builds/taco-remote/builds/96573/cordovaApp/platforms/ios/build/device -FMyApp/Plugins/cordova-plugin-facebook4 -filelist /Users/dogu/.taco_home/remote-builds/taco-remote/builds/96573/cordovaApp/platforms/ios/build/MyApp.build/Debug-iphoneos/MyApp.build/Objects-normal/armv7/MyApp.LinkFileList -miphoneos-version-min=7.0 -dead_strip -fembed-bitcode-marker -weak_framework CoreFoundation -weak_framework UIKit -weak_framework AVFoundation -weak_framework CoreMedia -weak-lSystem -ObjC -fobjc-arc -fobjc-link-runtime -framework AssetsLibrary /Users/dogu/.taco_home/remote-builds/taco-remote/builds/96573/cordovaApp/platforms/ios/build/device/libCordova.a -framework CoreGraphics -framework MobileCoreServices -framework CoreBluetooth -framework CoreLocation -weak_framework AudioToolbox -framework Bolts -framework FBSDKCoreKit -framework FBSDKLoginKit -framework FBSDKShareKit -weak_framework SystemConfiguration -weak_framework Social -weak_framework MessageUI -framework QuartzCore -Xlinker -dependency_info -Xlinker /Users/dogu/.taco_home/remote-builds/taco-remote/builds/96573/cordovaApp/platforms/ios/build/MyApp.build/Debug-iphoneos/MyApp.build/Objects-normal/armv7/MyApp_dependency_info.dat -o /Users/dogu/.taco_home/remote-builds/taco-remote/builds/96573/cordovaApp/platforms/ios/build/device/MyApp.app/MyApp

1>  ld: 'MyApp/Plugins/cordova-plugin-facebook4/Bolts.framework/Bolts(BFAppLinkTarget.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
1>clang : error : linker command failed with exit code 1 (use -v to see invocation)

1>
1>  ** BUILD FAILED **

**Comment by felquis** [comment]
This stackoverflow answer helped me solve this problem http://stackoverflow.com/a/32508368

I hope it helps you.
