### ISSUE TITLE
Prevent alert after login

### ISSUE THREAD

**Issue by elysiopires** [jeduan/cordova-plugin-facebook4#470]
Hello everyone,

I need help with this plugin, after I login with facebook always display an alert as a debug.

How can I disable this alert?

this is my code:
var fbLoginSuccess = function (userData) {
  facebookConnectPlugin.getAccessToken(function(token) {
      console.log("Token: " + token);
    });

function loginFacebook(){
	facebookConnectPlugin.login(["public_profile"], fbLoginSuccess,
	  function (error) {
	    console.error(error)
	  }
	);
}

Sincerely,
Elysio
![alertdisplay](https://cloud.githubusercontent.com/assets/4189312/24264205/6e887c4c-0fde-11e7-9155-fb2fd6b11163.jpg)

**Comment by John-Henrique** [comment]
In your code no have nothing to call alert, them, is you using some plugin to convert console.log to alert?

**Comment by Slavezax** [comment]
You need to check your fbLoginSuccess function.

**Comment by elysiopires** [comment]
Hello everyone!!!
First of all big thanks for the replies. Finally I got the problem. It was another plugin to activate the urlscheme. 
When the login process finish over Facebook and come back to the app fires the event.

Sincerely,
Elysio
