### ISSUE TITLE
Dynamically provide APP ID and APP NAME

### ISSUE THREAD

**Issue by esase** [jeduan/cordova-plugin-facebook4#472]
How can we do this from js side?

**Comment by krysalead** [comment]
Why do you need to have it dynamically injected?
You can do that at build time.

**Comment by fredgalvao** [comment]
I have interest in such feature too, and in my case, my application serves as a whitelabel application source, in which I have one source code, and build that into multiple applications for the store. Each one have a bunch of customizations, one of them being the social profile (facebook id). Currently, I have to reinstall the plugin with a diff set of variables to build each of my targets.

Having an option to provide that at runtime would be amazing, much of my build process would simplify tenfold.

**Comment by esase** [comment]
@krysalead The same story. I have one generic application with a lot of clients with own settings like facebook api key, etc. They enter site url and api provides all needed individual settings. I cannot use one facebook api key for all of them.

**Comment by jeetprksh** [comment]
@esase i am having the similar scene too.
Is there any resolution for this issue? I Need to set app id dynamically and not at the build time.

**Comment by tgensol** [comment]
I did it something like this : 
- For iOs, you have to define every app_ids in the info.plist first (so it is not fully dynamically)

But despite that point, I can change my app_id used in the login function dynamically, and getting the access_user_token. The app_name is linked to the facebook dashboard no ? 
If you are looking for something like that, I could provide the code

**Comment by filipsuk** [comment]
We have 2 facebook app ids for 2 countries. So I also need to set app id at runtime. 

How complicated is it to implement @jeduan? I would be very grateful for any guidance. I would do a PR, however I have no experience with cordova plugins and ObjectiveC.

Cheers

**Comment by jeduan** [comment]
I had this too, I don't think cordova can do it per se, the way I fixed it was with node and thinking of `platforms/`, `plugins/`, etc as build directories, so we'd remove and create them a lot of times.

We'd have templates for like `config.xml.tpl` for `config.xml` that looked like this

```xml
?xml version="1.0" encoding="utf-8"?>
<widget id="<%= package %>" version="<%= version %>" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0" android-versionCode="<%= buildNumber %>" ios-CFBundleVersion="<%= buildNumber %>">
  <name><%= name %></name>
 [...]
</widget>
```

and every time we had to build the app, for every target, we'd remove `platforms/`, `plugins/`, etc, populate the template, move it to `config.xml` and then run `cordova prepare`.

Very hacky and time consuming but it worked.

**Comment by filipsuk** [comment]
@jeduan thanks for the reply, however this is only build time right? We would like to change APP_ID when user changes country in the ionic app, so in runtime. This cannot be implemented in the plugin?

**Comment by jeduan** [comment]
Not that I'm aware of. I'm not even sure that could be made in native land.

**Comment by filipsuk** [comment]
Maybe this is what we are looking for? setApplicationId(String) here: https://developers.facebook.com/docs/reference/android/current/class/FacebookSdk/

**Comment by jeduan** [comment]
No idea if that would work because of key hashes. You can try by adding support to the plugin like this https://github.com/jeduan/cordova-plugin-facebook4/blob/master/src/android/ConnectPlugin.java#L333-L336 https://github.com/jeduan/cordova-plugin-facebook4/blob/master/www/facebook-native.js#L49-L52

**Comment by tgensol** [comment]
Hi guys,

I said before, I did it here : https://github.com/tgensol/cordova-plugin-facebook4/

But, you need to first call the "init function" with the app_id you want, and then use the "loginSecond".

For iOs, every app_id need to be put in the Info.plist like : 
 <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>fbXXXXX</string>
        </array>
      </dict>

**Comment by filipsuk** [comment]
@tgensol that looks promising! How about merging to this repo by creating pull request?

**Comment by tgensol** [comment]
I did it first for my purpose, I need to rename and comment it first,

Once I have time I will :) !

**Comment by filipsuk** [comment]
Great! Let me know if you need any help :) I think this would be very useful for other people, too.

**Comment by tgensol** [comment]
@filipsuk I tried to comment my code and the readme.

My code is only working for real device. Plus, I wanted to only get a second(or more) accessTokens, but my user is always logged to the main appId (so It is automatically signout from the new appId)

**Comment by slaviki** [comment]
Hi!

Is there any progress on this? 
I would also like to have an option to swith app id's in runtime.

**Comment by GeminiLegend** [comment]
+1 On progress for this

**Comment by Rakeshpatel87p** [comment]
+1

Any workarounds found? Still looking on my end.

**Comment by diarcastro** [comment]
I resolved this with some task in npm in this way:

`"fb:dev": "ionic cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID=\"1111111111\" --variable APP_NAME=\"APP-1\"",
"fb:prod": "ionic cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID=\"222222222\" --variable APP_NAME=\"APP-2\"",
"ionic:run:dev": "npm run fb:dev & ionic cordova run android",
"ionic:run:prod": "npm run fb:prod & ionic cordova run android --prod"`

And after I only run:
`npm run ionic:run:dev` or `npm run ionic:run:prod`

**Comment by tgensol** [comment]
@diarcastro, This is cool, but I think the idea here is to change the App_ID when the app is running (having multiple facebook ID on the same app).

My code is running on my app very well : https://github.com/tgensol/cordova-plugin-facebook4/

**Comment by lucasbasquerotto** [comment]
In my case I need only one `APP_ID` when my application is running, but I need different `APP_ID`s for different environments (`dev`, `prod`, etc...). 

I achieved that making a `before_prepare` hook script to replace variables in a template `config.xml` (`config.tpl.xml`) and save the changes in the real `config.xml` file (so the variable `${FACEBOOK_APP_ID}` is replaced by the value in my environment file).

Here are the steps: [https://stackoverflow.com/questions/37816035/using-environment-variables-parameterizing-config-xml/46345926#46345926](https://stackoverflow.com/questions/37816035/using-environment-variables-parameterizing-config-xml/46345926#46345926)

**Comment by rameshkatare9** [comment]
**gulpfile.js**

const gulp = require('gulp');
const Config = require('cordova-config');
var fs = require('fs');
var argv = require('yargs').argv;

gulp.task('config', function () {

    let data;
    let env = argv.channelTag;
    if (!env || env === 'dev') {
        data = fs.readFileSync('src/environments/environment.ts', 'utf-8');
    } else {
        data = fs.readFileSync('src/environments/environment.' + env + '.ts', 'utf-8');
    }

    let startIndex = data.indexOf("{");
    let lastIndex = (data.indexOf("}")) + 1;

    let configEnv = JSON.parse(data.substring(startIndex, lastIndex));
    console.log(configEnv);

    const configXml = new Config('config.xml');

    configXml.setID(configEnv.appId);
    configXml.setName(configEnv.appName);
    configXml.setVersion(configEnv.version);
    configXml.setAndroidVersionCode(configEnv.versionCode);


    // Write the config file
    configXml.writeSync();
});

**environment.ts**

export const environment = {
  "production": false,
  "appId": "in.xyz.abcDev",
  "appName": "MyApp Dev",
  "version": "0.0.1",
  "versionCode": "1000"
};

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect. The next major release includes getApplicationId, setApplicationId, getApplicationName, and setApplicationName methods.
