### ISSUE TITLE
Problem with Open Graph Dialog

### ISSUE THREAD

**Issue by ghost** [jeduan/cordova-plugin-facebook4#474]
Hello there!
I am using this plugin in my **ionic2 app**.
Until now everything is working like it is supposed too, **but** i can't get my app posting stuff on the current users feed.

my Code is this:
```
shareOnFacebook(alert:any){
      var obj = {};
      obj['og:type']='objectname';
      obj['og:title']='Random title';

      var ap = {};
      ap['expires_in'] = 4000;

      var options = {
        method: 'share_open_graph',
        action: 'shareAlert',
        action_properties: JSON.stringify(ap),
        object: JSON.stringify(obj)
      };

      this.fb.showDialog(options);
  }

```

If i open the app and click my share-button, a Dialog window with the following error message opens:
**Warning
The parameter action_type is required**

I don't know what to do to make it work, the doc also doesn't help me.
any help is appreciated.

**Comment by wcustodio** [comment]
Any solution? I had problem with Open Graph too:
"Facebook error: Error publishing message"

**Comment by peterpeterparker** [comment]
@wcustodio just posted a code which work for me in a duplicate issue #539

**Comment by peterpeterparker** [comment]
Close for non activity. Plz use other channels for support inquiry, like Stackoverflow, thx
