### ISSUE TITLE
IOS Login with native app not returned to main app 

### ISSUE THREAD

**Issue by Marcolino179** [jeduan/cordova-plugin-facebook4#475]
From the iPhone 6(IOS 10.3.1) when I try to log in, and I choose to do through native application, after accepting the permits does not return to the application from which it was called. On iphone 5 (IOS 10.3.1) works fine. Any idea?

**Comment by obermoserkitz** [comment]
Is it on the Simulator or on the real device?

**Comment by krysalead** [comment]
Hi,

I have the same issue on Android.
Changing my password on a laptop 
On the device launch the application which request a facebook login.
Application showing that token is invalidated
I request a login via Facebook
Facebook open and then I enter my new password
Once logged in I am staying on facebook page and I have to kill facebook to go back to my app.

Thanks & regards

**Comment by peterpeterparker** [comment]
Close, inactivity
