### ISSUE TITLE
App Invite return errorMessage : "Facebook error: Dialog failed with unknown error"

### ISSUE THREAD

**Issue by vo-land** [jeduan/cordova-plugin-facebook4#478]
On some devices, in particular, on Android 4.3, iOS 10.2, the call AppInIntive returns the error "Facebook error: Dialog failed with unknown error". At what the error appears only when the Fasebook application is installed. If the Facebook application is not installed, an empty pop-up window opens. Sometimes an error does not appear and the dialog is displayed normally. On other versions android and iOS also works fine.
Has anyone encountered a similar one and is there an opportunity to fix it?

**Comment by mscherer82** [comment]
which cordova version do you use?

**Comment by peterpeterparker** [comment]
App Invite isn't support by Facebook anymore, see https://github.com/jeduan/cordova-plugin-facebook4/issues/645
