### ISSUE TITLE
THREAD WARNING: exec() call to FacebookConnectPlugin.login blocked the main thread for 41ms. Plugin should use CordovaInterface.getThreadPool().

### ISSUE THREAD

**Issue by engrsandeep** [jeduan/cordova-plugin-facebook4#479]
Got error when tried to use plugin on Android device with latest cordova version.

THREAD WARNING: exec() call to FacebookConnectPlugin.login blocked the main thread for 41ms. Plugin should use CordovaInterface.getThreadPool().

Can you please help.

**Comment by chrisfilda** [comment]
Hi, I have exactly the same issue, but I saw that this thread is closed. Have you managed to figure out what is wrong on this?

Many thanks in advance

**Comment by fredgalvao** [comment]
That is just a default warning, not an issue.
