### ISSUE TITLE
update ios sdk to 4.22?

### ISSUE THREAD

**Issue by matrixreal** [jeduan/cordova-plugin-facebook4#482]
hi,
any update to fb ios sdk to 4.22?
thanks

**Comment by matrixreal** [comment]
@jeduan 
any updates ? :)
thanks in advance

**Comment by jeduan** [comment]
Send pr please

**Comment by matrixreal** [comment]
pr ?

**Comment by fredgalvao** [comment]
@jeduan I know you don't quite have the time to maintain this repo (it's okay, I understand, really). However, just to make this clear, there is an open PR for that: https://github.com/jeduan/cordova-plugin-facebook4/pull/481

@matrixreal `PR` = Pull Request

**Comment by souly1** [comment]
+1
