### ISSUE TITLE
Android login no longer works

### ISSUE THREAD

**Issue by Deadsoil** [jeduan/cordova-plugin-facebook4#483]
Hi guys,

Android login just stopped working in my app. I did not change anything. Out of nowhere it started giving the error saying no android hash key configured... I've never had the hash key configured and it was never a problem before....

So I set the hash key and now that error has gone away, however, when I try to log in now it shows the loader and tries to bring up the native login (it briefly flashes up) then it just disappears and nothing happens.

If I delete the facebook app from my phone it lets me log in through the browser and acts as expected.

I've tried removing my app from my phone, removing the platform and readding, removing the plugin and readding. Nothing fixes it. iPhone is fine.

I didn't change any code or do anything in regards to the facebook login function. Was working fine then the next day stopped. It's been working fine for 6 months, in a live environment. 

Any ideas?

**Comment by Virako** [comment]
The facebook API has changed: https://developers.facebook.com/docs/apps/changelog

**Comment by Deadsoil** [comment]
Yeah, I figured this out last night. Got it working now with the hash. Quite annoying for testing though.

Thanks

**Comment by ffabiosales** [comment]
How did you get it working?

**Comment by Deadsoil** [comment]
@ffabiosales I had to add the hash for my android signing key in the facebook developers settings then it works... And it will only work on an apk that you have signed. It won't work on an unsigned apk. It's pretty annoying for testing. I believe there is code for this plugin that forces it to use the web login instead of the native login, but I haven't tried it yet.

**Comment by Virako** [comment]
http://stackoverflow.com/questions/27468813/this-app-has-no-android-key-hashes-configured-login-with-facebook-sdk

**Comment by saiprince2595** [comment]
Hash key solved my issue.Thanx a ton @Deadsoil

**Comment by pedromonteiro221** [comment]
@Deadsoil Did you find a way to force the plugin to use web login instead of native login ? Im asking this because my app isen't signed. And I'm very new to ionic this is my very first app.

**Comment by jlsuarezs** [comment]
Yes, I am having the same issue. Any way to force web login instead?

**Comment by elton182** [comment]
@Deadsoil how to find the hash for the signing key ?

**Comment by Andalusio** [comment]
@elton182 Type "keytool -exportcert -alias GamurrPets -keystore GamurrPets.keystore | C:\OpenSSL-Win32\bin\openssl sha1 -binary | C:\OpenSSL-Win32\bin\openssl base64" in Command Prompt (requires downloading OpenSSL).

**Comment by peterpeterparker** [comment]
Could confirm the plugin still do works on Android and iOS.

Close it because old issue. For support inquiries plz use other channels like Stackoverflow, thx
