### ISSUE TITLE
iOS login never completes. No Errors thrown. Works on Android.

### ISSUE THREAD

**Issue by cwolff411** [jeduan/cordova-plugin-facebook4#484]
When going through the login flow the user is taken to Facebook to accept permissions. After permissions are granted the user is redirected to the app login page and nothing else happens.

I'm getting the token and authing with firebase. `Auth` is my angular factory for authorization.

No errors are thrown, and no callbacks are registered. The only thing that happens is the FB handle url is printed to the console.

It randomly worked once using my own Facebook account, but after logging out and changing to a test user it stopped working. Thinking it could have to do with using test users, I logged back in to my personal account and tried again, but it wouldn't work. Also tried with my wife's personal Facebook and it still wouldn't work.

No errors or problems with Android.

My login: 

        facebookConnectPlugin.login( ["email","user_friends"],  function (response) {

            Auth.login(response.authResponse.accessToken).then(function(){

                console.log('success callback worked.');
                $location.path('/home');               
                
            }, function() {
                alert("Sorry there was an error logging in.");
            })
        });

It never logs "success callback worked" or alerts for an error.

This is through both Xcode and `ionic run`.

> fb230044027390441://authorize#access_token=EAADROUyJCekBACaa8BttAPr06Tz2ZCdhRBUbfGw7SWRCNDHyTQVe2w4LiSAUD0iBN20GktGJfI46lzZBxq4RnjRi7qsOzfzMpSlk2sZAw0vafyG4DQWwje2MxQUwaQEdcnYmq8tLkGZCuTcbhEKLo6hXwROVsyGFQYVU8yiuNqIWUMleQv6FVXq1B6xZBQKeXU0micy6rZC62zlnEmPZBiO&denied_scopes=&expires_in=5146377&granted_scopes=user_friends%2Cemail%2Cpublic_profile&signed_request=aDA3zbtxBl5NhnQFOiSxVAXeOZa5RoP8rBLXKeVwgew.eyJhbGdvcml0aG0iOiJITUFDLVNIQTI1NiIsImNvZGUiOiJBUUN0YXF3dGtkTktkaVZyM2gtaW43NF9KMDJ2aGFNdGduOTgxYm9nYklOV2pEdEFaWmJWSUpiaW0tcVpQTG9weFNQSnNYSmZVeERtcDYwTi1sRTRkeUtDTkxkVnFmbUYyWjJkZ05acHNYNlRLbFhrcDk2X3NKVm1kblZkN1Q0cHpxTDlMS1BBX0hHVGZuVHdVRjJqbVNfeGYyUFNSYk03a3VKMHgtWTA4Rnp3TWdXOVV5VEVkZjFwcHRFNkg5OTNiLTFuWkJkU3FoZGllOHVfOXN2a3h3YWVPVEVnSU9KbTF5aEw1LWRkb2lPckxTaDgtUDJIeW5ZdV9GcGVVMkpkQ0NqQUY5Nk5fTmxBNjFMNUpWanpYSnlVTkJHNnZ4b1ROV2dLODV6NG1vMDVJS1RscThXYldVcktqaWZyWXg0VUR1RUpuN1phNmtIaTlrcjR4VktVeC1YOHU1aUxPRDRvZ2hvTy1LbnlBS3VFb29pQUlRSlMyY05MS1BQNjZua2IxNVUiLCJpc3N1ZWRfYXQiOjE0OTMwNDU4OTksInVzZXJfaWQiOiIxMDE0NzI4MjM3MzcwODIifQ&state=%7B%22challenge%22%3A%227dw6WRoH2HO%252BID1dimp0EdrUr5g%253D%22%2C%220_auth_logger_id%22%3A%224D346FC9-D50A-4177-9161-ED2A45F02905%22%2C%22com.facebook.sdk_client_state%22%3Atrue%2C%223_method%22%3A%22sfvc_auth%22%7D

Running on Cordova 6.5.0
Cordova iOS 4.3.1
Xcode 8.3 
iPhone 6+ running iOS 9.1

Any thoughts? I did two days of searching and research and can't seem to find a solution Is this a bug of some sort?

**Comment by souly1** [comment]
+1

**Comment by okanseremet** [comment]
+1 i have the same problem.
Why did you close the issue?

**Comment by cwolff411** [comment]
Sorry I don't remember. It was so many bugs ago.  I think I updated cordova and everything was fine.
