### ISSUE TITLE
New hash key every time I generate Android Project?

### ISSUE THREAD

**Issue by JonasWestAlro** [jeduan/cordova-plugin-facebook4#487]
Hi All, 

Every time I reset my android project the hashes has changed and therefore the facebook plugin doesn't work until I add the new hash on the facebook developer website. 

"Invalid key hash. The key hash HASH does not match any stored key hashes. Configure you app key hashes at https://developers.facebook.com/apps/ID".

Can't I make the hash key constant somehow for the app?

**Comment by andrewoodleyjr** [comment]
+1

**Comment by jeduan** [comment]
Not a cordova-plugin-facebook4 issue

**Comment by engrsandeep** [comment]
@jeduan Any help how to fix it. We are getting same issue.

**Comment by jeduan** [comment]
@engrsandeep I'd google if the same issue can be reproduced on native android. It probably will and there's a fix on that side. That what I mean by not an issue on this plugin. Can't give you support on how to use the Facebook android sdk because I don't know it that well.
