### ISSUE TITLE
Error in ./MyApp class MyApp - caused by: No provider for Facebook!

### ISSUE THREAD

**Issue by manhlh** [jeduan/cordova-plugin-facebook4#488]
help me,I follow the steps on ionic2 https://ionicframework.com/docs/native/facebook/ ,  but when I run, I get this error: Error in ./MyApp class MyApp - caused by: No provider for Facebook!

**Comment by tharrington** [comment]
@manhlh what was the solution for this?

**Comment by mayoralito** [comment]
ditto.

**Comment by sabrio** [comment]
Add `Facebook` to the `app.module.ts` under the providers. That's fixed my problem.

**Comment by mayoralito** [comment]
That's what I did and it worked for me as well. https://stackoverflow.com/questions/45135627/ionic3-cordova-plugin-facebook4-facebook-install-issues-errors/45176986#45176986
