### ISSUE TITLE
refresh cache getloginstatus with roundtrip parameter

### ISSUE THREAD

**Issue by ngt14** [jeduan/cordova-plugin-facebook4#490]
Hello, it possible to refresh cache of getloginstatus with additionnal parameter roundtrip to forced refresh of login status ? 

section : Roundtrips to Facebook's servers
[https://developers.facebook.com/docs/reference/javascript/FB.getLoginStatus](url)

**Comment by peterpeterparker** [comment]
Close it because old inquiry. Furthermore the provided documentation link point to a 404 now.
