### ISSUE TITLE
Facebook dialog not opening in Browser after logged out from FB website

### ISSUE THREAD

**Issue by SamLoy** [jeduan/cordova-plugin-facebook4#492]
Hi, 

While i'm developing testing my app I've been running it on phones in the browser rather than deploying it. However I've noticed a problem when launching the cordova-plugin-facebook4 plugin via the browser on both Android and IOS (9&10). 

If the user has cleared their browser data (i.e. cleared facebook cookies) the facebookConnectPlugin.login() function never returns in the IOS or Android browser. From reading around, I know that there have been some changes preventing the native app from being launched, but i'm finding even the facebook website doesn't open. If the user goes to the facebook website manually and logs in, the plugin opens the Facebook dialog via the website as expected and the user can log in/out via my app fine after this point. 

```javascript 
  facebookConnectPlugin.login(['email', 'public_profile'], function (response) {
       console.info("FB Response", response) //never called with cleaned browser data
   }, function(error) { 
      console.error("FB Error", error) //never called with cleaned browser data
   })
```

I've installed cordova-plugin-facebook4 with:

```bash
cordova platform rm browser
#then manually deleted all references to facebook from plugins/platforms
cordova platform add browser
cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="1234" --variable APP_NAME="myapp"
```
Can anybody help please?

**Comment by Bistaff** [comment]
Did you find the solution?

**Comment by peterpeterparker** [comment]
Close, inactivity
