### ISSUE TITLE
logPurchase reporting currency as an integer

### ISSUE THREAD

**Issue by danielkkelly** [jeduan/cordova-plugin-facebook4#493]
The logPurchase method is taking currency but converting it to an integer value before sending to FB.  For example, when using logPurchase for a value of 3.49, only 3 is logged as a purchase in Facebook's event.

I haven't taken more than a cursory look at this but it's possible that the code below just needs to update args.getInt(0) to get a decimal value instead:

        } else if (action.equals("logPurchase")) {
            /*
             * While calls to logEvent can be made to register purchase events,
             * there is a helper method that explicitly takes a currency indicator.
             */
            if (args.length() != 2) {
                callbackContext.error("Invalid arguments");
                return true;
            }
            int value = args.getInt(0);
            String currency = args.getString(1);
            logger.logPurchase(BigDecimal.valueOf(value), Currency.getInstance(currency));
            callbackContext.success();
            return true;

**Comment by MichaelMalony** [comment]
@danielkkelly, looks like the official plugin still hasn't updated. I put together a fix and tested. How do you want to go about using it? Might make sense for Boxcar to branch the repo and apply the fix to that. That way we could put in a pull request for the fix and in the meantime we can get any future updates to the plugin by merging into our branch. Pretty sure ionic/cordova plugins can directly reference a git repo so we could use it that way.

**Comment by noahcooper** [comment]
The PR to fix this issue was merged quite some time ago.
