### ISSUE TITLE
facebookConnectPlugin.login failures with android 6

### ISSUE THREAD

**Issue by appsasync** [jeduan/cordova-plugin-facebook4#494]
HI

I have this plugin working ok. but on one of my devices (android) I use facebook beta
and on this device the 
facebookConnectPlugin.login(["user_about_me"])
fails without error message
anyone experienced the same? 
I suppose since its facebook beta it will move to prod version, so this needs to be checked

Cheers

**Comment by subratawebops** [comment]
Do you have the release hash key for Facebook?

**Comment by appsasync** [comment]
I checked better my environments, and I have 2 devices ( android 5, android 6) and both have the same facebook app versions. so it's not from there.

Android 5 works ok, Android 6 fails the login. shows some native login and does not load the web permissions from facebook.

with logcat on android 5 I can see the oauth working
D/WebView ( 5737): loadUrl(extra headers)=https://m.facebook.com/auth.php?

On Android 6 I only see errors and no oauth attemp:

05-15 14:40:08.706  1383  1383 W System.err: 	at org.apache.cordova.facebook.ConnectPlugin.getErrorResponse(ConnectPlugin.java:976)
05-15 14:40:08.706  1383  1383 W System.err: 	at org.apache.cordova.facebook.ConnectPlugin.handleError(ConnectPlugin.java:835)
05-15 14:40:08.706  1383  1383 W System.err: 	at org.apache.cordova.facebook.ConnectPlugin.access$300(ConnectPlugin.java:57)
05-15 14:40:08.706  1383  1383 W System.err: 	at org.apache.cordova.facebook.ConnectPlugin$2.onError(ConnectPlugin.java:136)
05-15 14:40:08.706  1383  1383 W System.err: 	at com.facebook.login.LoginManager.finishLogin(LoginManager.java:595)
05-15 14:40:08.706  1383  1383 W System.err: 	at com.facebook.login.LoginManager.onActivityResult(LoginManager.java:221)
05-15 14:40:08.707  1383  1383 W System.err: 	at com.facebook.login.LoginManager$1.onActivityResult(LoginManager.java:164)
05-15 14:40:08.707  1383  1383 W System.err: 	at com.facebook.internal.CallbackManagerImpl.onActivityResult(CallbackManagerImpl.java:82)
05-15 14:40:08.707  1383  1383 W System.err: 	at org.apache.cordova.facebook.ConnectPlugin.onActivityResult(ConnectPlugin.java:275)

Is there any extra permission needed for android 6? it runs a different security system

I rulled out the hask key problem since it works ok on one device

**Comment by appsasync** [comment]
Ok figure it out now
I had no test user defined in facebook app, so only the device where I was personally logged was working fine.
any way in logcat there's a json parse failure, and i guess because of that we can't see the error in the javascript output

05-15 15:56:49.081 11416 11416 W System.err: org.json.JSONException: Unterminated object at character 142 of {"errorMessage": "Facebook error: SERVER_ERROR: [code] 1675030 [message]: Error performing query. [extra]: Errors while executing operation "ProxyAuthAppLoginQuery": At Query.proxy_auth_app_login: Failed to resolve field."}
05-15 15:56:49.081 11416 11416 W System.err:    at org.json.JSONTokener.syntaxError(JSONTokener.java:449)
05-15 15:56:49.081 11416 11416 W System.err:    at org.json.JSONTokener.readObject(JSONTokener.java:393)
05-15 15:56:49.081 11416 11416 W System.err:    at org.json.JSONTokener.nextValue(JSONTokener.java:100)
05-15 15:56:49.081 11416 11416 W System.err:    at org.json.JSONObject.<init>(JSONObject.java:156)
05-15 15:56:49.081 11416 11416 W System.err:    at org.json.JSONObject.<init>(JSONObject.java:173)

**Comment by KostyaM** [comment]
I have the application that is already released, but i have the same error on it. Tell me please, why it happening.
