### ISSUE TITLE
How to check granted or declined permissions

### ISSUE THREAD

**Issue by snakeman21** [jeduan/cordova-plugin-facebook4#496]
I tried doing 

```
facebookConnectPlugin.api('/me/permissions', function(response) {
  var declined = [];
  for (i = 0; i < response.data.length; i++) { 
    if (response.data[i].status == 'declined') {
      declined.push(response.data[i].permission)
    }
  }
  console.log(declined.toString());
},function error(error){console.log(error)});
```
But this doesn't work because it just console.logs the values but doesn't allow me to do anything with the response. Even if I take out the success callback, it still prints the response. I just can't use the value for some reason.

**Comment by peterpeterparker** [comment]
Close it because old issue. For support inquiries plz use other channels like Stackoverflow, thx
