### ISSUE TITLE
Facebook login doesn't make any effact on ios

### ISSUE THREAD

**Issue by MahmoudElmoghazy** [jeduan/cordova-plugin-facebook4#498]
When i try to login with facebook nothing happened on ios any solution ?

**Comment by snakeman21** [comment]
Works for me. Maybe try using an older version of the plugin

**Comment by MahmoudElmoghazy** [comment]
I have to add frame-src gap://ready to my Content-Security-Policy in index.html
 <meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' 'unsafe-inline'; script-src * 'unsafe-inline' 'unsafe-eval'; frame-src gap://ready">

**Comment by tiagomestreteixeira** [comment]
@MahmoudElmoghazy i'm with the same issue on ios can you elaborate on your answer please?

**Comment by MahmoudElmoghazy** [comment]
@tiagomestreteixeira put this code in index.html 
  <meta http-equiv="Content-Security-Policy" content="default-src data: gap://* file://* https://ssl.gstatic.com *; img-src 'self' * data:; style-src 'self' 'unsafe-inline' *; script-src 'self' 'unsafe-eval' 'unsafe-inline' *; connect-src 'self' * ws://* wss://*; frame-src gap://ready">

**Comment by peterpeterparker** [comment]
Close it because old issue. For support inquiries plz use other channels like Stackoverflow, thx
