### ISSUE TITLE
Xcode 7 build not running the Facebook App to login and uses the browser instead

### ISSUE THREAD

**Issue by dbroadhurst** [jeduan/cordova-plugin-facebook4#50]
Clean install using cordova 5.1.1

cordova create ftest com.domain.ftest ftest
cordova plugin add cordova-plugin-whitelist@1.0.0
cordova platform add ios
cordova plugin add https://github.com/jeduan/cordova-plugin-facebook4.git --save --variable APP_ID="MYID" --variable APP_NAME="MY NAME"

add to index.js

```
        console.log('facebook logging in');
        window.facebookConnectPlugin.login(['public_profile'],
          function (res) {
            console.log('login ', res);

            var postInfo = {
              method: 'share',
              href: 'http://someurl.html',
            };

            window.facebookConnectPlugin.showDialog(
                         postInfo,
                         function (res) {
                           console.log('post ', res);
                         },
                         function (err) {
                           console.log('error', err);
                         });

          },
          function (err) {
            console.log('error ', err);
          });

```

Open Xcode 7, build and run on real device

I get a login page which looks like the browser login rather than the app. When I post I get a message that says I need to login.

**Comment by csheppard** [comment]
Me too

**Comment by csheppard** [comment]
Related:
https://developers.facebook.com/bugs/786729821439894/
https://developers.facebook.com/bugs/1636969533209725/

**Comment by csheppard** [comment]
My solution so far has been to downgrade the SDK, see https://github.com/Wizcorp/phonegap-facebook-plugin/issues/1116

**Comment by jeduan** [comment]
Yep. This is not a bug in this plugin's code, but the path Facebook's SDK is taking.

**Comment by dbroadhurst** [comment]
I agree there's been a change in direction but it seems the current implementation is broken. Not sure if the SDK is broken or the lib needs to be implemented in a different way.

**Comment by jeduan** [comment]
I mean, I agree this will be disconcerting. But this is a thing affecting every user of the Facebook SDK, not just the ones using the SDK *and* this plugin.
