### ISSUE TITLE
post image on facebook from android device with specific url's does not work

### ISSUE THREAD

**Issue by Om3s** [jeduan/cordova-plugin-facebook4#502]
Hello,
I faced this problem a few months ago and could'nt find the cause of the bug, until today. I'm using a firebase database and the storage file download url contain parameters for security tokens.

cordova-plugin-facebook4 does not handle those correctly on android and I had to modify the java parts to get it working.

I described everything in detail on my stackoverflow [post](https://stackoverflow.com/questions/41998513/cordova-plugin-facebook4-post-with-image-error-on-android)

My fix is not the optimal solution, it just fixed it for my case, but you have to find a general solution for those kind of URL's

with best regards,
Om3s

**Comment by peterpeterparker** [comment]
Still the case? Would you like to submit a PR?

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect.

Facebook has deprecated the "publish_actions" permission, and in turn, the ability to upload user photos with the Graph API, so this is moot.
