### ISSUE TITLE
ionic v1, invalid scope z******@gmail.com

### ISSUE THREAD

**Issue by kudsyf** [jeduan/cordova-plugin-facebook4#503]
hi, i tried to install the cordova-plugin-facebook4 to use it with my ionic 1 application, i created the facebook App, get the App id, and run the ionic plugin add statement as mentioned in the documentation, i also added the login functionality inside the pageready block, but when i run the application on the emulator i keep getting "invalid scope z******@gmail.com", where this email is my contact email in the facebook app.

any idea why am getting this error ?

**Comment by jeduan** [comment]
this seems like an error in how you're using the Facebook sdk. Check there.
