### ISSUE TITLE
getLoginStatus not working in ionic2

### ISSUE THREAD

**Issue by araufdogan** [jeduan/cordova-plugin-facebook4#504]
Hello,

I am trying to check facebook login status. 

`Facebook.getLoginStatus().then((res) => function(){ console.log(res); })`
This is not working, does not write log on console.

`
console.log(Facebook.getLoginStatus());
`
This is working but results like `__zone_symbol__value: Object ...`

How can i use getLoginStatus function with "then"?

**Comment by fredgalvao** [comment]
Can you try it and reproduce the problem without being through Ionic?
Otherwise, I'll call it an Ionic issue, and thus you should create an issue on their repo, not here.

**Comment by araufdogan** [comment]
I dont know, I can not find any solution but javascript version of getLoginStatus function works fine. I am going to open new issue to ionic-native repo.
