### ISSUE TITLE
 Phonegap build error log -> You have not accepted the license agreements!

### ISSUE THREAD

**Issue by canado** [jeduan/cordova-plugin-facebook4#505]
Hello since today I have this error in my log, when I compile with phonegap build

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring root project 'project'.
> > You have not accepted the license agreements of the following SDK components:
>   [Android Support Repository].
>   Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
>   Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 2.372 secs
> Error: /project/gradlew: Command failed with exit code 1 Error output:

if I remove 
<gap:plugin name="cordova-plugin-facebook4" source="npm">

I can compile perfectly

Can you fix it from  your repository ?
Or do I have to modify the  config.xml, thanks

**Comment by canado** [comment]
Facebook made an update today, I believe this update is breaking the plugin

https://developers.facebook.com/docs/android/change-log-4x

**Comment by fredgalvao** [comment]
> You have not accepted the license agreements of the following SDK components:
[Android Support Repository].
Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

That has nothing to do with Facebook SDK or with this plugin. You just need to complete the setup of the Android SDK on your machine.

**Comment by canado** [comment]
I cannot update the Android SDK on  my machine since I am using phonegap build to compile and only the www folder is used for that.

When I remove the plugin from the config.xml everything is fine, the compilation works.
When I add the plugin back into the config.xml it shows this error.

Before today everything was working fine

**Comment by leomloureiro** [comment]
I'm having the same problem at the online phonegap build. The build error started today. Before today, the same app has been compiled without problem.

**Comment by canado** [comment]
If I am not mistaking I believe phonegap build has to update their compiling script in order for the apps to compile again.

Can you confirm @fredgalvao ?

**Comment by fredgalvao** [comment]
I'd say so, @canado . Ping the guys at PGB and tell them you need support with the Android SDK licence agreement there.

**Comment by robsco-git** [comment]
On Arch Linux with `android-sdk 26.0.2` I needed to run `/opt/android-sdk/tools/bin/sdkmanager --licenses`. I was then prompted to accept the licenses that were not yet accepted.
