### ISSUE TITLE
Build for Android fails :processDebugResources FAILED

### ISSUE THREAD

**Issue by rvfede** [jeduan/cordova-plugin-facebook4#506]
Hi, 

Since yesterday I'm experiencing a problem when building for Android platform :processDebugResources FAILED. iOS worked normally.

If I remove cordova-plugin-facebook4 I can build normally.

My environment:
Cordova 6.3.1
Android SDK target API 23

Hope you can help.
Thanks

OUTPUT:

:processDebugResources FAILED

1>MSBUILD : cordova-build error : D:\CC20-2017\BlankCordovaApp1\platforms\android\build\intermediates\res\merged\debug\values-v24\values-v24.xml:4: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
1>MSBUILD : cordova-build error : FAILURE: Build failed with an exception.
1>MSBUILD : cordova-build error : * What went wrong:
1>MSBUILD : cordova-build error : Execution failed for task ':processDebugResources'.
1>MSBUILD : cordova-build error : > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files (x86)\Android\android-sdk\build-tools\23.0.3\aapt.exe'' finished with non-zero exit value 1
1>MSBUILD : cordova-build error : * Try:
1>MSBUILD : cordova-build error : Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Command finished with error code 1: cmd /s /c "D:\CC20-2017\BlankCordovaApp1\platforms\android\gradlew.bat cdvBuildDebug -b D:\CC20-2017\BlankCordovaApp1\platforms\android\build.gradle -Dorg.gradle.daemon=true -Pandroid.useDeprecatedNdk=true"
1>MSBUILD : cordova-build error : Error: cmd: Command failed with exit code 1 Error output:

1>MSBUILD : cordova-build error : D:\CC20-2017\BlankCordovaApp1\platforms\android\build\intermediates\res\merged\debug\values-v24\values-v24.xml:3: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
1>MSBUILD : cordova-build error : D:\CC20-2017\BlankCordovaApp1\platforms\android\build\intermediates\res\merged\debug\values-v24\values-v24.xml:4: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
1>MSBUILD : cordova-build error : FAILURE: Build failed with an exception.
1>MSBUILD : cordova-build error : * What went wrong:
1>MSBUILD : cordova-build error : Execution failed for task ':processDebugResources'.
1>MSBUILD : cordova-build error : > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files (x86)\Android\android-sdk\build-tools\23.0.3\aapt.exe'' finished with non-zero exit value 1
1>MSBUILD : cordova-build error : * Try:
1>MSBUILD : cordova-build error : Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
1>MSBUILD : cordova-build error : Picked up _JAVA_OPTIONS: -Xmx512M

**Comment by amiriltd** [comment]
I think it's because plugin.xml says 1.8.0 and the latest in npm is 1.9.0

in either case, I used version from https://github.com/mpk2/cordova-plugin-facebook4 

source="git" spec="https://github.com/mpk2/cordova-plugin-facebook4"

**Comment by jacquesdev** [comment]
Hi there - so just a note it seems that this is being caused by the wrong version in plugin.xml. I have created a PR which should fix this issue #509.

In the meantime, here is an alternative/temporary solution to fixing it, https://stackoverflow.com/a/44311407/1280740, if you need to use the latest version 1.9.0, as opposed to version 1.7.4.

**Comment by jacquesdev** [comment]
@jeduan - see comment here, https://github.com/jeduan/cordova-plugin-facebook4/issues/497#issuecomment-306627258, perhaps this can also be re-opened?

**Comment by fredgalvao** [comment]
@jacquesdev This is most surelly not related to the alpha1 version issue *either*, so I'll reopen this.

@rvfede it seems like the output of your build log is incomplete. Would you mind providing the following info:

- exact plugin version installed
- platforms versions
- installed plugins
- full build output

**Comment by peterpeterparker** [comment]
I close this for inactivity 10 months old, I guess we were all able to live and found solutions since then ;)

**Comment by sergioChL** [comment]
@amiriltd after adding those values in the file strings, it returns me error of mergeDebugResources in the construction on duplicate values

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mergeDebugResources'.
> [string/fb_app_id] /Users/user/Desktop/home-made-repo/platforms/android/res/values/facebookconnect.xml	[string/fb_app_id] /Users/user/Desktop/home-made-repo/platforms/android/res/values/strings.xml: Error: Duplicate resources
  [string/fb_app_name] /Users/user/Desktop/home-made-repo/platforms/android/res/values/facebookconnect.xml	[string/fb_app_name] /Users/user/Desktop/home-made-repo/platforms/android/res/values/strings.xml: Error: Duplicate resources
