### ISSUE TITLE
FAILED BUILD Android with cordova-plugin-facebook4

### ISSUE THREAD

**Issue by ArtKuz** [jeduan/cordova-plugin-facebook4#51]
Hello.
I use OS Ubuntu 12, cordova 5.3.3, ionic 1.6.4.
Without the use of a plugin (cordova-plugin-facebook4)[https://github.com/jeduan/cordova-plugin-facebook4] assembly is successful.
Build with plugin (cordova-plugin-facebook4)[https://github.com/jeduan/cordova-plugin-facebook4] have error:
```
org.xwalk:xwalk_core_library:14+

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_armv7DebugCompile'.
   > Could not find any version that matches com.android.support:support-v4:[22,23).
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/maven-metadata.xml
         https://repo1.maven.org/maven2/com/android/support/support-v4/
         https://download.01.org/crosswalk/releases/crosswalk/android/maven2/com/android/support/support-v4/maven-metadata.xml
         https://download.01.org/crosswalk/releases/crosswalk/android/maven2/com/android/support/support-v4/
     Required by:
         :android:unspecified > com.facebook.android:facebook-android-sdk:4.6.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.404 secs

/home/artem/android/stretch/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /home/artem/android/stretch/platforms/android/gradlew with args: cdvBuildDebug,-b,/home/artem/android/stretch/platforms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /home/artem/android/stretch/platforms/android/cordova/build: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: /home/artem/android/stretch/platforms/android/cordova/build: Command failed with exit code 1
    at ChildProcess.whenDone (/usr/local/node/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```
The decision from issue #39 does not help me.

**Comment by fredgalvao** [comment]
This project requires `facebook-android-sdk`  which requires an **android-support** local library of at least version `22`, preferably `23` ([source here](https://github.com/facebook/facebook-android-sdk/blob/master/facebook/build.gradle#L10)). It is obtained and updated through the android sdk manager.

If you have the android sdk folders in your `$PATH`, you should be able to run `android` on a command line and let it update everything for you.

The fact that your project is not compiling means that you have an older version of android-support installed. Once you update your android sdk tools everything should work just fine.

This is the same issue as https://github.com/phonegap/phonegap-plugin-push/issues/141, btw, so you might be able to use one of the specific solutions mentioned there.

**Comment by Nofcale** [comment]
I've update the Android Support Library and install the Android Support Repository and the project just build without troubles.

Another tip is that facebook-android-sdk from this repo cannot run android sdk min version 14, it has to be from 15+.

**Comment by ArtKuz** [comment]
Thank you. It's work!

**Comment by deliverymanager** [comment]
I have the same problem and the following can reproduce it.
ionic start testwithcrosswalk
cd testwithcrosswalk
cordova platform add android
cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="123456789" --variable APP_NAME="myApplication"
cordova build android /*with success*/
ionic browser add crosswalk
cordova build android /*will pop an error about version 15. So then I change in config.xml the xwalkVersion to 15+. The android-minSdkVersion was set from ionic to 16.
Then I build again*/
cordova build android /*Now a new error Could not find any version that matches org.xwalk:xwalk_core_library:15+.
Even though I have every android library there is installed
*/ 

What am I missing? This issue just has to do with the facebook4 plugin. It is not a conflict of sdk libraries, multiple dex files etc.
Hope someone can reproduce it and help me!

**Comment by Hirbod** [comment]
As already posted more then 10 times, it's a crosswalk bug (somethin gets overwritten). You need to build it with a workaround.

cordova run android -- --minSdkVersion=15

Did you see the double -- ? This is important.

For release

cordova build android --release -- --minSdkVersion=15

**Comment by deliverymanager** [comment]
Thank you for your answer.
The reason that
cordova run android -- --minSdkVersion=15
 did not work for me was the fact that I went in the config.xml and changed the xwalkVersion to 15+ instead of 14+.
This change was suggested in another post, but it was the actual problem the solution.
So the only thing that is needed as you have already posted elsewhere is to build with
cordova run android -- --minSdkVersion=15

Thank you!

**Comment by Hirbod** [comment]
Yes, you're welcome. 15+ can't be installed trough the crosswalk plugin, only 14+.

**Comment by hvallenilla** [comment]
This work for me

ionic cordova build android --release -- --minSdkVersion=15
