### ISSUE TITLE
Taking Too Long To Log In

### ISSUE THREAD

**Issue by MejorCodigo** [jeduan/cordova-plugin-facebook4#511]
Hey guys, so I just installed this plugin yesterday and was working very well. However, this morning I tried opening my app and log in using Facebook and I noticed it takes a significant amount of time to log in. Any reason as to why this would happen? 

Another issue I just came across is when I log in for the first time and give it the permissions from Facebook nothing happens after the permission dialog box is closed. Any help is much appreciated!

This is the code I'm using: 

```
//Log in with facebook
  $(document).on("click", '.btnFacebookLogin', function(){
    facebookConnectPlugin.login(["public_profile", "email"], fbLoginSuccess,
      function loginError (error) {
        myApp.alert("Error....");
      }
    );
  });

  var fbLoginSuccess = function (response) {
    facebookConnectPlugin.api("/" + response.authResponse.userID + "?fields=id,name,email", [],
      function onSuccess (result) {
        registerUser(result.name, "", result.email, "123", "facebook");

      }, function onError (error) {
        alert("Error.");
      }
    );
  }
```

**Comment by zubinraja** [comment]
Same here.. fadded up with all possible workaround. After calling login, checked login status after 5 seconds of interval, after around 15-20 seconds, it gets connected. Then made API call but api call responded after the the login response - around 2-3 minutes :(

**Comment by ExoSkeleton321** [comment]
Yeah I know, takes way too long. Some people say to revert back to version 1.7.4 to solve this and other compatability issues. Haven't tried it yet, if you get it working please let me know hot you solved it. Thanks! @zubinraja

**Comment by peterpeterparker** [comment]
Close, inactivity
