### ISSUE TITLE
User not found error when trying to login through moto g 2

### ISSUE THREAD

**Issue by rajeevriitm** [jeduan/cordova-plugin-facebook4#512]
I have an ionic 2 app in release version which fails on facebook login in my moto g 2. It throws an error "user not found" . It is working in another phone i tested. I have tried re-adding the plugin and rebuilding the app but it is not working. I am using the version "1.9.1" 

When I run `facebook.login` it throws an error with "user not found " message. I have facebook app, but nothing comes up.

**Comment by peterpeterparker** [comment]
Close it because old issue. For support inquiries plz use other channels like Stackoverflow, thx
