### ISSUE TITLE
When accepting the app permissions but denying some, it doesn't work when asking login() again.

### ISSUE THREAD

**Issue by Scombr0** [jeduan/cordova-plugin-facebook4#515]
So, the flow goes like this.

Login with facebook. `login()`
I request _public_profile_, _user_birthday_, _email_ access.
Then facebook app loads asking for those permissions, but I uncheck email. Everything works as expected.
I check the API didn't give me email back after calling `api()` with next fields: `"id,first_name,last_name,name,email,birthday,gender,verified,age_range"`

I tell the user I need his email permission, and why. So I `logout()` and `login()` again.

Here, a new modal appears, its not the full facebook screen, it's just a square modal, telling me that the app needs email access, I accept it, and nothing happens. No promise is returned. So I don't know when the user accepted or declined, plus I can't call any other function because it doesn't enter the promise resolution (or rejection).

This is the modal I get, in which after I press the big blue button saying "CONTINUE AS [name]", nothing happens.

![fb-modal](https://user-images.githubusercontent.com/4380776/27007747-46bd36be-4e34-11e7-970e-86f93b829545.jpg)
PS: Facebook app is in spanish.

If you need any more information, please let me know.

**Comment by peterpeterparker** [comment]
Close it because old issue. For support inquiries plz use other channels like Stackoverflow, thx
