### ISSUE TITLE
Update Graph API

### ISSUE THREAD

**Issue by jacquesdev** [jeduan/cordova-plugin-facebook4#518]
Just received an email from Facebook:

**v2.3 Upgrade Reminder**
  
> Your App, is currently accessing Graph API v2.3 which will reach the end of its 2-year lifetime on 10 July, 2017. We estimate 3 endpoints that it calls will be impacted by this change and may stop working after the automatic upgrade push. To ensure a smooth transition, please migrate all calls to Graph API v2.4 or higher. Use the API Upgrade Tool to understand exactly how this change will impact your app.

I am not sure if this plugin uses a separate sdk for the Graph Api, but I guess it looks like it needs to be updated?

**Comment by fredgalvao** [comment]
That's mostly a  false positive. There's a link to the API Upgrade Tool from facebook in the email/notification you received to let you check whether you actually did any calls to deprecated API versions.

I have received that warning multiple times since 2.0 deprecation, and I was never actually affected by it (as my app wasn't really doing any deprecated calls).

**Comment by jacquesdev** [comment]
Hey @fredgalvao - thanks for that. I was just wondering if there is any reason that the plugin does not get updated to say v2.9 of the Graph Api? No idea if this is simply a version update in a config file, or if it may break things for existing users, but just wanted to get a better understanding of this. I appreciate you are probably very busy, and I would be happy to help with this, if you could just point me in the right direction of where to start (assuming you feel this would be helpful for the plugin).

**Comment by jacquesdev** [comment]
@fredgalvao - Have been reading through some of the issue - and realised that this plugin is using what looks like version 2.7. May I suggest that we update the readme to specify this version (if you can just confirm that is correct), then we can recommend that people check their back-end code, because I think it's happening where I am calling the unversioned graph api (and suspect many others are as well).

**Comment by fredgalvao** [comment]
I'm almost always biased towards updating stuff, and this is no exception. However, I am not familiar enough with the SDK code to actually help you on that, but updating the docs to specify the version the plugin uses is a nice and valid point (maybe someone who knows the SDK could confirm whether it's 2.7).

Now, regarding the possibility of the plugin making calls to a deprecated api version, I have received that email multiple times over the last 3 years, and it has always been a false positive. Facebook could do a better job to identify apps making calls to old versions before sending that warning, as they already have the tool to say so. If you check it [here](https://developers.facebook.com/tools/api_versioning/) you can determine if there's any old calls being made.

As far as I know, this plugin has never been anywhere near outdated to be close to deprecated api versions, so there's a certain safety there. This is not an excuse not to update though, I'm all for it.
