### ISSUE TITLE
showDialog doesn't work correctly

### ISSUE THREAD

**Issue by JustasKuizinas** [jeduan/cordova-plugin-facebook4#519]
When I use show dialog in my cordova app, image doesn't appear on my dialog and when I push POST, text get's posted on my facebook wall but not image.

![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_113950/BzK43Jg74SNDCsp3yD7QEy6fl9muNV/Screenshot_2017-06-15-02-05-51-837_com.facebook.katana.png%2B-%2BIrfanView%2B%2528Zoom_%2B351%2Bx%2B624%2529%2B2017-06-15%2B02.09.44.png?Expires=1497568295&Signature=hRnXgLs~JtYLeVUgaHjlYHiiWdWYSVXph4Zgbgko2dqCDnYhPSI9y02vTfBt9RLyWgoOGgGgipKFdZRecYEzfgdnbsPZIFlFXvm-TQr52GQ2ER2NrlQh9fxf1GDoorNkDwbFN9Po19YyQi2H0ouwCO43KZrT-n2zJuretkveeTA50NSha6xuQu-UEo5owc9Uz5FjeA6dlGXCcvokWGSojrAnRI2a6tlG7xWmtPCOBk9nJO~xutCibShhNL-YTFtd23cZEd~y586HWDnYzBVnnvt8biqPjM77ziy2idi9AkxDs4MXZogOoufg9WDoVdxm0sAmS8glrqSwzw0CAC1Q5A__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

facebookConnectPlugin.showDialog({
    method: "share",
    picture:'https://www.google.co.jp/logos/doodles/2014/doodle-4-google-2014-japan-winner-5109465267306496.2-hp.png',
    name:'Test Post',
    message:'First photo post',
    caption: 'Testing using phonegap plugin',
    description: 'Posting photo using phonegap facebook plugin'
  }, function (response) {
    console.log(response)
  }, function (response) {
    console.log(response)
  }
);

**Comment by fritio833** [comment]
Rolling back to facebook4 version 1.7.4 fixed the problem for me.

**Comment by renatobezerra** [comment]
I have a same issue. I installed a v1.9.1 but don't works, then I rollback version still not work.

**Comment by renanss** [comment]
replace picture by href

**Comment by Tocard** [comment]
Do you have all fields displayed on the post ?

for me message, caption, description doesn(t work

**Comment by gregor-srdic** [comment]
I am also trying to use this plugin, I would like to create a post with image and a separate link, that is opened if user clicks the post. Additionaly, I would also like to pre-fill the text (post title or description).
What I am currently seeing is the href with link is used, but the post is not nice without an image.
Anyone managed to get the post created nicely, with image, link and title?

**Comment by zabojad** [comment]
For me @fritio833 fixed it. I rolled back to 1.7.4 and it now displays title, caption and picture of what I request to share...

**Comment by peterpeterparker** [comment]
Showdialog works fine, I do

this.facebook.showDialog(
            {
                method: 'share',
                href: 'https://....',
                caption: 'Something',
                picture: 'https://....',
                hashtag: this.getHashtag()
            }
        );
