### ISSUE TITLE
Custom url on app name 

### ISSUE THREAD

**Issue by JustasKuizinas** [jeduan/cordova-plugin-facebook4#520]
For example in my app I am using facebookConnectPlugin.api(String requestPath, Array permissions, Function success, Function failure) to post photo from my app to user facebook wall. Is it possible to have custom url like Instagram, so users from the web can go directly to my apps web page post?

![](https://monosnap.com/file/O4m0cRXcvqSC4lAgF4bTUl4VrCMCvq.png)

**Comment by peterpeterparker** [comment]
Close it because old issue. For support inquiries plz use other channels like Stackoverflow, thx
