### ISSUE TITLE
crash on iOS 7

### ISSUE THREAD

**Issue by lordamon** [jeduan/cordova-plugin-facebook4#522]
Hi, the last two version of this plugin (1.9.1 and 1.9.0) crash if used on iOS7.x.x (but works with iOS10).
Instead, if i use version 1.8.0 it works fine in iOS7.

i'm using phonegap build cli 6.5.0

**Comment by 0x62** [comment]
iOS7 is old and should no longer be used. This plugin will use methods not available in iOS7, which is why recent versions crash. If you want to keep support for iOS7, stay on version 1.8.0.

**Comment by lordamon** [comment]
yeah i know it is old, but "stupid user" keep their iphone4 alive and pretend to use recent app.... So as long as apple dosent detonate old phone with old ios i need to support them....

**Comment by fredgalvao** [comment]
https://developer.apple.com/support/app-store/
You risk losing a whooping maximum of 3% of all potential users if you block versions bellow 8. Are you sure you wanna go through all this trouble for those 3%?

**Comment by fredgalvao** [comment]
By the way, not even cordova itself supports versions older than 8 as of right now:
https://cordova.apache.org/docs/en/latest/guide/platforms/ios/
> The device must have at least iOS 8 installed, the minimum iOS version supported as of Cordova 4.0.0.
