### ISSUE TITLE
"Tried calling Facebook.browserInit, but the Facebook plugin is not installed"

### ISSUE THREAD

**Issue by amrography** [jeduan/cordova-plugin-facebook4#523]
Hi, 

I have installed Facebook plugin and this message shows on the emulator console: `iPhone SE - iOS 10.1`

`[01:43:50]  console.warn: Native: tried calling Facebook.browserInit, but the Facebook plugin is not installed. `
`[01:43:50]  console.warn: Install the Facebook plugin: 'ionic plugin add cordova-plugin-facebook4' 
`

I am sure the plugin is installed and `ionic cordova plugin ls` show that.

My system info:
`
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v6.11.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.1 Build version 8B62 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.6 
    npm        : 3.10.10 
`
![screen shot 2017-06-22 at 1 49 44 am](https://user-images.githubusercontent.com/9614340/27411321-49cbbcc4-56ed-11e7-9939-de161ca3f8ef.png)
![screen shot 2017-06-22 at 1 49 52 am 2](https://user-images.githubusercontent.com/9614340/27411320-49cb4ab4-56ed-11e7-947b-6cb291dba2e3.png)

**Comment by MauroLescano** [comment]
Same configuration, same issue here

**Comment by phlashworth** [comment]
I'm having the same issue. Has anyone found anything that sheds some light on this?

**Comment by amrography** [comment]
When I updated to latest ionic version the problem disappeared. I am currently using:
`
@ionic/cli-utils  : 1.8.1
ionic (Ionic CLI) : 3.8.1
Cordova CLI : 7.0.1 
@ionic/app-scripts : 2.0.2
Cordova Platforms  : android 6.2.3 ios 4.4.0
Ionic Framework    : ionic-angular 3.5.0

System:
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.6 
    Node       : v6.11.0
    npm        : 3.10.10 
    OS         : macOS Sierra
    Xcode      : Xcode 8.1 Build version 8B62 
`

**Comment by omercnet** [comment]
also having this issue
```cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.3.0 browser 5.0.1 ios 4.5.3
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node  : v8.9.0
    npm   : 5.5.1 
    OS    : macOS Sierra
    Xcode : Xcode 9.1 Build version 9B55 
```

any update on a fix?

**Comment by waterkamp** [comment]
I have the same issue

`
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    Node              : v8.9.1
    npm               : 5.6.0
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : /Users/xxxx/Library/Android/sdk

Misc:

    backend : pro`

**Comment by kgeoir** [comment]
@waterkamp did you find a fix?
