### ISSUE TITLE
How to get email and name of user?

### ISSUE THREAD

**Issue by jeffersonmello** [jeduan/cordova-plugin-facebook4#525]
hello everyone, i need help to get email e and name from user

**Comment by jeffersonmello** [comment]
facebookConnectPlugin.api("<user-id>/?fields=id,email,name", ["public_profile"],
  function onSuccess (result) {
    console.log("Result: ", result);
  }, function onError (error) {
    console.error("Failed: ", error);
  }
);

**Comment by peterpeterparker** [comment]
Close it because old issue. For support inquiries plz use other channels like Stackoverflow, thx
