### ISSUE TITLE
Error 'User cancelled' on ios

### ISSUE THREAD

**Issue by tiagomestreteixeira** [jeduan/cordova-plugin-facebook4#528]
I'm trying to Login with facebook and then getting the user email, birthday, locale and picture.

- On the following platforms and versions it **works** perfectly as expected:

**Androids:**
5.1.1
6.0
7.0

**ios:**
IPhone 7S - 10.3.2
IPhone 5s - 10.3.2

- The following platforms and version the api retrieves the error: **'User Cancelled'**, as if the user cancelled the action:

**ios:**
IPhone 6s - 10.3.2
IPhone SE - 10.3.2 and 10.3.1

I used the following versions of the plugin:    

- Android - 1.7.4
- ios - 1.9.1

**Comment by lincolnthree** [comment]
I am also experiencing this issue, but the platforms seem a bit more scattered. Sometimes it'll work on my test device, other times it'll fail. It seems completely random to me, but I may just be missing some details... very difficult issue to debug.

**Comment by tiagomestreteixeira** [comment]
My conclusion is that the situation occurrence takes place whenever i try to get specific data from facebook, like the email for example. But in all cases i've successfully obtained the oauth token from facebook (with the userID and the accessToken)

**Comment by lincolnthree** [comment]
Hey @tiagomestreteixeira, so you're saying this happens when you do something like: 
```
this.facebook.login(callback, ['email', 'public_profile']) ?
```
But it works when you do this?
```
this.facebook.login(callback) ?
```
Is the behavior consistent or intermittent for you? I have been seeing the issue with the first line of code on some devices but not others.

**Comment by peterpeterparker** [comment]
Close, inactivity
