### ISSUE TITLE
iOS share not working on some devices

### ISSUE THREAD

**Issue by doombringer45** [jeduan/cordova-plugin-facebook4#529]
Hi just a problem with iOS,

tried to use the plugin to share something from our app. I used iphone 6+ with 10.3.2 ios version and the share to fb function works. however when i ran the same app, on an iphone 5s or 6, everytime i share something, it prompts to the login with fb dialog instead of automatically sharing it to facebook (which then returns a facebook posting success message). On the console it just says user cancelled. Any ideas? let me know if you need something else

plugin : cordova-plugin-facebook4 1.7.4 "Facebook Connect"
ios version on both devices : 10.3.2
fb app version: 100.0
ionic v: 3.5.0

**Comment by peterpeterparker** [comment]
Close it because old issue. For support inquiries plz use other channels like Stackoverflow, thx
