### ISSUE TITLE
When sharing a link, link metadata overrides caption and description in post on Android with app installed

### ISSUE THREAD

**Issue by firoze** [jeduan/cordova-plugin-facebook4#530]
this issue only seems to be happening when attempting to post on Android with the Facebook app installed (without the app, the web share dialog appears, which works fine. and on iOS, in either scenario, it works fine)

consider the following:
```javascript
            let options = {
                method: "feed",
                caption: `Caption`,
                picture: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Ulan_Spiral_2000x2000.png",
                description: `"Description"`,
                href: "https://www.google.com/"
            }
```

calling `facebookConnectPlugin.showDialog` with these options shows this dialog in the app:
![screen shot 2017-07-12 at 2 30 04 pm](https://user-images.githubusercontent.com/4399290/28133683-c4b16106-670e-11e7-8912-e195f3f3501f.png)

however, the eventual post replaces the picture, caption and description with the thumbnail, title and description from the link that was provided (in this example, Google's homepage) like so:
![screen shot 2017-07-12 at 2 32 09 pm](https://user-images.githubusercontent.com/4399290/28133727-e93a3c5a-670e-11e7-9b4f-eb5e5f2f7370.png)

currently, there is no way to force the app to use the web dialog on Android (`share_feedWeb` flag works on iOS only)

is there any other way around this issue? any help would be really appreciated 👍

**Comment by burton22ful** [comment]
i have the same issue

**Comment by quieterkali** [comment]
hey @firoze, 
reading facebook documentation i found out that camps(caption, description, picture) will be deprecated by october 2017. Would mind to tell me why you are not looking for another solution?
They said that we should use common object and action to publish stories now.

**Comment by firoze** [comment]
hello @quieterkali 

Yeah I came across the changelog a few days after opening this issue too. I ended up using the graph API (and the `publish_actions` permission) to make posts. That should be fine for now.

**Comment by quieterkali** [comment]
@firoze please could you tell me more about how to did that. i am trying to do the same but no success. any sample of code or explanation will be great for me.

Thanks

**Comment by uareurapid** [comment]
is this fixed in the plugin? it doesn´t seem that the share dialog is working anymore, so why close it?

**Comment by mattlin4567** [comment]
I can't have link sharing on android

**Comment by quieterkali** [comment]
@mattlin4567 paste your code here please.

**Comment by mattlin4567** [comment]
I just simply follow the document from Ionic

```
this.fb.showDialog({
      method: 'share',
      href: 'https://www.facebook.com/GuideofTW',
      caption: 'Such caption, very feed.',
      description: 'Much description',
      hashtag: '#GoTW'
    });
```

the code works fine on iOS, but when I running on Android,
it shows can't share link preview and no any text (caption, description, hashtag)
both of android & iOS device has Facebook app installed

**Comment by uareurapid** [comment]
they are deprecating these fields for the dialogs (also the `picture`, so most of the data is "taken" from the `href ` field instead. In my case i used the `quote` field instead as a workaround to show some custom text that was previously coming from those fields

**Comment by mattlin4567** [comment]
I saw that change log. but my point is the href or link can't show on android device.

**Comment by firoze** [comment]
@uareurapid is right, the picture, description etc fields are now deprecated. If the link metadata are not showing up on devices (android or ios) then it could be due to the relevant `<meta` tags being corrupted or missing from the page
