### ISSUE TITLE
Apprequests dialog not showing up

### ISSUE THREAD

**Issue by ilyakar** [jeduan/cordova-plugin-facebook4#531]
```
facebookConnectPlugin.showDialog({
				method: 'apprequests',
				message: 'I love this app. Join me!',
				to: attr.facebookId
			}, function(){
				console.log('success!');
			}, function(){
				console.log('some error');
			});
```

Nothing happens. No error, no log of any kind. All other features of this plugin work.

I'm using cordova ios v4.4.0 cordova v7.0.1

**Comment by jespertheend** [comment]
For me the problem was that I was using `action_type: "TURN"` like how it is documented in the javascript sdk. But from looking at the source code of this plugin you need to use `actionType: "TURN"` instead.

**Comment by bnfrnz** [comment]
For some reason, with `method: 'apprequests'` you need to also pass a string to `actionType`. It can even be an empty string `actionType: ''`. Then it works.

**Comment by peterpeterparker** [comment]
Close, inactivity
