### ISSUE TITLE
Change response_type

### ISSUE THREAD

**Issue by diegolameira** [jeduan/cordova-plugin-facebook4#532]
Hi there,

Is there a way to change response_type? 

I already have a server that I can`t touch made for angular satellizer and it receives code, clientId & redirectUri. 

Then I need to change the response type from token ( which is default in your cordova-plugin-facebook4 ) to code.

Thnx

**Comment by diegolameira** [comment]
Sorry, I see satellizer has responseType as provider property... lets check it out

**Comment by peterpeterparker** [comment]
Close it because old issue. For support inquiries plz use other channels like Stackoverflow, thx
