### ISSUE TITLE
How to clear Facebook in-app browser cookies

### ISSUE THREAD

**Issue by D-Marc1** [jeduan/cordova-plugin-facebook4#535]
If you use the built in sign in on iOS, rather than the Facebook Connect way, then you can't switch users. On Android you can't switch users with either method. The only way I was able to sign in with a different user was by manually clearing the cookies. I was wondering how this could be achieved, and if anyone has gotten this to work.

**Comment by John-Henrique** [comment]
You tried 

> facebookConnectPlugin.logout(function(){});

?

**Comment by D-Marc1** [comment]
Yes, that logs you out, but you can't switch users in the scenarios I described, without manually clearing the cookies.

**Comment by John-Henrique** [comment]
Show your `FBlogin`

**Comment by D-Marc1** [comment]
I think the code is fine, since the user is definitely logged out, as I check this every time the app is loaded. I just need to be able to clear the cookies inside of the Facebook InAppBrowser, which works when I manually do it on Safari.

**Comment by D-Marc1** [comment]
This needs to be done natively, like so https://stackoverflow.com/a/22194296/3822526. Would be a great addition to add to this plugin.

**Comment by marcelof49** [comment]
To make a complete logout in a facebook app, you have to call:

facebookConnectPlugin.api("/{user_id}/permissions?method=delete", [], success, error);

That way, you will be able to log in with another account. I recommend you to call the logout method, and then, this api method.

**Comment by D-Marc1** [comment]
That's actually an interesting workaround, but then this would obviously make the user have to accept Facebook permissions on every login. Not a huge deal since users of mobile apps will rarely log out and switch users. But still, I feel like there's a better solution to this. Possibly on Facebook's end or in this plugin natively to delete all cookies.

**Comment by peterpeterparker** [comment]
Close, inactivity

**Comment by giacomodeliberali** [comment]
I'm having the same issue here, even if I call `facebookConnectPlugin.api("/{user_id}/permissions?method=delete", [], success, error);` as said by @marcelof49. @D-Marc1 have you found a valid workaround?

**Comment by Kinore** [comment]
https://github.com/jeduan/cordova-plugin-facebook4/issues/378 - this help me
