### ISSUE TITLE
facebookConnectPlugin is Undefined ionic cordova app

### ISSUE THREAD

**Issue by LegionSPQR** [jeduan/cordova-plugin-facebook4#537]
Hi, I´ve installed the plugin with the described command line:

[Terminal Installation Result.txt](https://github.com/jeduan/cordova-plugin-facebook4/files/1177012/Terminal.Installation.Result.txt)

But when i call facebookConnectPlugin.Login in my controller chrome devtools returns an error stating that the plugin is undefined in the scope.

Here is the controller code:

    $scope.facebook = function(user) {
            facebookConnectPlugin.login(["email"], 
            function(userData){
                var userId = userData.authResponse.userID;
                var token = userData.authResponse.accessToken;
                if(userId && token){
                    $rootScope.usuarioId = userId;
                    window.localStorage.setItem("token", token);
                    manterAcesso(userId, null, "facebook");      
                }
                else{
                    if(userId){
                        $ionicLoading.hide();

                        var alertPopup = $ionicPopup.alert({
                            title: 'Erro no Login do Facebook (Token)',
                            template: token
                        });    
                    }
                    else{
                        $ionicLoading.hide();

                        var alertPopup = $ionicPopup.alert({
                            title: 'Erro no Login do Facebook (UID)',
                            template: userId
                        });
                    }  
                }
            },function(error){
                $ionicLoading.hide();

                var alertPopup = $ionicPopup.alert({
                    title: 'Erro no Login do Facebook',
                    template: error.message
                });
            })

Here is the package.json
[Package.json.txt](https://github.com/jeduan/cordova-plugin-facebook4/files/1177074/Package.json.txt)

and the config.xml
[Config.xml.txt](https://github.com/jeduan/cordova-plugin-facebook4/files/1177079/Config.xml.txt)

Is there anything wrong with my call to the plugin?

Thanks in advance

**Comment by alexkerber** [comment]
Same issue here …

**Comment by mdanics** [comment]
I had this issue, and it only happened in my browser. When I tested it on a device / emulator, it then worked

**Comment by peterpeterparker** [comment]
Close it because old issue, I guess you solved it. For support inquiries plz use other channels like Stackoverflow, thx
