### ISSUE TITLE
Ionic problem

### ISSUE THREAD

**Issue by NurGuz** [jeduan/cordova-plugin-facebook4#538]
Hi all,

i have a problem when run my app with ‘ionic cordova run android --device’. The Facebbok loggin run correctly in web, but in my android device have this error: '‘to use this url you must add a valid native plataform in you app’s settings’

I have the plataform for android correctly, but not run.

Someone can help me?

Thx

**Comment by all43** [comment]
Probably you have to add Android platform on the developers.facebook.com website
https://docs.ionic.io/services/auth/facebook-native.html#device-specific-configuration

**Comment by peterpeterparker** [comment]
Close it because old issue. For support inquiries plz use other channels like Stackoverflow, thx
