### ISSUE TITLE
showDialog using "share_open_graph" not publishing

### ISSUE THREAD

**Issue by quieterkali** [jeduan/cordova-plugin-facebook4#539]
I am trying to publish a story using common object and action. But i keep getting the follwing error: errorMessage:"Facebook error: Error publishing message".
Pease anyone can tell me what if i am doing wrong or is this a bug?
Here is the code:

publish() {
    this.facebook.getLoginStatus()
    .then(res => {
      console.log(res);
      if(res.status === 'connected') {
          let obj = {};
          obj['og:type'] = 'book';
          obj['og:title'] = 'Title';
          obj['og:url'] = 'https://www.facebook.com/fidsave';
          obj['og:image'] = 'https://upload.wikimedia.org/wikipedia/commons/9/99/Black_square.jpg';
          obj['og:description'] = 'YOu won something special';
        this.facebook.showDialog({
          method: 'share_open_graph', // Required
          action: 'og.likes', // Required
          object: JSON.stringify(obj) // Required
        }).then(data => console.log(data)).catch(err => console.error(err));
      }
    })
 }

system info:

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.11.0
    OS         : Linux 4.10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10

**Comment by peterpeterparker** [comment]
For me on Android it look like the action 'og.shares' is working just fine, I see you use 'og.likes', that may be the difference?

    showDialog(
                {
                    method: 'share_open_graph',
                    action: 'og.shares',
                    object: JSON.stringify({
                        'og:description': 'Hello, is it you?',
                        'og:image': 'https://mydomain.com/myimage.jpg',
                        'og:url ': ''https://mydomain.com',
                        'og:type': 'website'
                    })
                }

**Comment by peterpeterparker** [comment]
On Android with cordova-plugin-facebook4 the parameter `og:type` is mandatory (see code) but it look like Facebook.UI doesn't like that parameter

When I try following code in this debug http://www.fbrell.com/saved/2779dc018c325d85d650a3b723239650

    FB.ui({
        method: 'share_open_graph',
        action_type: 'og.shares',
        action_properties: JSON.stringify({
            object : {
               'og:url': 'http://astahdziq.in/', // your url to share,
               'og:title': 'Here my custom title',
               'og:description': 'here custom description',
               'og:image': 'http://example.com/link/to/your/image.jpg',
               'og:type': 'website'
            }
        })
      }, function(response){});

The sharing dialog face and error and didn't open. If I remove 'og:type': 'website' then the sharing dialog appear....weird

**Comment by peterpeterparker** [comment]
Close for non activity. Plz use other channels for support inquiry, like Stackoverflow, thx
