### ISSUE TITLE
issue on logout

### ISSUE THREAD

**Issue by alphacentory** [jeduan/cordova-plugin-facebook4#541]
`Refused to display 'https://www.facebook.com/home.php' in a frame because it set 'X-Frame-Options' to 'deny'.
sdk.js:73 GET https://www.facebook.com/home.php net::ERR_BLOCKED_BY_RESPONSE` 

I assume this is because of the api change or is this something on my end?

**Comment by peterpeterparker** [comment]
Close it, old task, furthermore plz use other channels for support inquiry, thx
