### ISSUE TITLE
Using on browser without cordova.js

### ISSUE THREAD

**Issue by all43** [jeduan/cordova-plugin-facebook4#543]
I'm building web version of my app without using cordova browser platform (because it's buggy and contains a lot of unneeded stuff)

In the docs I found the following:

> www/**facebookConnectPlugin.js** contains the JavaScript SDK and API file
however I cannot find this script and **facebook-browser.js** doesn't run without cordova. Probably there is should be fallback when cordova is not available.

**Comment by epetre** [comment]
Yeah I'm wondering if this would be hard to achieve too.

**Comment by peterpeterparker** [comment]
You could use the Facebook javascript lib to do so https://developers.facebook.com/docs/facebook-login/web
