### ISSUE TITLE
Missing permission NSPhotoLibraryUsageDescription on IOS

### ISSUE THREAD

**Issue by sirpy** [jeduan/cordova-plugin-facebook4#545]
When I try to upload to the appstore i get rejected because of missing NSPhotoLibraryUsageDescription key.
I'm not sure if it comes from this package, but since there's a facebook share image here i think it might be relevent.
IOS 10 requires that the plist contains the key NSPhotoLibraryUsageDescription, this should probably be added by this package,

**Comment by jedabero** [comment]
You should checkout [https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-camera/](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-camera/)

**Comment by peterpeterparker** [comment]
Close it I guess you resolved your issue
