### ISSUE TITLE
Ionic3 Android Show Dialog() print nothing

### ISSUE THREAD

**Issue by badbytes1** [jeduan/cordova-plugin-facebook4#549]
```
    this.facebook.showDialog({
      method: "share",
      picture:'https://www.google.co.jp/logos/doodles/2014/doodle-4-google-2014-japan-winner-5109465267306496.2-hp.png',
      name:'Test Post',
      message:'First photo post',
      caption: 'Testing using phonegap plugin',
      description: 'Posting photo using phonegap facebook plugin'
    })
    .then(() => {
      console.log('Success!');
    })
    .catch(() => {
       console.log('Error');
    });
```
It opens the share , but doesn't fill it with the ShowDialog parameters

**Comment by renanss** [comment]
same here

**Comment by renanss** [comment]
I figured out that the only available fields for the 'share' method are:
```
 method: "share",
 quote: 'a pre defined quote that you may want to input',
 href: 'image or site url',
 hashtag: '#OneTagOnly',
 mobile_iframe: boolean
```
I recommend you read:
https://developers.facebook.com/docs/sharing/reference/share-dialog
And for more advanced features use share_open_graph
https://developers.facebook.com/docs/reference/opengraph/

hope it helped.

**Comment by mattlin4567** [comment]
can't have link preview on android device too.
@renanss  did you get it work?

**Comment by JoaoCaixinha** [comment]
Any news about this issue?

**Comment by Tocard** [comment]
facebookConnectPlugin.showDialog({
            method: "share",
            message:"test message",
            quote: "test quote",
            name:'test name',
            caption: "test caption",
            description:"test decription"
            href: "https://i.imgur.com/KuQcvEV.png",
}

this code doesn't display message, caption, description, and name, do you have any fix ?

**Comment by luckyycool** [comment]
renanss, you are right but even after putting quote:

quote: 'a pre defined quote that you may want to input', 

You wil see this quote while posting to fb but after posting this text is no where in that FB post.

**Comment by peterpeterparker** [comment]
see @renanss answer for available fields
