### ISSUE TITLE
User cancelled

### ISSUE THREAD

**Issue by balicekt** [jeduan/cordova-plugin-facebook4#55]
Hey guys, 

when I start my app and want to log in on iOS I get "User cancelled". But when I try log in again immediately after this issue I can log in successfuly. And then when I log out and try log in it's working fine again. This is happening just when I start the app on IOS. 

Any idea? please help. Thank you

Thanks for any help

**Comment by fredgalvao** [comment]
@balicekt Could you share how you solved your problem, or what exactly was the issue? It might be helpful to other people.

**Comment by balicekt** [comment]
actually I didn't figure it out. But after hours of testing I found out it has something to do with this plugin: https://github.com/EddyVerbruggen/cordova-plugin-googleplus when I use this plugin before I want to log in with facebook4 plugin I will get "User canceled" and I have no idea why.  But when want to log in second time and don't use googleplus plugin between this two facebook4 logins everything is working fine. I will get relly crazy of it....
