### ISSUE TITLE
Re-ask permissions in Facebook login

### ISSUE THREAD

**Issue by DomyNik** [jeduan/cordova-plugin-facebook4#552]
Hi guys! Is there a way for this plugin to re-ask permission? I'm trying to connect my app to an API that requires the user's email. In my case, if users uncheck the email in my app and continues to login Facebook, when I check the Facebook account that I used to login, it is in my apps. So is there a way to :

1) re-ask permission in Facebook login?
or if that isn't happening
2) stop users from getting logged in Facebook if the user refuses to give his email?

I'm using ionic 3 btw.. I would appreciate some insight :D

**Comment by tiagomestreteixeira** [comment]
@DomyNik For re-ask permission, did you try using some logic with the signout method of the plugin?

**Comment by DomyNik** [comment]
@tiagomestreteixeira  What do you mean try some logic with signout method? The moment an app logs in Facebook, it is already registered in the Facebook account in the apps section- something I don't wan't to happen. Once an app is registered in a Facebook account and a user logs in the app, users are not prompted for permissions anymore. The only way the app is removed from being registered from Facebook so that permissions are re-requested is that the users go to their Facebook accounts and remove the app...

**Comment by sujitgawas19** [comment]
Hey i have the same issue. I want to know how to use graph api to re-ask permissions.

**Comment by peterpeterparker** [comment]
Close for non activity. Plz use other channels for support inquiry, like Stackoverflow, thx
