### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException

### ISSUE THREAD

**Issue by viveksinha121** [jeduan/cordova-plugin-facebook4#554]
Getting this NullPointerException in crashlytics. Please check

com.facebook.login.LoginFragment.onCreate (LoginFragment.java:100)
--
  | android.support.v4.app.Fragment.performCreate (Fragment.java:2226)
  | android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1290)
  | android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState (FragmentManager.java:1574)
  | android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1641)
  | android.support.v4.app.BackStackRecord.executeOps (BackStackRecord.java:794)
  | android.support.v4.app.FragmentManagerImpl.executeOps (FragmentManager.java:2415)
  | android.support.v4.app.FragmentManagerImpl.executeOpsTogether (FragmentManager.java:2200)
  | android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps (FragmentManager.java:2153)
  | android.support.v4.app.FragmentManagerImpl.execPendingActions (FragmentManager.java:2063)
  | android.support.v4.app.FragmentController.execPendingActions (FragmentController.java:388)
  | android.support.v4.app.FragmentActivity.onStart (FragmentActivity.java:554)
  | android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1171)
  | android.app.Activity.performStart (Activity.java:5143)
  | android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2184)
  | android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2261)
  | android.app.ActivityThread.access$600 (ActivityThread.java:141)
  | android.app.ActivityThread$H.handleMessage (ActivityThread.java:1256)
  | android.os.Handler.dispatchMessage (Handler.java:99)
  | android.os.Looper.loop (Looper.java:137)
  | android.app.ActivityThread.main (ActivityThread.java:5103)
  | java.lang.reflect.Method.invokeNative (Method.java)
  | java.lang.reflect.Method.invoke (Method.java:525)
  | com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:737)
  | com.android.internal.os.ZygoteInit.main (ZygoteInit.java:553)
  | com.android.internal.os.ZygoteInit.main (ZygoteInit.java)
  | dalvik.system.NativeStart.main (NativeStart.java)

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect. I'm not seeing this NPE with that plugin, and I'm fairly certain the Support library was dropped some time ago.
