### ISSUE TITLE
Callbacks of showDialog

### ISSUE THREAD

**Issue by papattes** [jeduan/cordova-plugin-facebook4#555]
a little note that could help some developer:

To use the callbacks of the dialog box under Android, the user must be connected with facebookLogin. Otherwise, the success callback will always be called.

On iOS, I did not notice that.

**Comment by mattlin4567** [comment]
the share dialog on android can't show anything(link, caption)
and iOS worked fine.
but both of device have facebook app installed and login
should I need to login again?

**Comment by GianFF** [comment]
@papattes thanks for that tip, I'm running on that issue rigth now. 

What did you mean with `the user must be connected with facebookLogin.`?

**Comment by papattes** [comment]
@gianFF
I wanted to say that android, we must call the method Login before using the dialog box sharing otherwise the callback success is called in all cases

**Comment by peterpeterparker** [comment]
Since this issue is an information and not an issue, I close it. Feel free to submit a PR if you want to improve the doc
