### ISSUE TITLE
Not working in Android 7.0, If facebook app is installed

### ISSUE THREAD

**Issue by rahulit70** [jeduan/cordova-plugin-facebook4#558]

**Comment by Hypher** [comment]
Everything works very well for me on Android 7.0
Explain more

**Comment by maciejgos** [comment]
I confirm not working on Galaxy S7 with Android 7.0. Application version is downloaded from Google Play Store. After removal of Facebook app it start work as expected.

I try to debug this and add some input.

**Comment by maciejgos** [comment]
It seems that it is a problem with compilation on this particular configuration. After Cordova project recompilation in Android Studio under SDK 7.0 it starts work as expected.

I try to put some code with issue details.

**Comment by JayzeeHuang** [comment]
Same issue here, I am running ionic app on android 7.0. Plugin login launch failed when Facebook installed. When I removed the Facebook app, everything working fined. Any one working on this issue? Thanks in advance.

**Comment by Hypher** [comment]
@JayzeeHuang did you try to recompile your project in Android Studio with SDK 7.0 as maciejgos did?

**Comment by peterpeterparker** [comment]
Work fine on Android 7, for support request plz use other channels like Stackoverflow
