### ISSUE TITLE
showDialog empty content

### ISSUE THREAD

**Issue by volodymyrl** [jeduan/cordova-plugin-facebook4#56]
I use this code to show share dialog 
```
var post_id = fid.split('_');
            var options = {
                method: "feed",
                link: 'http://www.facebook.com/permalink.php?story_fbid=' + post_id[1] + '&id=' + post_id[0]
            };

            $cordovaFacebook.showDialog(options)
                .then(function(success) {
                    console.log(success)
                    alert('options');
                },
                function(error) {
                    console.log(error)
                });
```
on iOS it's work ok, but on Android I get empty content
http://prntscr.com/8m9vm1

What can be the reason for it?

**Comment by volodymyrl** [comment]
@jeduan can you confirm that plugin show empty content on Android or give supporting how to fix it?

**Comment by taejaehan** [comment]
Change the 'href' as 'link' in buildContent function in the file ConnectPlugin.java.
it works for me :)

**Comment by auching** [comment]
It's still showing empty content... any fix for PGB users? Thanks.

**Comment by edriang** [comment]
Please, take a look at my answer here: https://github.com/jeduan/cordova-plugin-facebook4/issues/36

**Comment by robertarnesson** [comment]
https://github.com/jeduan/cordova-plugin-facebook4/commit/895fffad2064d794e3fa60ea60c71d2c369b4376
