### ISSUE TITLE
facebookConnectPlugin.appInvite not sending notification not android or in ios ?

### ISSUE THREAD

**Issue by Swapniltdatalogy** [jeduan/cordova-plugin-facebook4#563]
I am using PGB . <preference name="phonegap-version" value="cli-6.3.0" />
 <preference name="android-minSdkVersion"      value="15" />

**Comment by Tanmay2905** [comment]
Hello,
I am stuck a same issue.Did you find any solution for this?
Thank You

**Comment by alexandranb** [comment]
Hello,

I have the same problem with the notifications. Did you find a solution for this or maybe a cause?

Thanks

**Comment by shahkhalid-me** [comment]
I have the same problem.

**Comment by peterpeterparker** [comment]
Closed, `appInvite` doesn't exist anymore

https://github.com/jeduan/cordova-plugin-facebook4/issues/645
