### ISSUE TITLE
permissions.indexOf is not a function

### ISSUE THREAD

**Issue by RenanRosa** [jeduan/cordova-plugin-facebook4#564]
I am having the following issue:

"permissions.indexOf is not a function" in the facebook-browser.js:51  file.

I did not change the code, its just stopped to work.

**Comment by noahcooper** [comment]
This error seems to indicate that you passed an invalid `permissions` argument to the login method, e.g. an object instead of an array.

This plugin is deprecated. See https://www.npmjs.com/package/cordova-plugin-facebook-connect.
