### ISSUE TITLE
How to set the auth_type to 'rerequest' ?

### ISSUE THREAD

**Issue by gerwinbrunner** [jeduan/cordova-plugin-facebook4#566]
I like to set the auth_type of every request, but I seem not to be able to find a way to do so for a regular `facebookConnectPlugin.login` call.

**Comment by gerwinbrunner** [comment]
Any idea how to get this working?

**Comment by erdimeola** [comment]
This would be an awesome update. It's crucial to ask for permissions again if user removed some permissions.

**Comment by gerwinbrunner** [comment]
Any idea on how to do this?

**Comment by tobischulz** [comment]
+1 for set auth_type

**Comment by gerwinbrunner** [comment]
Anybody?

**Comment by allanpoppe** [comment]
Actually, Facebook SDK does it automatically.

Using ionic-native, you should ask for permissions with:
```
this.fb.login([permission])
```

The same goes for using facebookConnectPlugin without native.

This will set the auth_type to 'rerequest' inside Facebook SDK.

**Comment by oshratCh** [comment]
@allanpoppe you right BUT need to add "rerequest" to permission list.

**Comment by noahcooper** [comment]
This plugin is deprecated. See `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect.

As noted above, you don't need to set auth_type yourself -- the Facebook SDK will automatically handle this for you when you call the login method.
