### ISSUE TITLE
First time iOS login fails, restarting app makes it work

### ISSUE THREAD

**Issue by heshamghandour** [jeduan/cordova-plugin-facebook4#567]
Hi all,

If I try to connect with fb right after I install the app on my iphone, it fails throwing this error in the xcode console:

Attempt to present <FBSDKContainerViewController: 0x153d48ac0> on <FBSDKContainerViewController: 0x153d4d430> whose view is not in the window hierarchy!

However after restarting the app everything works fine. Any ideas what the problem could be?

**Comment by heshamghandour** [comment]
Actually simple connecting a second time without restarting the app makes it work. Strange.

**Comment by Remco75** [comment]
I experience the same on a iPhone6 (not very consitent though)

**Comment by skrchr** [comment]
i have the same problem. It started happening recently on ios devices

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect.

This must've been a temporary issue with a previous version of iOS. The plugin works as expected the first time you login, no restart is required.
