### ISSUE TITLE
iOS App crashes instantly after hitting facebook login.

### ISSUE THREAD

**Issue by W1ldW1ngs** [jeduan/cordova-plugin-facebook4#570]
On our app's login/signup page we have a facebook login button. In the latest build we have done the app instantly crashes the moment a user hits the button. We haven't been able to get any logs since this happens exactly when you hit the button and the logs aren't dropped into local storage. 

Wondering if anyone has any insight or help, for right now we've tried disabling Facebook Audience Network to see if that was maybe related but no dice.

Temporary solution would be to push a new build with out the facebook login until fixed.

**Comment by peterpeterparker** [comment]
Plz use other channels like Stackoverflow for support inquiry, thx
