### ISSUE TITLE
Logout handled inconsistently between platforms

### ISSUE THREAD

**Issue by greg84** [jeduan/cordova-plugin-facebook4#571]
I've noticed that if a user is already logged out (i.e. there is no access token) and you call `logout` the plugin behaves differently depending on the platform.

On Android, the plugin [returns an error](https://github.com/jeduan/cordova-plugin-facebook4/blob/master/src/android/ConnectPlugin.java#L284).

On iOS, the plugin [executes the success callback](https://github.com/jeduan/cordova-plugin-facebook4/blob/master/src/ios/FacebookConnectPlugin.m#L230).

I would suggest that the iOS behaviour is preferred, as there's nothing the user can do if they don't have an access token, other than log in again.

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect. That plugin has been updated to make the `logout` method consistent across platforms, and call the success callback even if there is no current access token defined.
