### ISSUE TITLE
Receiver is not getting app-invite

### ISSUE THREAD

**Issue by Tanmay2905** [jeduan/cordova-plugin-facebook4#574]
I have integrated this plugin.Followed all steps. The plugin sends app-invite to friends, but people to whom I sent the app-invite did not get a invite or notification.
Thank You.

**Comment by alexandranb** [comment]
Hello,

I have the same problem, did you manage to solve this?

**Comment by peterpeterparker** [comment]
App Invite isn't support by Facebook anymore, see https://github.com/jeduan/cordova-plugin-facebook4/issues/645
