### ISSUE TITLE
Can not login again with Facebook after logout

### ISSUE THREAD

**Issue by Niore** [jeduan/cordova-plugin-facebook4#575]
When I open my app i can login with facebook at the first time. then i log out of my app and want to login again with facebook. after the click on the login button a spinner appers but nothing happens. the method fb.login gets called but nothing happens afterwards. 

```javascript
this.fb.login(['public_profile', 'email']).then((facebookData: FacebookLoginResponse) => {
                    let provider = firebase.auth.FacebookAuthProvider.credential(facebookData.authResponse.accessToken);
                    //this.handleSignInWithProvider(provider, observer);

                     this.afAuth.auth.signInWithCredential(provider).then(firebaseData => {
                        observer.next();
                     }, error => {
                         observer.error(error);
                     });
                    /* */
                }).catch(e => {
                    console.log(e);
                    observer.error(e);
                });
```

Special about this is that most of the time the first login with facebook works. but when i immediatly log out and not close the app and try to login again the spinner appers and nothing happens. No error code nothing. Could you help me ???????

**Comment by Kritsana-Punyaporn** [comment]
@Niore Same problem. I need some help.

**Comment by talarcon** [comment]
On the relogin after logout is trying to use graphPath var, but is null. Commented this lines on ConnectPlugin.java is a workaround.
```
if (lastGraphContext != null) {
    makeGraphCall(lastGraphContext);
    return;
}
```

**Comment by ErxrilOwl** [comment]
Same Issue. Any solution for this?

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out the actively maintained fork `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect. Please feel free to log a new issue there with more details if you're still running into problems.
