### ISSUE TITLE
Plugin in VUE application

### ISSUE THREAD

**Issue by zirra** [jeduan/cordova-plugin-facebook4#578]
I am trying to get this plugin to allow me to connect to facebook in a vue js application.   when I call the method nothing happens, if I hit the home button on my iphone and show my open apps, the screen will update to the facebook login, this will never happen if I stay in the app.  The login screen shows, I gill out the form, I hit login, complete and the success is called.  but the move to next page never happens.

why does the login window never pop up?

**Comment by peterpeterparker** [comment]
Plz use other channels like Stackoverflow or Ionic forum for support inquiry, thx
