### ISSUE TITLE
showdialog method is not showing image in feed dialog in ionic 1 app.

### ISSUE THREAD

**Issue by Vo0Do0** [jeduan/cordova-plugin-facebook4#580]
Hi,

I am working in a Ionic 1 app, I am using this plugin to share a link with image as a feed dialog in facebook. Previously it was working perfectly. But after reinstalling the plugin, the picture is not showing in feed dialog as well as in the post. This problem is occurring in both android and ios. I have already seen [this](https://stackoverflow.com/questions/27399608/facebookconnectplugin-showdialog-is-not-showing-image-on-share-dialog) and [this](https://stackoverflow.com/questions/41730145/facebook-cordova-plugin-sharing-a-photo-with-no-link-results-in-empty-share) links but those didn't solved my problem.

Here is my system information:
Cordova CLI: 6.4.0 
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
ios-deploy version: 1.9.2 
ios-sim version: 6.1.2 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 9.0.1 Build version 9A1004

plugin:
cordova-plugin-facebook4 1.9.1

and here is my code sample:

> facebookConnectPlugin.showDialog({
            method: "feed",
            href: 'http://www.testingmyapp.com',
            picture: 'https://www.google.co.jp/logos/doodles/2014/doodle-4-google-2014-japan-winner-5109465267306496.2-hp.png',
            name: 'Test Plugin Post',
            message: 'Test Plugin photo post',
            caption: 'Testing picture is not appearing issue',
            description: 'Testing picture is not appearing issue',
        },
        function(response) {
            console.log(JSON.stringify(response));
        },
        function(response) {
            console.log(JSON.stringify(response));
        });

Please suggest me the workaround. Thanks in advance.

**Comment by camdav** [comment]
I have the same issue. Have you found a solution?

**Comment by aweklin** [comment]
I am having exactly same issue on my ionic 2 app. Need very very urgent help please.

**Comment by globules-io** [comment]
"As of April 18, 2017, the following parameters are no longer supported by Graph API versions 2.9 and higher. For versions 2.8 and lower, the parameters will continue working until July 17, 2017." : picture, name, caption, description, thumbnail. Found https://developers.facebook.com/docs/sharing/reference/feed-dialog/
Is there a replacement? Thanks

**Comment by gregor-srdic** [comment]
I am also encountering troubles trying to share the link and the image in the Facebook post in an Ionic3 app. What is the proper config to do this?

**Comment by aweklin** [comment]
I can now share images but it takes several tap on the share button before the share dialog appears.

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect.

Facebook deprecated the `image` property (or `picture`) in 2017.
