### ISSUE TITLE
How do we do a POST graph API?

### ISSUE THREAD

**Issue by yauluntang** [jeduan/cordova-plugin-facebook4#581]
The JS SDK has a parameter to set either GET or POST but this seems to be lack of this functionality.

**Comment by TadijaB** [comment]
There doesn't seem to be a way to use any [Publishing ](https://developers.facebook.com/docs/graph-api/reference/v2.11/user/feed/) functionality without POST-ing to graph API?

**Comment by oladipo** [comment]
Has anyone found a way to do POSTs with the plugin?

**Comment by gpinkham** [comment]
seems like PR's aren't being merged..   I wonder if there is another fork of this more up to date?

**Comment by gpinkham** [comment]
@jmmclean thanks again for this.   hate to bug but curious..   have you posted links using this?  or scheduled posts?       I basically put all the params I had in the body of the post I was successfully sending thru the JS api into the query string..    and it calls back to the failure function. .but the error object is empty..  and nothing posted to FB..    so I was guessing maybe it rejected these query params..   /shrug...  

code example just in case it matters
````
   var timestamp = (postInfo.timestamp === undefined ? '' : `&published=${postInfo.published}&scheduled_publish_time=${postInfo.scheduled_publish_time}`)
  facebookConnectPlugin.api(`/${id}/feed?method=post&link=${postInfo.link}&message=${postInfo.message}&access_token=${postInfo.access_token}${timestamp}`, ['manage_pages','publish_pages'], function(pageResponse){
        console.log(pageResponse);
        if (!pageResponse) {
            callback(new Error('no response from Facebook'), null);
         } else {
            callback(null, pageResponse)
          }
     }, function(error) {
        callback(error, null);  // <- this gets called with an empty error object... no message or anything..
     });
````

**Comment by jmmclean** [comment]
@gpinkham I think your code looks off. This package utilizes promises to handle asynchronous execution, not callbacks (as you have done in your code). the below MAY work, trying to vet through this:
```javascript
${postInfo.access_token}${timestamp}`, ['manage_pages','publish_pages'].then(function(pageResponse){
    console.log(pageResponse);
    if (!pageResponse) {
        callback(new Error('no response from Facebook'), null);
    } else {
        callback(null, pageResponse)
    }
})
.catch(function(error) {
    callback(error, null);  // <- this gets called with an empty error object... no message or anything..
});
```

**Comment by gpinkham** [comment]
@jmmclean the docs look like callbacks (but admittedly JS is not my strong suit).. But also my other code works (login.. getting info about the user etc..)..       for instance this is from the readme.      I thought the success and failure functions were callbacks..     (I will see what happens when I switch to a promise though..  )
````
facebookConnectPlugin.api(String requestPath, Array permissions, Function success, Function failure)
````

**Comment by jmmclean** [comment]
ha! how right you are. i use this with Ionic https://ionicframework.com/docs/native/facebook/

The only thing i can think is its a bad request....to debug, i would log out your api string template, just to make sure everything looks right

**Comment by gpinkham** [comment]
> log out your api string template
? 
 I was just looking into how to enable FB api request logging..    I know how in when I'm doing java..  just not cordova/JS..

**Comment by jmmclean** [comment]
to clarify, i just mean the string that you populate for the api, log it out and make sure there are no null fields. Not sure if you have a handler for your `postResponse`.

```javascript
console.log(`/${id}/feed?method=post&link=${postInfo.link}&message=${postInfo.message}&access_token=${postInfo.access_token}${timestamp}`);
```

**Comment by gpinkham** [comment]
oh ok..  i thought you meant the api debug logging..    I did check that earlier..  but will verify again..     code changed so many times quite possible I messed up one of those fields..

**Comment by gpinkham** [comment]
@jmmclean just to finish the thread.. it was me .   my link being from the cordova app was file://somethingsomething  and I guess FB was rejecting without a message..      changed it to a valid url and the post works now.    thanks and sorry for making this issue a "help Gary with his stuff" thread..

**Comment by jmmclean** [comment]
@gpinkham no worries...we all stumble for too long on the obvious.

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect. That plugin now supports providing an HttpMethod when calling the Graph API.
