### ISSUE TITLE
FacebookInitProvider: A valid Facebook app id must be set in the AndroidManifest.xml

### ISSUE THREAD

**Issue by intelli-dave** [jeduan/cordova-plugin-facebook4#582]
We have issues with this plugin on Android. 

When calling the `login` method, the login dialog does not show and an error with no data is thrown.

We looked into the phone's log and found the following errors.

`FacebookInitProvider: Failed to auto initialize the Facebook SDK`

`FacebookInitProvider: A valid Facebook app id must be set in the AndroidManifest.xml or set by calling FacebookSdk.setApplicationId before initializing the sdk.`

Not sure what is going on. We have tried this in a new Ionic app with the same issue.

**Comment by jeduan** [comment]
Follow this https://developers.facebook.com/docs/android/getting-started/
