### ISSUE TITLE
getting empty appInvite facebook friendlist cordova 

### ISSUE THREAD

**Issue by shivam05aggarwal** [jeduan/cordova-plugin-facebook4#583]
I am using the appInvite function but it is showing blank friendlist popup.
   firstly it checks for login and when i click on continue a blank popup comes which previously showing friend list from which i can mark several and can send then facebook invite. If anyone has any idea please help me out in solving the issue.

function callFacebookInvite(){
 facebookConnectPlugin.login(['email'],
        function(response)
        {
        
            facebookConnectPlugin.appInvite(
                {
                    url: "https://fb.me/1460466087382078",
                    picture: "https://lh5.ggpht.com/tZfWMCjiXZf1HiDbCZvfpgbpr2vBs2XB3YnczDGeOv-
                           eRDS7fWEH8Uz-PmsQPFMIUcQ=w300"
                },
                function(obj){
                    console.log(obj);
                    if(obj) {
                        if(obj.completionGesture == "cancel") {
                            // user canceled, bad guy
                        } else {
                            // user really invited someone :)
                        }
                    } else {
                        // user just pressed done, bad guy
                },
                function(obj){
                    // error
                    console.log(obj);
                }
            );
     console.log(response)
        },
        function(failure){
            console.log(failure, 'failure')

        });
 }

**Comment by renatobezerra** [comment]
In my case, I get error "Unable to show dialog".

**Comment by shivam05aggarwal** [comment]
I am also getting "Unable to show dialog" and sometimes
errorMessage : "Facebook error: Dialog failed with unknown error"

**Comment by shivam05aggarwal** [comment]
Is there any update?

**Comment by peterpeterparker** [comment]
Closed, `appInvite` doesn't exist anymore

https://github.com/jeduan/cordova-plugin-facebook4/issues/645
