### ISSUE TITLE
Broken with googleplus plugin

### ISSUE THREAD

**Issue by thegalah** [jeduan/cordova-plugin-facebook4#584]
If google plus signing plugin is installed the following behaviour occurs.

Upon facebook login approval from the facebook app, the web dialog will remain and will not return to the app.

If the user taps on "Done" from this point the plugin will say that the user cancelled the dialog

**Comment by peterpeterparker** [comment]
Plz use other channels like Stackoverflow or Ionic forum for support inquiry, thx
