### ISSUE TITLE
Broken with cordova-plugin-ionic

### ISSUE THREAD

**Issue by Sengrith** [jeduan/cordova-plugin-facebook4#585]
After complying, the FB.init use cordova-plugin-ionic "APP_ID" instead of cordova-plugin-facebook4 "APP_ID", which give error in console as follow:

`Uncaught ReferenceError: bd97d6a8 is not defined
    at window.fbAsyncInit (facebook-browser.js:131)`

NOTE: `bd97d6a8` is my ionic pro APP_ID

**Comment by mfbasso** [comment]
I have the same problem here, did you find a solution?

**Comment by mfbasso** [comment]
I fix this change in "package.json" the order of plugins:

`"cordova": {
    "plugins": {
      "cordova-plugin-facebook4": {
        "APP_ID": "XXXXXXXXXXXXX",
        "APP_NAME": "XXXXXXXX"
      },
      "cordova-plugin-ionic": {
        "APP_ID": "XXXXXXXXX",
        "CHANNEL_NAME": "Master",
        "UPDATE_METHOD": "background"
      },
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {}
    },
    "platforms": [
      "android",
      "browser"
    ]
  }`

**Comment by peterpeterparker** [comment]
For same error, see solution of @mfbasso
