### ISSUE TITLE
Error Installing Plugin

### ISSUE THREAD

**Issue by baviskarmitesh** [jeduan/cordova-plugin-facebook4#586]
I am adding plugin with 
cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="12345" --variable APP_NAME="JumboApp" 

after ionic build command gives error as 
 No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'. FAILED

Even after importing project t eclipse I am getting com.facebook not found error

**Comment by peterpeterparker** [comment]
Maybe https://stackoverflow.com/questions/32075498/error-retrieving-parent-for-item-no-resource-found-that-matches-the-given-name

I close this discussion since it's a support issue, use other channels like Stackoverflow, thx in advance for your understanding
