### ISSUE TITLE
Unable to do appInvite in Android

### ISSUE THREAD

**Issue by sunojvijayan** [jeduan/cordova-plugin-facebook4#587]
Hi I am able to open appInvite dialog in ios and send (But not received by the other person). And if i do the same in Android its showing "Unable to show dialog".

Please help. Thanks in advance.

**Comment by shahkhalid-me** [comment]
I have the same problem.

**Comment by renatobezerra** [comment]
I have a same issue.

**Comment by sunojvijayan** [comment]
No didn't find any solution till now.

**Comment by cuongmt** [comment]
I have a same issue,Did you find any solution?

**Comment by Borongaj** [comment]
Same here...

**Comment by phonic** [comment]
same here, version 1.9.1

**Comment by phonic** [comment]
Seems to be outdated anyway, so just give up on this functionallity...

https://stackoverflow.com/questions/47196972/facebook-app-invites-is-deprecated

**Comment by peterpeterparker** [comment]
Closed, `appInvite` doesn't exist anymore

https://github.com/jeduan/cordova-plugin-facebook4/issues/645
