### ISSUE TITLE
Cannot read property 'login' of undefined

### ISSUE THREAD

**Issue by HellHound90** [jeduan/cordova-plugin-facebook4#590]
Hello guys,
I'm working on a phonegap application for ios and android and I need a fb login.
Running the Phonegap Developer Application I'm giving this issue: "Cannot read property 'login' of undefined"

I have the facebook ID and facebook name and I installed the plugin correctly.
I also included the js file FacebookConnectPlugin.js inside the index.html.

This is my code inside onDeviceReady, #lfb is a button for the login process:

`
$('#lfb').on('click', function() {

        try {

            var fbLoginSuccess = function (userData) {
              alert("UserInfo: "+userData);
              facebookConnectPlugin.getAccessToken(function(token) {
                alert("Token: " + token);
              });
            }

            facebookConnectPlugin.login(["public_profile"], fbLoginSuccess,
              function (error) {
                alert(error);
              }
            );

        }

        catch (e) {
             alert('error1='+e.message);
        }

    });

`

Hope someone can help me soon!
Cheers!

**Comment by peterpeterparker** [comment]
Plz use other channels like Stackoverflow or Ionic forum for support inquiry, thx
