### ISSUE TITLE
Can't Switch users after one time Login

### ISSUE THREAD

**Issue by ahsan154** [jeduan/cordova-plugin-facebook4#591]
Hi Experts!

Sorry for my bad english.

I installed this plugin and every thing is working fine, except i can't switch users in the app. It always picks the one i logged in for the first time. Now if i want to use any other facebook account, i cant.

I even tried logout multiple times like before calling login, after login etc, even i cleared the all the local-storage. at last i cleared cache/data of the app too but still its uses the old facebook account logged in last time.

Any help in this regard will be really appreciated.

Regards,
Ahsan Ali

**Comment by Bistaff** [comment]
Any news?

**Comment by ahsan154** [comment]
:( not yet

**Comment by ErxrilOwl** [comment]
Same issue, any news?

**Comment by kalaiprakash93** [comment]
try to call log out function

**Comment by thanhnguyen92** [comment]
I still have the same issue with @ahsan154 until now, and the problem isn't solve... I'm using the latest version is 5.0.0

**Comment by rodriguezmanu** [comment]
+1

**Comment by JianhuisHuang** [comment]
Same issue, any news? I'm using the plugin version is 2.0.1 and ionic 4

**Comment by lonwi** [comment]
I can see this was reported multiple times and the logout does not work properly on android.

**Comment by iamqinglong** [comment]
any news for this? it's frustrating.
