### ISSUE TITLE
Login is extremely slow on Android

### ISSUE THREAD

**Issue by remisture** [jeduan/cordova-plugin-facebook4#594]
Has anyone else experienced that logging on Android is suddenly extremely slow? Like several minutes?

Any ideas what might be the problem? This has worked perfectly fine for 6 months.

**Comment by remisture** [comment]
Anyone?

**Comment by MrRobWad** [comment]
I'm also seeing this issue, specifically on Android. Taking up to 2-3 minutes.

**Comment by lcya86** [comment]
Same issue

**Comment by peterpeterparker** [comment]
Plz use other channels like Stackoverflow for support inquiry

P.S.: I test every single version of my app and the plugin with real devices Android v7 and v8, never had this issue
