### ISSUE TITLE
How to destroy login information after uninstall the app  

### ISSUE THREAD

**Issue by riaydh06** [jeduan/cordova-plugin-facebook4#596]
I try to destroy login information after uninstall the cordova app but I don't see any documentation here. How can I fix it?

**Comment by shriswissfed** [comment]
First you have to getlogin status and if it is connected ,then you have to call logout().
this.fb.getLoginStatus().then((data) => {
          console.log('fb', data);
          if (data.status == 'connected') {

            this.fb.logout().then(data => {
              console.log(data, 'fb logged out');
              this.storage.remove('login_via').then(done => {
                console.log('all data removed');
                this.loading.dismiss();
              })
            }).catch(err => { console.log(err, 'error in fb logout') });

          }
        }).catch(err => { console.log(err, 'error in getting fb status') });

**Comment by DaveNguyenHuy** [comment]
I call facebookConnectPlugin.logout(successFunction, errorFunction), the success function worked, but when I close the App and Login again, my FB account is still on the app, I cannot logout and use other account :(

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out the actively maintained fork `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect. If you're still experiencing issues with logout, feel free to log a new issue there with more details.
