### ISSUE TITLE
When run android "Could not find com.android.support:support-v4:27.0.1."

### ISSUE THREAD

**Issue by Theng** [jeduan/cordova-plugin-facebook4#597]
I am using ionic 3 when I try to build my project to android it show the message "Could not find com.android.support:support-v4:27.0.1."

Full message:
```

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not find com.android.support:support-v4:27.0.1.
     Searched in the following locations:
         file:/Users/cglt_0029/Library/Android/sdk/extras/android/m2repository/com/android/support/support-v4/27.0.1/support-v4-27.0.1.pom
         file:/Users/cglt_0029/Library/Android/sdk/extras/android/m2repository/com/android/support/support-v4/27.0.1/support-v4-27.0.1.jar
         file:/Users/cglt_0029/Desktop/hybrid-mobile-loyalty/platforms/android/sdk-manager/com/android/support/support-v4/27.0.1/support-v4-27.0.1.jar
     Required by:
         project :
   > Could not find com.android.support:support-v4:27.0.1.
     Searched in the following locations:
         file:/Users/cglt_0029/Library/Android/sdk/extras/android/m2repository/com/android/support/support-v4/27.0.1/support-v4-27.0.1.pom
         file:/Users/cglt_0029/Library/Android/sdk/extras/android/m2repository/com/android/support/support-v4/27.0.1/support-v4-27.0.1.jar
         file:/Users/cglt_0029/Desktop/hybrid-mobile-loyalty/platforms/android/sdk-manager/com/android/support/support-v4/27.0.1/support-v4-27.0.1.jar
     Required by:
         project :
   > Could not find com.android.support:appcompat-v7:27.0.1.
     Searched in the following locations:
         file:/Users/cglt_0029/Library/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/27.0.1/appcompat-v7-27.0.1.pom
         file:/Users/cglt_0029/Library/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/27.0.1/appcompat-v7-27.0.1.jar
         file:/Users/cglt_0029/Desktop/hybrid-mobile-loyalty/platforms/android/sdk-manager/com/android/support/appcompat-v7/27.0.1/appcompat-v7-27.0.1.jar
     Required by:
         project :
   > Could not find com.android.support:customtabs:27.0.1.
     Searched in the following locations:
         file:/Users/cglt_0029/Library/Android/sdk/extras/android/m2repository/com/android/support/customtabs/27.0.1/customtabs-27.0.1.pom
         file:/Users/cglt_0029/Library/Android/sdk/extras/android/m2repository/com/android/support/customtabs/27.0.1/customtabs-27.0.1.jar
         file:/Users/cglt_0029/Desktop/hybrid-mobile-loyalty/platforms/android/sdk-manager/com/android/support/customtabs/27.0.1/customtabs-27.0.1.jar
     Required by:
         project : > com.onesignal:OneSignal:3.5.7
   > Could not find com.android.support:support-v4:27.0.1.
     Searched in the following locations:
         file:/Users/cglt_0029/Library/Android/sdk/extras/android/m2repository/com/android/support/support-v4/27.0.1/support-v4-27.0.1.pom
         file:/Users/cglt_0029/Library/Android/sdk/extras/android/m2repository/com/android/support/support-v4/27.0.1/support-v4-27.0.1.jar
         file:/Users/cglt_0029/Desktop/hybrid-mobile-loyalty/platforms/android/sdk-manager/com/android/support/support-v4/27.0.1/support-v4-27.0.1.jar
     Required by:
         project : > com.google.android.gms:play-services-maps:11.0.4 > com.google.android.gms:play-services-basement:11.0.4
   > Could not find com.android.support:support-annotations:27.0.1.
     Searched in the following locations:
         file:/Users/cglt_0029/Library/Android/sdk/extras/android/m2repository/com/android/support/support-annotations/27.0.1/support-annotations-27.0.1.pom
         file:/Users/cglt_0029/Library/Android/sdk/extras/android/m2repository/com/android/support/support-annotations/27.0.1/support-annotations-27.0.1.jar
         file:/Users/cglt_0029/Desktop/hybrid-mobile-loyalty/platforms/android/sdk-manager/com/android/support/support-annotations/27.0.1/support-annotations-27.0.1.jar
     Required by:
         project : > com.facebook.android:facebook-android-sdk:4.29.0 > com.facebook.android:facebook-core:4.29.0
   > Could not find com.android.support:support-core-utils:27.0.1.
     Searched in the following locations:
         file:/Users/cglt_0029/Library/Android/sdk/extras/android/m2repository/com/android/support/support-core-utils/27.0.1/support-core-utils-27.0.1.pom
         file:/Users/cglt_0029/Library/Android/sdk/extras/android/m2repository/com/android/support/support-core-utils/27.0.1/support-core-utils-27.0.1.jar
         file:/Users/cglt_0029/Desktop/hybrid-mobile-loyalty/platforms/android/sdk-manager/com/android/support/support-core-utils/27.0.1/support-core-utils-27.0.1.jar
     Required by:
         project : > com.facebook.android:facebook-android-sdk:4.29.0 > com.facebook.android:facebook-core:4.29.0
   > Could not find com.android.support:appcompat-v7:27.0.1.
     Searched in the following locations:
         file:/Users/cglt_0029/Library/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/27.0.1/appcompat-v7-27.0.1.pom
         file:/Users/cglt_0029/Library/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/27.0.1/appcompat-v7-27.0.1.jar
         file:/Users/cglt_0029/Desktop/hybrid-mobile-loyalty/platforms/android/sdk-manager/com/android/support/appcompat-v7/27.0.1/appcompat-v7-27.0.1.jar
     Required by:
         project : > com.facebook.android:facebook-android-sdk:4.29.0 > com.facebook.android:facebook-common:4.29.0
   > Could not find com.android.support:cardview-v7:27.0.1.
     Searched in the following locations:
         file:/Users/cglt_0029/Library/Android/sdk/extras/android/m2repository/com/android/support/cardview-v7/27.0.1/cardview-v7-27.0.1.pom
         file:/Users/cglt_0029/Library/Android/sdk/extras/android/m2repository/com/android/support/cardview-v7/27.0.1/cardview-v7-27.0.1.jar
         file:/Users/cglt_0029/Desktop/hybrid-mobile-loyalty/platforms/android/sdk-manager/com/android/support/cardview-v7/27.0.1/cardview-v7-27.0.1.jar
     Required by:
         project : > com.facebook.android:facebook-android-sdk:4.29.0 > com.facebook.android:facebook-common:4.29.0
   > Could not find com.android.support:customtabs:27.0.1.
     Searched in the following locations:
         file:/Users/cglt_0029/Library/Android/sdk/extras/android/m2repository/com/android/support/customtabs/27.0.1/customtabs-27.0.1.pom
         file:/Users/cglt_0029/Library/Android/sdk/extras/android/m2repository/com/android/support/customtabs/27.0.1/customtabs-27.0.1.jar
         file:/Users/cglt_0029/Desktop/hybrid-mobile-loyalty/platforms/android/sdk-manager/com/android/support/customtabs/27.0.1/customtabs-27.0.1.jar
     Required by:
         project : > com.facebook.android:facebook-android-sdk:4.29.0 > com.facebook.android:facebook-common:4.29.0
   > Could not find com.android.support:support-v4:27.0.1.
     Searched in the following locations:
         file:/Users/cglt_0029/Library/Android/sdk/extras/android/m2repository/com/android/support/support-v4/27.0.1/support-v4-27.0.1.pom
         file:/Users/cglt_0029/Library/Android/sdk/extras/android/m2repository/com/android/support/support-v4/27.0.1/support-v4-27.0.1.jar
         file:/Users/cglt_0029/Desktop/hybrid-mobile-loyalty/platforms/android/sdk-manager/com/android/support/support-v4/27.0.1/support-v4-27.0.1.jar
     Required by:
         project : > com.facebook.android:facebook-android-sdk:4.29.0 > com.facebook.android:facebook-common:4.29.0
```

**Comment by debajyotiwgt** [comment]
i face same problem

**Comment by ahuviy** [comment]
me too

**Comment by alexvibealex** [comment]
Please try this : https://forum.ionicframework.com/t/run-android-platform-error-with-cordova-plugin-facebook4/114510/11?u=alexvibealex

**Comment by peterpeterparker** [comment]
(copy of my post on the Ionic forum):

Just tried to build my app. I noticed a lot of unexpected downloads (see log here under) but the build went thru with success

Would you like to give a try again? Maybe these libs weren't published when you tried earlier today?


> Download https://jcenter.bintray.com/com/facebook/android/facebook-android-sdk/maven-metadata.xml
> Download https://jcenter.bintray.com/com/facebook/android/facebook-android-sdk/4.29.0/facebook-android-sdk-4.29.0.pom
> Download https://jcenter.bintray.com/com/facebook/android/facebook-core/4.29.0/facebook-core-4.29.0.pom
> Download https://jcenter.bintray.com/com/facebook/android/facebook-login/4.29.0/facebook-login-4.29.0.pom
> Download https://jcenter.bintray.com/com/facebook/android/facebook-share/4.29.0/facebook-share-4.29.0.pom
> Download https://jcenter.bintray.com/com/facebook/android/facebook-common/4.29.0/facebook-common-4.29.0.pom
> Download https://jcenter.bintray.com/com/facebook/android/facebook-places/4.29.0/facebook-places-4.29.0.pom
> Download https://jcenter.bintray.com/com/facebook/android/facebook-applinks/4.29.0/facebook-applinks-4.29.0.pom
> Download https://jcenter.bintray.com/com/facebook/android/facebook-messenger/4.29.0/facebook-messenger-4.29.0.pom
> Download https://maven.google.com/com/android/support/support-core-utils/27.0.1/support-core-utils-27.0.1.pom
> Download https://maven.google.com/com/android/support/cardview-v7/27.0.1/cardview-v7-27.0.1.pom
> Download https://maven.google.com/com/android/support/customtabs/27.0.1/customtabs-27.0.1.pom
> 
> Download https://maven.google.com/com/android/support/support-compat/27.0.1/support-compat-27.0.1.pom
> Download https://maven.google.com/com/android/support/support-v4/27.0.1/support-v4-27.0.1.pom
> Download https://maven.google.com/com/android/support/support-fragment/27.0.1/support-fragment-27.0.1.pom
> Download https://maven.google.com/com/android/support/support-core-ui/27.0.1/support-core-ui-27.0.1.pom
> 
> Download https://maven.google.com/com/android/support/support-media-compat/27.0.1/support-media-compat-27.0.1.pom
> Download https://maven.google.com/com/android/support/support-annotations/27.0.1/support-annotations-27.0.1.pom
> 
> Download https://maven.google.com/com/android/support/appcompat-v7/27.0.1/appcompat-v7-27.0.1.pom
> Download https://maven.google.com/com/android/support/support-vector-drawable/27.0.1/support-vector-drawable-27.0.1.pom
> Download https://maven.google.com/com/android/support/animated-vector-drawable/27.0.1/animated-vector-drawable-27.0.1.pom
> 
> Download https://jcenter.bintray.com/com/facebook/android/facebook-login/4.29.0/facebook-login-4.29.0.aar
> 
> Download https://jcenter.bintray.com/com/facebook/android/facebook-android-sdk/4.29.0/facebook-android-sdk-4.29.0.aar
> 
> Download https://jcenter.bintray.com/com/facebook/android/facebook-share/4.29.0/facebook-share-4.29.0.aar
> 
> Download https://jcenter.bintray.com/com/facebook/android/facebook-common/4.29.0/facebook-common-4.29.0.aar
> 
> Download https://maven.google.com/com/android/support/appcompat-v7/27.0.1/appcompat-v7-27.0.1.aar
> 
> Download https://maven.google.com/com/android/support/support-v4/27.0.1/support-v4-27.0.1.aar
> Download https://jcenter.bintray.com/com/facebook/android/facebook-applinks/4.29.0/facebook-applinks-4.29.0.aar
> 
> Download https://jcenter.bintray.com/com/facebook/android/facebook-places/4.29.0/facebook-places-4.29.0.aar
> 
> Download https://jcenter.bintray.com/com/facebook/android/facebook-messenger/4.29.0/facebook-messenger-4.29.0.aar
> 
> Download https://jcenter.bintray.com/com/facebook/android/facebook-core/4.29.0/facebook-core-4.29.0.aar
> 
> Download https://maven.google.com/com/android/support/support-fragment/27.0.1/support-fragment-27.0.1.aar
> 
> Download https://maven.google.com/com/android/support/support-core-utils/27.0.1/support-core-utils-27.0.1.aar
> 
> Download https://maven.google.com/com/android/support/support-media-compat/27.0.1/support-media-compat-27.0.1.aar
> 
> Download https://maven.google.com/com/android/support/cardview-v7/27.0.1/cardview-v7-27.0.1.aar
> 
> Download https://maven.google.com/com/android/support/customtabs/27.0.1/customtabs-27.0.1.aar
> 
> Download https://maven.google.com/com/android/support/animated-vector-drawable/27.0.1/animated-vector-drawable-27.0.1.aar
> 
> Download https://maven.google.com/com/android/support/support-core-ui/27.0.1/support-core-ui-27.0.1.aar
> 
> Download https://maven.google.com/com/android/support/support-vector-drawable/27.0.1/support-vector-drawable-27.0.1.aar
> 
> Download https://maven.google.com/com/android/support/support-compat/27.0.1/support-compat-27.0.1.aar

**Comment by torstahl** [comment]
me too

**Comment by Mykiee** [comment]
You can get it working by changing

`<framework src="com.facebook.android:facebook-android-sdk:4+"/>`
to 
`<framework src="com.facebook.android:facebook-android-sdk:4.26.0"/>`
in **plugin.xml** of plugin located in **/plugins/cordova-plugin-facebook4**

and overwrite
`compile "com.facebook.android:facebook-android-sdk:4.+"`
with
`compile "com.facebook.android:facebook-android-sdk:4.26.0"`
both in **/platforms/android/build.gradle** and **/platforms/android/project.properties** in your cordova or ionic project.

Thanks

**Comment by sfarzo** [comment]
Same problem here. A workaround has been the @Mykiee  suggestion, but is not the solution for me. Thanks.

**Comment by rmvgaines** [comment]
@Mykiee Why 4.26.0 instead of 4.28.0?

**Comment by jasonandress** [comment]
@Mykiee suggestion fixed my issue.

It looks like facebook released version facebook-android-sdk:4.29.0 which is somehow breaking the build (haven't updated their docs as well). Based on the logs some other components are not available. Unfortunately it has affected us since this plugin.xml didn't locking down the version.

@rmvgaines I kind of agree with your logic of going with 4.28.0 because if you've compiled your app since 11/7, especially on PGB you're already using that version.

I may go through all of my plugins and check their dependencies for this sort of thing. It's bit me twice before.

**Comment by Mykiee** [comment]
@rmvgaines Because v4.28.0 was also breaking my code while building the ionic/cordova application at ':processDebugResources' that why I needed to downgrade my version to 4.26.0. But that doen't mean we need to get it fixed at 4.26.0, I would suggest to use version as close as possible to the latest (if it does not breaks the code).

**Comment by citadelind01** [comment]
<framework src="com.facebook.android:facebook-android-sdk:4.14.+"/>

just replace above in plugin.xml file of facebook. it is working perfectly.

Thanks

**Comment by gregor-srdic** [comment]
i believe installing this plugin https://github.com/dpa99c/cordova-android-support-gradle-release solved this issue for me.

```
    <plugin name="cordova-android-support-gradle-release" spec="^1.1.5">
        <variable name="ANDROID_SUPPORT_VERSION" value="25.+" />
    </plugin>
```
cordova (Cordova CLI) : 7.1.0
 Cordova Platforms  : android 6.2.3

**Comment by scottcarter87** [comment]
@gregor-srdic's suggestion plus...

`sudo chmod 755 /Applications/Android\ Studio.app/Contents/gradle/gradle-XXX/bin/gradle`

for Android Studio 3.0.1 and now I am back in business.

**Comment by Sampath-Lokuge** [comment]
Thank you Sir @Mykiee You saved my day!

**Comment by Erbolking** [comment]
@Mykiee Thanks a lot man

**Comment by cusspvz** [comment]
So, should't the plugin be changed as well?
https://github.com/jeduan/cordova-plugin-facebook4/blob/master/plugin.xml#L63

**Comment by AASH1234** [comment]
In the project level gradle file, under allproject repositories write  jcenter() below maven { url 'https://maven.google.com' }. If those are not written the write. That might be the solution.

**Comment by krischik** [comment]
Same here!

**Comment by krischik** [comment]
> In the project level gradle file, under allproject repositories write jcenter() below maven { url 'https://maven.google.com' }. If those are not written then include those. That might be the solution.

Thanks. Correct order of repositories does the trick.

@everyone : the google repositories to the top 

```
   repositories {
	 google ()
	 maven {
	    url "https://maven.google.com/"
	 } // maven
```
one of the two should be enough.
