### ISSUE TITLE
publish updates to your local apk from local development server

### ISSUE THREAD

**Issue by Heena-Vora** [jeduan/cordova-plugin-facebook4#604]
hello all,
i am working on an ionic app. I've created an APK for it. I want my app to receive updates as soon as i make changes in my code. Just like app updates from play store, but it will be local.
I'm using **ionic cli** **ionic-3** 

can any one help me with this?

[plugin](https://github.com/nordnet/cordova-hot-code-push/wiki/Local-Development-Plugin)

will it be helpful to fulfill my purpose for apk updates?

**Comment by peterpeterparker** [comment]
This has nothing todo with this plugin

Plz use stackoverflow or the ionic forum to post your question
