### ISSUE TITLE
Error codes for login

### ISSUE THREAD

**Issue by dland512** [jeduan/cordova-plugin-facebook4#605]
What are the possible values for the argument to the failure handler for the `login` method?

```
facebookConnectPlugin.login(someData, fbLoginSuccess, loginError(error) {
    // what are the possible values of error?
});
```

On android, I get this an object like this:
```
{
    errorCode: "4201",
    errorMessage: "User cancelled dialog"
}
```

On iOS I get a string like this:

`"User cancelled."`

I want to be able to show the user an error when a true error has occurred, such as when there is a networking issue. I do not want to show the user an error when they simply close the dialog. So I need to be able to distinguish between these issues. Is there any documentation on the relevant error codes and error strings?

**Comment by speedfl** [comment]
I was asking me the same question. Some of my tester have issues with login. And I am not able to handle them properly. They just my generic error.

**Comment by g4-KN** [comment]
yeah, we are having the same problem as well

**Comment by expcapitaldev** [comment]
const errorString: string | undefined = error ? error.toString() : undefined;
if (errorString && errorString.indexOf("User cancelled") > -1) {
						// do nothing, popup closed by user
					}

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect. The next major release of that plugin updates the error callback on iOS to return an object like on Android. If the `errorCode` returned is "4201", that means the user clicked "Cancel". Any other `errorCode` can be considered a true error.
