### ISSUE TITLE
Does not add app-id or app-name to the android manifest

### ISSUE THREAD

**Issue by runezor** [jeduan/cordova-plugin-facebook4#609]
Adding
<string name="fb_app_id">...</string>
<string name="fb_app_name">...</string>
to platforms/android/app/src/main/res/values/strings.xml fixes this, though it would be nice to have to do without it.

**Comment by valmirphp** [comment]
Tenta adicionar no seu config.xml

<platform name="android">
    <config-file parent="/resources" target="./res/values/strings.xml">
        <string name="fb_app_id">1234</string>
        <string name="fb_app_name">foobar</string>
    </config-file>

**Comment by peterpeterparker** [comment]
See Android Guide
