### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by sergiiy-oliynik** [jeduan/cordova-plugin-facebook4#617]
Hi, all. Now I'm trying to compile simple cordova project and I've got exeption:

Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not find com.android.support:support-annotations:27.0.2.
     Searched in the following locations:
         file:/E:/Work/Android/SDK/extras/android/m2repository/com/android/support/support-annotations/27.0.2/support-annotations-27.0.2.pom
         file:/E:/Work/Android/SDK/extras/android/m2repository/com/android/support/support-annotations/27.0.2/support-annotations-27.0.2.jar
         file:/E:/Work/cordova-fb/mobile/platforms/android/sdk-manager/com/android/support/support-annotations/27.0.2/support-annotations-27.0.2.jar
     Required by:
         project : > com.facebook.android:facebook-android-sdk:4.30.0 > com.facebook.android:facebook-core:4.30.0
   > Could not find com.android.support:support-core-utils:27.0.2.
     Searched in the following locations:
         file:/E:/Work/Android/SDK/extras/android/m2repository/com/android/support/support-core-utils/27.0.2/support-core-utils-27.0.2.pom
         file:/E:/Work/Android/SDK/extras/android/m2repository/com/android/support/support-core-utils/27.0.2/support-core-utils-27.0.2.jar
         file:/E:/Work/cordova-fb/mobile/platforms/android/sdk-manager/com/android/support/support-core-utils/27.0.2/support-core-utils-27.0.2.jar
     Required by:
         project : > com.facebook.android:facebook-android-sdk:4.30.0 > com.facebook.android:facebook-core:4.30.0
   > Could not find com.android.support:support-v4:27.0.2.
     Searched in the following locations:
         file:/E:/Work/Android/SDK/extras/android/m2repository/com/android/support/support-v4/27.0.2/support-v4-27.0.2.pom
         file:/E:/Work/Android/SDK/extras/android/m2repository/com/android/support/support-v4/27.0.2/support-v4-27.0.2.jar
         file:/E:/Work/cordova-fb/mobile/platforms/android/sdk-manager/com/android/support/support-v4/27.0.2/support-v4-27.0.2.jar
     Required by:
         project : > com.facebook.android:facebook-android-sdk:4.30.0 > com.facebook.android:facebook-common:4.30.0
   > Could not find com.android.support:appcompat-v7:27.0.2.
     Searched in the following locations:
         file:/E:/Work/Android/SDK/extras/android/m2repository/com/android/support/appcompat-v7/27.0.2/appcompat-v7-27.0.2.pom
         file:/E:/Work/Android/SDK/extras/android/m2repository/com/android/support/appcompat-v7/27.0.2/appcompat-v7-27.0.2.jar
         file:/E:/Work/cordova-fb/mobile/platforms/android/sdk-manager/com/android/support/appcompat-v7/27.0.2/appcompat-v7-27.0.2.jar
     Required by:
         project : > com.facebook.android:facebook-android-sdk:4.30.0 > com.facebook.android:facebook-common:4.30.0
         project : > com.facebook.android:facebook-android-sdk:4.30.0 > com.facebook.android:facebook-login:4.30.0
   > Could not find com.android.support:cardview-v7:27.0.2.
     Searched in the following locations:
         file:/E:/Work/Android/SDK/extras/android/m2repository/com/android/support/cardview-v7/27.0.2/cardview-v7-27.0.2.pom
         file:/E:/Work/Android/SDK/extras/android/m2repository/com/android/support/cardview-v7/27.0.2/cardview-v7-27.0.2.jar
         file:/E:/Work/cordova-fb/mobile/platforms/android/sdk-manager/com/android/support/cardview-v7/27.0.2/cardview-v7-27.0.2.jar
     Required by:
         project : > com.facebook.android:facebook-android-sdk:4.30.0 > com.facebook.android:facebook-common:4.30.0
   > Could not find com.android.support:customtabs:27.0.2.
     Searched in the following locations:
         file:/E:/Work/Android/SDK/extras/android/m2repository/com/android/support/customtabs/27.0.2/customtabs-27.0.2.pom
         file:/E:/Work/Android/SDK/extras/android/m2repository/com/android/support/customtabs/27.0.2/customtabs-27.0.2.jar
         file:/E:/Work/cordova-fb/mobile/platforms/android/sdk-manager/com/android/support/customtabs/27.0.2/customtabs-27.0.2.jar
     Required by:
         project : > com.facebook.android:facebook-android-sdk:4.30.0 > com.facebook.android:facebook-common:4.30.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Can anybody helps me? Thanks!

**Comment by adrianowead** [comment]
Hi,

I have the same issue, I did solve it adding Google Maven URL on **build.gradle**

Change:

```gradle
// Allow plugins to declare Maven dependencies via build-extras.gradle.
allprojects {
    repositories {
        mavenCentral();
        jcenter()
    }
}
```

To:

```gradle
// Allow plugins to declare Maven dependencies via build-extras.gradle.
allprojects {
    repositories {
        mavenCentral();
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }
}
```

Adctionally you may change project.properties file, update **target=android-25** to **target=android-26**

**Comment by adrianowead** [comment]
After update these files, re-run build command.
On first time all dependencies will be downloaded, and project will be compiled.

**Comment by anshsoni143** [comment]
Now it give another error

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple
 dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat;

**Comment by adrianowead** [comment]
To solve it, remove all folders inside platforms/android/build.

- generated
- intermediates
- outputs
- tmp

It will clean all old compiled binaries, and rebuild all.

Alternatively, ou can try remove android platform and re-add it again.

```shell
$ ionic cordova platform remove android

$ ionic cordova platform add android
```

**Comment by anshsoni143** [comment]
Already did this but still same error and FYI i have android@6.3.0

**Comment by adrianowead** [comment]
Maybe this is the problem.
Because my android project version is 6.2.3, and works well.

**Comment by anshsoni143** [comment]
changed my android platform to 6.2.3
cordova platform add android@6.2.3 same error exist

:transformClassesWithJarMergingForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/v4/print/PrintHelper$1.class

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 11.743 secs
(node:6552) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/v4/print/PrintHelper$1.class

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by anshsoni143** [comment]
Fixed it by changing the build.gradle and adding this line
configurations {
            all*.exclude group: 'com.android.support', module: 'support-v4'
        }

in 
allprojects {
    configurations {
            all*.exclude group: 'com.android.support', module: 'support-v4'
        }
    repositories {
        mavenCentral();
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }
}

**Comment by viking2917** [comment]
I have this problem in Cordova 7, it appears in relation to the Barcode Scanner plugin. I filed an issue with that although I am not sure which plugin may be at fault, if either. (https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/606). The solution of @anshsoni143 does not seem to work for me.

**Comment by jarekskuder** [comment]
Same here

**Comment by jarekskuder** [comment]
Ok guys, i fixed it like this:

1) As @anshsoni143 sayd i added 
maven {
url "https://maven.google.com"
}
Then i tried to build it again, it started to download some packages and again i get errors. This time they are like this:
AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

2) I changed my compileSdkVersion and buildToolsVersion in build.gradle:
compileSdkVersion 26
buildToolsVersion "26.0.1"

And it worked

**Comment by anshsoni143** [comment]
@jarekskuder I also have did that it was for another error not for this issue anyone else having same issue can do 

On windows machine
set ORG_GRADLE_PROJECT_cdvCompileSdkVersion=android-26
set ORG_GRADLE_PROJECT_cdvBuildToolsVersion=26.0.1

Make sure you have these libraries installed

**Comment by jesse1981** [comment]
Can this be resolved outside of Android Studio via Phonegap/Build?

**Comment by Baburaomannepalli** [comment]
i have to faced the same issue and resolved it

you can add the code in bandle.gradle file

allprojects {
    repositories {
        mavenCentral();
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }
}

**Comment by A110SHT** [comment]
Hello,
When i use this plugin i get the error i try to fix the error from above discussion. Now i cannot solve the error. 
 
![screenshot 6](https://user-images.githubusercontent.com/26458033/39045715-5c063cf2-44b3-11e8-851f-0bf1d969c0b9.png)
how to slove this problem.

**Comment by Baburaomannepalli** [comment]
hi! first check the android version(26) android SDK manager after that install on facebook4 plugin

**Comment by peterpeterparker** [comment]
This is most probably a conflict with the Android SDK version

See for example #550

For support questions plz use other channels like Stackoverflow or Ionic forum

**Comment by Baburaomannepalli** [comment]
hi,currently which varsion u have used in Android SDK.cordova-plugin-facebook4 ,this plug in works on Android SDK(26) only

**Comment by A110SHT** [comment]
Baburaomannepalli ok thankyou for reply ok i will update my Android SDK.  What if i update the android sdk greater than 26 is it work on.

**Comment by peterpeterparker** [comment]
@gregavola I've got no idea to be really honest with you. You should try to post a support question on Stackoverflow for example, maybe someone with more know-how will be able to help you

**Comment by gregavola** [comment]
@peterpeterparker Sorry about that, I figured it out - conflict with Android Support problems. Sorry for pinging, thanks for your support!

**Comment by peterpeterparker** [comment]
@gregavola no worries, cool to hear you found a solution, well done 😃
