### ISSUE TITLE
Can't use with Crosswalk(v2.1.0, minsdk 16)

### ISSUE THREAD

**Issue by usmakas** [jeduan/cordova-plugin-facebook4#619]
I can't build my app via PhoneGap Build when use cordova-plugin-facebook4 and crosswalk plugin. It display error below.

crosswalk plugin: minSdk version 16
cordova-plugin-facebook4 : minSdk version 15 

..................................................................................................................................
My Configuration
..................................................................................................................................

preference name="phonegap-version" value="cli-7.1.0" />
gap:plugin name="cordova-plugin-facebook4" source="npm" spec="1.7.4">
    param name="APP_ID" value="=" />
    param name="APP_NAME" value="=" />
  /gap:plugin>
gap:plugin name='cordova-plugin-crosswalk-webview' source='npm' spec='2.1.0'/>

PhoneGap (iOS / Android / Windows)
cli-7.1.0 (4.5.4 / 6.3.0 / 5.0.0)

..................................................................................................................................
Error Log from PhoneGap Build
..................................................................................................................................
:mergeArmv7DebugAssets
:createXwalkCommandLineFileArmv7Debug
:generateArmv7DebugResValues
:generateArmv7DebugResources
:mergeArmv7DebugResources
:processArmv7DebugManifest/AndroidManifest.xml:39:5-74 Error:
	uses-sdk:minSdkVersion 15 cannot be smaller than version 16 declared in library [org.xwalk:xwalk_core_library:21.51.546.7] /build/intermediates/exploded-aar/org.xwalk/xwalk_core_library/21.51.546.7/AndroidManifest.xml
	Suggestion: use tools:overrideLibrary="org.xwalk.core" to force usage

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

:processArmv7DebugManifest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processArmv7DebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 15 cannot be smaller than version 16 declared in library [org.xwalk:xwalk_core_library:21.51.546.7] /build/intermediates/exploded-aar/org.xwalk/xwalk_core_library/21.51.546.7/AndroidManifest.xml
  	Suggestion: use tools:overrideLibrary="org.xwalk.core" to force usage

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 11.025 secs
Error: /gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/AndroidManifest.xml:39:5-74 Error:
	uses-sdk:minSdkVersion 15 cannot be smaller than version 16 declared in library [org.xwalk:xwalk_core_library:21.51.546.7] /build/intermediates/exploded-aar/org.xwalk/xwalk_core_library/21.51.546.7/AndroidManifest.xml
	Suggestion: use tools:overrideLibrary="org.xwalk.core" to force usage

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processArmv7DebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 15 cannot be smaller than version 16 declared in library [org.xwalk:xwalk_core_library:21.51.546.7] /build/intermediates/exploded-aar/org.xwalk/xwalk_core_library/21.51.546.7/AndroidManifest.xml
  	Suggestion: use tools:overrideLibrary="org.xwalk.core" to force usage

**Comment by fredgalvao** [comment]
Specify `<preference name="android-minSdkVersion" value="16" />` on your `config.xml` and test again.

**Comment by peterpeterparker** [comment]
Crosswalk is deprecated therefore I close this issue
