### ISSUE TITLE
logPurchase and logEvent doesn't send value

### ISSUE THREAD

**Issue by jarekskuder** [jeduan/cordova-plugin-facebook4#620]
In my app when i pay for parking i want to log purchase. But when i try to logPurchase or logEvent all info comes to facebook analytics but no value. 

My code:

```
facebookConnectPlugin.logPurchase(parseFloat(CurrentAmount), selected_country.currency_code, function (data) {
       console.log(data);
}, function (error) {
       console.log(error);
});
facebookConnectPlugin.logEvent('Pay for parking', null, parseFloat(CurrentAmount), function (data) {
       onsole.log(data);
 }, function (error) {
       console.log(error);
});
```

CurrentAmount is a string like 0.2000
selected_country.currency_code is a currency code in ISO format like EUR

I need only logPurchase, but when i saw that value isn't coming i tried to logEvent with valueToSum parameter, but it didn't send value to analytics...

**Comment by jarekskuder** [comment]
Ok now i understand that it sends only first number, example if i send 1.78, it will send 1, or if its 0.20 it will send 0. So why i can't send float numbers?

**Comment by peterpeterparker** [comment]
Probably a wrong number casting somewhere according your last msg. Feel free to submit a PR to fix the problem, thx in advance
