### ISSUE TITLE
Build failed for ionic with this plugin

### ISSUE THREAD

**Issue by alexvibealex** [jeduan/cordova-plugin-facebook4#622]
ionic info : 
cli packages: (npm\node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v6.11.3
    npm  : 3.10.10
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

Followed this tip : https://github.com/jeduan/cordova-plugin-facebook4/issues/609
and this one too : https://github.com/jeduan/cordova-plugin-facebook4/issues/617 

But none is helping out .

Whenever I remove facebook plugin build succeeds  .
Can anyone please share a full proof solution to this problem .Really got stuck on this .

**Comment by ojgenn** [comment]
we have the same problem

**Comment by ojgenn** [comment]
solved it by adding to config.xml

**Comment by alexvibealex** [comment]
Thanks @ojgenn ,but I have already tried this and app id and app name were added to the respective xml file. 
But after that im getting this new error : 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex


Any idea why is that appearing now?

**Comment by alexvibealex** [comment]
Resolved need to run 

`cordova clean`

**Comment by hiepxanh** [comment]
thank you @alexvibealex
