### ISSUE TITLE
Plugin conflict with barecode-scanner

### ISSUE THREAD

**Issue by speedfl** [jeduan/cordova-plugin-facebook4#623]
Hello.

Facebook added a dependency to ``` com/google/zxing``` which is used for barecode scanning.
This has been added certainly because facebook has a qrcode integrated to its app...

Anyway it could be nice if we can ignore this by adding a custom build.gradle to ignore it.

```
dependencies {
	compile ("com.facebook.android:facebook-android-sdk:4+"){
        exclude group: 'com.google.zxing'
    }
}
```
Here is a demo of a custom build.gradle

https://github.com/zyra/cordova-plugin-linkedin/blob/master/src/android/LinkedIn.gradle

Regards

Geoffrey MUSELLI

**Comment by yurik94** [comment]
@speedfl same issue here, a few months ago :D

**Comment by speedfl** [comment]
You can do what I suggest manually.
You create a gradle dependencies and in your project.properties instead of pointing to android sdk you point to this dependency file.

**Comment by peterpeterparker** [comment]
This is most probably a conflict with the Android SDK version

See for example #550

For support questions plz use other channels like Stackoverflow or Ionic forum
