### ISSUE TITLE
Fail to make it work in Phonegap

### ISSUE THREAD

**Issue by cszasz** [jeduan/cordova-plugin-facebook4#625]
I am a bit new in cordova, phonegap and ios development, but I managed to solved most of the issues so far. But not this time.

What I am trying to do is to integrate with Facebook for single-sign-on.

I am using cordova and testing it from my from with Phonegap.
I installed this plugin and what I experience is that it works fine in the browser but when I test it in my mobile using Phonegap the facebookConnectPlugin does not initialize.

Any idea what's wrong?

**Comment by jeduan** [comment]
Ask for help in stackoverflow
