### ISSUE TITLE
showDialog [read more] being converted to @2131766245

### ISSUE THREAD

**Issue by ediboy** [jeduan/cordova-plugin-facebook4#627]
Hi Guys,

I was using showDiaglog with a long description but seems like the [read more] is converted to @2131766245. Please see the screenshot.

Anyone encountered the same problem?

I'm using ionic 3 and running in Android 7.1.1

Thanks in advance!
![28547523_1847827968625335_1736216722_o](https://user-images.githubusercontent.com/8133093/36667242-30c5f2ee-1b28-11e8-95bc-b488acd46be6.png)
![28499735_1847827955292003_499099440_o](https://user-images.githubusercontent.com/8133093/36667244-3108459a-1b28-11e8-848d-f476361aac5a.jpg)

**Comment by peterpeterparker** [comment]
Plz use other channels like Stackoverflow or Ionic forum for support inquiry, thx
