### ISSUE TITLE
README... future plugin updates

### ISSUE THREAD

**Issue by matteobattista** [jeduan/cordova-plugin-facebook4#629]
Relate to old post: "Please consider the pull requests #616"

The owner of the plugin @jeduan has commented 27 days ago:

"Hey guys. Yeah, I’m no longer using Cordova and so I don’t  plan on mantaining this project anymore. If one of you is interested I  can give you write access or transfer ownership to a org."

Now the question... is someone can/would be interested to the ownership?

Please comment this post to understand his future

Thank you!

**Comment by jackvial** [comment]
Doesn't sound like there are many takers!

**Comment by deliverymanager** [comment]
This is a huge thing!
This plugin is so widely used...
It is also one of the most important plugins for an app.
I really cannot think of not having a stable cordova plugin for Facebook.
I mean it is Facebook...
It is not some random sdk...
I hope there will be a leader to be able to handle this huge plugin.

**Comment by jeduan** [comment]
The plugin itself is less than 1000 lines of code per platform. Pretty small.

**Comment by jacquesdev** [comment]
@jeduan, in that case, is there any chance you can maintain it for a while longer? Pretty please :) :)

**Comment by mlynch** [comment]
We're looking into the possibility of something like that, though probably not maintaining this specific project as we'd prefer to bring a more cohesive auth offering closer to Ionic, with more than just facebook. That, and we are making the decision to focus on Swift for all plugins going forward. I'll think on what we might be able to do here in the meantime.

**Comment by jacquesdev** [comment]
Thank you @mlynch!

**Comment by peterpeterparker** [comment]
I could not commit as being a maintainer of this plugin, answering issues and developing new features, but it's a core feature of my startup

Therefore, as long as I don't run out of money and even if I am not a cordova-android or cordova-ios expert, you could count on me for being around if breaking changes has to be push forward

**Comment by jacquesdev** [comment]
@mlynch - just bumping this, any chance your team can take over this plugin?

**Comment by peterpeterparker** [comment]
Two years later, I'm giving up being the active maintainer of the plugin.

Reach me out if you want to takeover!

P.S.: For those interested I wrote a blog post about the why, how and why 👉 https://dev.to/daviddalbusco/takeover-the-cordova-facebook-plugin-maintenance-4j8f

**Comment by noahcooper** [comment]
@peterpeterparker I'd be interested in being added as a maintainer of this project.

**Comment by peterpeterparker** [comment]
@noahcooper cool 👍 unfortunatelly I don't have enough privileges to grant roles. try to reach out the owner of the repo Jeduan Cornejo @jeduan / https://twitter.com/jeduan

btw. if anyone has an active fork, I'll be happy to merge a PR to add a notice about it in the [READMED.md](README.md)

**Comment by jeduan** [comment]
Hey @peterpeterparker thanks for supporting this plugin for so long!

@noahcooper I think it's time for this plugin to find a new home. We can transfer it to an org. I'm a bit concerned of creating a left-pad situation, so my preference would be to archive this repo and putting a notice in the README redirecting folks to any new active forks.

Thanks!

**Comment by noahcooper** [comment]
@jeduan thanks for the response! I created an org (`cordova-plugin-facebook-connect`), would you prefer to transfer the repository, or should I just create a new fork?

**Comment by noahcooper** [comment]
The more I think about it, creating a new fork is the only thing that makes sense.

I've created https://github.com/cordova-plugin-facebook-connect/cordova-plugin-facebook-connect and will be working on updating it to the most recent version of the Facebook SDK, then will tackle some of the pull requests submitted here. If you'd like to point people there in the README, feel free!

**Comment by jeduan** [comment]
@noahcooper great. I’ll forward people there in README. I agree it’s better to create another fork as I don’t want you to start extremely burdened by open issues. Godspeed in your efforts taking this forward!

**Comment by jeduan** [comment]
Quick note that I added a notice in the readme and put a deprecation notice in npm
