### ISSUE TITLE
Should I care about this?

### ISSUE THREAD

**Issue by ThorvaldAagaard** [jeduan/cordova-plugin-facebook4#631]
I have received this mail from Apple

![image](https://user-images.githubusercontent.com/10560652/37021992-cf77b1bc-2121-11e8-83fb-5de0113ee1a9.png)

Should I care, when using this cordova-plugin-facebook4?

**Comment by r34lp0w3r** [comment]
I received that message too. Do we need to do anything?

**Comment by gregavola** [comment]
I think the SDK needs to be updated in this repo and republished to NPM so we can update.

**Comment by AdamKraif** [comment]
+

**Comment by gregavola** [comment]
@jeduan Can the SDK updated here?

**Comment by jeduan** [comment]
I’m not maintaining this anymore. Let me know if you’re up for this.

**Comment by D-Marc1** [comment]
This is probably not a big deal, as it even states that the update is a better login experience for 14% of users on iOS11. Nothing stated nor implied that any functionality will break.

That's a shame, but thank you so much for the time you spent taking over the de facto official Facebook Cordova plugin @jeduan. I really hope we'll find someone to maintain it before actual breaking changes occur though.

**Comment by peterpeterparker** [comment]
@jeduan I just provided a PR for this https://github.com/jeduan/cordova-plugin-facebook4/pull/634

Important: I'm a newbie in this field aka I'm no Cordova or neither Objective-C expert

I have update the library, add a look to the declarations diff (looks fine to me) and finally build it and tested login and share methods with my app (my productive app respectively in a real app where I would have been able to detect problems)

I would highly appreciate your expertise or the expertise of anyone else (@fredgalvao ?) to review the PR

I tried my best, hope it gonna be ok for you guys

**Comment by fredgalvao** [comment]
@peterpeterparker Thanks for suggesting me (I'll take that as a compliment) but I can't review Objective-C or Swift code, as I have almost zero experience on both/any. I'm hoping you find someone to do it though, we need to keep this project updated somehow.

**Comment by peterpeterparker** [comment]
@fredgalvao totally agree, hope we find someone to keep this project up and running

p.s.: I'll keep in mind that your are then a Cordova/Android expert 😉

**Comment by peterpeterparker** [comment]
PR https://github.com/jeduan/cordova-plugin-facebook4/pull/634 is merged

Update of the Facebook SDK as requested by Facebook will be published in v2.0.0

**Comment by peterpeterparker** [comment]
This has been now release to npm

Plugin version v1.10.0
