### ISSUE TITLE
Graph API v.2.5 Upgrade Changes

### ISSUE THREAD

**Issue by joewoodhouse** [jeduan/cordova-plugin-facebook4#633]
I've been getting lots of warnings recently along the lines of:

```
<apps> currently have access to Graph API v2.5 which will reach the end of its 2-year lifetime on 12 April, 2018. We estimate 2 endpoints in total will be impacted by this change and may stop working after the automatic upgrade push. To ensure a smooth transition, please migrate all calls to Graph API v2.6 or higher. Use the API Upgrade Tool to understand exactly how this change will impact your app.

Note: If you do not see any impacted calls in the API Upgrade Tool, your app/code may not be affected by this upgrade.

Visit our changelog to see the full list of changes in all Graph API versions.
```

My apps only use facebook via this plugin. Anyone know if I'm going to have any problems?

**Comment by fredgalvao** [comment]
It's bad/sad that this comes up everytime, but here we go again:

Click the link that's on:
> Use the API Upgrade Tool to understand exactly how this change will impact your app.

And then ask the dashboard to help you migrate from 2.5 to 2.6 (change the values on the comboboxes), and see if there's any call made from your app using the v2.5 API on the table down the page.
If there's any, then you have something to worry.

Hint: I've done my checkup, and there's none. This plugin uses v2.10+ (on my case).


Feel free to re-open this issue if you ever confirm this plugin uses any soon-to-be-depreciated API versions.
