### ISSUE TITLE
i Cant login with permissions manage_pages pages_show_list

### ISSUE THREAD

**Issue by alvarheras** [jeduan/cordova-plugin-facebook4#636]
When I insert more permissions into the array such as send pages and view the list, it doesn't respond correctly and I don't get an answer.

Who knows what's going on? What I'm looking for is to authenticate myself with instagram through the new api of facebook instagram, here is my code
`constructor(
    public navCtrl: NavController,
    public fb: Facebook,
    public nativeStorage: NativeStorage
    ) {
    this.fb.browserInit(this.FB_APP_ID, "v2.12");
  }

  doFbLogin() {
    let permissions = new Array<string>();
    let nav = this.navCtrl;
    permissions = ["public_profile","manage_pages","pages_show_list"];
    this.fb.login(permissions)
    .then((response) => {
      alert(JSON.stringify(response));`

I have to login on one side and then request new permissions?

**Comment by peterpeterparker** [comment]
Plz use other channels like stackoverflow for support requests. Thx in advance
