### ISSUE TITLE
Build Error - minSdkVersion 14 cannot be smaller than version 15

### ISSUE THREAD

**Issue by Vasanth19** [jeduan/cordova-plugin-facebook4#64]
Hello,

I am using the command 
cordova build android  --minSdkVersion=15
 but, Still get the following error.  I am pretty much stuck here for a while. Would appreciate any help

Error:
        uses-sdk:minSdkVersion 14 cannot be smaller than version 15 declared in library ....\platforms\android\build\intermediates\exploded-aar\com.facebook.android\f
acebook-android-sdk\4.6.0\AndroidManifest.xml
        Suggestion: use tools:overrideLibrary="com.facebook" to force usage
:processArmv7DebugManifest FAILED

FAILURE: Build failed with an exception.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more l
og output.

BUILD FAILED

Thanks

**Comment by Hirbod** [comment]
You need to call it like that

cordova build android -- --minSdkVersion=15

The redundant -- is important - don't ask me why

**Comment by Vasanth19** [comment]
That Helped. Thanks a lot @Hirbod

**Comment by abirdridi** [comment]
where can i call  cordova build android -- --minSdkVersion=15 ?? 

Please

**Comment by neculaionutni** [comment]
Ok. @Hirbod , your solution works. I don't understand why but it works. Any idea on how to fix to also work for `cordova run android` ??

**Comment by artiberde27** [comment]
@Hirbod Thanks your solution works when i have build project using cordova command line.I want to build same project using android studio.When i am building project using android studio i am again facing same issue.
