### ISSUE TITLE
[Emergency] Cordova build Issue (Could not resolve all dependencies for configuration ':_debugApkCopy')

### ISSUE THREAD

**Issue by namlunthkl** [jeduan/cordova-plugin-facebook4#644]
Hi guys, today I'm very unsatisfied with whatever happened. At 9:00 AM, I uploaded my project to build.phonegap.com, everything seems to be well. I didn't see any error in the logs or got any problem... But at 1:00PM, I can't build my Project anymore.

Here is the log: https://pastebin.com/95t917y9

After reading the log for hours and checkout for many solutions, I can't solve this problem and I thought it comes from the cordova-plugin-facebook4. I have tried to install old version of this plugin but It doesn't effect. Now, I think the problem is Cordova Build Service.
Please help me if you have any solution for this problem and excuse me for my bad English.

I really need to build my project right now so please help me...

Many thanks!

**Comment by peterpeterparker** [comment]
This is most probably a conflict with the Android SDK version

See for example https://github.com/jeduan/cordova-plugin-facebook4/issues/550

For support questions plz use other channels like stackoverflow or ionic forum
