### ISSUE TITLE
Height bug when used with Ionic on IOS

### ISSUE THREAD

**Issue by rubz0** [jeduan/cordova-plugin-facebook4#648]
Hi,

So I am facing an issue since a couple of months and I just discovered that this issue is caused by this cordova plugin.
I looked everywhere for someone in the same case than me but I didn't find anyone speaking about it.
What is happening is simple and I was able to narrow this bug to the facebook connection.
The height of the phone in iOS is modified after the user has signed in with this facebook connect. Just after the success callback, when I can see the screen of my app again, the height is bigger than it was before.
The result of this is causing major issues on my app, because the only way to fix it is to totally close the app and open it one more time. And because the user is already logged in the height of the screen is now displaying properly.
If he is not restarting the app like that, our users see only half of the bottom tab bar and half of the status bar because the height that we got from platform.height (This is the command to get the height of the screen in Ionic 3) is not the correct one.

If you could help me to solve this bug asap it could be really really nice, because I have no idea how to fix it and it's really embarrassing to promote an app to my users that they need to close after the connection in order to make it run correctly :(..

If you need any other details be free to ask me anything, I should be able to give you answer at anytime!

Thanks a lot!

**Comment by peterpeterparker** [comment]
This looks like a problem related to your app or dependency.

Plz use the Ionic forum or Stackoverflow channels for support, thx in advance

Of course if it turns out that at the end it isn't restricted to your app, feel free to open an issue with more details
