### ISSUE TITLE
Build Failed in Ionic Blank application

### ISSUE THREAD

**Issue by leoassiscosta** [jeduan/cordova-plugin-facebook4#651]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt

**Comment by peterpeterparker** [comment]
Plz use other channels like Stackoverflow or Ionic forum for support

P.S.: you might need to give a bit more details on your error, just saying

**Comment by Sebschock** [comment]
For reference, this fixed the issue for me:

Add 
`<config-file parent="/resources" target="./res/values/strings.xml">
    <string name="fb_app_id">123456789</string>
    <string name="fb_app_name">myApplication</string>
</config-file>`
in the android platform tag of your config.xml

See: https://github.com/jeduan/cordova-plugin-facebook4/blob/master/docs/android/README.md

**Comment by sommerper** [comment]
I had to do this as well. Is this not something that should be handled by the plugin itself?
