### ISSUE TITLE
Login page loading slowly (about 30 seconds) at first time on android

### ISSUE THREAD

**Issue by lcya86** [jeduan/cordova-plugin-facebook4#655]
Hi guys, I got a problem with the login page on android.
This is my platform info:
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    Cordova Platforms : android 7.1.0 ios 4.5.4
    Ionic Framework   : unknown

System:

    ios-deploy : 1.9.1 
    ios-sim    : 4.1.1 
    Node       : v6.9.5
    npm        : 5.7.1 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

And I test it in android 5.1 simulator, it comes up when the first time click login button, and the second time it will show up quickly, but it also comes up after first time several minutes. And I did some debugs on it, found that the most time consuming is a request to https://fbsbx.com/security/hsts-pixel.gif , and when I request the login page in the android browser it is same problem, but when I request the login page in laptop chrome it's very quick.

This is the logcat after click the login button:

    05-09 03:08:54.223 17746-17746/online.lifevault.lifevaultapp I/chromium: [INFO:CONSOLE(1603)] "Fb chosen to login..", source: file:///android_asset/www/static/js/app.min.js (1603)
    05-09 03:09:00.311 1709-3325/system_process I/ActivityManager: START u0 {act=NATIVE_WITH_FALLBACK cmp=online.lifevault.lifevaultapp/com.facebook.FacebookActivity (has extras)} from uid 10085 on display 0
    05-09 03:09:00.314 17746-17746/online.lifevault.lifevaultapp W/com.facebook.appevents.AppEventsLogger: deactivateApp events are being logged automatically. There's no need to call deactivateApp, this is safe to remove.
    05-09 03:09:00.315 17746-17884/online.lifevault.lifevaultapp W/PluginManager: THREAD WARNING: exec() call to FacebookConnectPlugin.login blocked the main thread for 6025ms. Plugin should use CordovaInterface.getThreadPool().
    05-09 03:09:00.587 17746-17746/online.lifevault.lifevaultapp W/art: Attempt to remove local handle scope entry from IRT, ignoring
    05-09 03:09:00.588 17746-17746/online.lifevault.lifevaultapp W/AwContents: onDetachedFromWindow called when already detached. Ignoring
    05-09 03:09:01.153 1709-1747/system_process I/ActivityManager: Displayed online.lifevault.lifevaultapp/com.facebook.FacebookActivity: +837ms
    05-09 03:09:10.318 1709-1736/system_process W/ActivityManager: Launch timeout has expired, giving up wake lock!
    05-09 03:09:11.888 17746-17759/online.lifevault.lifevaultapp I/art: Background sticky concurrent mark sweep GC freed 30961(1344KB) AllocSpace objects, 2(32KB) LOS objects, 9% free, 12MB/13MB, paused 6.569ms total 38.848ms

And this is the log after the login page loaded

    05-09 03:09:45.819 17746-17867/online.lifevault.lifevaultapp E/chromium: [ERROR:buffer_manager.cc(313)] [.Parent-Compositor-0xaeb66dd0]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
    05-09 03:09:45.946 1709-2388/system_process W/InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@3629e85b attribute=android.view.inputmethod.EditorInfo@2605d8f8, token = android.os.BinderProxy@323b712d

It's perfect on ios, this just occurs on android.

Is anyone facing the same problem?

**Comment by peterpeterparker** [comment]
Plz use other channels like Stackoverflow or the Ionic forum for support requests, thx
