### ISSUE TITLE
Unable to pre-populate the "quote" field

### ISSUE THREAD

**Issue by dfibuch** [jeduan/cordova-plugin-facebook4#657]
Plugin version: 1.7.4
Cordova version: 7.1.0
Facebook API version: 2.8

I might be completely wrong here because I can't remember exactly how this worked when I first implemented it a while back but I thought there was a way to pre-populate the "Write something..." part of the dialog box. Here is the code I am running:

```
this.showFacebookDialog<void>({
                method: 'share',
                href: post.link,
                quote: "hello this is a test quote"
            })
```

I would expect to see `hello this is a test quote` in the Facebook Dialog but all I see is the link from the `href` parameter. Looking at the Facebook Share Dialog documentation it says that the `quote` parameter is still supported and when I use their test sandbox I do see it.

Anyone experience this also?

**Comment by peterpeterparker** [comment]
This has been deprecated by Facebook a while ago

**Comment by dfibuch** [comment]
What has been deprecated? I can see it working in the Facebook example:

![image](https://user-images.githubusercontent.com/4235431/39868999-e2af036a-5453-11e8-80a5-f5d9f071e6ed.png)

Do you mean its deprecated from being done via the plugin or mobile devices in general?

**Comment by peterpeterparker** [comment]
you are right sorry, I mixed up the info. 

From the SDK

> /**
>   Some quote text of the link.
> 
>  If specified, the quote text will render with custom styling on top of the link.
>  - Returns: The quote text of a link
>  */
> @property (nonatomic, copy) NSString *quote;

If it doesn't work then sure feel free to submit a PR to fix the issue, thx in advance

**Comment by dfibuch** [comment]
Thank you. I should have found that myself, sorry. Been out of the loop with this plugin for a while as we've not had any changes requested around the Facebook functionality

**Comment by peterpeterparker** [comment]
@dfibuch no worries

**Comment by peterpeterparker** [comment]
@dfibuch could we close this, were you able to solve your problem?

**Comment by dfibuch** [comment]
Sorry, I was away on Friday. I haven't attempted to fix this yet but also just found out the feature that was order is no longer needed so I won't be making any changes. If I do get to doing this in the future I will update you. Happy to close.

**Comment by peterpeterparker** [comment]
@fibuch coolio thx for the feedback :)
