### ISSUE TITLE
Facebook login modal is opening and automatically closing

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [jeduan/cordova-plugin-facebook4#659]
I have integrated this plugin, it is just opening the modal window and closing in fraction of seconds with the error `{ }`
There is no way to see why it is happening.

**Comment by peterpeterparker** [comment]
Plz use other channels like stackoverflow for support purpose

**Comment by rajeshwarpatlolla** [comment]
I think you should close this repo too, along with issues here.
