### ISSUE TITLE
Duplicate CFBundleURLSchemes into -Info.plist

### ISSUE THREAD

**Issue by felquis** [jeduan/cordova-plugin-facebook4#66]
Each time I run `cordova prepare ios` - which happens multiple times during development - into the -Info.plist the snippet bellow is duplicated.
```xml
<dict>
  <key>CFBundleURLSchemes</key>
  <array>
    <string>fb001122334455660</string>
  </array>
</dict>
```

I couldn't find where in the repo it is been added, someone could point me where is it?

**Comment by fredgalvao** [comment]
That's not a plugin bug, but rather a cordova bug. You can check the details [here](https://issues.apache.org/jira/browse/CB-9354) and the pull-request discussion and code [here](https://github.com/apache/cordova-lib/pull/256).

It seems that it hasn't been released yet, though...

**Comment by zwacky** [comment]
why does cordova-plugin-facebook4 add a CFBundleURLSchemes in the first place?

**Comment by jeduan** [comment]
https://developers.facebook.com/docs/ios/getting-started#xcode
