### ISSUE TITLE
SignedRequest after log in

### ISSUE THREAD

**Issue by luanmanfre** [jeduan/cordova-plugin-facebook4#660]
why don't have the key 'signedRequest' in return of api('/me'), to use the app key secret to decrypt on the server?

https://developers.facebook.com/docs/games/gamesonfacebook/login#parsingsr

**Comment by peterpeterparker** [comment]
No idea, but if you would like to submit a PR to add it, go for it ;)

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out the actively maintained fork `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect.
