### ISSUE TITLE
[Feature] Android min sdk version 26

### ISSUE THREAD

**Issue by peterpeterparker** [jeduan/cordova-plugin-facebook4#662]
[X] I want to submit a feature request

**Description**

In August 2018, Android SDK v26 will be mandatory for new app to submit in the Play Store.
In November 2018, Android SDK v26 will be mandatory for any app updates.

Source: https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html

**What to do**

Even if it isn't breaking or anything, it will be good at some point to set the min-sdkversion of the plugin (see `plugin.xml` property `android-minSdkVersion`) to **26** instead of **15**

**Side note**

I have just tested to build an application using Api v26 with the current version of the plugin and I could confirm that everything works fine respectively that I didn't face any errors at build time. To specify to use of this Api level, I have added the following to entries to the `config.xml` of my Cordova app:

    <preference name="android-minSdkVersion" value="26" />
    <preference name="android-targetSdkVersion" value="26" />

**Comment by xale76** [comment]
I forked and changed minsdkversion to 26 (from 15)
The build fails. maybe because of ANDROID_SDK_VERSION set to 4+?
what I have to set there?

**Comment by MicaelPereira** [comment]
Hey @peterpeterparker I have this problem:

Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
C:\{FOLDER}\platforms\android\app\build\intermediates\manifests\full\debug\AndroidManifest.xml:135: AAPT: error: resource string/fb_app_id (aka com.physiconnect.app:string/fb_app_id) not found.

**Comment by peterpeterparker** [comment]
@MicaelPereira no idea, you should probably open a support inquiry on stackoverflow or the ionic forum for example and give there more details

**Comment by Flaviocrtt** [comment]
I'm having problem with this plugin, i use Phonegap cli-8.0.0, when i remove the facebook4 plugin it builds, but if add the plugin, the build fail. Can you take a look on the logs?
thanks!

[not_using_facebook4-plugin_build-sucess.txt](https://github.com/jeduan/cordova-plugin-facebook4/files/2534590/not_using_facebook4-plugin_build-sucess.txt)
[using_facebook4-plugin_build-fail.txt](https://github.com/jeduan/cordova-plugin-facebook4/files/2534591/using_facebook4-plugin_build-fail.txt)

**Comment by peterpeterparker** [comment]
@Flaviocrtt 

```
/app/build/intermediates/manifests/full/release/AndroidManifest.xml:120: AAPT: error: resource string/fb_app_id (aka br.com.ravex.appentregador:string/fb_app_id) not found.
    
/app/build/intermediates/manifests/full/release/AndroidManifest.xml:123: AAPT: error: resource string/fb_app_name (aka br.com.ravex.appentregador:string/fb_app_name) not found.
```

=> https://github.com/jeduan/cordova-plugin-facebook4/issues/599

**Comment by MicaelPereira** [comment]
I use this comment, for adjust.
https://github.com/jeduan/cordova-plugin-facebook4/issues/599#issuecomment-355259914

**Comment by peterpeterparker** [comment]
@MicaelPereira thx. ps.: comment which is also documented in the "Android Guide" https://github.com/jeduan/cordova-plugin-facebook4/blob/master/docs/android/README.md btw. ;)

**Comment by Flaviocrtt** [comment]
Ok, that worked, thank you.

**Comment by Andrewpk** [comment]
I think the only necessary portion is targetSdk. Minsdk can still be whatever, they just want us building against some version of the tools that aren't a million years old

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect.

There's really no reason for the plugin itself to enforce a minSdkVersion unless there is some specific issue with earlier Android versions. That being said, cordova-android itself only supports SDK version 22 as of June 2020.
