### ISSUE TITLE
Aggressive Adware

### ISSUE THREAD

**Issue by front-stream** [jeduan/cordova-plugin-facebook4#664]
After successful build, Bitdefender App (Android) detects Adware.GingerMaster.CA adware. How to fix that? Everything is ok when I uninstall cordova-plugin-facebook4 and build ionic project without this.

android 7.1.0
cordova-plugin-facebook4 2.1.0 "Facebook Connect"

**Comment by peterpeterparker** [comment]
Your colleague, I'm guessing, opened an issue today about it. After tests from my side and his side we could amend that the problem isn't related to this plugin

See duplicate https://github.com/jeduan/cordova-plugin-facebook4/issues/663

**Comment by front-stream** [comment]
Hmm, rather not, these issue still exists for me and we have totally different apps...

**Comment by peterpeterparker** [comment]
Anyhow I don't gonna repeat myself, see duplicate https://github.com/jeduan/cordova-plugin-facebook4/issues/663

Afterwards, if you still do think the error is related to the plugin, provide **full details**, **sample repo** or **access to your code**
