### ISSUE TITLE
Not working on iOS

### ISSUE THREAD

**Issue by erperejildo** [jeduan/cordova-plugin-facebook4#665]
It might be an Ionic issue but I'm testing with Ionic Devapp and I'm getting this warning all the time:

> [18:29:15]  console.warn: Native: tried calling Facebook.login, but the Facebook plugin is not installed.
> [18:29:15]  console.warn: Install the Facebook plugin: 'ionic cordova
> plugin add cordova-plugin-facebook4'

I installed it like this:
```
ionic cordova plugin add cordova-plugin-facebook4 --variable APP_ID="XXX" --variable APP_NAME="Recipic"
npm install --save @ionic-native/facebook
```

**Comment by peterpeterparker** [comment]
DevApp doesn't support the Facebook plugin, see documetation https://ionicframework.com/docs/pro/devapp/

**Comment by erperejildo** [comment]
I see... thanks for letting me know

**Comment by peterpeterparker** [comment]
@erperejildo no worries :)

**Comment by erperejildo** [comment]
This has to be supported from Ionic or from Facebook plugin?

**Comment by peterpeterparker** [comment]
DevApp is something has to be done, but my guess, it would have been already the case if it would have been in the plan, I guess it just not gonna happen, but only my guess

**Comment by erperejildo** [comment]
Perfect, thanks
