### ISSUE TITLE
Anndroid and Cordova 8.0.0

### ISSUE THREAD

**Issue by mikmargiotta** [jeduan/cordova-plugin-facebook4#666]
About a year ago I created an app with cordova 6.5.0 and cordova-plugin-facebook4 1.7.4 and everything worked perfectly.

Today, I was trying a new app with cordova 8.0.0 and cordova-plugin-facebook4 2.1.0, but I received these errors:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
    at ChildProcess.whenDone (/Users/michael/Desktop/hello/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
(node:10447) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10447) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Can you help me? Thanks
[config.txt](https://github.com/jeduan/cordova-plugin-facebook4/files/2059650/config.txt)
[terminal_error.txt](https://github.com/jeduan/cordova-plugin-facebook4/files/2059654/terminal_error.txt)

**Comment by peterpeterparker** [comment]
Plz use other channels for support request, like Stackoverflow or Ionic forum

Feel free to link your support question here

**Comment by peterpeterparker** [comment]
@mikmargiotta 

    AAPT: error: resource string/fb_app_id (aka com.example.hello:string/fb_app_id) not found.

=> see documentation chapter "cordova-android >= 7"

https://github.com/jeduan/cordova-plugin-facebook4/blob/master/docs/android/README.md

**Comment by mikmargiotta** [comment]
Sorry and thank you!
Problem solved
