### ISSUE TITLE
Help understanding how to validate subscriptions

### ISSUE THREAD

**Issue by dfibuch** [jeduan/cordova-plugin-facebook4#667]
This is not an issue, more of a question.

I'm trying to figure out how I can validate if a user has a valid subscription for both Apple and Google for my app. I had a look at the article about validating, which points to `voltrue2/in-app-purchase` module but when reading the documentation there it says that Google Subscriptions are not supported.

So my question is how do people validate if a person is still subscribed whenever they access the app?

**Comment by peterpeterparker** [comment]
For support or question plz use channels like Stackoverflow or the Ionic forum, thx in advance

**Comment by dfibuch** [comment]
Oh, but this is specific to this plugin. That's why I thought it would make sense to ask it here.

**Comment by peterpeterparker** [comment]
@dfibuch to keep the plugin afloat, use other channels for support or questions, thx for your understanding

**Comment by dfibuch** [comment]
Sorry @peterpeterparker, I only just had my coffee and realised my mistake. See edits above.

**Comment by peterpeterparker** [comment]
@dfibuch no worries 😉
