### ISSUE TITLE
ios - FBSDKCoreKit/FBSDKCoreKit.h not found error 

### ISSUE THREAD

**Issue by sid-Puttur** [jeduan/cordova-plugin-facebook4#669]
I am using this plugin with ionic version 3.20.0 and also using Xcode 9.2 for ios build. I get this error while building the app. Cleaning and building sometimes do the magic. But most of the time I have to go back remove the plugin and platform and install it again to make it work. Any help would be appreciated.

Thanks

**Comment by peterpeterparker** [comment]
For support requests or "How to" questions, please use channels like StackOverflow or the Ionic forum
