### ISSUE TITLE
Android new Key Hash after updating plugin

### ISSUE THREAD

**Issue by dfibuch** [jeduan/cordova-plugin-facebook4#672]
I had a search around for the answer but couldn't find anything useful, so I am hoping I can get an answer here.

I updated the version of this plugin today from 1.7.4 to 2.1.0 and upon running it on android I get the "invalid key hash" error. Now I know I can just add this key hash to my Facebook portal and it will work but my question is, why did this change? I have 3 key hashes in there now and it just feels weird adding more and more every time this happens.

Is this expected behaviour after updating the plugin or is it just a coincidence that it happened at the same time?

**Comment by peterpeterparker** [comment]
I would say coincidence, I did all upgrade one after the other in my app from 1.7.4 to 2.1.0 and didn't had too change the hash anytime

Do that answer your question? Could we close the issue/question?

**Comment by dfibuch** [comment]
Ok that's fine. One last question, does this plugin need @ionic-native\facebook plugin present? I cant remember why I have it installed and I don't see any direct dependency on it in this plugin but just want to check.

**Comment by peterpeterparker** [comment]
No it doesn't respectively this plugin doesn't need @ionic-native\facebook but @ionic-native\facebook do need this plugin ;)

@ionic-native\facebook is a handy wrapper you could use if you want to use the plugin respectively it also helps you with the typings. But it's not mandatory, you could write your own definition files or access the plugin like `window....`. But it's handy

I close then your question/issue. If you would face problems with hashes in the future, feel free to bump me or open a new issue
