### ISSUE TITLE
iOS Build Fails With Facebook4 Plugin

### ISSUE THREAD

**Issue by raychz** [jeduan/cordova-plugin-facebook4#677]
**Bug or feature request**

[ x ] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

**Describe the Bug of feature request**

The iOS build fails after installing cordova-plugin-facebook4.  Can be reproduced as follows:

`$ ionic cordova plugin remove cordova-plugin-facebook4 --variable APP_ID="xxxx" --variable APP_NAME="xxxx"`
`$ ionic cordova build ios`

> ** BUILD SUCCEEDED **

`$ ionic cordova plugin add cordova-plugin-facebook4 --variable APP_ID="xxxx" --variable APP_NAME="xxxx"`
`$ ionic cordova build ios`
> ...
> ld: framework not found FileProvider for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
>         Ld build/emulator/myapp.app/myapp normal x86_64
> (1 failure)
> ...

**Plugin version, OS, devices, etc**
`"cordova-plugin-facebook4": "^2.1.0"`
`$ ionic info`

> cli packages: (/Users/username/.nvm/versions/node/v6.11.2/lib/node_modules)
> 
>     @ionic/cli-plugin-proxy : 1.5.8
>     @ionic/cli-utils        : 1.19.2
>     ionic (Ionic CLI)       : 3.20.0
> 
> global packages:
> 
>     cordova (Cordova CLI) : 8.0.0
> 
> local packages:
> 
>     @ionic/app-scripts : 3.1.9
>     Cordova Platforms  : android 7.0.0 browser 5.0.3 ios 4.5.4
>     Ionic Framework    : ionic-angular 3.9.2
> 
> System:
> 
>     Node  : v6.11.2
>     npm   : 5.8.0
>     OS    : OS X El Capitan
>     Xcode : Xcode 8.2.1 Build version 8C1002
>
> Misc:
> 
>     backend : pro

**Additional Context**

From the research I've already done, this issue might be related to the version of Xcode that I am running.  Unfortunately, I do not currently have the option of updating it.

**Comment by peterpeterparker** [comment]
Thx for taking the time to describe the issue following the canvas 👍 

I guess there isn't any programmatic solution, the last versions of the plugin include the library Facebook requested which enhance the compatibility with iOS v11

Therefore you've got two solutions:

1. Upgrade XCode
2. Downgrade/stick to version v1.7.4 of this plugin

Ping me if none of these work

**Comment by raychz** [comment]
Thanks!  Downgrading to 1.7.4 worked.
