### ISSUE TITLE
minSdkVersion 14 cannot be smaller than version 15 declared in library

### ISSUE THREAD

**Issue by joidegn** [jeduan/cordova-plugin-facebook4#68]
I am using Ionicframework. Installing cordova-plugin-facebook4 via ```ionic plugin add cordova-plugin-facebook4``` makes the build fail like so:

[blabla]/platforms/android/AndroidManifest.xml:32:5 Error:
        uses-sdk:minSdkVersion 14 cannot be smaller than version 15 declared in library [blabla]/platforms/android/build/intermediates/exploded-aar/com.facebook.androi
d/facebook-android-sdk/4.7.0/AndroidManifest.xml
        Suggestion: use tools:overrideLibrary="com.facebook" to force usage
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processArmv7DebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 15 declared in library [blabla]/platforms/android/build/intermediates/exploded-aar/
com.facebook.android/facebook-android-sdk/4.7.0/AndroidManifest.xml
        Suggestion: use tools:overrideLibrary="com.facebook" to force usage

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by Hirbod** [comment]
cordova run android -- --minSdkVersion=15

It is a crosswalk or Ionic bug. Btw: did you see the double -- ? Thats right, it has to be like this

**Comment by joidegn** [comment]
very cool! thanks!

**Comment by AisonBird** [comment]
very cool! I have the same problem! thank you very much!

**Comment by faraz9x** [comment]
perfect hirbod 👍 ... But is it a temporary solution or we should look to fix the issue further more?

**Comment by vibinflogesoft** [comment]
Thanks hirbod,saved a lot of time
