### ISSUE TITLE
Error when executing API call: "There was an error making the graph call" (iOS Only)

### ISSUE THREAD

**Issue by JacobBradt** [jeduan/cordova-plugin-facebook4#680]
**Bug or feature request**

[X] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

**Describe the Bug of feature request**

When executing a graph API call using the ".api function" in an attempt to post a link to a Facebook Page in iOS, I receive the following xCode logs.

> 2018-06-30 15:04:47.760490-0500 Rockford Buzz[11257:747778] Task <0325A7CE-6449-4EA6-88BD-7BF600367236>.<1> finished with error - code: -1002
> 2018-06-30 15:04:47.779632-0500 Rockford Buzz[11257:736620] Finished GraphAPI request
> 2018-06-30 15:04:47.787678-0500 Rockford Buzz[11257:736620] There was an error making the graph call.

API call executes successfully in Android

**Expected Behavior**

API call to execute successfully in iOS

**Plugin version, OS, devices, etc**

_BASIC INFO_
Plugin Version: 2.2.0
Device: xCode Simulated iPhone 6
Device OS : iOS 11.4

_IONIC INFO_
cli packages:
    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:
    cordova (Cordova CLI) : 7.0.1 

local packages:
    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.7.1

_INSTALLED PLUGINS_
cordova-clipboard 1.0.0 "Clipboard"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-badge 0.8.1 "Badges"
cordova-plugin-calendar 4.6.0 "Calendar"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-facebook4 2.2.0 "Facebook Connect"
cordova-plugin-fcm 2.1.2 "FCMPlugin"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-filepath 1.0.2 "FilePath"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.7 "Ionic's WKWebView Engine"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
de.appplant.cordova.plugin.local-notification 0.8.5 "LocalNotification"
ionic-plugin-deeplinks 1.0.15 "Ionic Deeplink Plugin"

**Sample repo**
Here is the function I'm executing. 

```
this.fb.api("/" + this.requestData.facebook_id + "?fields=access_token",["manage_pages","publish_pages"])
              .then(res => {
                let access_token = String(res.access_token);

                let facebookString = "/" + this.requestData.facebook_id + "/feed?fields=id" + "&method=post" + "&link=" + link
                if(this.post.facebook_message != null && this.post.facebook_message != ""){
                  facebookString += "&message=" + this.post.facebook_message;
                }
                facebookString += "&access_token=" + access_token;

                this.fb.api(facebookString,["manage_pages","publish_pages"])
                  .then(res => {
                    console.log(res);
                  })
                  .catch(e => {
                    console.log(e);
                  });
              })
              .catch(e => {
                console.log(e);
              });
```

**Additional Context**

A Facebook user with Page Manager access to at least one page will be required to reproduce. You can hardcode the variable "this.requestData.facebook_id" (Facebook Page ID), as well as the "link" & "message" pieces to the "facebookString" variable, to reproduce.

_link to existing Ionic Forum Post:_
https://forum.ionicframework.com/t/ionic-3-cordova-plugin-facebook4-there-was-an-error-making-the-graph-call-ios-only-android-working/134017/10

_Link to existing StackOverflow Post:_
https://stackoverflow.com/questions/51110411/ionic-3-cordova-plugin-facebook4-there-was-an-error-making-the-graph-call-io

_Facebook Docs for publishing to Page Feeds:_
https://developers.facebook.com/docs/graph-api/reference/v3.0/page/feed#publish

**Comment by JacobBradt** [comment]
Thanks Peter. Like I said here... the code is working in Android and I confirmed my request and tokens were all good using Facebook's tools. The only other thing I could think of was an issue with how your plugin is interfacing with the iOS Facebook SDK when constructing the request. I'll continue to try different things on my end and see if I can get a different result.

**Comment by peterpeterparker** [comment]
OP solving his/her issue "posting to graph API using HTTP", reference https://forum.ionicframework.com/t/ionic-3-cordova-plugin-facebook4-there-was-an-error-making-the-graph-call-ios-only-android-working/134017/18

I close this issue because we couldn't figure out if it's really an issue related to this plugin or not
