### ISSUE TITLE
facebookConnectPlugin.api() runtime error: "expected 2 arguments, but got 4"

### ISSUE THREAD

**Issue by hAz4rd0uS** [jeduan/cordova-plugin-facebook4#683]
[x] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

**Describe the Bug of feature request**

I'm running Ionic 3.20.0 and I got an unexpected runtime error with the following runtime error "expected 2 arguments, but got 4" on a call to fbPlugin.api();

See the code below:

`fbLogin(): void {
    var self = this;
    this.fb.login(['public_profile', 'email'])
    .then((res: FacebookLoginResponse) => this.fb.api(res.authResponse.userID + "/?fields=id,email,first_name&access_token="+res.authResponse.accessToken+"", ["public_profile"],
      function onSuccess (result) {
        let user = new NmUser({
          email: result.email,
          username: result.firstName,
          password: result.id
        });
        self.userService.facebook(user).subscribe(
          (result) => {
            console.log(result);
          },
          (error) => {
            console.log(error);
          }
        );
      }, function onError (error) {
        console.error("Failed: ", error);
      }
    ))
    .catch(e => console.log('Error logging into Facebook', e));
  }`

**Expected Behavior**

According to your doc, this call takes 4 parameters including two callbacks onSuccess and onError. My code should work.

**Plugin version, OS, devices, etc**

Plugin version: 2.2.0

**Comment by peterpeterparker** [comment]
The problem is on your side, plz use other channels for support request

For Ionic use I suggest to use Ionic native https://ionicframework.com/docs/native/facebook/

Also note, difficult to say exactly where the error is, you not formatted code isn't that readable, but I would say probably somewhere around the keyword `function onSuccess (result)`. Rather not use that but rather `=>`

**Comment by hAz4rd0uS** [comment]
According to the doc of the plugin, this is the right way to do. Why did you closed my issue ?

Please see your doc example: 
facebookConnectPlugin.api("<user-id>/?fields=id,email", ["user_birthday"],
  function onSuccess (result) {
    console.log("Result: ", result);
    /* logs:
      {
        "id": "000000123456789",
        "email": "myemail@example.com"
      }
    */
  }, function onError (error) {
    console.error("Failed: ", error);
  }
);

No arrows used.

Thanks in advance,

**Comment by peterpeterparker** [comment]
read my previous msg again, good luck
