### ISSUE TITLE
Not able to add the plugin

### ISSUE THREAD

**Issue by AjayKumarJ** [jeduan/cordova-plugin-facebook4#686]
I have tried the below commands on the terminal and both are responding in time:

cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID=<XXX> --variable APP_NAME=<XXX>

cordova plugin add https://github.com/jeduan/cordova-plugin-facebook4.git --save --variable APP_ID=<XXX> --variable APP_NAME=<XXX>

**Comment by desmeit** [comment]
I have the same problem. I get:

command not found

if I write the command:

cordova plugin add cordova-plugin-facebook4 --variable APP_ID="XXX" --variable APP_NAME="XXX"

all other plugins working.
