### ISSUE TITLE
iOS build error after installing plugin

### ISSUE THREAD

**Issue by rahulsahu013** [jeduan/cordova-plugin-facebook4#687]
ld: framework not found IOSurface for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

please help me resolve above issue.

**Comment by rahulsahu013** [comment]
@peterpeterparker Why you closed this? Don't you have any solution for this.

**Comment by peterpeterparker** [comment]
https://github.com/jeduan/cordova-plugin-facebook4/blob/master/.github/issue_template.md
