### ISSUE TITLE
Issue with Graph API

### ISSUE THREAD

**Issue by Saurabh995** [jeduan/cordova-plugin-facebook4#69]
App crashes when graph api is called .Please help.

**Comment by jeduan** [comment]
Need a lot more info than this. Please check https://github.com/jeduan/cordova-plugin-facebook4/blob/master/CONTRIBUTING.md#creating-an-issue

**Comment by Saurabh995** [comment]
I would try to be more specific. Actually when I login with my own account , graph api call is successful but when some other users log in then the graph api result sin crashing the app. And if I test it on browser then there is no issue. Thanks for the response.

**Comment by Saurabh995** [comment]
Its working now, all I did was change facebookConnectPlugin.api("me/?fields=id,name,gender,link ",["public_profile"],........  to  facebookConnectPlugin.api("me/?fields=id,name,gender ",["public_profile"]
Basically I didn't fetch link this time and it worked. Can you please tell me what could have happened?
