### ISSUE TITLE
AccessToken is not getting validated on serverside

### ISSUE THREAD

**Issue by techno2mahi** [jeduan/cordova-plugin-facebook4#690]
As per the documentation below the accessToken received in the authResponse.accessToken is throwing the following error when i am using this facebook api to check the token validity on server side

https://graph.facebook.com/debug_token?ACCESS-TOKEN&access_token=APP-TOKEN

Documentation: 
**"If you need the Facebook access token (for example, for validating the login on server side),"**

Error:
`{
    "error": {
        "message": "(#100) The App_id in the input_token did not match the Viewing App",
        "type": "OAuthException",
        "code": 100,
        "fbtrace_id": "GE4jgm1Go8u"
    }
}`

**Comment by peterpeterparker** [comment]
https://github.com/jeduan/cordova-plugin-facebook4/blob/master/.github/issue_template.md
