### ISSUE TITLE
AccessToken is not getting validated from Facebook API on Server side

### ISSUE THREAD

**Issue by techno2mahi** [jeduan/cordova-plugin-facebook4#691]
**Bug**

I'm reporting a reproducible issue with the code
 
**Description**

The accessToken received in the authResponse.accessToken is not getting validated at the Facebook api when checked on server side.

The facebook api used for the verification is as follows.
https://graph.facebook.com/debug_token?ACCESS-TOKEN&access_token=APP-TOKEN

Where APP-TOKEN is retrieved from the facebook developer console. ie  appid |app secret
or can be retrieved from this URL
https://developers.facebook.com/tools/accesstoken

However the accessToken is getting validated from the below Facebook API, but the app_id is not retrieved from the response. 
https://graph.accountkit.com/v1.1/me/?access_token=xxxxxxxxxxxx
`{
   "id": "user Id",
   "name": "Your Name"
}` 

Plugin Version: 2.2.0
OS : Windows
Device : Android Nugot
 

**Expected Behavior**

The accessToken should be validated from the facebook api with app_id and user_id as response. Then the accessToken will be verified from the particular app and user.

**Comment by peterpeterparker** [comment]
Sorry but I don't understand your description and question, what's your actual issue or problem? are you asking for support or what?

**Comment by techno2mahi** [comment]
Thanks for the quick response.

I have retrieved the accessToken from the call as below 
`facebookConnectPlugin.login(['public_profile', 'email'], function (result) 
{
                const externalAccessToken = result.authResponse.accessToken;
});`

This accessToken is being sent to the server for registration or local access token retrieval. 
This accessToken is validated from facebook graph API in the server side  for confirming that the accessToken is issued to the user id and for the app id.

**Comment by peterpeterparker** [comment]
So if I understand you, you are searching for help/support to achieve your implementation? If so plz use other channels to report your question

Or are you actually facing an issue? If so, which issue, what?

**Comment by techno2mahi** [comment]
No, I am saying the accessToken received from the plugin upon login success is not recognized by Facebook as a valid one. 

This prevents us from authenticating the user or uniquely identify the user.

**Comment by peterpeterparker** [comment]
Ok thx for the explanation, now I understand

This plugin doesn't use AccountKit respectively `graph.accountkit.com` therefore I think you can't verify a token with this service (it didn't worked for me neither)

If you want to verify a token in your backend use the graph api like `https://graph.facebook.com/v3.0/`

I gonna then close this issue but I have opened a feature request regarding AccountKit to not forget the subject and maybe launch the discussion, https://github.com/jeduan/cordova-plugin-facebook4/issues/692

**Comment by techno2mahi** [comment]
Thanks for the quick update. 
I was checking now for the same facebook API for verifying the accessToken and it worked. 

PFA (some infos are masked).
![debugtoken](https://user-images.githubusercontent.com/19298486/44258860-9b727e00-a22d-11e8-9f62-239917d62e3f.png)

**Comment by peterpeterparker** [comment]
@techno2mahi coolio
