### ISSUE TITLE
[Feature] Migrate and use Facebook AccountKit (?)

### ISSUE THREAD

**Issue by peterpeterparker** [jeduan/cordova-plugin-facebook4#692]
**Bug or feature request**

[X] I'm reporting a feature request

**Describe the feature request**

In 2018 Facebook slowly migrated the login flow to their new AccountKit https://www.accountkit.com

In both of their documentation for iOS and Android, Facebook is advising to use AccountKit

https://developers.facebook.com/docs/accountkit/ios

https://developers.facebook.com/docs/accountkit/android

This plugin doesn't use AccountKit

Furthermore, in the backend, it seems that the proved token could "only" be validated thru the GraphAPI and not thru the AccountKit API (see https://github.com/jeduan/cordova-plugin-facebook4/issues/691)

**Expected Behavior**

Should we migrate the plugin to the use of AccountKit?

**Important note**

I guess that might be a relative kind of big work...

Do anyone knows if Facebook plan to deprecate the current login flow?

**Comment by stck** [comment]
For now account kit will be closed in 2 month, so this issue should be closed

**Comment by peterpeterparker** [comment]
Cool, thx for pinging me about this 👍 

Ref: https://developers.facebook.com/blog/post/2019/09/09/account-kit-services-no-longer-available-starting-march/
