### ISSUE TITLE
ShowDialog - Send a photo to a user's feed

### ISSUE THREAD

**Issue by CharlesPoullain** [jeduan/cordova-plugin-facebook4#694]
Hi !
I am trying to use the showDialog exemple to send a photo.
The problem is that the "picture" property don't work. The properties links and href work fine, but I just want a picture without links (like the exemple at the bottom of the readme) and when I load a picture with the ui it work.
Also, I can't populate the message, I tried with caption, description, message, name etc, but it still not work.

Any ideas ?

**Comment by peterpeterparker** [comment]
Please use other channels for support request, thx in advance

Spontaneously I would say it's correct that you can't populate a msg, I think that's discarded since a while from Facebook

About "picture", it has to be an url (at least it's how I use it in my app)

    this.facebook.showDialog(
                {
                    method: 'share',
                    href: 'https://mywebsite.io',
                    caption: 'what ever',
                    picture: 'https://mywebsite.io/super.jpg'
                }

**Comment by CharlesPoullain** [comment]
Sorry, I thought it was a bug and on the correct channel.
Yes, your exemple work but I don't wan't the link provide by the href parameter.

**Comment by peterpeterparker** [comment]
Not sure it's possible with this plugin sorry, but don't take it for granted ;)

Have you tried the share plugin? https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin
