### ISSUE TITLE
Nothing happens on login

### ISSUE THREAD

**Issue by ysharoiko** [jeduan/cordova-plugin-facebook4#695]
I'm trying to make login

var c = new Array("photo","friends","email");
	facebookConnectPlugin.login(c, function fb_succ(data) {
		alert("LOGIN SUC");
		alert(data);
		},
		function fb_fail(data) {
		alert("LOGIN FAILED");
		alert(data);});

alert("FB TRY DONE");
}

But nohing happens. It's just rolling.

I tought my situation was like in Troubleshooting descriped and tryied the code from there to get hash

try {
  PackageInfo info =
  cordova.getActivity().getPackageManager().getPackageInfo("com.goapes.golearn", PackageManager.GET_SIGNATURES);

  for (Signature signature : info.signatures) {
      MessageDigest md = MessageDigest.getInstance("SHA");
      md.update(signature.toByteArray());
      Log.e("MY KEY HASH:", Base64.encodeToString(md.digest(), Base64.DEFAULT));
  }

} catch (NameNotFoundException e) {

} catch (NoSuchAlgorithmException e) {

}

But it does not work at all with no error

**Comment by ysharoiko** [comment]
Why is closed?

**Comment by peterpeterparker** [comment]
https://github.com/jeduan/cordova-plugin-facebook4/blob/master/.github/issue_template.md
