### ISSUE TITLE
Sporadic App Crash on GraphRequest.onCompleted ConnecctPlugin.onCompleted

### ISSUE THREAD

**Issue by guyman** [jeduan/cordova-plugin-facebook4#697]
I'm reporting a sporadic issue with the code.
Crash with NPE on login.

**Plugin version, OS, devices, etc**
Many different android devices
Cordova 8.0.0
Cordova-Android 7.1.0
cordova-plugin-facebook4 2.2.0

Stack Traces:

#0. Crashed: main
       at java.net.URLDecoder.decode(URLDecoder.java:137)
       at org.apache.cordova.facebook.ConnectPlugin.makeGraphCall(ConnectPlugin.java:754)
       at org.apache.cordova.facebook.ConnectPlugin.access$200(ConnectPlugin.java:54)
       at org.apache.cordova.facebook.ConnectPlugin$2$1.onCompleted(ConnectPlugin.java:110)
       at com.facebook.GraphRequest$1.onCompleted(GraphRequest.java:301)
       at com.facebook.GraphRequest$5.run(GraphRequest.java:1380)
       at android.os.Handler.handleCallback(Handler.java:754)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6221)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

--

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
       at java.net.URLDecoder.decode(URLDecoder.java:137)
       at org.apache.cordova.facebook.ConnectPlugin.makeGraphCall(ConnectPlugin.java:754)
       at org.apache.cordova.facebook.ConnectPlugin.access$200(ConnectPlugin.java:54)
       at org.apache.cordova.facebook.ConnectPlugin$2$1.onCompleted(ConnectPlugin.java:110)
       at com.facebook.GraphRequest$1.onCompleted(GraphRequest.java:301)
       at com.facebook.GraphRequest$5.run(GraphRequest.java:1380)
       at android.os.Handler.handleCallback(Handler.java:754)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6221)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by peterpeterparker** [comment]
Could you provide a sample repo?

If not, could you try to add the following outputs to your local plugin, reproduce the error and post here the results plz

In the plugin, in ConnectPlugin.java`,add the following in method `private void makeGraphCall(final CallbackContext graphContext ) {` (line 752):

     System.out.println("graphPath is:" + graphPath);
     Log.e("Activity", "graphPath is:" + graphPath);

and also add the same in method `private void executeGraph(JSONArray args, CallbackContext callbackContext) throws JSONException {` (line 520):

     System.out.println("arg graph path is:" + args.getString(0));
     Log.e("Activity", "arg graph path is:" + args.getString(0));

Thx

**Comment by guyman** [comment]
Hi the error is very sporadic so it's hard to reproduce.
The app is already in production on the Play Store, and the crash happens in a very low frequency - about once in a couple of days when we have about 100 users per day.
What do you suggest to do ?

The connect code is pretty straightforward:
function attemptFBLoginMobile() {
			if (typeof facebookConnectPlugin != 'undefined') {
				console.log("Going to attempt login status");
				attemptedConnect = true;
				facebookConnectPlugin.getLoginStatus(function(response) {
					statusChangeCallback(response);
				}, function(response) {
					console.log(JSON.stringify(response));
					fbStatusProblem();
				});
			} else {
				console.log("Facebook wasn't ready yet for attempt");
				fbStatusProblem();
			}
		}

**Comment by peterpeterparker** [comment]
@guyman the stacktrace you posted above

> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
> at java.net.URLDecoder.decode(URLDecoder.java:137)
> at org.apache.cordova.facebook.ConnectPlugin.makeGraphCall(ConnectPlugin.java:754)
> at org.apache.cordova.facebook.ConnectPlugin.access$200(ConnectPlugin.java:54)
> at org.apache.cordova.facebook.ConnectPlugin$2$1.onCompleted(ConnectPlugin.java:110)

you app request a new permissions requests after a previous login or something but in the meantime the variable `graphPath` end up being null

see `onCompleted` in `registerCallback` in `pluginInitialize()` in `ConnectPlugin.java

Right now I understand how do you land in this situation where `graphPath` is null but `lastGraphContext` isn't, that's weird

what do you do in your `fbStatusProblem`? do you try to reconnect? how?

**Comment by guyman** [comment]
In fbStatusProblem() I just show the Login Screen to the user to let him connect with Google, Facebook or Username/Password.

**Comment by guyman** [comment]
If I can do anything in order to help track the problem I will.
Reproducing is very difficult, but the users do suffer from crashes in a very low frequency which is something we obviously want to avoid.

**Comment by peterpeterparker** [comment]
Honestly reproducing the problem would really help, then it's "just" debugging and finding a solution

Without a clear pattern it's a bit only assumption and I'm a bit afraid that doing a fix to avoid the error breaks something in another app

**Comment by guyman** [comment]
Can it be related to calling "delete app requests" upon login? Can it be related to a user clicking twice on login with Facebook without waiting for the first call to finish processing?

**Comment by peterpeterparker** [comment]
@guyman thx for trying to reproduce the problem but `attemptFBLoginMobile`? there isn't such a method in the plugin

**Comment by guyman** [comment]
@peterpeterparker I was talking about the attempFBLoginMobile() that I attached before which basically just calls facebookConnectPlugin.getLoginStatus()

**Comment by peterpeterparker** [comment]
@guyman understood

then, if the problems happens when you call your method multiple times very fast, the solution is on your side to disabled the action when it was calling once till the action is finished

that's probably the easiest solution

**Comment by guyman** [comment]
@peterpeterparker Yeah that's what i've done. I think that if you are not going to fix it now, you should at least document the fact that this method is not thread safe. Users clicking on a button twice is a common behavior.

**Comment by guyman** [comment]
@peterpeterparker I'm sorry, I'll update one of my old comments. The method that is being called on each button click is:
`facebookConnectPlugin.login(['public_profile','email','user_friends'], function(response) `

**Comment by guyman** [comment]
@peterpeterparker Well the problem is now reproducible. It's just calling facebookConnectPlugin.login multiple times fast.
As a third-party library, documenting thread-safety of functions is something pretty standard. As a "client" of this library, if I knew this method is not thread safe, I would take care for that issue in my code.

**Comment by peterpeterparker** [comment]
@guyman feel free then to submit a PR to extend the documentation if you wish

**Comment by felipedrumond** [comment]
I have the same problem when login-in a second time and having the facebook app installed. The issue is not present if you don't have fb app installed.

After updatind the cordova-plugin-facebook4 version, it didint'work. However, performing a clean install of the plugin solved the problem straight away. 

cordova plugin rd cordova-plugin-facebook4
cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="your_fb_app_id" --variable APP_NAME="your_fb_app_name"
