### ISSUE TITLE
cordovaFacebookPlugin is not defined for browser platform

### ISSUE THREAD

**Issue by LukeeeeBennett** [jeduan/cordova-plugin-facebook4#70]
I bumped into this issue today, is there any further advice? I saw there was an old thread but haven't had a response yet so opened a new issue.

I've noticed it's to do with the fact that when building for the browser platform it's not properly injecting the <js-module src="www/facebook-browser.js" ... library as defined in plugins/cordova-plugin-facebook4/plugin.xml.

I noticed on android and ios that the network logs successfully request the www/facebook-native.js library but on the browser platform there is no attempt to request the www/facebook-browser.js library.

I could refactor the library slightly, include it in my frontend dependencies and inject it or clobber it manually, which would in turn initialize the facebook SDK and allow use of the same API methods for compatibility, but I'd like to avoid the hackyness.

**Comment by olegwn** [comment]
i can confirm this, how to fix it?

**Comment by aldryss** [comment]
I'm having problems with this issue too, is there a clean way to fix it ?

**Comment by LukeeeeBennett** [comment]
It's been a while since I had this error, I believe I hacked a fix together by simply manually requesting the facebook-browser.js resource that is failng to be injected by cordova using the plugin.xml in the browser.

I don't mean to direct anyones attention away from this repo, if I was a better man with twice as many hours in my days I would contribute a fix but instead I moved to using [r-wettstaedt/ngOpenFB](https://github.com/r-wettstaedt/ngOpenFB).

**Comment by aldryss** [comment]
Hi !
Thanks for your reply, I'll keep an eye on OpenFB updates but I switched to
facebookconnect4 because I need appinvites to work and they don't seem to
be implemented on OpenFB.
I'll try to add the JS when I'm not on a device

2016-01-27 5:25 GMT+01:00 Luke Bennett <notifications@github.com>:

> It's been a while since I had this error, I believe I hacked a fix
> together by simply manually requesting the facebook-browser.js resource
> that is failng to be injected by cordova using the plugin.xml in the
> browser.
>
> I don't mean to direct anyones attention away from this repo, if I was a
> better man with twice as many hours in my days I would contribute a fix but
> instead I moved to using r-wettstaedt/ngOpenFB
> <https://github.com/r-wettstaedt/ngOpenFB>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jeduan/cordova-plugin-facebook4/issues/70#issuecomment-175383542>
> .
>



-- 
Aldryss
