### ISSUE TITLE
Dependencies missing

### ISSUE THREAD

**Issue by chadsfatherlali** [jeduan/cordova-plugin-facebook4#700]
Please do not submit support requests or "How to" questions here. Instead, please use channels like [StackOverflow](http://stackoverflow.com/) or the [Ionic forum](https://forum.ionicframework.com)

For issues or feature requests related to the code **in this repository** file a Github issue and provide as much details as possible

**Bug or feature request**

[X] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

**Describe the Bug of feature request**

Dependencies missing

08-31 15:22:37.073 14668-14668/io.ionic.starter E/dalvikvm: Could not find class 'android.view.autofill.AutofillManager', referenced from method com.facebook.internal.Utility.isAutofillAvailable
08-31 15:22:37.102 14668-14668/io.ionic.starter E/com.facebook.internal.AttributionIdentifiers: getAttributionIdentifiers should not be called from the main thread

**Plugin version, OS, devices, etc**

LGE LG-D331 (Android 4.4.2, API 19)
ionic 3.20.0
cordova 8.0.0
cordova-plugin-facebook4 ^2.2.0

**Comment by peterpeterparker** [comment]
I think the problem is not related to the plugin but rather to a conflict you are facing locally aka a support inquiry

Maybe some of the solution listed on Stackoverflow might work https://stackoverflow.com/questions/36816684/android-studio-e-dalvikvm-could-not-find-class-referenced-from-method/39465556

**Comment by chadsfatherlali** [comment]
This is a better solution.

https://stackoverflow.com/questions/52113549/app-getting-stuck-with-e-com-facebook-internal-attributionidentifiers/52113623#52113623
