### ISSUE TITLE
Apps crash and show blank page after install this pluggin.

### ISSUE THREAD

**Issue by tunathoni** [jeduan/cordova-plugin-facebook4#702]
**Bug**

[ x ] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

**Describe the Bug of feature request**

I already install this plugin and follow the steps provided, after i build into android device, the apps show blank page.

**Expected Behavior**

No more error occured

**Plugin version, OS, devices, etc**

I use the latest version of this plugin, i run on Android, iOS

**Additional Context**

I already install it last week, and can run well, but yesterday when i build the apps again, apps show blank page.

**Comment by tunathoni** [comment]
Hi @peterpeterparker why you closed this issue ? have you solve this problem ?

**Comment by peterpeterparker** [comment]
https://github.com/jeduan/cordova-plugin-facebook4/blob/master/.github/issue_template.md

**Comment by bloodknight2010** [comment]
Me too.Same error.How to solve?Pls help me.

**Comment by bloodknight2010** [comment]
I got the solution.It must be same name Google Play Package Name in dev facebook app and wiget id in config.xml.
