### ISSUE TITLE
Plugin Couldn't Make The App Start (Android)

### ISSUE THREAD

**Issue by wargun02** [jeduan/cordova-plugin-facebook4#704]
I can be certain that the below will very likely to re-produce the issue, once the plugin was installed, the app entirely blank screen after running "cordova run android" and even showing LAUNCHED SUCCESS.

**Versions:**
cordova-plugin-facebook4: 2.4.0
cordova: 8.0.0
cordova-android: 7.0.0
Android Studio: 3.1.4 (for Mac) with Android API 28

**To reproduce this:**
1) Fresh install of Android Studio and cordova, accept all licenses from Android `sdkmanager --licenses`. Make sure that app is registered in developers.facebook.com.
2) Terminal: `cordova create appy222 appy222.com appy222`
3) cd into the appy222
4) `cordova plugin add cordova-plugin-facebook4 -v --save --variable APP_ID="whateverid" --variable APP_NAME="Appy222"`
5) insert the xml fragment to cordova-plugin-facebook4's plugin.xml `<config-file parent="/resources" target="./res/values/strings.xml">
        <string name="fb_app_id">$APP_ID</string>
        <string name="fb_app_name">$APP_NAME</string>
      </config-file>`
6) Change the "android-minSdkVersion" to **16**.
7) `cordova platform add android` this will install cordova-android@7.0.0
8) Run by hooking up to the Android mobile phone with develop options enabled. Terminal: `cordova run android`

And the result was a blank screen...black. The app will run fine without cordova-plugin-facebook4.

**Comment by peterpeterparker** [comment]
Plz don't submit support issue, use other channels to do so, like stackoverflow (https://github.com/jeduan/cordova-plugin-facebook4/blob/master/.github/issue_template.md)

Feel free to link your support question here

Just noticed something, why did you set "android-minSdkVersion" to 16? try without doing that and also pay attention to the `ANDROID_SDK_VERSION` see https://github.com/jeduan/cordova-plugin-facebook4/blob/master/docs/android/README.md

**Comment by wargun02** [comment]
Sorry, here you go. The reason to change the android-minSdkVersion to 16 is there as well.

[https://stackoverflow.com/questions/52217275/cordova-plugin-facebook4-couldnt-make-the-app-start-android](https://stackoverflow.com/questions/52217275/cordova-plugin-facebook4-couldnt-make-the-app-start-android)

**Comment by bloodknight2010** [comment]
Me too. I got the solution.It must be same name Google Play Package Name in dev facebook app and wiget id in config.xml.

**Comment by sudarshandk** [comment]
Did anyone find the solution? I am getting the blank screen as well

**Comment by sudarshandk** [comment]
> Me too. I got the solution.It must be same name Google Play Package Name in dev facebook app and wiget id in config.xml.
@bloodknight2010  Can you please elaborate what you did?
