### ISSUE TITLE
how can get the gender using this plugin

### ISSUE THREAD

**Issue by YeisonVelez11** [jeduan/cordova-plugin-facebook4#709]
With this code:

`facebookConnectPlugin.api('/me?fields=email,name,gender,picture&access_token=' + authResponse.accessToken, ["public_profile"],
          function (response) {
`
I am getting this response:
`
{"email":"xxxxx@hotmail.com","name":"xxxx Molina","picture":{"data":{"height":50,"is_silhouette":false,"url":"https://platform-lookaside.fbsbx.com/platform/profilepic/?asid=2076928542548945&height=50&width=50&ext=1539748506&hash=AeRdIrWpWFtDY_k8","width":50}},"id":"2076928542548xxx"}`

**Comment by YeisonVelez11** [comment]
what is the solution???

**Comment by YeisonVelez11** [comment]
The user accepts loggiarse with facebook, but I am unable to obtain that information. apparently it is not possible to obtain it.

**Comment by rutbastoni** [comment]
Again, dive into login documentation, especially for permission request: https://developers.facebook.com/docs/facebook-login/permissions/requesting-and-revoking
You should pass to the login flow the right scope to get the non-basic fields you want.
And again, this will work in sandbox or with test users, until you haven't completed review for your facebook app

**Comment by YeisonVelez11** [comment]
I have currently authenticated using this plugin, and since facebook I have already registered my app. and I only have access to these fields. Additionally, this link informs that it is not possible to access these fields:
https://developers.facebook.com/docs/graph-api/changelog/version3.0

or as I understand you, do I have to obtain some special permits to obtain them?

**Comment by rutbastoni** [comment]
The link states that those fields are deprecated in public profile, that is default fields you get with 'basic' authentication.
If you read further, it also explains that there are some new permissions, like 'user_gender' and so on.
To have this data, it is not enough to authenticate but you need to fully understand the Facebook extended permission flow, and study documentation in here: [https://developers.facebook.com/docs/facebook-login/permissions/overview](url)
Once you do, you'll also understand the difference between simply registering your application on Facebook and submitting it for permissions review.
