### ISSUE TITLE
Blank Dialog - Not Logged In: You are not logged in. Please login and try again.

### ISSUE THREAD

**Issue by lightbeard** [jeduan/cordova-plugin-facebook4#711]
**Screenshot**

![Image of Error](http://lightbeard.github.io/img/fb-login-error2.png)

**Bug or feature request**

[x ] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

**Describe the Bug of feature request**

facebookConnectPlugin.login dialog shows error in screenshot. The only thing that can be done is selection of the X close-out button which results in the following error:

errorCode: "4201"
errorMessage: "User cancelled dialog"
loginError @ facebook.js:13

**Expected Behavior**

Login dialog that provides the option for user to enter facebook username / password if they are not logged in.

**Plugin version, OS, devices, etc**

8.1.1 (cordova-lib@8.1.0)
cordova-plugin-facebook4 3.0.0 "Facebook Connect"
Android 7.1.1
OSX 10.13.6

**code**

https://github.com/lightbeard/reproduce-fb-login
```
document.addEventListener('deviceready', deviceReady, false);

function deviceReady() {

  var fbLoginSuccess = function (userData) {
    console.log("UserInfo: ", userData);
  }

  facebookConnectPlugin.login(["public_profile"], fbLoginSuccess,
    function loginError (error) {
      console.error(error)
    }
  );
}
```

**Comment by peterpeterparker** [comment]
Thx for taking the time to document your problem and to provide a repo but I think that the issue isn't related to the plugin but rather to your config therefore plz use other channels like Stackoverflow for support inquiry, thx in advance

Of course feel free to link the post you will create here

Spontaneously one first thought about your problem would be is that something is missing in your config.xml, see chapter `cordova-android >= 7` in the documentation https://github.com/jeduan/cordova-plugin-facebook4/blob/master/docs/android/README.md 

With android 7.1.1 you probably have to add an config-file to your config.cml

**Comment by lightbeard** [comment]
Thanks. I've posted the problem on stackoverflow:
https://stackoverflow.com/questions/52612610/cordova-plugin-facebook4-blank-dialog-with-not-logged-in-you-are-not-logged

The config.xml suggestion was a good one, but did not solve the issue. I've updated the repo
