### ISSUE TITLE
Login status callback is not executed until locking and unlocking screen on iOS Simulator (works on browser/Android simulator)

### ISSUE THREAD

**Issue by wlin-incaps** [jeduan/cordova-plugin-facebook4#714]
**Bug or feature request**

[x] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

**Describe the Bug of feature request**

When checking login status, the callback is not executing until the iOS simulator is locked and unlocked using the large side button. The behavior on browser and android simulator are okay.

**Expected Behavior**

Expected that the callout would be called soon after invoking getting login status without user intervention.

**Plugin version, OS, devices, etc**

Plugin version 3.1, iOS 11.4 simulated, Cordova 8.1.2, Cordova iOS 4.5.5, Cordova Browser 5.0.4, Cordova Android 7.1.1.

`try{
facebookConnectPlugin.getLoginStatus((response:{status:string, authResponse:any|null}) => {
        this.setState({ ...this.state, status: response.status });
        let storage = window.localStorage;
        if(response.status === 'connected' && response.authResponse) {
          // also has expiresIn, reauthorize_required_in, signedRequest
          const {accessToken, userID} = response.authResponse;
...`

**Comment by wlin-incaps** [comment]
This also occurs with the login call for iOS. I have to lock the screen and unlock before the login alert appears. I have to then lock and unlock for the Facebook login site to load. Finally, I have to lock and unlock for the login site to go away.

**Comment by peterpeterparker** [comment]
just double checked and successfully tested `getLoginStatus` with the iOS simulator. if you are facing a problem it's probably then related to your setup/app, therefore I close the inquiry since I think it's a support request. Plz use other channels to handle it and of course link it here, thx in advance

**Comment by wlin-incaps** [comment]
Reporting back, the issue was the CSP set on index.html. The base project was old, so it didn't have gap: added. Cordova had the proper CSP to use in its whitelist documentation.

Content Security Policy section explains:
https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-whitelist/

**Comment by peterpeterparker** [comment]
@wlin-incaps cool to hear you found your solution and thx for the feedback/documenting it 👍
