### ISSUE TITLE
Documentation for iOS installation if plugin directly installed from Cordova Registry

### ISSUE THREAD

**Issue by jehadja** [jeduan/cordova-plugin-facebook4#715]
thanks for the great work !
i have a problem of bulid crash on IOS i already spend 6 hours to find solution was useless
until i open origin plugin and found this note

<< --- Cordova Registry Warning [iOS]
Installing this plugin directly from Cordova Registry results in Xcode using a broken FacebookSDK.framework, this is because the current publish procedure to NPM breaks symlinks CB-6092. Please install the plugin through a locally cloned copy or re-add the FacebookSDK.framework to Xcode after installation.
------------------------------------------ >>
so i suggest to add it to documentation please !
code for do it

```
cd cordova-plugin-facebook4/src/ios/
curl -o FacebookSDKs-iOS-4.17.0.zip  https://origincache.facebook.com/developers/resources/?id=FacebookSDKs-iOS-4.17.0.zip
unzip -o FacebookSDKs-iOS-4.17.0.zip
```

**Comment by peterpeterparker** [comment]
@jehadja PR are welcome if you would like to add a note in the documentation. Thx in advance

**Comment by fredgalvao** [comment]
@jehadja Which version of cordova are you using? Cordova hasn't had plugin installations default to the old registry for a long time now.

**Comment by guylando** [comment]
Note that the new version requires additional steps to make it work as added to README file.

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out https://www.npmjs.com/package/cordova-plugin-facebook-connect to install the actively maintained fork from npm.
