### ISSUE TITLE
Cordova 7.1.0 + Android 7.1.1 can't compile/make changes to manifest

### ISSUE THREAD

**Issue by globules-io** [jeduan/cordova-plugin-facebook4#718]
**Bug or feature request**

[x] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

**Describe the Bug of feature request**

Unable to build app on Android with Cordova 7.1.0 + Android 7.1.1. 
config file res/values/facebookconnect.xml requested for changes not found at D:\Server\ROOT\MYAPP\platforms\android\res\values\facebookconnect.xml, ignoring
config file res/values/facebookconnect.xml requested for changes not found at D:\Server\ROOT\MYAPP\platforms\android\res\values\facebookconnect.xml, ignoring
Conflict found, edit-config changes from config.xml will overwrite plugin.xml changes
Error: Pruning at selector "/resources" from "D:\Server\ROOT\MYAPP\platforms\android\app\src\main\res\xml\config.xml" went bad.
The system cannot find the path specified.

Config.xml:

     <plugin name="cordova-plugin-facebook4" spec="^3.1.0">
        <variable name="APP_ID" value="123456789" />
        <variable name="APP_NAME" value="MYAPP" />
        <variable name="FACEBOOK_ANDROID_SDK_VERSION" value="4.37.0" />
    </plugin>

    <platform name="android">
          <edit-config file="res/values/strings.xml" mode="add" target="/resources">
            <string name="fb_app_id">123456789</string>
            <string name="fb_app_name">MYAPP</string>
        </edit-config>
    </platform>

Also tried

    <config-file parent="/resources" target="./res/values/strings.xml">
    <config-file parent="/*" target="app/src/main/res/values/strings.xml">

**Plugin version, OS, devices, etc**

Cordova 7.1.0 + Android 7.1.1

**Comment by peterpeterparker** [comment]
1. You didn't tried as displayed in the document (remove `mode` and correct `target`) https://github.com/jeduan/cordova-plugin-facebook4/blob/master/docs/android/README.md

2. Duplicate https://github.com/jeduan/cordova-plugin-facebook4/issues/599

**Comment by globules-io** [comment]
Yes I did test that too, see

"Also tried

<config-file parent="/resources" target="./res/values/strings.xml">"

**Comment by globules-io** [comment]
Please reopen

**Comment by peterpeterparker** [comment]
1. It's a duplicate of 
https://github.com/jeduan/cordova-plugin-facebook4/issues/599

2. It's a support request

**Comment by globules-io** [comment]
Also not suing Cordova v8 but v7.x + Android 7.x

**Comment by globules-io** [comment]
Ok seemed like some workaround was working for some people but I can't do anything here. should I consider this plugin does not work?

**Comment by peterpeterparker** [comment]
Again it's a duplicate of 
https://github.com/jeduan/cordova-plugin-facebook4/issues/599 so if you want to participate to that topic use 
https://github.com/jeduan/cordova-plugin-facebook4/issues/599 or any other channels for support request

**Comment by globules-io** [comment]
Ok got it.
