### ISSUE TITLE
Add LSApplicationQueriesSchemes to plugin.xml (iOS9)

### ISSUE THREAD

**Issue by johnrobertcobbold** [jeduan/cordova-plugin-facebook4#72]
Hi people,

The following has to be added to the app-Info.plist file for iOS9 (https://developers.facebook.com/docs/ios/ios9)

```
<key>LSApplicationQueriesSchemes</key>
<array>
    <string>fbapi</string>
    <string>fb-messenger-api</string>
    <string>fbauth2</string>
    <string>fbshareextension</string>
</array>
```

I believe you can make this happen by editing the plugin's config.xml file.
Meanwhile, I have done so by using a hook (https://gist.github.com/marcocarnazzo/6f01a57d390e8fe3071f)  and adding the above to my app's config.xml 

With this, the plugin does switch to the FB app for authentication. Only pb that I see is that when it switches back to your app, there is a "back to Facebook" which stays in the upper left corner..

**Comment by jeduan** [comment]
https://github.com/jeduan/cordova-plugin-facebook4/blob/master/plugin.xml#L136-L143

**Comment by barocsi** [comment]
What if someone has the AllowArbitraryLoads set to true by default? This exception then disables facebook loading...

**Comment by gslender** [comment]
I think the wrong stuff was added to the plugin.xml

Check this out... isn't the SDK used < 4.5 ??

https://developers.facebook.com/docs/ios/ios9
