### ISSUE TITLE
Installing the packages takes forever

### ISSUE THREAD

**Issue by bellalMohamed** [jeduan/cordova-plugin-facebook4#720]
[x] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

**Describe the Bug of feature request**

npm install cordova-plugin-facebook4 takes forever even on high-speed network connections

**Plugin version, OS, devices, etc**

Ionic:

   ionic (Ionic CLI)  : 4.0.6 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.5

System:

   ios-deploy : 1.9.2
   NodeJS     : v8.9.2 (/usr/local/Cellar/node/8.9.2/bin/node)
   npm        : 6.4.1
   OS         : macOS High Sierra
   Xcode      : Xcode 10.0 Build version 10A255

Environment:

   ANDROID_HOME : not set

**Comment by peterpeterparker** [comment]
Nothing we could do on the plugin side. The problem is on your side or somewhere else, like on the npm side, but not related to the code itself

Also just tested

```
ionic cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="123456789" --variable APP_NAME="myApplication"
```

which just worked fine
