### ISSUE TITLE
Android install issue not adding proper values to strings.xml file

### ISSUE THREAD

**Issue by rolinger** [jeduan/cordova-plugin-facebook4#721]
This might be a simple fix, but why when I install this plugin does it not properly update the `android/app/src/main/res/values/strings.xml` file?

I have to go in and manually add the following two lines to the `strings.xml` file:
```
 <string name="fb_app_id">111122223333444</string>
 <string name="fb_app_name">MyApp</string>
```

I am installing the plugin as:
`cordova plugin add cordova-plugin-facebook4 --variable APP_ID="111122223333444" --variable APP_NAME="MyApp" `

Environment:
```
Cordova CLI: 8.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.3.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Windows 7 SP1
Node Version: v6.10.3
```

**Comment by peterpeterparker** [comment]
See documentation "Installation > Android > Cordova >= v7 chapter"
If still doesn't work, see https://github.com/jeduan/cordova-plugin-facebook4/issues/599

**Comment by rolinger** [comment]
@peterpeterparker - well, I missed that.  read it too quickly and assumed that was referring to the <plugin name="cordova-plugin-facebook4"> that is auto-added to the config.xml file.

either way, we must manually add the platform specific entry in that v7 chapter....why can't it be automated.

**Comment by peterpeterparker** [comment]
PR including backwards compatibility are welcome
