### ISSUE TITLE
Apple Rejects due to "Missing Push Notification Entitlement"

### ISSUE THREAD

**Issue by Mike1707** [jeduan/cordova-plugin-facebook4#724]
**Bug or feature request**

[x] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

**Describe the Bug of feature request**

After building the app with the facebook4 plugin, apple sends an email due to missing push notification entitlement after uploading to appstoreconnect.

Currently, the app isn't using push notifications. Nevertheless, activating the capabilities for the AppId and in Xcode does not help either. 

**Expected Behavior**

The app should be uploaded successfully and therefore not rejected in app approval.

**Plugin version, OS, devices, etc**

Ionic Info:

```
Ionic:

   ionic (Ionic CLI)  : 4.3.1 (/Users/mike/.nvm/versions/node/v10.11.0/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.2, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, (and 13 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/mike/Library/Android/sdk)
   ios-deploy        : 2.0.0
   NodeJS            : v10.11.0 (/Users/mike/.nvm/versions/node/v10.11.0/bin/node)
   npm               : 6.4.1
   OS                : macOS
   Xcode             : Xcode 10.1 Build version 10B61
```

Cordova Plugins: 

```
cordova-background-geolocation 2.13.2 "BackgroundGeolocation"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-appsee 2.4.13 "Appsee"
cordova-plugin-background-fetch 5.4.1 "CDVBackgroundFetch"
cordova-plugin-browsertab 0.2.0 "cordova-plugin-browsertab"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-facebook4 3.1.0 "Facebook Connect"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**Comment by peterpeterparker** [comment]
Actually I don't think that's related to this plugin for the reason that it seems that this issue has never been reported before and that the code and packaging of the plugin didn't changed in months for not saying years. What did changes in the last few months is the Facebook SDK but the plugin has no effect on that

Therefore I close the issue because I really think it isn't related to the plugin itself

If you are able to find in the code a place where this would effectively would happens and could provide a PR, of course ping me, will then reopen the issue

**Comment by cloke** [comment]
FWIW this is happening to me today after installing this plugin. Still trying to track down the issue, but this was the only change to the app.
