### ISSUE TITLE
How .getDeferredApplink() function should work?

### ISSUE THREAD

**Issue by tomilenko** [jeduan/cordova-plugin-facebook4#726]
```               facebookConnectPlugin.activateApp();
                facebookConnectPlugin.getDeferredApplink(
                    function(result) {
                        console.log(JSON.stringify(result));
                    },
                    function(error) {
                        console.log(JSON.stringify(error));
                    }
                );
```
It should look like this? And after that, this plugin should trigger my deferred deep link from the facebook add after app install, right? Or should I add some custom functionality for triggering deep link after fetching in this function?

**Comment by peterpeterparker** [comment]
Plz use other channels like Stackoverflow for support request (like described in https://github.com/jeduan/cordova-plugin-facebook4/blob/master/.github/issue_template.md). Thx in advance
