### ISSUE TITLE
Which version has 4.25 framework for IOS?

### ISSUE THREAD

**Issue by xale76** [jeduan/cordova-plugin-facebook4#727]
Hello problems with build for my Phonegap Build. It's in contrast with 
phonegap-plugin-barcodescanner
that uses same library, and the error is:

`com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/zxing/aztec/AztecDetectorResult.class`

so I think the best solution is to use facebook4 plugin version with 4.25 IOS framework (I read that after that FB added QR Code function), but how to do it? I tried by adding 

```
<platform name="android">
    <framework src="com.facebook.android:facebook-android-sdk:4.25.0" />
</platform>
```
in my config.xml but it seems it's ignored.
Please help me

**Comment by peterpeterparker** [comment]
Plz use other channels for support request, thx for your understanding

Beside that, use `FACEBOOK_ANDROID_SDK_VERSION` to specify a FB sdk version see documentation https://github.com/jeduan/cordova-plugin-facebook4/blob/master/docs/android/README.md
