### ISSUE TITLE
when I click to login facebook, and there was no response.

### ISSUE THREAD

**Issue by SURYAKANTSHARMA** [jeduan/cordova-plugin-facebook4#729]
I got a mistake when I click to login, and there was no response.

-canOpenURL: failed for URL: "fbauth2:/" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
Error Domain=com.facebook.sdk.core Code=3 "(null)" UserInfo={com.facebook.sdk:FBSDKErrorDeveloperMessageKey=Unknown error building URL.}

**Comment by evinkuraga** [comment]
@SURYAKANTSHARMA you closed the issue. Ever fixed it? Remember what it was?

**Comment by SURYAKANTSHARMA** [comment]
Yes it's related to version in pod
