### ISSUE TITLE
[Feature] Analytics: setUserID and updateUserProperties

### ISSUE THREAD

**Issue by ugnich** [jeduan/cordova-plugin-facebook4#730]
Feature request:

Developers can set a unique user ID and some custom user properties to be shown in Facebook Analytics. This feature is included in Facebook SDK for Android, iOS and JavaScript. It would be very useful to be able to use this API in Cordova apps.

More information: https://developers.facebook.com/docs/analytics/send_data/user_properties/

**Comment by peterpeterparker** [comment]
How could that be possible, this plugin doesn't integrate Facebook Analytics? Or are you looking to provide a PR to add Facebook Analytics to this plugin?

**Comment by ugnich** [comment]
Since this plugin already has logEvent and logPurchase, why not setUserID? Usually, these features come together.

**Comment by peterpeterparker** [comment]
Ok Analytics seems to be part of Core right so maybe it could work. Feel free to provide a PR if you are interested in this feature

**Comment by ugnich** [comment]
Sorry, I don't code for iOS/Android. But I'm willing to give $50 to anyone who will implement this feature. Thank's!

**Comment by noahcooper** [comment]
User properties are deprecated by Facebook as of June 2020.

This plugin is deprecated. See `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect.
