### ISSUE TITLE
No json response after login

### ISSUE THREAD

**Issue by pancadewa** [jeduan/cordova-plugin-facebook4#733]
Hi, I have a problem with some Androids, that is when the user logs in by pressing "contunue as" but there is no response to anything, even when trying to log. Login is successful but the dialog is just closed. Has anyone ever experienced this?

![untitled-1](https://user-images.githubusercontent.com/46710281/51175984-56429d00-18ee-11e9-9d40-cdea960c08e1.png)

**Comment by peterpeterparker** [comment]
Plz use other channels like the Ionic forum or Stackoverflow for support requests, thx
