### ISSUE TITLE
Uncaught ReferenceError: facebookConnectPlugin is not defined

### ISSUE THREAD

**Issue by geobotsar** [jeduan/cordova-plugin-facebook4#734]
Been getting Uncaught ReferenceError: facebookConnectPlugin is not defined after the installation of the plugin.
I am using framework7 and android platform version 6.4. 
I have installed the plugin successfully, setting the APP ID and NAME using:

cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="***" --variable APP_NAME="***"

Framework7 is loaded after the deviceready method, so my code is fired after the device is ready. I am building the app and debugging on my android phone.

Below the code am using on the onclick event of my facebook button:

var fbLoginSuccess = function (userData) {
    alert("UserInfo: " + JSON.stringify(userData));
    facebookConnectPlugin.getAccessToken(function(token) {
        alert("Token: " + token);
    }, function(err) {
        alert("Could not get access token: " + err);
    });
}

facebookConnectPlugin.login(["public_profile"],
    fbLoginSuccess,
    function (error) { alert("" + error) }
);

When running the app on my android device i keep getting this error:

Uncaught ReferenceError: facebookConnectPlugin is not defined

Any help would be much appreciated,thanks

**Comment by perfectdeveloper53** [comment]
@geobotsar  I have same issue here when I run android version.

May you help me how to resolve this? 

Thanks in advance.

**Comment by geobotsar** [comment]
@perfectdeveloper53  rookie mistake on my end. I had to include the cordova.js file in my project in order for the plugins to work. Since it was generated when you build the project and was not visible in the project directory, i didnt know that i had to include it.
