### ISSUE TITLE
Support setAutoLogAppEventsEnabled for automatic events delay

### ISSUE THREAD

**Issue by davidanaya** [jeduan/cordova-plugin-facebook4#736]
[X] I'm reporting a feature request

Facebook SDK already has a way to delay the automatic log of events to be compliant with GDPR (privacy protection data in Europe).

https://developers.facebook.com/docs/app-events/getting-started-app-events-android#auto-events

The way to do that is by disabling it and then enabling it back programaticaly with ```setAutoLogAppEventsEnabled(true);```

I think there is no way to do that with this version of the plugin.

Is there any plan to do this?

**Comment by peterpeterparker** [comment]
I have personally no plan to implement anything new other than maintenance

But of course PR are welcome

**Comment by davidanaya** [comment]
Thanks, I submitted a PR
https://github.com/jeduan/cordova-plugin-facebook4/pull/737

I'm not an expert on Android nor cordova plugins, please let me know if you think I left something out.

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect, which supports delaying automatic event collection.
