### ISSUE TITLE
Error on login - Object(...) is not a function

### ISSUE THREAD

**Issue by ErxrilOwl** [jeduan/cordova-plugin-facebook4#738]
Upon calling on login, the function returns some error message.

![image](https://user-images.githubusercontent.com/19930568/51734486-a6281d80-20bf-11e9-85a3-122c02c8158d.png)

My code is just only this piece of code

![image](https://user-images.githubusercontent.com/19930568/51734518-ba6c1a80-20bf-11e9-8f91-ace00fdb7091.png)

**Comment by peterpeterparker** [comment]
Plz don't post support issue in this repo. Furthermore just google your issue you gonna find a lot of answer regarding this question, like I answered it at least 10 times on the Ionic Forum
