### ISSUE TITLE
HTTP error 400

### ISSUE THREAD

**Issue by yjajkiew** [jeduan/cordova-plugin-facebook4#739]
Hi,

I'm here to report a bug my app encounters :

**Description**
My cordova app has the new relic mobile agent installed, which helped me discovered it has a lot of background call to facebook that fails.

The following URL is often called and always results into http error 400 : https://graph.facebook.com/v3.1/XXXXXXXXXXXXXXX/button_auto_detection_device_selection

**Expected Behavior**

No HTTP errors

**Plugin version, OS, devices, etc**

From my statistics this issue exists only on android devices (on multiple devices of different brands) and not iOS.

Maybe this could come from a feature of the android SDK being deprecated ? I'm not sure if this is really a bug but I figured someone here would have an explanation if it's not !

Thank you !

**Comment by peterpeterparker** [comment]
I've got no idea and no time. 

If someone could confirm the issue would be cool?
If there is one, would be also cool to find where it comes from? as OP said maybe deprecated stuffs?

And then of course, PR are welcome

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect.

Facebook's documentation for this Graph API endpoint are pretty sparse (https://developers.facebook.com/docs/graph-api/reference/application/button_auto_detection_device_selection/). I'm not sure when this endpoint would be called, but whatever it is, it's not coming from the plugin. I'd recommend checking to see if this is still happening in the updated plugin, which uses v8 of the Facebook SDKs.
