### ISSUE TITLE
Update Facebook Android SDK for iOS v4.40.0 and Android to v4.40.0

### ISSUE THREAD

**Issue by matrixreal** [jeduan/cordova-plugin-facebook4#740]
Hello,
does this plugin updated to the latest ios sdk 4.40.0 released on January 23, 2019 ?
https://developers.facebook.com/docs/ios/downloads/
thanks for reply

**Comment by peterpeterparker** [comment]
In December I tried the Facebook SDK v4.39.0 but if was buggy (see https://github.com/jeduan/cordova-plugin-facebook4/issues/728)

I could give a try when I've got a bit of time if they fixed there SDK in v4.40.0, thx for pointing out that it was released

**Comment by phiferd** [comment]
FYI, we are using this plugin and received the following email from Facebook yesterday.  Note the **very short timeline** given to upgrade. Did anyone else get this notice?

I will reply to FB and point them to this and related issue, although I'm not sure it will make any difference to them.

--------

Hi,

In working to create a great Platform experience for everyone, we ask developers to ensure the apps they build comply with our Platform Policies. Your app (AppId: XXX) doesn't comply with the following:

Platform Policy 8.2: Native iOS and Android apps that implement Facebook Login must use our official SDKs for Login. 
  
Please make sure your iOS app is using the most recent version of our SDK for Login. You can find more information on our iOS SDK for Login and other Login-related products here: https://developers.facebook.com/docs/facebook-login/ios.
  
You can see our visual example for this policy here: https://developers.facebook.com/policy#7-2-photo.

    
You can access the full list of our Platform Policies here: https://developers.facebook.com/policy/.

Please make the requested changes by 2019-02-03 at 12:00 PST.

Let us know when you've updated your app by replying to this email. If we do not hear back from you, your app will be subject to enforcement. If you have outstanding questions, respond here and we'll do our best to help.

**Comment by peterpeterparker** [comment]
@phiferd which version of the plugin are u using for your app deployed in store?

**Comment by phiferd** [comment]
We are using version 3.10, so maybe we should upgrade. 

However, Facebook replied (moments ago) and said they rechecked the app and there was actually no issue. They said they previously logged in using Facebook and were prompted for username and password, but this time they were sent to the app.  So, I don't know what happened...

**Comment by phiferd** [comment]
Yes, thanks.

**Comment by matrixreal** [comment]
the latest version v4.40.0 fixes almost bugs

**Comment by peterpeterparker** [comment]
Fb changelog (https://developers.facebook.com/docs/ios/change-log-4x/)

v.4.40.0:

```
Fixed

Various bug fixes
```

aka they use that text for every single versions they release (have a look each and every single version they release, they just copy/paste that part of the release notes)

**Comment by matrixreal** [comment]
i don't think so ... but we should try

**Comment by peterpeterparker** [comment]
yep, one of these days personnaly if I've got time

**Comment by matrixreal** [comment]
i did some tests and i can see that the 4.40.0 is stable and fix previous bugs on android and ios
hope that this repo will be updated soon
thanks guys

**Comment by peterpeterparker** [comment]
"...and fix previous bugs..."

Which one? What are the references or issues which suppose to be fixed?

**Comment by peterpeterparker** [comment]
The Facebook SDK v4.40.0 isn't compatible neither with this plugin. I opened a new issue to track the problem 
https://github.com/jeduan/cordova-plugin-facebook4/issues/743
