### ISSUE TITLE
[Feature] user data access expiration

### ISSUE THREAD

**Issue by modestjoust** [jeduan/cordova-plugin-facebook4#741]
**Bug or feature request**

[ ] I'm reporting a reproducible issue with the code
[X] I'm reporting a feature request

**Describe the Bug of feature request**

Need a way to test if access to user data has expired (`isDataAccessExpired`, `dataAccessExpirationTime`) as well as the ability to request the user's permission to reauthorize application's data access(`reauthorizeDataAccess()`), as documented for the sdk here:
https://developers.facebook.com/docs/facebook-login/auth-vs-data/#data-access-expiration

Is this already exposed/available? Or currently being developed?

Thanks for everything, all! :)

**Comment by peterpeterparker** [comment]
Doesn't seems to be already implemented, but someone correct me if I'm wrong.

If I'm not wrong, it isn't being developed neither. 

PR are welcome.

**Comment by AndreiLN** [comment]
Hi, some advance in this?

**Comment by modestjoust** [comment]
Not that I know of - I haven't found the time..

**Comment by AndreiLN** [comment]
Hello,
I found an alternative: Call login again every time, expiration is handled by this.

**Comment by modestjoust** [comment]
Yeah, that's essentially the solution I ended up using for the time being.
:)

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out the actively maintained fork `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect. That plugin now includes `isDataAccessExpired` and `reauthorizeDataAccess`, and the next major release will see an update to the auth response object to include `data_access_expiration_time`.
