### ISSUE TITLE
getLoginStatus is never fired on Android

### ISSUE THREAD

**Issue by ThibautShr** [jeduan/cordova-plugin-facebook4#744]
The facebookConnectPlugin works fine on IOS but on Android, the getLoginStatus callbacks (success / failure) are never fired.
This feature worked well before...

Here are my only logs :

D/SystemWebChromeClient: https://connect.facebook.net/en/sdk/debug.js: Line 3644 : The method FB.getLoginStatus will soon stop working when called from http pages. Please update your site to use https for Facebook Login. https://developers.facebook.com/blog/post/2018/06/08/enforce-https-facebook-login/

I/chromium: [INFO:CONSOLE(3644)] "The method FB.getLoginStatus will soon stop working when called from http pages. Please update your site to use https for Facebook Login. https://developers.facebook.com/blog/post/2018/06/08/enforce-https-facebook-login/", source: https://connect.facebook.net/en/sdk/debug.js (3644)

On my Facebook dashboard, HTTPS is well enforced.

Here is how I include the Facebook SDK from my index.html : 
<script type="text/javascript" src="https://connect.facebook.net/en_US/sdk.js"></script>

Do you know what could be wrong ?

Thanks.

Thibaut.

**Comment by peterpeterparker** [comment]
It looks like a support request, plz use other channel for such purposes.
Also note, nothing changed in the plugin on the browser support (see commit history) since a while.
