### ISSUE TITLE
iOS Reported app Version Not working

### ISSUE THREAD

**Issue by simllll** [jeduan/cordova-plugin-facebook4#749]
I already reviewed the native iOS Facebook SDK, I found

```
 _longVersion = [mainBundle objectForInfoDictionaryKey:@"CFBundleVersion"];
 _shortVersion = [mainBundle objectForInfoDictionaryKey:@"CFBundleShortVersionString"];
```
But in the facebook event stream, the app version is not set. Even though plist entries with bundle version and bundle short version are set.

Has anyone else the same issue? I'm willing to dig further into this,but want to clarify if this problem exists for others as well.
It worked in the past, but for our new app with wkwebview something seems to be different.

Facebook event stream: https://www.facebook.com/events_manager/app/verify

Thanks, please let me know!
Simon

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect.

I checked apps using cordova-plugin-facebook-connect, and the events are logged with the version as expected. If you're still running into issues, feel free to log an issue on cordova-plugin-facebook-connect with more details.
