### ISSUE TITLE
-canOpenURL: failed for URL: "fbauth2: /" - error: "The operation could not be complete. (OSStatus error -10814)"

### ISSUE THREAD

**Issue by papattes** [jeduan/cordova-plugin-facebook4#752]
Hi ! I'm having a bug when calling the facebookConnectPlugin.showDialog function on iOS.

the xcode console returns:
-canOpenURL: failed for URL: "fbauth2: /" - error: "The operation could not be complete. (OSStatus error -10814)" and the callback error is called with NULL error

I tried to add fbauth2 in my whitelist without result.

I add in the info.plist file (according to facebook recommendation) without result either.
```

<Key> LSApplicationQueriesSchemes </ key>
<Array>
<String> fbapi </ string>
<String> fbapi20130214 </ string>
<String> fbapi20130410 </ string>
<String> fbapi20130702 </ string>
<String> fbapi20131010 </ string>
<String> fbapi20131219 </ string>
<String> fbapi20140410 </ string>
<String> fbapi20140116 </ string>
<String> fbapi20150313 </ string>
<String> fbapi20150629 </ string>
<String> fbapi20160328 </ string>
<String> fbauth </ string>
<String> fbauth2 </ string>
<String> fb-messenger-api20140430 </ string>
<String> fb-messenger-platform-20150128 </ string>
<String> fb-messenger-platform-20150218 </ string>
<String> fb-messenger-platform-20150305 </ string>
<String> fb-messenger-api </ string>
<String> fbshareextension </ string>
</ Array>
```

OS : iOS 12
Plugin version : 4.2.1

**Comment by papattes** [comment]
It's my fault !
canOpenURL return "NO" because I do not have the Facebook app installed on the phone. In addition, I used dialog.share_native or dialog.share_sheet (depending on the version of iOS). As a result, this method was not available.

Leaving the dialog in automatic (without defining it) it works properly.

**Comment by okanseremet** [comment]
Problem still exists for me. Cordova 8.1.2 and cordova-ios 5.0.1. What if a user has no facebook app on the phone?

**Comment by pghoratiu** [comment]
I encountered the same issue recently on an old Ionic 3 project with:
cordova-ios: 4.5 
cordova: 8.1.2
and noticed that it works fine when I build my mobile app with XCode 10.x but I get the error above when building with XCode 11.x.

**Comment by amritk** [comment]
I'm getting this error as well, how can we use this plugin if they don't have the app installed? Shouldn't it just launch a child browser like on android?

**Comment by pghoratiu** [comment]
I don't have this issue after downgrade of XCode to version 10.3.
If you use latest Xcode 11.x you will need to use latest cordova and cordova-ios versions.

**Comment by evinkuraga** [comment]
Did anyone manage to get it to work without the facebook app installed?

**Comment by pghoratiu** [comment]
For me it works without the facebook app, there is no dependency between the two.

**Comment by evinkuraga** [comment]
> For me it works without the facebook app, there is no dependency between the two.

You managed to get it to work on iOS? It only worked if you downgraded to xcode? 
Currently am getting this issue with cordova ios 5.0.0 and xcode 11

**Comment by pghoratiu** [comment]
I'm currently running with the latest version of cordova-ios (5.1.1) and cordova-plugin-facebook4 and XCode 11.3 and it's working for me.

**Comment by evinkuraga** [comment]
For those who land here, I resolved the issue by:
Updating cordova ios to 5.1.1
xcode v11 (didn't update it.)
removing platform, removing facebook plugin
readding plugin and plugin

It works on ios & android regardless of whether you have app installed. 
thanks to @pghoratiu for help
