### ISSUE TITLE
A plugin you are using requires a preference: FACEBOOK_ANDROID_SDK_VERSION

### ISSUE THREAD

**Issue by fgubert** [jeduan/cordova-plugin-facebook4#753]
**Bug**

[x] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

**Describe the Bug of feature request**

I was using version 1.7.4 in my app, but i had to upgrade because of the minSdkVersion on phonegap Build. When i try to install the last version, and then compile, i got this error:
Error - A plugin you are using requires a preference: FACEBOOK_ANDROID_SDK_VERSION

My app is build on Phonegap (last version), and compiled on https://build.phonegap.com

Full compile log from Phonegap Build:
https://pastebin.com/A93076R8

My Config file:

`
<preference name="ANDROID_SDK_VERSION" value="4.40.0" />
<preference name="FACEBOOK_ANDROID_SDK_VERSION" value="4.40.0" />
<plugin name="cordova-plugin-facebook4" spec="4.2.1">
        <variable name="APP_ID" value="172419546878979" />
        <variable name="APP_NAME" value="TopInvest - Integração APP" />
        <variable name="FACEBOOK_HYBRID_APP_EVENTS" value="false" />
        <variable name="FACEBOOK_ANDROID_SDK_VERSION" value="4.40.0" />
    </plugin>
    <config-file parent="/resources" target="./res/values/strings.xml">
        <string name="fb_app_id">172419546878979</string>
        <string name="fb_app_name">TopInvest - Integração APP</string>
    </config-file>`

I even tried to create a new app from scratch and compile, and got the same error.

Full config file:
https://pastebin.com/WwSX2hVT

**Expected Behavior**

To compile without errors

**Plugin version, OS, devices, etc**

Plugin Version: 4.40.0
Platforms: Android / iOS / Browser

**Comment by peterpeterparker** [comment]
Plz use other channels like Stackoverflow for support request

That being it's probably because your cordova/phonegap version is too old

You could have a look to:

https://github.com/jeduan/cordova-plugin-facebook4/tree/master/docs/android

and

https://github.com/jeduan/cordova-plugin-facebook4/issues/599

**Comment by vpc30** [comment]
@fgubert Did you find a solution to this problem? I've also tried to build my application through build.phonegap.com, but I've encountered the same issue.

**Comment by fgubert** [comment]
@vpc30 For what i see, is something related to another plugin that i use that cause some kind of conflict.
The only way that worked for me was trying older versions until i find one that worked. 
I'm currently using the version **4.2.1**

**Comment by fgubert** [comment]
@mgh-html not using the plugin anymore. Too much problems.
And leaving cordova/phonegap as well.
