### ISSUE TITLE
Upgrade to Facebook Android SDK 4.41.0?

### ISSUE THREAD

**Issue by phiferd** [jeduan/cordova-plugin-facebook4#759]
I'm seeing app crashes due to a bug in the Facebook Android SDK Java library that was recently fixed here:

https://github.com/facebook/facebook-android-sdk/commit/66d9c6288eb95bfa0a583d00abfd751cbbd763b5

The fix is included in [Facebook's SDK version 4.41.0](https://github.com/facebook/facebook-android-sdk/releases/tag/sdk-version-4.41.0). I realize it has only been out for 26 days, but I just wanted to see if others are having this issue and if there is a timeline for upgrading.

Including crash logs line from our app in case others are looking for the same:

> Fatal Exception: java.lang.NullPointerException
> Attempt to invoke virtual method 'boolean org.json.JSONObject.optBoolean(java.lang.String, boolean)' on a null object reference
> com.facebook.UserSettingsManager$1.run

**Comment by phiferd** [comment]
Does anyone have any insight on what ultimately causes the code to get into this state?  If there's something I can do to prevent the NPE at the application level (e.g. "make sure you call X before you call Y") that would be fine as well.  I can ask the same question on the FB SDK repo, but I assume they will just instruct me to download the updated version.

**Comment by diegodotta** [comment]
Yeah, same here!

**Comment by jayantpaliwal** [comment]
same here!

**Comment by peterpeterparker** [comment]
A new version of the plugin v5.0.0 has been released which include Fb SDK v5.0.2 thx to @guylando PR #751
