### ISSUE TITLE
does this work with ngcordova?

### ISSUE THREAD

**Issue by Freundschaft** [jeduan/cordova-plugin-facebook4#76]

**Comment by Freundschaft** [comment]
I have an issue where only the browser is opened even though I installed cordova plugin facebook4 :(

**Comment by Freundschaft** [comment]
never mind now it worked

**Comment by TonGarcia** [comment]
No, it didn't. how to add it plugin to ionic through ngCordova?

**Comment by fredgalvao** [comment]
@TonGarcia  That's an issue to be created on ionic native, not on this plugin.
`O lugar certo pra reportar problemas com o ngCordova ou ionic é nos repositórios do ionic, pois este plugin não mantém nada relacionado ao ionic.`
