### ISSUE TITLE
config file res/values/facebookconnect.xml requested for changes not found

### ISSUE THREAD

**Issue by ThorvaldAagaard** [jeduan/cordova-plugin-facebook4#761]
**Bug or feature request**

[ ] I'm reporting a reproducible issue with the code
[X] I'm reporting a feature request

**Describe the Bug of feature request**

I am getting this warning each time I build and would like to get rid of it
```config file res/values/facebookconnect.xml requested for changes not found at <my project>\platforms\android\res\values\facebookconnect.xml, ignoring```

**Expected Behavior**

According to the plugin.xml the copy statement is for Cordova 6, but I am using Cordova 7

**Plugin version, OS, devices, etc**

```
Ionic:

   ionic (Ionic CLI)  : 4.12.0 
   Ionic Framework    : ionic-angular 3.9.4
   @ionic/app-scripts : 3.2.3

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.2, browser 5.0.4, ios 4.5.4
   Cordova Plugins       : cordova-plugin-ionic-webview 4.0.1, (and 34 other plugins)

System:

   Android SDK Tools : 26.1.1 
   NodeJS            : v10.15.0 
   npm               : 6.5.0
   OS                : Windows 10
```

**Sample repo**

Can be done using the ionic starter template and then add this plugin

**Comment by AmrAlmagic** [comment]
This error occurs with me when the names of icons in path 'resources\android\icon' are incorrect.
solved by edit to correction name of icons

**Comment by ThorvaldAagaard** [comment]
@AmrAlmagic Can you show, what you did change?

I have the following files in that directory
![image](https://user-images.githubusercontent.com/10560652/59466962-d4b85200-8e2e-11e9-94e6-3e95fd48b1ef.png)

And my config.xml has these references
![image](https://user-images.githubusercontent.com/10560652/59467006-ee599980-8e2e-11e9-9759-8b4cbfb1f44e.png)

And it is strange that icons could caused the above error

**Comment by AmrAlmagic** [comment]
@ThorvaldAagaard 
your names of icons and path of them in config.xml are correct !.

> This error occurs with me when the names of icons in path 'resources\android\icon' are incorrect.
solved by edit to correction name of icons

That's happened to me!

can you get a screenshot of the issue occurring to you?

**Comment by ThorvaldAagaard** [comment]
Each time i build for android I get this

![image](https://user-images.githubusercontent.com/10560652/59966454-5e49dd00-951d-11e9-8da0-07c290b9bedc.png)

The app works fine

building with --verbose does not add much extra information
![image](https://user-images.githubusercontent.com/10560652/59966453-525e1b00-951d-11e9-8200-fafe402db468.png)

**Comment by AmrAlmagic** [comment]
Are you try to remove plugins and platforms and install them again?!

**Comment by ThorvaldAagaard** [comment]
I just found this
https://github.com/jeduan/cordova-plugin-facebook4/issues/599#issuecomment-461505609
seems it works as intended to support bordova 6 and 7+

**Comment by guylando** [comment]
I read somewhere that this error can happen 3 times in android build but it can be safely ignored and it shouldn't influence anything.

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect. The new plugin works without issue on cordova-android 7 (and later versions).
