### ISSUE TITLE
cordova-android@8.0.0 issue

### ISSUE THREAD

**Issue by syonip** [jeduan/cordova-plugin-facebook4#763]
[ ] I'm reporting a reproducible issue with the code

Using cordova 9 (android platform version 8) doesn't compile. 

```
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 15 cannot be smaller than version 19 declared in library [:CordovaLib]
```

**Expected Behavior**

Should compile

**Plugin version, OS, devices, etc**

Plugin version: 4.2.1
Cordova version: 9
Android platform version: 8

**Sample repo**

https://github.com/syonip/fb-plugin-error

**Additional Context**

To reproduce:
```
cordova create fbtest com.example.fbtest FBTest
cd fbtest
cordova platform add android
cordova plugin add cordova-plugin-facebook4 --variable APP_ID=value --variable APP_NAME=value
cordova build android
```

> When forcing cordova-android@7.1.4 the project compiles successfully

**Comment by Ladekarl** [comment]
I had the same error, however I dont think it has anything specifically to do with this plugin as I had it even before installing.

I solved it by changing the minSdkVersion to 19 in config.xml:

`<preference name="android-minSdkVersion" value="19" />`

And then removing the platform and adding it again:

`cordova platform remove android`
`cordova platform add android@8.0`

**Comment by peterpeterparker** [comment]
Plz use other channels for support request thx. 

P.S.: I just tested with Cordova v9 and Android 8.0.0 and it worked well

**Comment by syonip** [comment]
Hi @peterpeterparker,
I think this is more of a bug report than a support request.
I just checked with the reproduction steps above, and still the same error.
Did you also use the same reproduction steps?
```
cordova create fbtest com.example.fbtest FBTest
cd fbtest
cordova platform add android
cordova plugin add cordova-plugin-facebook4 --variable APP_ID=value --variable APP_NAME=value
cordova build android
```

**Comment by peterpeterparker** [comment]
Like I said I just tested it successfully with  Cordova v9 and Android 8.0.0

```
ionic start
cd fbtest
ionic cordova platform add android
ionic cordova plugin add cordova-plugin-facebook4 --variable APP_ID=value --variable APP_NAME=value
ionic cordova build android
```

try @Ladekarl solution provided above, if doesn't work, plz use another channel, thx in advance for your comprehension
