### ISSUE TITLE
Unable to sign in at first time.

### ISSUE THREAD

**Issue by kalaiprakash93** [jeduan/cordova-plugin-facebook4#768]
Whenever, I am try to login at first time the Facebook  login is not working.
It returns error code 10. I couldn't able to see the proper error message also.

**Comment by mino922** [comment]
I'm also seeing this issue. The login fails the first time and my app crashes. Then I relaunch and I can login fine. Any ideas?

There are no errors messages.

**Comment by peterpeterparker** [comment]
Plz use other channels for support request, thx
