### ISSUE TITLE
Facebook Login Error: Please try again later

### ISSUE THREAD

**Issue by kennyalmendral** [jeduan/cordova-plugin-facebook4#769]
Hello, I've been using this plugin for some time and it's working just fine... However, recently it doesn't anymore, everytime I click the facebook login button it goes to facebook and just shows the following error message:

**Login Error: There is an error in logging you into this application. Please try again later.**

_Screenshot:_ https://cdn1.imggmi.com/uploads/2019/5/27/d81a7b9bc566d0f08b2a94fc1f273ab8-full.jpg

Anyone else currently experiencing this? I tried to start from a blank project from scratch, installed the dependencies and still I got the same error.

Here's the straightforward login function:

```javascript
loginAction() {
  this.fb.login(['public_profile', 'user_photos', 'email']).then((res: FacebookLoginResponse) => {
    console.log(res);
  }).catch((e) => {
    console.log('Error logging into Facebook', e);
  });
}
```

...and here's the `ionic info`:

```
Ionic:

   ionic (Ionic CLI)  : 4.10.3 (C:\Users\Kenny\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 4 other plugins)

System:

   NodeJS : v10.15.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

Thanks everyone!

**Comment by gesielrosa** [comment]
Same issue for me.

**Comment by gesielrosa** [comment]
@kennyalmendral, remove 'user_photos' from permissions.

**Comment by kennyalmendral** [comment]
@gesielrosa uhmmm... I need the `user_photos` though :|

**Comment by gesielrosa** [comment]
Go to "https://developers.facebook.com/apps/### your app id ####/app-review/my-permissions/"
and make a request for user_photos. (Sorry, bad english).

**Comment by kennyalmendral** [comment]
Thanks @gesielrosa , will try that one

**Comment by Chuckv01** [comment]
@kennyalmendral were you able to solve this issue? Facing the same thing over here.

**Comment by kennyalmendral** [comment]
@Chuckv01 can you try deploying it on an actual device? 

`ionic cordova run android --prod --device`

The error didn't show up when I test it on an actual device and was able to login through facebook without problems.

**Comment by chrisweight** [comment]
@kennyalmendral ^^ We've seen this on-device in a real-world production deployment

**Comment by amritk** [comment]
Also seeing the same issue

**Comment by panassidi** [comment]
Same problem for me, cordova 8.

**Comment by Chuckv01** [comment]
This ended up being an issue with the Android keystore hash. We had the proper **development** hash in the facebook console, but the hash for our **production** build was incorrect. The issue only happened when the facebook app is installed on the device, and the app was downloaded from Google Play.

Once the proper keystore hash was saved into the facebook dev console this error went away.

**Comment by peterpeterparker** [comment]
Thx for using other channels for support request. I hope in the meantime you found a solution.
