### ISSUE TITLE
"appInvite" not really work in android

### ISSUE THREAD

**Issue by bau720123** [jeduan/cordova-plugin-facebook4#77]
hi @jeduan 
I am using PGB cli-5.2.0 with your latest plugin from npm
![01](https://cloud.githubusercontent.com/assets/5110085/11019057/d8801e5a-8620-11e5-82ce-bbf7d3c73ff6.jpg)
![02](https://cloud.githubusercontent.com/assets/5110085/11019058/dd08909c-8620-11e5-9091-f09b2d38a019.jpg)

**Comment by michel-eu** [comment]
You can't use common URLs, they must be AppLinks type. See more in https://developers.facebook.com/docs/applinks/add-to-content

**Comment by bau720123** [comment]
thanks @michel-eu 
problem solved in Android
iOS not try yet
if anything wrong，I will post a new one

**Comment by bau720123** [comment]
hi @michel-eu 
for now I am using 1.6.3 version
https://www.npmjs.com/package/cordova-plugin-facebook4
but the appinvite still have some trouble with Android and iOS
just like above picture
any idea ?

these are my code
```
facebookConnectPlugin.appInvite(    
  {
  url: "http://www.littlebau.com/phonegap/invite.php",
  picture: "http://36.media.tumblr.com/c066cc2238103856c9ac506faa6f3bc2/tumblr_nmstmqtuo81tssmyno1_1280.jpg"
  },
... 
```

**Comment by bau720123** [comment]
hi @Hirbod 
why close it ?

**Comment by bau720123** [comment]
hi @jeduan @michel-eu 
any suggest with my question ?
