### ISSUE TITLE
Is not returning user profile picture.

### ISSUE THREAD

**Issue by andrisole92** [jeduan/cordova-plugin-facebook4#772]
Does anyone know permission for a profile picture? On Facebook developer page it says default, however when I use `home.fb.login(['email','default'])`, it says `Invalid Scope: default
`.

When I am trying `home.fb.login(['email','public_profile'])`, there is no profile picture in response.

Looking forward to hearing from you soon.

**Comment by edgargrs** [comment]
try this

```
$cordovaFacebook.login(["public_profile", "email"]).then(function(success) {
   $cordovaFacebook.api("me?fields=id,name,email,picture.width(500).height(500)", ["public_profile", "email"]).then(function(succ) {
      var img = succ.picture.data.url;  // <- img src
   }, function(error) {
      // Handle your error here
   });
}, function(error) {
 // Handle your error here
});
````

**Comment by MoisesValera** [comment]
This one worked for me:

`    facebookConnectPlugin.login(["public_profile", "email"], function(socialAuthData) {
        console.log(socialAuthData);
        facebookConnectPlugin.api("me?fields=id,name,email,picture.width(500).height(500)", ["public_profile", "email"], function(profileData) {
           console.log(profileData);
        }, function(error) {
          console.log(error);
        });
    }, function(error) {
      console.log(error);
    });   
`

**Comment by MoisesValera** [comment]
@andrisole92 This one worked for me:

```
facebookConnectPlugin.login(["public_profile", "email"], function(socialAuthData) {
    console.log(socialAuthData);
    facebookConnectPlugin.api("me?fields=id,name,email,picture.width(500).height(500)", ["public_profile", "email"], function(profileData) {
        console.log(profileData);
    }, function(error) {
        console.log(error);
    });
}, function(error) {
    console.log(error);
});
```

**Comment by peterpeterparker** [comment]
Plz use other channels for support request, thx
