### ISSUE TITLE
This plugin and the privacy of our users

### ISSUE THREAD

**Issue by Bramzor** [jeduan/cordova-plugin-facebook4#775]
When installing the plugin to use for example Facebook Login, it will actually install and load the full SDK which includes even Facebook Analytics.

How can we make sure that we protect the privacy of our users, even if we just want to add Facebook Login for the users that want it. But this should not load Facebook Analytics for everyone else which will directly impact their privacy.

Should we all move away from social logins like Facebook Login in the future? In a few months Apple Login will also force everyone who is currently using a social login to add Apple Login or they will be rejecting your app from the App Store. Just another reason to remove it anyway?

**Comment by peterpeterparker** [comment]
Plz use other channels for support inquiry, thx in advance
