### ISSUE TITLE
Cannot build for cordova-android@8.0.0

### ISSUE THREAD

**Issue by adamulator** [jeduan/cordova-plugin-facebook4#778]
**Bug or feature request**

[x] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

**Describe the Bug of feature request**

Hello, I'm using cordova version 8.1.2 with android platform version 8.0.0 to build my Ionic 3 app. Everything worked fine on android platform version 7.0.0, however it stopped working after changing to 8.0.0 (which I did to solve other issue with Firebase plugin).
`> Task :app:mergeDebugResources FAILED
[string/fb_app_id] /Users/macbook/Projects/touralert-app-kopia/platforms/android/app/src/main/res/values/facebookconnect.xml    [string/fb_app_id] /Users/macbook/Projects/touralert-app-kopia/platforms/android/app/src/main/res/values/strings.xml: Error: Duplicate resources
[string/fb_app_name] /Users/macbook/Projects/touralert-app-kopia/platforms/android/app/src/main/res/values/facebookconnect.xml  [string/fb_app_name] /Users/macbook/Projects/touralert-app-kopia/platforms/android/app/src/main/res/values/strings.xml: Error: Duplicate resources`

**Expected Behavior**

Should compile without errors.

**Plugin version, OS, devices, etc**

Plugin version 5.0.0
Cordova version: 8.0.0
Android platform version: 8.0.0

** Additional Context**

These are my excerpts from config.xml regarding Facebook:
```
<platform name="android">
   <config-file mode="add" parent="/resources" target="./res/values/strings.xml">
     <string name="fb_app_id">...</string>
     <string name="fb_app_name">...</string>
   </config-file>
</platform>
<plugin name="cordova-plugin-facebook4" spec="^5.0.0">
        <variable name="APP_ID" value="..." />
        <variable name="APP_NAME" value="..." />
        <variable name="FACEBOOK_HYBRID_APP_EVENTS" value="false" />
        <variable name="FACEBOOK_ANDROID_SDK_VERSION" value="5.0.2" />
</plugin>
```

Thanks in advance

**Comment by adamulator** [comment]
Fixed by removing
```
<config-file parent="/resources" target="./res/values/strings.xml">
            <string name="fb_app_id">286560168717561</string>
            <string name="fb_app_name">Wakacje.IN</string>
</config-file>
```
from config.xml.

**Comment by zxcfdxc** [comment]
Thanks, it works for me
> Fixed by removing
> 
> ```
> <config-file parent="/resources" target="./res/values/strings.xml">
>             <string name="fb_app_id">...</string>
>             <string name="fb_app_name">...</string>
> </config-file>
> ```
> 
> from config.xml.
