### ISSUE TITLE
IOS crash - FB handle url loop when using FB app to login

### ISSUE THREAD

**Issue by pietromanneschi** [jeduan/cordova-plugin-facebook4#779]
Hello,
I have a problem with version 5.0.0 of the plugin, in a pretty standard cordova app with various plugins.

When calling the facebook login, the app opens the standard facebook page where you can choose to login with FB App or with email and password. 
If you go with email and password everything works fine, but if you chose to login with FB app, when coming back to your application, it just crashes.

I tried this with xcode console open, and at the time of crashes the logger said this:
`FB handle url using application:openURL:options: <facebook access token string here>`

Looks like it goes in an infinite loop, since it continuously try to read the openURL without success. And this leads to a crash when you not have the debugger attached.

For now I have solved the issue downgrading to v4.2.1 of the plugin.
Any ideas?

**Comment by peterpeterparker** [comment]
Duplicate https://github.com/jeduan/cordova-plugin-facebook4/issues/776

**Comment by pietromanneschi** [comment]
Sorry but it doesn't seem like a duplicate to me.

I can login with facebook, the problem is when i come back to my application.

**Comment by pietromanneschi** [comment]
Here is my package.json with list of cordova plugins.

{
    "name": "fly-app-cordova",
    "version": "0.1.0",
    "private": true,
    "scripts": {
        "serve": "vue-cli-service serve",
        "build": "vue-cli-service build --dest www",
        "ios": "vue-cli-service build --dest www && cordova build ios",
        "android": "vue-cli-service build --dest www && cordova run android"
    },
    "dependencies": {
        "@fortawesome/fontawesome-free": "^5.4.1",
        "axios": "^0.19.0",
        "bootstrap": "^4.3.1",
        **"cordova": "^8.1.2",
        "cordova-android": "^7.0.0",
        "cordova-ios": "^4.5.5",
        "cordova-plugin-add-swift-support": "^2.0.2",
        "cordova-plugin-camera": "^4.0.3",
        "cordova-plugin-device": "^2.0.2",
        "cordova-plugin-facebook4": "4.2.1",
        "cordova-plugin-file": "^6.0.1",
        "cordova-plugin-file-transfer": "^1.7.1",
        "cordova-plugin-geolocation": "^4.0.1",
        "cordova-plugin-googleplus": "^7.0.1",
        "cordova-plugin-inappbrowser": "^3.0.0",
        "cordova-plugin-ionic-keyboard": "^2.1.3",
        "cordova-plugin-qrscanner": "^3.0.1",
        "cordova-plugin-screen-orientation": "^3.0.1",
        "cordova-plugin-statusbar": "^2.4.2",
        "cordova-plugin-whitelist": "^1.3.3",
        "cordova-plugin-x-socialsharing": "^5.4.7",**
        "es6-promise-plugin": "^4.2.2",
        "fastclick": "^1.0.6",
        "jquery": "^3.4.1",
        "moment": "^2.24.0",
        "phonegap-plugin-multidex": "^1.0.0",
        "phonegap-plugin-push": "^2.1.3",
        "swiper": "^4.4.6",
        "vue": "^2.5.17",
        "vue-class-component": "^6.0.0",
        "vue-js-modal": "^1.3.26",
        "vue-property-decorator": "^7.0.0",
        "vue-range-slider": "^0.6.0",
        "vue-router": "^3.0.1",
        "vue2-collapse": "^1.0.15",
        "vuex": "^3.0.1"
    },
    "devDependencies": {
        "@vue/cli-plugin-babel": "^3.4.1",
        "@vue/cli-plugin-typescript": "^3.8.1",
        "@vue/cli-service": "^3.8.0",
        "typescript": "^3.0.0",
        "vue-template-compiler": "^2.5.17"
    },
    "cordova": {
        "platforms": [
            "android",
            "ios"
        ],
        "plugins": {
            "cordova-plugin-camera": {},
            "cordova-plugin-whitelist": {},
            "cordova-plugin-inappbrowser": {},
            "cordova-plugin-device": {},
            "phonegap-plugin-multidex": {},
            "cordova-plugin-screen-orientation": {},
            "cordova-plugin-ionic-keyboard": {},
            "cordova-plugin-statusbar": {},
            "cordova-plugin-file-transfer": {},
            "phonegap-plugin-push": {
                "FCM_VERSION": "11.8.0"
            },
            "cordova-plugin-geolocation": {},
            "cordova-plugin-x-socialsharing": {
                "ANDROID_SUPPORT_V4_VERSION": "24.1.1+"
            },
            "cordova-plugin-qrscanner": {},
            "cordova-plugin-facebook4": {
                "APP_ID": "xxxxxxxxxxxx",
                "APP_NAME": "XXXXXX",
                "FACEBOOK_HYBRID_APP_EVENTS": "false",
                "FACEBOOK_ANDROID_SDK_VERSION": "4.40.0"
            }
        }
    }
}

**Comment by peterpeterparker** [comment]
The above log isn't related to your error therefore I'm guessing that it's a duplicate as downgrading solve your problem.

If you think it isn't then please provide more logs of the error, a sample app to reproduce the problem, steps to reproduce the problem etc.

**Comment by mcherubin** [comment]
@pietromanneschi did you solve the problem? I've the same issue and I need SDK 5.0

**Comment by duncanreid** [comment]
@pietromanneschi I had the same issue and I too was using "cordova-ios": "^4.5.5".  Happened across this [comment](https://github.com/jeduan/cordova-plugin-facebook4/issues/750#issuecomment-466036388) by @guylando and upgraded cordova-ios to 5.0.1 and the problem went away.

**Comment by pietromanneschi** [comment]
hey, yes i confirm that upgrading cordova ios version worked.
If you don't want to change the package.json manually, you can just 
cordova platform rm ios
and then
cordova platform add ios@5

then build and proceed as always.
Thank you for the tip @duncanreid

**Comment by rlogical-techsoft** [comment]
> @pietromanneschi did you solve the problem? I've the same issue and I need SDK 5.0

Worked for me Thanks

**Comment by rlogical-techsoft** [comment]
> @pietromanneschi I had the same issue and I too was using "cordova-ios": "^4.5.5". Happened across this [comment](https://github.com/jeduan/cordova-plugin-facebook4/issues/750#issuecomment-466036388) by @guylando and upgraded cordova-ios to 5.0.1 and the problem went away.

Worked for me Thanks

**Comment by kleeb** [comment]
this still occurs on iOS 12
