### ISSUE TITLE
not compatible with ionic state restore

### ISSUE THREAD

**Issue by Freundschaft** [jeduan/cordova-plugin-facebook4#78]
I have the problem that when I just have the plugin in my package.json, then the plugin will always install twice due to it adding in the config.xml with
```xml
<plugin name="cordova-plugin-facebook4" spec="~1.3.0-0">
        <variable name="APP_ID" value="1504451109842017" />
        <variable name="APP_NAME" value="RoadAtlas" />
    </plugin>
```
but if I remove that entry and only use the one in package.json, then the plugin will never launch the facebook app during login, instead showing me a browser login prompt.
That issue does not exist with the wizcorp plugin, can someone help?

Cheers

**Comment by jeduan** [comment]
The browser login prompt (with a SFSafariView) is the latest supported login method with Facebook SDK. If you download the SDK and run the examples, that's the behaviour you'll get. This is not a bug.
