### ISSUE TITLE
iOS App crashes on startUp when installing the plugin

### ISSUE THREAD

**Issue by ldiaz** [jeduan/cordova-plugin-facebook4#780]
Hello guys, first of all thanks for your hard work. Recently we added support for ionic-capacitor in our app. Unfortunately we have some issues with the plugin. App crashes when trying to open, we created a blank app using ionic blank template just installed the plugin and the crash happens too.  

[X ] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

App crashes reporting error. 
```

2019-07-09 23:30:06.090014-0500 App[32344:3358188] +[FBSDKBasicUtility objectForJSONString:error:]: unrecognized selector sent to class 0x10de44ae0
2019-07-09 23:30:06.099055-0500 App[32344:3358188] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[FBSDKBasicUtility objectForJSONString:error:]: unrecognized selector sent to class 0x10de44ae0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001116db6fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010ef22ac5 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001116f99b4 +[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00000001116e0443 ___forwarding___ + 1443
	4   CoreFoundation                      0x00000001116e2238 _CF_forwarding_prep_0 + 120
	5   CordovaPlugins                      0x000000010ddc0037 +[FBSDKAppEventsUtility
....  full log at error_output.log
```

Here is a repo with a blank app that reproduces the error. 
[https://github.com/ldiaz/cordova-plugin-facebook4/tree/master](https://github.com/ldiaz/cordova-plugin-facebook4/tree/master)

The repo describes the commands executed to create the app from official documentation,a and many other guides.

We try many "workarounds"  for similar issues from stackoverflow.
* -ObjC   flag, which is already configured by the ionic
* Force_load   flag
* Ensure the frameworks of the sdk are added (Compiler showed the warning of duplicated framework)
* Force using differents versions of facebook sdk. but compilation fails with 5.1 and 5.2

Platform info:

```
Ionic:

   Ionic CLI                     : 5.2.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.1
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Capacitor:

   Capacitor CLI   : 1.1.0
   @capacitor/core : 1.1.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

Utility:

   cordova-res : 0.5.1 (update available: 0.5.2)
   native-run  : 0.2.7 

System:

   Android SDK Tools : 26.1.1 (/Users/leonardo/Library/Android/sdk)
   NodeJS            : v10.16.0 (/usr/local/Cellar/node@10/10.16.0/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001
```

**Additional Context**

This is a guide that shows the same process we did creating the demo repo.
https://www.joshmorony.com/using-cordova-plugins-that-require-install-variables-with-capacitor/
More important it shows a year ago this process worked just fine.

Thanks again, hope you get same results as our test and we can solve this.

**Comment by peterpeterparker** [comment]
Duplicate https://github.com/jeduan/cordova-plugin-facebook4/issues/776

Any help and PR to solve the related issue is welcomed
