### ISSUE TITLE
Version 5 crashes app immediatly

### ISSUE THREAD

**Issue by oliverandersencox** [jeduan/cordova-plugin-facebook4#781]
> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[FBSDKBasicUtility objectForJSONString:error:]: unrecognized selector sent to class 0x103571c68'
> *** First throw call stack:
> (
> 	0   CoreFoundation                      0x0000000106ab66fb __exceptionPreprocess + 331
> 	1   libobjc.A.dylib                     0x0000000104650ac5 objc_exception_throw + 48
> 	2   CoreFoundation                      0x0000000106ad49b4 +[NSObject(NSObject) doesNotRecognizeSelector:] + 132
> 	3   CoreFoundation                      0x0000000106abb443 ___forwarding___ + 1443
> 	4   CoreFoundation                      0x0000000106abd238 _CF_forwarding_prep_0 + 120
> 	5   CordovaPlugins                      0x00000001034ecf97 +[FBSDKAppEventsUtility retrievePersistedAnonymousID] + 231
> 	6   CordovaPlugins                      0x00000001034ec3c9 +[FBSDKAppEventsUtility anonymousID] + 47
> 	7   CordovaPlugins                      0x00000001034fd504 +[FBSDKAppEvents initialize] + 180
> 	8   libobjc.A.dylib                     0x0000000104651698 CALLING_SOME_+initialize_METHOD + 19
> 	9   libobjc.A.dylib                     0x0000000104651a2a initializeNonMetaClass + 269
> 	10  libobjc.A.dylib                     0x000000010465254f _ZL24initializeAndMaybeRelockP10objc_classP11objc_objectR8mutex_ttILb0EEb + 144
> 	11  libobjc.A.dylib                     0x00000001046583e2 lookUpImpOrForward + 205
> 	12  libobjc.A.dylib                     0x00000001046660d4 _objc_msgSend_uncached + 68
> 	13  CordovaPlugins                      0x00000001034efcad +[FBSDKSettings _logIfSDKSettingsChanged] + 1227
> 	14  libobjc.A.dylib                     0x0000000104651698 CALLING_SOME_+initialize_METHOD + 19
> 	15  libobjc.A.dylib                     0x0000000104651a2a initializeNonMetaClass + 269
> 	16  libobjc.A.dylib                     0x000000010465254f _ZL24initializeAndMaybeRelockP10objc_classP11objc_objectR8mutex_ttILb0EEb + 144
> 	17  libobjc.A.dylib                     0x00000001046583e2 lookUpImpOrForward + 205
> 	18  libobjc.A.dylib                     0x00000001046660d4 _objc_msgSend_uncached + 68
> 	19  CordovaPlugins                      0x00000001034ce881 +[FBSDKApplicationDelegate load] + 33
> 	20  libobjc.A.dylib                     0x0000000104652317 call_load_methods + 691
> 	21  libobjc.A.dylib                     0x0000000104653814 load_images + 77
> 	22  ???                                 0x000000010304e07e 0x0 + 4345618558
> 	23  ???                                 0x000000010305b3e7 0x0 + 4345672679
> 	24  ???                                 0x000000010305b392 0x0 + 4345672594
> 	25  ???                                 0x000000010305a5d3 0x0 + 4345669075
> 	26  ???                                 0x000000010305a665 0x0 + 4345669221
> 	27  ???                                 0x000000010304e379 0x0 + 4345619321
> 	28  ???                                 0x0000000103052434 0x0 + 4345635892
> 	29  ???                                 0x000000010304d630 0x0 + 4345615920
> 	30  ???                                 0x0000000109e61234 0x0 + 4461040180
> 	31  ???                                 0x0000000109e5f0ce 0x0 + 4461031630
> 	32  ???                                 0x0000000109e5a503 0x0 + 4461012227
> 	33  ???                                 0x0000000109e5a036 0x0 + 4461010998
> )
> libc++abi.dylib: terminating with uncaught exception of type NSException
> (lldb) 

**Bug or feature request**

[ x] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

**Describe the Bug of feature request**

I have installed the new version with Ionic native wrapper as well. As soon as the app opens, it crashes with the error above. I have no option but to update as Facebook have blocked me using the older version!

**Comment by peterpeterparker** [comment]
Duplicate https://github.com/jeduan/cordova-plugin-facebook4/issues/776

Help and PR are welcomed
