### ISSUE TITLE
Gamerequests require to login again into facebook even after user logged correctly

### ISSUE THREAD

**Issue by jebava** [jeduan/cordova-plugin-facebook4#783]
Hi,

I am using gamerequests for app invitation. The problem is, that it does not matter whether user already used login , first gamerequest requires webview based login again.  I have investigated this problem on multiple android and IOS versions and it behaves like this everywhere. I think the problem is, that when user is logging into app via Facebook app the session is not shared to webview. And GameRequests seems to be implemented in a webview container. If I uninstall facebook app, and do first login with webview, than gamerequests does not require additional login. I have spend many days trying to debug it and find a solution, but it seems plugin is done according official documentation. I have investigated other apps in play store and they managed to solve this problem and do not require additional login. What is the problem? I am offering $100 bounty paid via paypal for a solution that will solve this problem. Can you fix it? Contact me to linteo@protonmail.com if you plan to fix it. Thank you

**Comment by vincent-schirmann** [comment]
Hi,
I'm facing the same issue, did you find a solution?
Thanks

**Comment by jebava** [comment]
Hello, no I did not find any. But games like candy crush solved it. If you find out how, please let me know. I will pay you $100.

Wish you luck.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Rigwarl** [comment]
Hello, I got the same issue.
Any update on this?

**Comment by jebava** [comment]
Hello,
No I don't have a solution. If you find some please share it with me, I will give you $200 as a reward if it works.

Thanks

Linteo

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out the actively maintained fork `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect.

This issue is expected behavior according to Facebook. See https://github.com/facebook/facebook-ios-sdk/issues/1072.
