### ISSUE TITLE
Whitespace on top on iPhone X layout on iOS 13 beta 4

### ISSUE THREAD

**Issue by VinlorJiang** [jeduan/cordova-plugin-facebook4#785]
![IMG_0239](https://user-images.githubusercontent.com/17903952/61861289-1e03c300-aefe-11e9-945a-98cfac6cce67.PNG

![IMG_0241](https://user-images.githubusercontent.com/17903952/61861305-29ef8500-aefe-11e9-83a3-074920901324.PNG)

![IMG_0240](https://user-images.githubusercontent.com/17903952/61861315-3378ed00-aefe-11e9-81ab-3997f796be34.PNG)
)

**Comment by peterpeterparker** [comment]
Plz use other channels for support request, thx in advance

**Comment by VinlorJiang** [comment]
> in advance

Thank you very much. But I don't understand , could you tell me more details? Thanks!
