### ISSUE TITLE
Plugin does not use native Facebook SDK

### ISSUE THREAD

**Issue by ilyakar** [jeduan/cordova-plugin-facebook4#79]
I installed the plugin by doing the following:

1. git clone https://github.com/jeduan/cordova-plugin-facebook4 temp/facebook4
2. cordova plugin add temp/facebook4 --variable APP_ID="1023656864333287" --variable APP_NAME="Revine"

**Comment by fredgalvao** [comment]
How exactly do you know it's not using the native SDK?

**Comment by ilyakar** [comment]
Nevermind. I found this: https://github.com/jeduan/cordova-plugin-facebook4/issues/46
Apparently this is how the Facebook SDK works now.
