### ISSUE TITLE
Your Facebook SDK is out-of-date. Please upgrade to v5.0 for access to new privacy features

### ISSUE THREAD

**Issue by abhishek3999** [jeduan/cordova-plugin-facebook4#790]
How do I upgrade facebook sdk for Ionic Framework?

**Comment by peterpeterparker** [comment]
Plz use other channels for support request, thx

**Comment by abhishek3999** [comment]
Please let me know if you know of any channels where I can post to get
answers

**Comment by peterpeterparker** [comment]
Stackoverflow, Ionic forum, Ionic slack channel etc.

**Comment by abhishek3999** [comment]
Thanks
