### ISSUE TITLE
iOS build fails with Phonegap Build

### ISSUE THREAD

**Issue by phiasco12** [jeduan/cordova-plugin-facebook4#794]
Please do not submit support requests or "How to" questions here. Instead, please use channels like [StackOverflow](http://stackoverflow.com/) or the [Ionic forum](https://forum.ionicframework.com)

For issues or feature requests related to the code **in this repository** file a Github issue and provide as much details as possible

**Bug or feature request**

[ ] I'm reporting a reproducible issue with the code

**Describe the Bug of feature request**

The plugin was working fine up until today. I'm using Phonegap build to build my app and everything was working fine but today when i tried to build the app again, I get the following error:

`Error - The following 3rd-party plugin is causing the build to fail and may need to be updated to a newer version: cordova-plugin-facebook4`

I am using the latest version using this code in my config.xml file:

```
 <plugin name="cordova-plugin-facebook4" source="npm">
    <params>
       <param name="APP_ID" value="XXXXXXXXXXXXXX" />
       <param name="APP_NAME" value="XXXX" />
    </params>
 </plugin>
```

**Expected Behavior**

To build the app successfully the same way that it has always been building on PGB.

**Plugin version, OS, devices, etc**

Latest.

**Sample repo**

A sample repo will dramatically decrease the time needed for this issue to be fixed, if you could, please provide one in order to reproduce the problem

Not required. if you simply use this plugin with cli-9.0.0 on phonegap build, the iOS build will fail.

**Additional Context**

N/A

**Important note**

Unfortunately since this is a project done in spare time, support requests or "How to" questions will be closed without any further comments

If we consider your issue to not be well documented, it will be closed without further comments too

Thx you in advance for your understanding

**Comment by phiasco12** [comment]
on here: https://www.npmjs.com/package/cordova-plugin-facebook4 i noticed that the last publish was 19 hours ago! I wonder if this last publish has caused some issues?

**Comment by peterpeterparker** [comment]
Which Cordova version are you using?

Yesterday's version introduced Cocoapods as dependency manager. If your version don't support it that might explain your problem.

**Comment by phiasco12** [comment]
> Which Cordova version are you using?
> 
> Yesterday's version introduced Cocoapods as dependency manager. If your version don't support it that might explain your problem.

I'm using Phonegap build.


PhoneGap (iOS / Android / Windows)
cli-9.0.0 (5.0.1 / 8.0.0 / 7.0.0)

**Comment by peterpeterparker** [comment]
Should be good, it has been tested by multiple persons with Cordova v9

Try to remove and add the plugin again.

If you could provide a sample repo to reproduce the problem I could try on my machine. Otherwise I've got no idea.

**Comment by phiasco12** [comment]
> Should be good, it has been tested by multiple persons with Cordova v9
> 
> Try to remove and add the plugin again.
> 
> If you could provide a sample repo to reproduce the problem I could try on my machine. Otherwise I've got no idea.

Yes, it was all good for me as well up until today. I even built 2 days ago and all worked fine. and i haven't changed anything in my app or the config.xml file. so i was wondering why the build is failing today!

I did remove the plugin and re-added it a few times to no avail.

I can build successfully for iOS if i use a spec="xxx" in the plugin like so:

```
<plugin name="cordova-plugin-facebook4" spec="5.0.0">
    <params>
       <param name="APP_ID" value="XXXXXXXXXXXX" />
       <param name="APP_NAME" value="XXXX" />
    </params>
 </plugin>

```


What is the latest version of this plugin?

**Comment by peterpeterparker** [comment]
https://github.com/jeduan/cordova-plugin-facebook4/blob/master/CHANGELOG.md

**Comment by phiasco12** [comment]
> https://github.com/jeduan/cordova-plugin-facebook4/blob/master/CHANGELOG.md

Yes, the issue seems to be with the version 6.0.0. 
With that version i get this error in phonegap build: 

`Error - The following 3rd-party plugin is causing the build to fail and may need to be updated to a newer version: cordova-plugin-facebook4`

Even though the 6.0.0 is the latest version!!


But I can build successfully with the 5.0.0 version...

**Comment by phiasco12** [comment]
> https://github.com/jeduan/cordova-plugin-facebook4/blob/master/CHANGELOG.md

and here's a sample repo as requested:

https://github.com/phiasco12/facebook-test

I included a sample config.xml so you can upload to Phonegap build to see the build fail.

**Comment by peterpeterparker** [comment]
How could I build your test project on my machine, it just contains an `index.html` and `config.xml`. No `package.json`? Which commands should I run then?

**Comment by phiasco12** [comment]
> How could I build your test project on my machine, it just contains an `index.html` and `config.xml`. No `package.json`? Which commands should I run then?

That's what i've been saying. I'm not building on my machine. I'm building directly on Phonegap Build which is here: https://build.phonegap.com/

**Comment by peterpeterparker** [comment]
I see, well then can't help sorry, I don't use build.phonegap

Could you reach them out to ask why it fails now that Cocoapods as dependencies manager was introduced?

Sorry can't help more. Hope some could help and plz document your findings, thx in advance

**Comment by phiasco12** [comment]
> I see, well then can't help sorry, I don't use build.phonegap
> 
> Could you reach them out to ask why it fails now that Cocoapods as dependencies manager was introduced?
> 
> Sorry can't help more. Hope some could help and plz document your findings, thx in advance

thanks and sure. I will deffo update this thread as soon as I find something.

**Comment by peterpeterparker** [comment]
P.S.: Don't think that's the problem, as you are using cli-9 aka Cordova v9 but according @pellaras (see https://github.com/jeduan/cordova-plugin-facebook4/pull/765#issuecomment-523001216) `podspec tag` aren't supported in earlier version, perhaps the build.phonegap actually downgrade when building?

just the last things which popped in my mind, again sorry for not being able to help more

**Comment by danieldanielecki** [comment]
Hi @phiasco12, could you please share how you access this plugin on iOS? I have it working for over 2 years on Android, but on iOS the plugin isn't working for me. Great if you could share your code [issue#791](https://github.com/jeduan/cordova-plugin-facebook4/issues/791) I'd try it out. My app compiles on iOS, but the plugin doesn't gives any signals/logs etc.

**Comment by phiasco12** [comment]
> Hi @phiasco12, could you please share how you access this plugin on iOS? I have it working for over 2 years on Android, but on iOS the plugin isn't working for me. Great if you could share your code [issue#791](https://github.com/jeduan/cordova-plugin-facebook4/issues/791) I'd try it out. My app compiles on iOS, but the plugin doesn't gives any signals/logs etc.

This is what i currently use for iOS build:

```
<plugin name="cordova-plugin-facebook4" spec="5.0.0">
    <params>
       <param name="APP_ID" value="456593391497381" />
       <param name="APP_NAME" value="FreeMind" />
    </params>
 </plugin>
```

**Comment by phiasco12** [comment]
> P.S.: Don't think that's the problem, as you are using cli-9 aka Cordova v9 but according @pellaras (see [#765 (comment)](https://github.com/jeduan/cordova-plugin-facebook4/pull/765#issuecomment-523001216)) `podspec tag` aren't supported in earlier version, perhaps the build.phonegap actually downgrade when building?
> 
> just the last things which popped in my mind, again sorry for not being able to help more

yes, that could be one possible issue. The PGB support should resolve this issue i would assume.

**Comment by tmdevde** [comment]
same for me

**Comment by danieldanielecki** [comment]
+1 here, for a freshly generated projects version `6.0.0` throws an error, a little bit different though, i.e. `FBSDKCoreKit/FBSDKCoreKit.h file not found`.

**Comment by joshlatimer** [comment]
Same issue here
`Running command: pod install --verbose
Failed to install 'cordova-plugin-facebook4': Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (/Users/ionic/builds/joshlatimer/FUTPackSim/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
Failed to restore plugin "cordova-plugin-facebook4" from config.xml. You might need to try adding it again. Error: Error: pod: Command failed with exit code 31`

5.0.0 works fine, latest doesn't build

**Comment by Sevensnake** [comment]
Same issue for me for IOS.

**Comment by peterpeterparker** [comment]
@phiasco12 was your problem solved?

**Comment by snblackout** [comment]
I'm using Phonegap Build as well.  If I set the plugin to 6.2.0 I don't get the `FBSDKCoreKit/FBSDKCoreKit.h file not found` but now get a pretty generic build error:

The following build commands failed:

```
CompileC /Library/Developer/Xcode/DerivedData/AppName-dwftdvhqhhhbsubmzwpuwsmlxbpm/Build/Intermediates.noindex/ArchiveIntermediates/AppName/IntermediateBuildFilesPath/AppName.build/Release-iphoneos/AppName.build/Objects-normal/armv7/FacebookConnectPlugin.o AppName/Plugins/cordova-plugin-facebook4/FacebookConnectPlugin.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: xcodebuild: Command failed with exit code 65
    at ChildProcess.whenDone (/private/project/cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```

I've added the below to my config.xml, which I've read should do the correct cocoapod dependency link correctly?:

```
<platform name="ios">
        <framework src="FBSDKCoreKit" type="podspec" spec="5.7.0" />
        <framework src="FBSDKLoginKit" type="podspec" spec="5.7.0" />
        <framework src="FBSDKShareKit" type="podspec" spec="5.7.0" />
</platform>
```

If I set to 5.0.2 it builds just fine.

**Comment by REPTILEHAUS** [comment]
Running latest ```cordova v9``` 
and ```cordova-ios v5```

**Comment by arielhasidim** [comment]
same here
cordova 9
cordova ios 5.0.1

**Comment by snblackout** [comment]
To make this work I had to fork this project to my own custom plugin and go back to providing the FB framework files instead of Cocoapods.

See: https://github.com/jeduan/cordova-plugin-facebook4/issues/819#issuecomment-545113783

**Comment by alanxp** [comment]
Me too, i can't build it in phonegap, says 
`Error - The following 3rd-party plugin is causing the build to fail and may need to be updated to a newer version: cordova-plugin-facebook4`
I hope someone can reach and share a solution for the phonegap users :(

**Comment by 2diegoduque** [comment]
I have the same problem, any news?

**Comment by Habka** [comment]
I have the same problem, any news?

**Comment by snblackout** [comment]
Please see my comment above.  I got it to work with a hackish workaround.  It's not the most desired solution because you have to fork the project and point your config.xml to your own repo after that.  But if you're in desperate need to get your project updated, this is the best solution I could come up with.  Maybe someone has a better one they can share.

**Comment by bboldi** [comment]
running `pod repo update` solved this for me

**Comment by snblackout** [comment]
> 
> 
> running `pod repo update` solved this for me

I don't think that has to do with **Phonegap Build** specifically.

**Comment by arielhasidim** [comment]
After more then a month of struggling its finally works. I tried to recollect all of the steps here:
See: [#795 (comment)](https://github.com/jeduan/cordova-plugin-facebook4/issues/795#issuecomment-568289028)

I hope these steps will help other people and maybe be a clue to find the reason for this. Anyway, I think #795 is a duplicate.

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out https://www.npmjs.com/package/cordova-plugin-facebook-connect for the fork that is actively maintained.

This issue appears to have been primarily related to PhoneGap Build, which is itself deprecated.
