### ISSUE TITLE
window.facebookConnectPlugin.showDialog always return "OK"

### ISSUE THREAD

**Issue by Netpolice** [jeduan/cordova-plugin-facebook4#8]
var options = { method:"feed",name:title,caption: "test",description: desc,"link": url,"picture": pic};  
window.facebookConnectPlugin.showDialog(options, 
	function (result) {
		alert(JSON.stringify(result));
		$(this).alertmsg('Thanks for sharing','short','center');
	}, 
	function (e) {
});

window.facebookConnectPlugin.showDialog always return "OK", but nothing shared.

**Comment by jeduan** [comment]
need more data, what platform is this?

**Comment by Netpolice** [comment]
Android. There is no facebook share mesage dialog popup, then return "OK"

**Comment by kelvinlee79** [comment]
Hi, I got the Facebook share message dialog popup but no returns on either success or fail response at all regardless I post successfully or cancel the post.
Using Android platform.

Please advise. Thanks!

**Comment by dbroadhurst** [comment]
I found that I needed to use 'share' and href rather than 'feed'.

```
facebookConnectPlugin.showDialog({
              method: 'share',
              href: articleInfo.url
            },
```
