### ISSUE TITLE
Plugin version 1.10.1 - IOS and Android SDK version is old (IOS 4.31.1 Android 4.42.0) 

### ISSUE THREAD

**Issue by idanb007** [jeduan/cordova-plugin-facebook4#800]
Hi 

i'm using this plugin for login and I got a message in facebook developer dashboard that its old SDK even tough I got the latest version of the plugin .

is there any update version of this plugin for the latest version of Facebook sdk v5 ?

thanks

**Comment by peterpeterparker** [comment]
The last version of the plugin do use Fb SDK v5.2.x, see [CHANGELOG](https://github.com/jeduan/cordova-plugin-facebook4/blob/master/CHANGELOG.md)

**Comment by idanb007** [comment]
So why in facebook developer dashboard I see : IOS 4.31.1 Android 4.42.0 ?

**Comment by peterpeterparker** [comment]
No idea, either linked to your app or to Facebook but this plugin do use, as mentioned above, FB SDK v5.2.x

iOS: https://github.com/jeduan/cordova-plugin-facebook4/blob/363befe2b8f1454e6cc56178695aa533289fd184/plugin.xml#L169

Android: https://github.com/jeduan/cordova-plugin-facebook4/blob/363befe2b8f1454e6cc56178695aa533289fd184/plugin.xml#L23

**Comment by idanb007** [comment]
neither of this keys exist in my app , Im using Plugin version 1.10.1.

**Comment by peterpeterparker** [comment]
then you've got your answer. 1.10.1 use and older version of the SDK

**Comment by idanb007** [comment]
that's the result of "cordova-check-plugin" command : 

plugin: cordova-plugin-facebook4
source: npm://cordova-plugin-facebook4@^1.9.1
installed version: 1.10.1
remote version: 1.10.1

and its not updatable ...

**Comment by peterpeterparker** [comment]
For further support requests plz use other channels, thx in advance

**Comment by idanb007** [comment]
What channel you suggest ?

**Comment by peterpeterparker** [comment]
stackoverflow, ionic forum or slack etc.
