### ISSUE TITLE
Error in IOS 5.0.0 with cordova cli 9.0.1

### ISSUE THREAD

**Issue by MarioOlivera** [jeduan/cordova-plugin-facebook4#801]
Please do not submit support requests or "How to" questions here. Instead, please use channels like [StackOverflow](http://stackoverflow.com/) or the [Ionic forum](https://forum.ionicframework.com)

For issues or feature requests related to the code **in this repository** file a Github issue and provide as much details as possible

**Bug or feature request**

[ ] I'm reporting a reproducible issue with the code

**Describe the Bug of feature request**

Hi, I am using the plug-in and I have an error with the command line "cordova build ios".

I followed the installation steps (which are not many), just run "cordova platform add ios", then "cordova plugin add ...." and I took care to have everything updated regarding cocoapods

sudo gem install cocoapods-dependencies
cd platforms / ios /
Pod dependencies.

When installing the plugin I get the following:

"Installing" cordova-plugin-facebook4 "for ios
Running command: pod install --verbose

[!] The `HelloCordova [Debug]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in` Pods / Target Support Files / Pods-HelloCordova / Pods-HelloCordova.debug.xcconfig '. This can lead to problems with the CocoaPods installation "

[!] The `HelloCordova [Release]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in` Pods / Target Support Files / Pods-HelloCordova / Pods-HelloCordova.release.xcconfig '. This can lead to problems with the CocoaPods installation

Adding cordova-plugin-facebook4 to package.json "

When executing the "cordova build ios" command I get the following:

"/Users/juancarloscalabro/Desktop/TestFacebook/platforms/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/AppEvents/Internal/FBSDKAppEventsUtility.m:66:66: error:
      no getter method for read from property
  ... = @ (! FBSDKSettings.limitEventAndDataUsage) .stringValue;
          ~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~
1 error generated.

** BUILD FAILED ** "

**Plugin version, OS, devices, etc**

cordova 9.0.1
cordova platform ios 5.0.0
xcode 9.2

**Comment by peterpeterparker** [comment]
1. Maybe a too old version of Xcode (v9)? would you give a try with something more recent?

2. If doesn't work, could you provide a repo to reproduce the error?

**Comment by MarioOlivera** [comment]
> * Maybe a too old version of Xcode (v9)? would you give a try with something more recent?
> * If doesn't work, could you provide a repo to reproduce the error?

Hello men, excuse for the long time, my new version Xcode is 10.0.

My new error is
The following build commands failed:
	CompileC /Users/juancarloscalabro/Library/Developer/Xcode/DerivedData/HelloCordova-csbglptlxkvrrsgegoumlgqxozeb/Build/Intermediates.noindex/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/Objects-normal/x86_64/FacebookConnectPlugin.o /Users/juancarloscalabro/Desktop/facebookTest/platforms/ios/HelloCordova/Plugins/cordova-plugin-facebook4/FacebookConnectPlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65

**Comment by peterpeterparker** [comment]
You new error msg is the same as in https://github.com/jeduan/cordova-plugin-facebook4/issues/795, therefore I think we could close the issue

As documented in, either upgrade Cordova-ios >= v5 or process as indicated in https://github.com/jeduan/cordova-plugin-facebook4/issues/795#issuecomment-525291796

**Comment by MarioOlivera** [comment]
> You new error msg is the same as in #795, therefore I think we could close the issue
> 
> As documented in, either upgrade Cordova-ios >= v5 or process as indicated in [#795 (comment)](https://github.com/jeduan/cordova-plugin-facebook4/issues/795#issuecomment-525291796)

It has not solved my problem, I have cordova 9.0.1 and ios 5.0.1 and xcode 10, in that comment they are talking about versions ios <5.
Please do not close the issue if I have not yet solved it.

**Comment by peterpeterparker** [comment]
Seems you solved your above error msg as the new issue https://github.com/jeduan/cordova-plugin-facebook4/issues/803 you just opened isn't displaying the same stack trace anymore

**Comment by hengvenchang** [comment]
got the same issue when building with ionic cordova build ios --prod --release
removing node_modules/ and plugins/ 
and re-add the platforms 
the build seems to work fine

**Comment by danieldanielecki** [comment]
See [issue#795 (comment)](https://github.com/jeduan/cordova-plugin-facebook4/issues/795#issuecomment-542858885).
