### ISSUE TITLE
Login returns with cancelled result on iOS 13

### ISSUE THREAD

**Issue by yosikal** [jeduan/cordova-plugin-facebook4#802]
Login returns with cancelled result on iOS 13. Updating Facebook SDK to version 5.6.0 solves this issue. 

However, when updating the SDK to version 5.6.0 I encountered different problem of method openURL (newer) being called in infinite loop. I solved it for now by commenting out the newer function.

**Comment by francescotonini** [comment]
@jeduan Is there any ETA for this fix? Unfortunately it's pretty critical since it breaks the login function as well

**Comment by peterpeterparker** [comment]
@francescotonini PR are welcome

**Comment by jeduan** [comment]
@francescotonini If this is critical, I recommend hiring a developer with solid understanding of Cordova to fix this and consider contributing that back.

**Comment by francescotonini** [comment]
Of course I will try to send a PR with a fix, I was just wondering if someone was already working on it since this plugin it's used by a significant amount of developers.

**Comment by peterpeterparker** [comment]
PR from @francescotonini (thx again 👍)  has been merged.
Plugin v6.1.0 has been released.
Therefore this should be solved.

Ping me if not to reopen the issue.

**Comment by peterpeterparker** [comment]
@yosikal could you check the openUrl problem. if doesn't we should reopen the issue too. thx

**Comment by francescotonini** [comment]
Thanks @peterpeterparker and apologies for my first comment on this issue, it's a bit over the line.

**Comment by peterpeterparker** [comment]
@francescotonini no problem at all!

keep me posted about this in case it should be reopened, thx in advance
