### ISSUE TITLE
Error in IOS 5.0.1

### ISSUE THREAD

**Issue by MarioOlivera** [jeduan/cordova-plugin-facebook4#803]
I have problem with installation of plugin facebook

output with command Cordova plugin add Cordova-plugin-facebook4

[!] The `HelloCordova [Debug]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-HelloCordova/Pods-HelloCordova.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `HelloCordova [Release]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-HelloCordova/Pods-HelloCordova.release.xcconfig'. This can lead to problems with the CocoaPods installation

Error with command Cordova build iOS

 following build commands failed:
	CompileC /Users/juancarloscalabro/Library/Developer/Xcode/DerivedData/HelloCordova-csbglptlxkvrrsgegoumlgqxozeb/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBSDKCoreKit.build/Objects-normal/x86_64/FBSDKPaymentObserver.o /Users/juancarloscalabro/Desktop/facebookTest/platforms/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/AppEvents/Internal/FBSDKPaymentObserver.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65

My versions
9.0.0 (cordova-lib@9.0.1)
iOS 5.0.1
Xcode Version 10.0 (10A255)
plugin facebook version 6.0.0
macOS Sierra 10.13.6

My public repo in GitHub https://github.com/MarioOlivera/temporal_fb4

**Comment by peterpeterparker** [comment]
Just work fine on my machine

```
git clone https://github.com/MarioOlivera/temporal_fb4
cd temporal_fb4
npm install
cordova build ios
```

Result:

```
** BUILD SUCCEEDED **
```

Try to update Xcode I would say spontaneously.
