### ISSUE TITLE
APP_ID on facebook-browser.js should be a string

### ISSUE THREAD

**Issue by rrlevy** [jeduan/cordova-plugin-facebook4#804]
**Bug or feature request**

[X] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

**Describe the Bug of feature request**

When being replaced in the cordova build, the APP_ID in the facebook-browser.js gets replaced by the app id, but the app id is not a string, so we get an error. 

**Expected Behavior**

Line 157 of facebook-browser.js should read
      appId      : 'APP_ID',  // APP_ID is populated by the cordova after_prepare hook
instead of:
      appId      : APP_ID,  // APP_ID is populated by the cordova after_prepare hook

**Plugin version, OS, devices, etc**
Ionic 3, Cordova, platform browser

"@ionic-native/core": "4.20.0",
"cordova-browser": "6.0.0"
"cordova-plugin-ionic": "5.4.4"
"@ionic-native/facebook": "4.20.0",
"cordova-plugin-facebook4": "6.0.0",

**Comment by noahcooper** [comment]
This plugin is now deprecated, however, this issue is now fixed on the browser platform in the new `cordova-plugin-facebook-connect` plugin:

https://www.npmjs.com/package/cordova-plugin-facebook-connect
