### ISSUE TITLE
Android OS 10 (API Level 29, Q) Issue

### ISSUE THREAD

**Issue by timbo1437** [jeduan/cordova-plugin-facebook4#806]
[X ] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

**Describe the Bug of feature request**

Using Android OS Q (API Level 29) in the emulator and on a physical device, it is not functional.  There are no errors in the console.  It starts to open the screen then immediately closes with no errors in the console.  I have tried this with OS Pie (API Level 28) and it works perfectly.  I have performed a test with a fresh Cordova app and all plugins removed with no success.

**Expected Behavior**

It should work as it does with other Android OS's

**Plugin version, OS, devices, etc**

Latest version of Cordova (9.0.0), Android Version (8.1.0), Plugin Version (6.0.0), Android OS Q (API Level 29)

**Comment by alexeiDiachek** [comment]
i had the same issue

**Comment by peterpeterparker** [comment]
Facebook released an update of their Android SDK, v5.5.2, the 4. October, which "Fix issue of listing crash report files" (no more info than that).

This version is now referenced per default by the last release of the plugin. Could you give a try?

**Comment by zabojad** [comment]
I can confirm version `6.2.0` solves the issue with Android 10...

**Comment by peterpeterparker** [comment]
Cool thx for the test and confirmation @zabojad 👍
