### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by akadebnath** [jeduan/cordova-plugin-facebook4#816]
My app used to build fine until last week. Today I tried to build my app and getting this error:

![error](https://user-images.githubusercontent.com/18642790/66800464-db68ea00-ef32-11e9-9cac-e21483798032.jpg)

I uninstalled Cordova, installed again, built the app from the beginning, but still getting the error.

**Comment by peterpeterparker** [comment]
Plz use other channels for support request, thx.

**Comment by akadebnath** [comment]
Is this supposed to be support request, or issue?
