### ISSUE TITLE
Incompatible with cordova-plugin-androidx

### ISSUE THREAD

**Issue by akadebnath** [jeduan/cordova-plugin-facebook4#818]
I'm reporting a reproducible issue with the code

I am using Cordova 9.0.0 in Windows.

I have created a new cordova project and installed cordova-plugin-facebook4
Everything goes fine till this point. 
cordova build android successfully build the app.

Next I added below two plugins:
cordova-plugin-androidx
cordova-plugin-androidx-adapter

Now things are no longer good. Android build fails with below error:

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:processDebugResources'.
> > Android resource linking failed
>   error: resource style/Theme.AppCompat.NoActionBar (aka com.akasdigitalstudio.test:style/Theme.AppCompat.NoActionBar) not found.
>   error: resource style/Theme.AppCompat.Dialog (aka com.akasdigitalstudio.test:style/Theme.AppCompat.Dialog) not found.
>   error: failed linking references.
> 
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug
> option to get more log output. Run with --scan to get full insights.
> 
> 23 actionable tasks: 21 executed, 2 up-to-date
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 10s
> D:\Freelancer\PhoneGap\test\platforms\android\gradlew: Command failed with exit
> code 1 Error output:
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:processDebugResources'.
> > Android resource linking failed
>   error: resource style/Theme.AppCompat.NoActionBar (aka com.akasdigitalstudio.test:style/Theme.AppCompat.NoActionBar) not found.
>   error: resource style/Theme.AppCompat.Dialog (aka com.akasdigitalstudio.test:style/Theme.AppCompat.Dialog) not found.
>   error: failed linking references.
> 
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug
> option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 10s

**Comment by peterpeterparker** [comment]
Plz provide a sample repo to reproduce the problem.

**Comment by jbfm** [comment]
I'm running into the same issue with `cordova-android@8.1.0`

**Comment by deliverymanager** [comment]
@jbfm Add the plugin cordova-plugin-androidx-adapter

**Comment by jbfm** [comment]
@deliverymanager Not using `cordova-plugin-androidx` to begin with. Again though, same issue with those two plugins installed as well.

**Comment by akadebnath** [comment]
Turned out my gradle version (3.3.0) was outdated.
I updated gradle version to 3.5.0 and finally build succeeded.
