### ISSUE TITLE
Unable to connect with Facebook with Android

### ISSUE THREAD

**Issue by Yngdev31** [jeduan/cordova-plugin-facebook4#82]
Hello, 

I have a big problem since 5 day : I build for android (with success), with ionic and when I click for connect with Facebook in my app, I have a pop-up "Loading" and nothing !
The app don't connect to Facebook.
It had worked once , but I had not yet installed the plugin PushWoosh (I had PushPlugin Telerik, but I had to uninstall it because he's depreciated and replace it with PushWoosh and now notification working well.)

My plugin list : 

com.ionic.keyboard 1.0.4 "Keyboard"
com.pushwoosh.plugins.pushwoosh 3.6.14 "Pushwoosh"
cordova-plugin-crosswalk-webview 1.3.1 "Crosswalk WebView Engine"
cordova-plugin-facebook4 1.3.0-0 "Facebook Connect"
cordova-plugin-geolocation 1.0.2-dev "Geolocation"
cordova-plugin-splashscreen 2.1.0 "Splashscreen"
cordova-plugin-statusbar 1.0.1 "StatusBar"
cordova-plugin-whitelist 1.0.0 "Whitelist"
org.apache.cordova.console 0.2.13 "Console"
org.apache.cordova.device 0.3.0 "Device"
org.apache.cordova.file 1.3.3 "File"
org.apache.cordova.globalization 0.3.4 "Globalization"

My dependencies : 

dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DEPENDENCIES START
    debugCompile project(path: ":CordovaLib", configuration: "debug")
    releaseCompile project(path: ":CordovaLib", configuration: "release")
    compile "com.google.android.gms:play-services-gcm:+"
    compile "com.android.support:support-v4:+"
    compile "com.facebook.android:facebook-android-sdk:4.+"
    // SUB-PROJECT DEPENDENCIES END
}

I can add code if you want ...

Please, save my day !

Thanks all !

**Comment by MaicolBen** [comment]
@Yngdev31 Try to use console.log to see if it throws some error, you can use http://jsconsole.com/?%3Alisten service to see the logs

**Comment by jeduan** [comment]
Use [phonegap-plugin-push](https://github.com/phonegap/phonegap-plugin-push#co-existing-with-facebook-plugin)
