### ISSUE TITLE
unable to list saved accounts on device

### ISSUE THREAD

**Issue by juszczec** [jeduan/cordova-plugin-facebook4#824]
[ ] I'm reporting a reproducible issue with the code
[X ] I'm reporting a feature request

**Describe the Bug of feature request**

I'd like to present a list of all saved accounts on this device, let the user pick one and then sign in
with it.

**Expected Behavior**

A list of saved accounts (username only) is returned.  

**Plugin version, OS, devices, etc**

cordova version 9.0.0 on macOS Catalina v10.15

cordova-plugin-facebook4 6.2.0

I want to use whichever Android/iOS versions are supported by the following Cordova platform versions:

  android 8.1.0
  browser 6.0.0

**Comment by peterpeterparker** [comment]
If I'm not wrong, that's something the Facebook SDK doesn't offer right? Therefore nothing we could do on this plugin side.

Of course, if the Fb SDK does offer such a feature, let me know, happy to reopen the feature request if that's the case.
