### ISSUE TITLE
Build for ios gives error

### ISSUE THREAD

**Issue by ejerskov** [jeduan/cordova-plugin-facebook4#825]
**Bug or feature request**

[x] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

**Describe the Bug of feature request**

Build error when building for ios

**Plugin version, OS, devices, etc**

```
Ionic:

   Ionic CLI                     : 5.4.4
   Ionic Framework               : @ionic/angular 4.11.2
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 4 other plugins)

Utility:

   cordova-res : 0.8.1 
   native-run  : 0.2.9 

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v10.15.1 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS Catalina
   Xcode      : Xcode 11.1 Build version 11A1027

```

**Sample repo**

Following this tutorial:
https://www.djamware.com/post/5d949fa24ca99c5ee51238ef/ionic-4-tutorial-facebook-login-example

When running `ionic cordova build ios` I get the following error:

> The following build commands failed:
> CompileC /Users/Username/Library/Developer/Xcode/DerivedData/MyApp-awlowjhmvfnzthersopbcucvbcjt/Build/Intermediates.noindex/MyApp.build/Debug-iphonesimulator/MyApp.build/Objects-normal/x86_64/FacebookConnectPlugin.o /Users/Shared/Relocated\ Items/Security/localhost/myionicfacebook/platforms/ios/MyApp/Plugins/cordova-plugin-facebook4/FacebookConnectPlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
> (1 failure)
> xcodebuild: Command failed with exit code 65
> [ERROR] An error occurred while running subprocess cordova.
>         
> cordova build ios exited with exit code 65.

**Comment by peterpeterparker** [comment]
Plz use other channels for support request, thx
