### ISSUE TITLE
On IOS 13 facebook sdk login event return user cancel

### ISSUE THREAD

**Issue by Anish-ichigo** [jeduan/cordova-plugin-facebook4#827]
On IOS 13 facebook sdk login event return user cancel but on other old IOS version return login successfull. It's means new IOS has issue regarding facebook login. So there is any solution for this bug for Ionic app?

**Comment by Anish-ichigo** [comment]
Recently cordova-plugin-facebook4 sdk version is 4.40.0. I am facing this issue on IOS new updated version 13 & vice versa.

**Comment by peterpeterparker** [comment]
Thx in advance for using other channels for support request.

That being said maybe you'll be able to solve your problem like displayed in https://github.com/jeduan/cordova-plugin-facebook4/issues/820
