### ISSUE TITLE
Browser version not working

### ISSUE THREAD

**Issue by ilyakar** [jeduan/cordova-plugin-facebook4#83]
I followed the instructions to every extent, the native plugin seems to work fine, however I am having troubles with the browser.

It seems that the SDK never gets initiated since "success initing browser!!" is never called.
When trying to get the loginStatus afterwards I get the following log: "some error with facebookConnect: init not called with valid version"

    facebookConnectPlugin.browserInit(settings.facebookAppId, 'v2.4', function(){ console.log('success initing browser!!') });

    setTimeout(function(){
        facebookConnectPlugin.getLoginStatus(function(response){
            console.log('got login status');
        }, function(e){
            console.log('some error with facebookConnect:', e);
        });
    }, 1000);

**Comment by tuvistavie** [comment]
I had to put `facebookConnectPlugin.browserInit` in Cordova `deviceready` callback for it to work, I hope it can help.

**Comment by jeduan** [comment]
Looks like @tuvistavie's method works. Feel free to reopen if it's not.
