### ISSUE TITLE
activateApp never calls any of the callbacks (Success & Error)

### ISSUE THREAD

**Issue by omardoma** [jeduan/cordova-plugin-facebook4#836]
**Bug or feature request**

[X] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

**Describe the Bug of feature request**

I have two environments for my Ionic 4 app, staging and production, so I need a way to programmatically enable facebook events only on production, so I disabled auto events collection like so in Cordova's Config.xml

Android:
`
        <config-file parent="/manifest/application" target="app/src/main/AndroidManifest.xml" xmlns:android="http://schemas.android.com/apk/res/android">
            <meta-data android:name="com.facebook.sdk.AutoLogAppEventsEnabled" android:value="false" />
        </config-file>
`

iOS:
`
        <config-file target="*-Info.plist">
            <dict>
                <key>FacebookAutoLogAppEventsEnabled</key>
                <false />
            </dict>
        </config-file>
`

And I relied on this part of the [docs](https://github.com/jeduan/cordova-plugin-facebook4#manually-log-activation-events) to activate the app only on production, but the problem is that I call it and none of the callbacks are getting invoked, so I can't even get an error.

**Expected Behavior**

activateApp should work correctly.

**Plugin version, OS, devices, etc**

Plugin Version: 6.2.0

Ionic:

   Ionic CLI                     : 5.4.6 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.4
   @angular-devkit/build-angular : 0.803.18
   @angular-devkit/schematics    : 8.3.18
   @angular/cli                  : 8.3.18
   @ionic/angular-toolkit        : 2.1.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 19 other plugins)

Utility:

   cordova-res : 0.8.0 (update available: 0.8.1)
   native-run  : 0.2.8 (update available: 0.2.9)

System:

   Android SDK Tools : 26.1.1 (/Users/omardoma/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v10.16.3 (/usr/local/Cellar/node@10/10.16.3/bin/node)
   npm               : 6.12.0
   OS                : macOS Mojave
   Xcode             : Xcode 11.1 Build version 11A1027

**Comment by omardoma** [comment]
Any updates on this please ? @peterpeterparker

**Comment by peterpeterparker** [comment]
Not that I know. Could you provide a PR?

**Comment by omardoma** [comment]
I am afraid I don't really have experience in developing Cordova plugins, is the plugin no longer maintained?

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect. That plugin now properly calls the callbacks passed to it.
