### ISSUE TITLE
Problem with iOS 13 - THREAD WARNING

### ISSUE THREAD

**Issue by vincom-dev** [jeduan/cordova-plugin-facebook4#837]
on iOS 13 i get error:

By clicking link - nothing happend and in console log i see - 
- THREAD WARNING: ['FacebookConnectPlugin'] took '11.569824' ms. Plugin should use a background thread.

i use  <plugin name="cordova-plugin-facebook4" spec="5.0.0"> 

Thank you

**Comment by peterpeterparker** [comment]
Plz use other channels for support requests, thx in advance
