### ISSUE TITLE
 Android Build issue : AAPT: error: unescaped apostrophe in string

### ISSUE THREAD

**Issue by vishal-arham** [jeduan/cordova-plugin-facebook4#838]
![screenshot--2019 11 26-16_08_17](https://user-images.githubusercontent.com/58214119/69622549-26fcd080-1067-11ea-85c7-033f3776d2da.png)

I get above issue in creating android build i need it's urgent please do needful.

**Comment by peterpeterparker** [comment]
Plz use other channels for support request, thx

**Comment by peterpeterparker** [comment]
P.S.: Maybe same problem as the one reported for iOS https://github.com/jeduan/cordova-plugin-facebook4/issues/812

**Comment by ZumelzuR** [comment]
This could help you

https://stackoverflow.com/questions/52712063/build-failing-during-merge-resources-with-android-gradle-plugin-3-3-0/54615423#54615423
