### ISSUE TITLE
android-minSdkVersion conflict

### ISSUE THREAD

**Issue by newbie78** [jeduan/cordova-plugin-facebook4#840]
i'm describe my problem here: https://github.com/apache/cordova-android/issues/588

how to change AndroidManifest.xml minSdkVersion?
i'm add
```
    <platform name="android">
        <preference name="android-minSdkVersion" value="15" />
        <preference name="android-targetSdkVersion" value="19" />
```
in config.xml
rm & add platform
then build an get error
in /home/alpine/project/src-cordova/platforms/android/CordovaLib/build/intermediates/library_manifest/debug/AndroidManifest.xml i'm get
```
<uses-sdk android:minSdkVersion="19" />
```
then install ordova plugin add cordova-android-support-gradle-release --variable ANDROID_SUPPORT_VERSION=15

error when build still here

need help
thanx

**Comment by peterpeterparker** [comment]
plz use other channels for support request.

that being said, put your preference at the root

```
<widget...
    
    <preference name="android-minSdkVersion" value="21" />
    <preference name="android-targetSdkVersion" value="26" />
   <platform name="android">
      ....
```
