### ISSUE TITLE
Ionic 4 crashes on Android java.lang.ClassNotFoundException: org.apache.cordova.facebook.ConnectPlugin

### ISSUE THREAD

**Issue by butterfly-valley** [jeduan/cordova-plugin-facebook4#841]
Trying to implement Facebook login on my Ionic 4 Android app and getting this error. The recognizes the plugin with version 6.2 and builds with no errors but on launch the app crashes with the error above

**Comment by peterpeterparker** [comment]
Plz use other channels for support requests, thx

**Comment by butterfly-valley** [comment]
Sorry, is this not an issue with the plugin?

**Comment by SalSchein** [comment]
@butterfly-valley 

I am also getting the same crash
How did you fix this error?

Thanks.
