### ISSUE TITLE
Cannot get the cordova plugin facebook 4 6.2.0 working on IOS 13

### ISSUE THREAD

**Issue by bboldi** [jeduan/cordova-plugin-facebook4#842]
**Bug**

[x] I'm reporting a reproducible issue with the code

**Describe the Bug of feature request**

When I try to compile the application i get the following error in xcode

```
FBSDKRestrictiveDataFilterManager.m:138:65: No known class method for selector 'JSONStringForObject:error:invalidObjectHandler:'
```

**System Info**

```

Plugin version: 6.2.0

Ionic:

   ionic (Ionic CLI)  : 4.0.5
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : ios 5.1.1

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.4
   ios-sim           : 7.0.0
   NodeJS            : v9.11.1 (/usr/local/bin/node)
   npm               : 5.6.0
   OS                : macOS
   Xcode             : Xcode 11.2.1 Build version 11B500
``

**Comment by peterpeterparker** [comment]
I quickly Googled your error and it seems to be linked with the FB SDK or Pod. I hope one of these will fix your local issue.

https://stackoverflow.com/questions/56374163/updated-facobooklogin-pod-got-error-no-known-class-method-for-selector-object

https://github.com/firebase/FirebaseUI-iOS/issues/684

**Comment by bboldi** [comment]
Thank you, I googled it myself, but none of the above posts offers a solution. But thanks anyway for taking the time. cheers!
