### ISSUE TITLE
APP_ID is not defined in browser?

### ISSUE THREAD

**Issue by htorbov** [jeduan/cordova-plugin-facebook4#844]
I'm using the latest versions of everything, clean project, testing on Browser.

---

Installed by:

> cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="XXX" --variable APP_NAME="XXX"

---

Gives error on Browser:

> APP_ID is not defined

---

It did not add anything in config.xml (I don't know if that's normal), but even when I added these parameters, it gives the same error:
```xml
<plugin name="cordova-plugin-facebook4" spec="6.2.0">
  <params>
    <param name="APP_ID" value="XXX" />
    <param name="APP_NAME" value="XXX" />
  </params>
</plugin>
```

**Comment by peterpeterparker** [comment]
Plz use other channels for support requests, thx.

**Comment by htorbov** [comment]
@peterpeterparker thank you for your fast response, but I'm afraid that this is a bug report. The plugin works perfectly both on Android/iOS, but have the mentioned issue on Browser.

Please close the issue if that's not the place for bug reports.

Thanks!

**Comment by peterpeterparker** [comment]
Oki doki. If you could provide a PR to fix the problem let me know, happy to review it.

**Comment by htorbov** [comment]
@peterpeterparker thanks, buddy! I really appreciate your support, it's an awesome plugin, it would be really cool if it works in `browser` platform also! :-)

---

A few commands and it's ready:
```
npm install -g @vue/cli
npm install -g cordova
vue create test
cd test
vue add cordova
// select Android + iOS + Browser
cd src-cordova
cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="123456" --variable APP_NAME="test"
cd ..
npm run cordova-serve-browser
```

**Comment by htorbov** [comment]
@peterpeterparker I apologise, it suddenly started working (I didn't even made any changes in the code). Weird!

For future reference, I think it should be installed once, delete the project, and create it again, in order to work.

Thanks!

**Comment by peterpeterparker** [comment]
Coolio, happy to hear it worked out. Thx for the feedback 👍
