### ISSUE TITLE
When removing the plugin, an Variable(s) missing error is spawned

### ISSUE THREAD

**Issue by renanccastro** [jeduan/cordova-plugin-facebook4#845]
**Bug or feature request**

[X] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

**Describe the Bug of feature request**

If you start a new project with cordova and add the plugin with:

`cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="123456789" --variable APP_NAME="myApplication"`

and try to remove it with:

`cordova plugin rm cordova-plugin-facebook4`

The following error should be printed:

`Variable(s) missing (use: --variable APP_ID=value --variable APP_NAME=value).`

**Expected Behavior**

It's expected to be removed without an error.

**Additional Context**

This can impact other projects that uses this plugin like meteor because the build step breaks if an error is spawned in the plugin remove step, as it is used for rebuilding the project.

**Comment by noahcooper** [comment]
This is a cordova-cli issue:

https://github.com/apache/cordova-cli/issues/446

You must currently specify variables when removing a plugin.

This plugin is deprecated. See `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect.
