### ISSUE TITLE
IOS build failed while using this library.

### ISSUE THREAD

**Issue by tarun57** [jeduan/cordova-plugin-facebook4#852]
Hi,
I'm using ionic 3 and now working on ios build but my ios build failed many times.
i'm facing issue 'FBSDKCoreKit/FBSDKCoreKit.h'
but when this issue is solved then the error is showing in library files in xcode. i'm providing a screenshot with errors in xcode and please help.
![Screenshot 2020-03-05 at 11 24 48 AM](https://user-images.githubusercontent.com/43084605/75952621-38ab0b00-5ed5-11ea-86b7-957e63ab6c2c.png).

**Comment by peterpeterparker** [comment]
Double check that you followed all the steps of the [iOS installation guide](https://github.com/jeduan/cordova-plugin-facebook4/blob/master/docs/ios/README.md)

If still doesn't work, checkout the duplicates https://github.com/jeduan/cordova-plugin-facebook4/issues?q=FBSDKCoreKit.h

**Comment by tarun57** [comment]
I was already follow these steps but not any solution.
