### ISSUE TITLE
Send Dialog on iOS 12 shows empty (no content)

### ISSUE THREAD

**Issue by maxymczech** [jeduan/cordova-plugin-facebook4#854]
Please do not submit support requests or "How to" questions here. Instead, please use channels like [StackOverflow](http://stackoverflow.com/), the [Ionic forum](https://forum.ionicframework.com) or the [Ionic slack channel](http://ionicworldwide.herokuapp.com)

For issues or feature requests related to the code **in this repository** file a Github issue and provide as much details as possible

**Bug or feature request**

[x] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

**Describe the Bug of feature request**

I am using Send Dialog to send link via Facebook Messenger. On iOS 12, Messenger window opens, but content is empty and there are no "Send" buttons.

**Plugin version, OS, devices, etc**

- Plugin version 6.3.0
- iPhone 6 with iOS 12.4.5

**Comment by peterpeterparker** [comment]
Plz use other channels for support requests.

However if you do think it's a bug, plz provide a repo and test case to reproduce the issue.

**Comment by maxymczech** [comment]
This was not a support request, this was a bug report :)
