### ISSUE TITLE
Not working on IOS Simulator

### ISSUE THREAD

**Issue by burton22ful** [jeduan/cordova-plugin-facebook4#856]
[x] I'm reporting a reproducible issue with the code

**Describe the Bug of feature request**

When logging in on the Xcode simulator it shows the dialog "My App" wants to use "Facebook.com" to sign in.  After clicking continue it just shows a blank white "facebook.com" window and after a few seconds shows the same dialog again and does the same thing.

**Expected Behavior**

After clicking continue it should show a Login with facebook window with the facebook login webpage.  It works on all devices i've tried just not on the simulator.  I want to use the simulator to take screen shots for the XS max and 6.5" screen.

Plugin version is 6.3.0. 

simulator version iOS is 13.3

simulator device XS max or iPhone 8 Plus

Hard Devices work fine 

![Simulator Screen Shot - iPhone 8 Plus - 2020-03-11 at 18 06 42](https://user-images.githubusercontent.com/1515907/76406661-0d3c8a80-63c5-11ea-9055-507e05271de9.png)
![Simulator Screen Shot - iPhone 8 Plus - 2020-03-11 at 18 06 49](https://user-images.githubusercontent.com/1515907/76406667-10d01180-63c5-11ea-92ae-13a56a71ced4.png)

**Comment by peterpeterparker** [comment]
Works fine for me with Xcode 11.3 and simulated iPhone 8 Plus (see screenshots).

Give a try to the [sample](https://github.com/peterpeterparker/cordova-plugin-facebook4-lab) app.

Therefore I close the issue, seems not related to the plugin itself. If you do find and error and can provide a sample repo to reproduce the problem, ping me.

<img width="547" alt="Capture d’écran 2020-03-11 à 11 41 37" src="https://user-images.githubusercontent.com/16886711/76408664-9637cf80-638d-11ea-93c8-ecbaec494c6e.png">
<img width="547" alt="Capture d’écran 2020-03-11 à 11 41 43" src="https://user-images.githubusercontent.com/16886711/76408666-9768fc80-638d-11ea-9de6-391c7b89edd3.png">
<img width="547" alt="Capture d’écran 2020-03-11 à 11 41 47" src="https://user-images.githubusercontent.com/16886711/76408668-9768fc80-638d-11ea-9042-a303662852d8.png">
<img width="547" alt="Capture d’écran 2020-03-11 à 11 42 04" src="https://user-images.githubusercontent.com/16886711/76408669-98019300-638d-11ea-8323-1d8ee9ee0c37.png">
<img width="547" alt="Capture d’écran 2020-03-11 à 11 42 07" src="https://user-images.githubusercontent.com/16886711/76408674-9afc8380-638d-11ea-8f75-63eceaea0f72.png">
