### ISSUE TITLE
iOS: UIWebView to WKWebView

### ISSUE THREAD

**Issue by davidericardo** [jeduan/cordova-plugin-facebook4#857]
Due to the ITMS-90809: Deprecated API Usage, Apple will stop allow app submissions that are using the UIWebView. So, instead we may use WKWebView. 

Since this plugin is using UIWebView, is it foreseen to have it updated according to Apple requirements? Or is there a way by using the current solution to avoid this issue?

Thanks.
DR

**Comment by davidericardo** [comment]
It seems that using the Cocoa Pods (correctly) the issue is solved by Apple. So, I would close this topic once the app is submitted without any reported issues.

**Comment by neerajsaxena0711** [comment]
@davidericardo  I am facing the same issue. Can you tell me how did you exactly solve this? 
I did not understand what you meant by "using cocoa pods correctly"

**Comment by antonello-alfatauristudio** [comment]
any news about this?

**Comment by demym** [comment]
I have the same problem with this plugin. Also for me, what ‘using cocoapods correctly’ means ?

**Comment by permsaknmk** [comment]
@neerajsaxena0711 , @antonello-alfatauristudio , @demym 
1. find and open Podfile
2. change version of 	pod 'FBSDKCoreKit', 'x.x.x'
	                                 pod 'FBSDKLoginKit', 'x.x.x'
	                                 pod 'FBSDKShareKit', 'x.x.x'
   to 
                                         pod 'FBSDKCoreKit', '5.5.0'
	                                 pod 'FBSDKLoginKit', '5.5.0'
	                                 pod 'FBSDKShareKit', '5.5.0'
3. run command 'pod update' in terminal
4. Archives and upload again

reference : https://github.com/facebook/facebook-ios-sdk/issues/1028
hope it help you.

**Comment by RaghavCoddle** [comment]
Hi 
I have added below things to pod file:
pod 'FBSDKCoreKit', '5.5.0'
pod 'FBSDKLoginKit', '5.5.0'
pod 'FBSDKShareKit', '5.5.0'

But do we need to install cordova-plugin-facebook4 ? 
My app is getting rejected again and again by app store due to UIWebView.

Can anybody help me out?

**Comment by assertdesignuk** [comment]
I've forked the plugin and changed the ".framework" files the latest ones in the FB SDK off the FB SDK website.

I will then include this plugin in my config.xml and it should no longer use UIWEBVIEW.

Will update later.
