### ISSUE TITLE
User cancelled. No login opportunity

### ISSUE THREAD

**Issue by wkaskie** [jeduan/cordova-plugin-facebook4#858]
Please do not submit support requests or "How to" questions here. Instead, please use channels like [StackOverflow](http://stackoverflow.com/), the [Ionic forum](https://forum.ionicframework.com) or the [Ionic slack channel](http://ionicworldwide.herokuapp.com)

For issues or feature requests related to the code **in this repository** file a Github issue and provide as much details as possible

**Bug or feature request**

[X ] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

**Describe the Bug of feature request**

I have a fresh Ionic App, no customizations except the facebook4 plugin. It doesn't work. I get the response, "user cancelled" as the error from the then/catch. I'm also using the sample code from the readme. I test for loginStatus first which returns unknown.

Error in X-Code shows:
```
-canOpenURL: failed for URL: "fbauth2:/" - error: "The operation couldn’t be completed. (OSStatus error -10814.)
```

**Expected Behavior**

I should either receive authentication credentials or be prompted to login to Facebook.

**Sample repo**

https://github.com/peterpeterparker/cordova-plugin-facebook4-lab doesn't work.

**Plugin version, OS, devices, etc**

Testing on iPhone 7 iOS 13 as well as several emulators.
```
    "@angular/common": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@ionic-native/core": "^5.22.0",
    "@ionic-native/facebook": "^5.22.0",
    "@ionic-native/splash-screen": "^5.22.0",
    "@ionic-native/status-bar": "^5.22.0",
    "@ionic/angular": "^5.0.0",
    "cordova": "^9.0.0",
    "cordova-android": "^8.1.0",
    "cordova-ios": "^5.1.1",
    "cordova-plugin-facebook4": "^6.3.0",
    ...
```

**Comment by peterpeterparker** [comment]
Duplicate your other message in issue [#125](https://github.com/jeduan/cordova-plugin-facebook4/issues/125#issuecomment-601695353), please don't flood the issue tracker.

Note that I just tested the sample repo and it worked out.

<img width="1440" alt="Capture d’écran 2020-03-20 à 15 05 04" src="https://user-images.githubusercontent.com/16886711/77171092-3d1e1900-6abc-11ea-8db6-5426ea2d373b.png">

**Comment by wkaskie** [comment]
I created the new issue mainly because that one was 4 years old.  But I'll add my additional information to that one.  

For the lab, I should have been more specific. I'm getting a BUILD FAILED error.

**Comment by diego-lipinski-de-castro** [comment]
im getting this too, as a lot of other peiople, did you solved?
