### ISSUE TITLE
CordovaFacebook.logout() not working on IOS >= 9.0

### ISSUE THREAD

**Issue by jagdishadusumalli** [jeduan/cordova-plugin-facebook4#86]
I'm using cordova-cli 5.4.0 and platform cordova-ios 3.9.2 with this plugin.
ON IOS >= 9.0 which uses the SFSafariViewController to ask for facebook credentials,
When a user logs out of my app i have called CordovaFacebook.logout(); for logging out of facebook  as well then when the user wants to re-login the app is not asking for entering the credentials again and just asks for confirmation "OK" to authenticate the user.

This works perfectly on android platform where the user is asked to re-login and authenticate in an in-app browser (in context of fb native app does not exist).

**Comment by dipanjanc** [comment]
On iOS, the user has to log off from facebook "on safari" as opposed to the facebook app itself. There is no need to clear safari cache or meddle with the saved passwords too.

**Comment by PaulNguyen147** [comment]
yes, I also have same issue, How could I change the Facebook account after logining because the APP has remembered my old authenticated user!

**Comment by jagdishadusumalli** [comment]
Hi @PaulNguyen147  have you tried the trick mentioned by @dipanjanc

**Comment by jeduan** [comment]
What @dipanjanc mentioned is correct. Running the Facebook SDK examples yields the exact same result. Closing due to this not being a bug in this plugin.
