### ISSUE TITLE
Share Dialog always returns a null object

### ISSUE THREAD

**Issue by pixael** [jeduan/cordova-plugin-facebook4#861]
**Bug or feature request**

[ x ] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

**Describe the Bug of feature request**

The showDialog with method share returns a null object on success.

**Expected Behavior**

It should return a post id.

**Sample repo**

`        let options = {
            method: 'share',
            href: 'https://pixael.com',
            share_feedWeb: true,
        }
        this.fb.showDialog(options).then((result) => {
            console.log(result);
        }).catch((e) => {
            console.log(e)
        });`

**Plugin version, OS, devices, etc**

![image](https://user-images.githubusercontent.com/14755958/77588563-02fcaf00-6ee2-11ea-99a7-5764938a21d3.png)

![image](https://user-images.githubusercontent.com/14755958/77588601-190a6f80-6ee2-11ea-994e-ec09c878e845.png)

**Comment by peterpeterparker** [comment]
Can you provide a repo to reproduce the issue or extend the [sample](https://github.com/peterpeterparker/cordova-plugin-facebook4-lab) with an example?

**Comment by pixael** [comment]
> Can you provide a repo to reproduce the issue or extend the [sample](https://github.com/peterpeterparker/cordova-plugin-facebook4-lab) with an example?

Hi David I've sent you an invitation to the repo here on Github.

**Comment by peterpeterparker** [comment]
I have duplicated your  example in a public repo respectively in the [sample](https://github.com/peterpeterparker/cordova-plugin-facebook4-lab)

When I give it a try, even tough the share function feature works as expected I do also receive an empty object as result.

My guts feelings would say that the reason behind is that Fb doesn't provide any results.

But anyone willing to invest time in this and/or submit a PR is welcomed.

**Comment by pixael** [comment]
So did you try sharing via the app Cordova Plugin Lab? Is the app approved by Facebook? Cause I was wondering maybe it doesn't return a result because my Facebook app is still not approved?

**Comment by peterpeterparker** [comment]
Tried with a not approved Fb App too. `JSON.parse(result);`

**Comment by pixael** [comment]
Ok then that COULD be the issue... I'm wondering if anyone got it working fine with an approved FB app.

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out the actively maintained fork `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect.

It looks like, as strange as it sounds, this is expected behavior. As noted on https://developers.facebook.com/docs/reference/iossdk/current/FBSDKShareKit/protocols/fbsdksharingdelegate.html/:

```
The results from the sharer. This may be nil or empty.
```

It looks like some time ago, you would receive a response object if and only if the user had approved `publish_actions` permissions for your app. Now that `publish_actions` is deprecated, it would appear the response is basically _always_ empty.
