### ISSUE TITLE
npm install cordova-plugin-facebook4 capacitor

### ISSUE THREAD

**Issue by dodomui** [jeduan/cordova-plugin-facebook4#862]
Please do not submit support requests or "How to" questions here. Instead, please use channels like [StackOverflow](http://stackoverflow.com/), the [Ionic forum](https://forum.ionicframework.com) or the [Ionic slack channel](http://ionicworldwide.herokuapp.com)

For issues or feature requests related to the code **in this repository** file a Github issue and provide as much details as possible

**Bug or feature request**

[ ] I'm reporting a reproducible issue with the code
[X ] I'm reporting a feature request

**Describe the Bug of feature request**
May I know how to install this plugin with capacitor?
How to add App ID and secret for this.

**Comment by iOlivier** [comment]
This guide may help you:
[https://www.joshmorony.com/using-cordova-plugins-that-require-install-variables-with-capacitor/](https://www.joshmorony.com/using-cordova-plugins-that-require-install-variables-with-capacitor/)
