### ISSUE TITLE
Plans to support version 6+ of facebook's SDK 

### ISSUE THREAD

**Issue by michalsisak** [jeduan/cordova-plugin-facebook4#865]
Thanks for your work. 

What is a status on updating the package to support recent versions of FB's SDK? They launched version 6 in February. [Changelog](https://github.com/facebook/facebook-android-sdk/blob/master/CHANGELOG.md)

I am asking because Facebook admin page strongly suggests updating to the recent SDK in order to user all features. Otherwise, there are no problems as far as I know, everything works well.

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect`. I've updated to the most recent version of the Facebook SDK for each platform:

https://www.npmjs.com/package/cordova-plugin-facebook-connect
