### ISSUE TITLE
Change message or remove confirmation alert to use facebook login in IOS (I am using IONIC 5)

### ISSUE THREAD

**Issue by YeisonVelez11** [jeduan/cordova-plugin-facebook4#870]
feature request

[ ] I'm reporting a reproducible issue with the code
[ x ] I'm reporting a feature request

When I try to authenticate with Facebook, this alert appears every time I try to log in. I fear that the appstore will reject the application since the alert messages must be modified. I have 2 scenarios:

1- how to eliminate that alert (I have read that by downloading the facebook sdk, I am new to the use of xcode, I do not know how to do this, I am not sure which version I should download it)

2- how to change the alert message?.

Thanks a lot.
![uA9O6](https://user-images.githubusercontent.com/1949889/81239764-57a84500-8fcb-11ea-8e8d-82955c4202b3.png)

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect.

This is a standard dialog that is part of the Facebook Login flow.
