### ISSUE TITLE
get acces_token for send in my personnal login 

### ISSUE THREAD

**Issue by CedLP** [jeduan/cordova-plugin-facebook4#874]
Hello, i try to get access_token with ionic but i can't i have nothing 

Facebook.login(['email', 'public_profile']).then((response: FacebookLoginResponse) => {
      console.log(response);
      this.fbk.api('me?fields=id,name,email,first_name,picture.width(720).height(720).as(picture_large)', []).then(profile => {
        console.log('uciu', profile);
      });
    });

i use this, how can i get access_token please ? 
I received token when dialogue is open but when dialog is close i can't receive token, someone can help me how to received token after dialog is close ?

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect.

Your syntax doesn't look correct for using the Ionic wrapper. See the docs at https://ionicframework.com/docs/native/facebook.
