### ISSUE TITLE
cordova-plugin-facebook4 issue with UIWebView

### ISSUE THREAD

**Issue by RaghavCoddle** [jeduan/cordova-plugin-facebook4#875]
I am getting again rejection from the app store.

Which version of cordova-plugin-facebook4 should I use in my ionic project?

I see I have used latest version as well by seems like it will still have some reference UIWebView

/Plugins/cordova-plugin-facebook4/Bolts.framework/Bolts
/Plugins/cordova-plugin-facebook4/Bolts.framework/Headers/BFWebViewAppLinkResolver.h
/Plugins/cordova-plugin-facebook4/FBSDKCoreKit.framework/FBSDKCoreKit
/Plugins/cordova-plugin-facebook4/FBSDKCoreKit.framework/Headers/FBSDKWebViewAppLinkResolver.h
/Plugins/cordova-plugin-facebook4/FBSDKLoginKit.framework/Headers/FBSDKLoginManager.h
/Plugins/cordova-plugin-facebook4/FBSDKShareKit.framework/Headers/FBSDKShareDialogMode.h

**Comment by marieptremblay31** [comment]
I'm having the same issue. I currently have to push a bunch of new apps into production with facebook disabled since Itunes Connect rejects this plugin using UIWebView.

It seems that there is no release yet that officially fixes the facebook SDK version (should be 5.5, which removes all traces of UIWebKit). 

Should we expect one eventually ?

**Comment by assertdesignuk** [comment]
You can fork the plugin and replace the frameworks with the WKWebView ones.

It requires some mods to the *.m file but works fine afterwards.

**Comment by assertdesignuk** [comment]
Here is a link to my fork, you can use this until this plugin is updated:
https://www.npmjs.com/package/ee-cordova-plugin-facebook4

It includes FB SDK 5.5 and modified files which have been updated to work with 5.5. Also removed Bolts Framework as it was removed 5.5.

Use version 4.0.0

<plugin name="ee-cordova-plugin-facebook4" spec="^4.0.0">
        <variable name="APP_ID" value="" />
        <variable name="APP_NAME" value="" />
        <variable name="ANDROID_SDK_VERSION" value="4.+" />
    </plugin>

**Comment by assertdesignuk** [comment]
Here is a link to my fork, you can use this until this plugin is updated:
https://www.npmjs.com/package/ee-cordova-plugin-facebook4

It includes FB SDK 5.5 and the modified files which have been updated to work with SDK 5.5. 

Also removed Bolts Framework as it was removed in SDK 5.5.

Use version 4.0.1

**Comment by AbdullaevTimur** [comment]
When I try to install your plugin version, NPM ask me new variable and throw error: Variable(s) missing (use: --variable APP_URL_SUFFIX=value). What is this?

**Comment by assertdesignuk** [comment]
That would be your deeplink or custom url. I.e.

mylink://

If you don’t use custom url scheme in your app simply use anything like above.

**Comment by RaghavCoddle** [comment]
> When I try to install your plugin version, NPM ask me new variable and throw error: Variable(s) missing (use: --variable APP_URL_SUFFIX=value). What is this?

**Comment by RaghavCoddle** [comment]
> When I try to install your plugin version, NPM ask me new variable and throw error: Variable(s) missing (use: --variable APP_URL_SUFFIX=value). What is this?

I think you are missing CFBundleURLSchemes under CFBundleURLTypes in your info.plist.

Add this in your config.xml and then build ios 
    <plugin name="cordova-plugin-facebook4">
        <variable name="APP_ID" value="" />
        <variable name="APP_NAME" value="" />
    </plugin>

**Comment by RaghavCoddle** [comment]
> When I try to install your plugin version, NPM ask me new variable and throw error: Variable(s) missing (use: --variable APP_URL_SUFFIX=value). What is this?

This is because you don't have CFBundleURLSchemes in your infor.plist files. Add APP_ID and APP_NAME in your config.xml for cordova-plugin-facebook4 and then build ios.

**Comment by assertdesignuk** [comment]
I have all 3 variables in my config.xml

The reason I added the suffix variable was because I needed the plugin to be compatible with Facebook apps for multiple apps rather than creating a Facebook app for each app.

**Comment by marieptremblay31** [comment]
@RaghavCoddle I think you should reopen this issue. 
The problem is still persistent within the plugin since the only fix requires a fork or manual edit of files of the project.
Apple will reject all apps (new or updated) as of december 2020 so more people will complain about this issue. I think they should not have to reopen an issue each time.

This problem will not resolved until this plugin is updated to FB SDK 5.5.

**Comment by assertdesignuk** [comment]
> @RaghavCoddle I think you should reopen this issue.
> The problem is still persistent within the plugin since the only fix requires a fork or manual edit of files of the project.
> Apple will reject all apps (new or updated) as of december 2020 so more people will complain about this issue. I think they should not have to reopen an issue each time.
> 
> This problem will not resolved until this plugin is updated to FB SDK 5.5.

Correct my fork is just to help people get by until the original developer update the plugin.

**Comment by dev3inv** [comment]
Hi @assertdesignuk, could you please help me apply the fork that you apply. Since I have the same problem.

**Comment by nieok** [comment]
@assertdesignuk i am using your version. thank you. but wheni want to upload to the store. i gt the following from apple. 

> The following URL schemes found in your app are not in the correct format: [fb707225786717723boxedandgo://]. URL schemes need to begin with an alphabetic character, and be comprised of alphanumeric characters, the period, the hyphen or the plus sign only. Please see RFC1738 for more detail.

i used boxedandgo:// as urlprefix. 

any advice?

**Comment by assertdesignuk** [comment]
Hi

Remove The colon and slashes.

Just need the text part.

**Comment by nieok** [comment]
perfect, thank you 👍😊

**Comment by kenw232** [comment]
I can't get this fork to work.  I add it to my Ionic 3 project and compile and submit to Apple but Apple always rejects with "ITMS-90809: Deprecated API Usage".  

When will the original plugin be updated?  Or what exactly has to be changed to make this get accepted by Apple?

**Comment by assertdesignuk** [comment]
It may be another plugin. I am using this and the Apple message disappeared.

What other plugins are you using?

**Comment by kenw232** [comment]
> 
> It may be another plugin. I am using this and the Apple message disappeared. What other plugins are you using?

I cannot get it to work.  When I remove the plugin Apple accepts my app fine.  So either the fork does not work or I'm implementing it wrong.    I don't know where to turn for help, I'm a bit of an amateur at these custom forks.

**Comment by assertdesignuk** [comment]
Are you sure your using the fork in your config? Please post your config.xml here.

**Comment by EmreAkkoc** [comment]
so on my multi-platform app, clients won't be able to login into their existing account on ios? Cordova is almost done apparently

**Comment by saperlipopette45** [comment]
@assertdesignuk , is there a specific thing to do after installing your package ? Here is my config.xml : 

`<plugin name="cordova-plugin-facebook4" spec="^6.4.0">
        <variable name="APP_ID" value="2822918717758609" />
        <variable name="APP_NAME" value="Chrono blue" />
        <variable name="FACEBOOK_HYBRID_APP_EVENTS" value="false" />
        <variable name="FACEBOOK_ANDROID_SDK_VERSION" value="5.13.0" />
    </plugin>`

**Comment by assertdesignuk** [comment]
These are the variables:

```
<plugin name="ee-cordova-plugin-facebook4" spec="^4.0.1">
        <variable name="APP_URL_SUFFIX" value="DEEPLINK SUFFIX" />
        <variable name="APP_ID" value="APP_ID" />
        <variable name="APP_NAME" value="APP_NAME" />
        <variable name="ANDROID_SDK_VERSION" value="4.+" />
</plugin>
```

APP_URL_SUFFIX was an additional variable I added to the plugin to allow multiple apps to use the same FB app. Its basically your deeplink i.e. myapp://.

**Comment by eryzerz** [comment]
> Here is a link to my fork, you can use this until this plugin is updated:
> https://www.npmjs.com/package/ee-cordova-plugin-facebook4
> 
> It includes FB SDK 5.5 and the modified files which have been updated to work with SDK 5.5.
> 
> Also removed Bolts Framework as it was removed in SDK 5.5.
> 
> Use version 4.0.1

Didn't work. The app stuck on splash screen. I already installed the plugin correctly, the plugin tag for ee-cordova-plugin-facebook4 is in my config.xml and also inside package.json within plugin object. I'm using cordova-ios 5.1.1.

I get this error that catches my attention while running on simulator in xcode
`Task <0B379656-E74C-41A3-9BA0-677D37B54520>.<1> finished with error [-1001] Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x600001fa2af0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://graph.facebook.com/v3.2/2133605310204776?advertiser_id=00000000-0000-0000-0000-000000000000&fields=app_events_feature_bitmask,name,default_share_mode,ios_dialog_configs,ios_sdk_dialog_flows.os_version(13.2.2),ios_sdk_error_categories,supports_implicit_sdk_logging,gdpv4_nux_enabled,gdpv4_nux_content,ios_supports_native_proxy_auth_flow,ios_supports_system_auth,app_events_session_timeout,logging_token,auto_event_mapping_ios,auto_event_setup_enabled,sdk_update_message&format=json&include_headers=false&sdk=ios, NSErrorFailingURLKey=https://graph.facebook.com/v3.2/2133605310204776?advertiser_id=00000000-0000-0000-0000-000000000000&fields=app_events_feature_bitmask,name,default_share_mode,ios_dialog_configs,ios_sdk_dialog_flows.os_version(13.2.2),ios_sdk_error_categories,supports_implicit_sdk_logging,gdpv4_nux_enabled,gdpv4_nux_content,ios_supports_native_proxy_auth_flow,ios_supports_system_auth,app_events_session_timeout,logging_token,auto_event_mapping_ios,auto_event_setup_enabled,sdk_update_message&format=json&include_headers=false&sdk=ios, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.}`

Any thought?

**Comment by saperlipopette45** [comment]
Thanks @assertdesignuk  !! That solves the issue on iOS, but that makes the app crash on Android. The build performs well, but when launching the app, the app instantly stops...

**Comment by Ultima2876** [comment]
@assertdesignuk is it possible to get a PR for your fork, or a link to a repo? I want to make a fork with this and https://github.com/jeduan/cordova-plugin-facebook4/pull/860 as a base.

**Comment by jonasmedeiros** [comment]
@saperlipopette45 I will try today to get rid off the apple message, but for your issue in Android you can use Plugman

**Comment by rolinger** [comment]
@assertdesignuk - running into this today with a new app.  The fork listed above shows spec=4.0.1, but current facebook4 spec is 6.4.0 - why the discrepancy?  Gonna give this a shot, if no worky then I am going to rip FB out of app for now.  Will post results.

**Comment by rolinger** [comment]
@assertdesignuk - well, it installed without a single issue.  Nice job - thanks for forking this and doing the leg work.  Searched all my plugins for `UIWebView` and only find references in the README files, so I hope I am ok.  About to submit app again.  Will post results.

**Comment by taisatk** [comment]
> 
> 
> Here is a link to my fork, you can use this until this plugin is updated:
> https://www.npmjs.com/package/ee-cordova-plugin-facebook4
> 
> It includes FB SDK 5.5 and the modified files which have been updated to work with SDK 5.5.
> 
> Also removed Bolts Framework as it was removed in SDK 5.5.
> 
> Use version 4.0.1

I'm using Ionic v3 and this fork worked like a charm (no more rejection message from Apple because of UIWebView). Thank you very much, @assertdesignuk ! I'm using version 4.0.2 along with cordova-ios@5.1.1

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect. That plugin uses v8 of the Facebook SDK, and there are no references to UIWebView.

**Comment by winstonab** [comment]
@assertdesignuk I am using ionicv3 and I have install the fork, but when it back from facebook, nothing happen(i.e. cannot get the FacebookLoginResponse) and the facebook login screen is not closed. And I found it call the deeplink function with xxx://authorize#blahblahblah, how can I solve this? Thanks.
