### ISSUE TITLE
Compatibility Facebook SDK v7

### ISSUE THREAD

**Issue by eun-choi** [jeduan/cordova-plugin-facebook4#878]
Facebook has released SDK(a.k.a Graph API) v6 from Feb and v7 from May.

In this regard, currently using APIs that have been deprecated since v6

Could you have a compatibility update plan?

**Comment by orl99** [comment]
I also need this please

**Comment by orl99** [comment]
Any news about this? we need more contributors to capacitor :(

**Comment by vvarda** [comment]
The same. Got the alert:

**Version Deprecation**
_Your App, currently has access to **Graph API v3.0** which will reach the end of its 2-year lifetime on 28 July, 2020. To ensure a smooth transition, please migrate all calls to **Graph API v3.1 or higher**. Use the API Upgrade Tool to understand exactly how this change will impact your app.

Note: If you do not see any impacted calls in the API Upgrade Tool, your app/code may not be affected by this upgrade._

**Comment by fishgrind** [comment]
I did this, set my API version to v4 for App Roles, tested everything with my App role login user. Everything worked so also set it for "Upgrade all calls"

I think this is all we need to do as the latest version of the plugin ships with SDK v 5.13.0 for both android and ios

I guess now we wait until 28 July 😏

 https://stackoverflow.com/questions/38411972/how-to-update-upgrade-a-facebook-app-api-version-on-facebooks-developers-panel/46228825

**Comment by Nilay-git** [comment]
Hello, as of today the latest SDKs are 7.1.0(Android) and 8.0.0(iOS)..

I was able to update the Android SDK from 5.15.0 to 7.1.0 by following the documentation, and it's working.

```
ionic cordova plugin rm cordova-plugin-facebook4 --save --variable APP_ID=<MY_APP_ID> --variable APP_NAME=<MY_APP_NAME>
ionic cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="<MY_APP_ID> --variable APP_NAME=<MY_APP_NAME> --variable FACEBOOK_ANDROID_SDK_VERSION="7.1.0"
```


But still unable to update the iOS SDK. I tried the following steps:

 - Removed iOS platform from the project

 - Update `podspec` in /plugins/cordova-plugin-facebook4/plugin.xml as follows:

```
<podspec>
     <config>
         <source url="https://cdn.cocoapods.org/"/>
     </config>
     <pods use-frameworks="true">
         <pod name="FBSDKCoreKit" spec="8.0.0"/>
         <pod name="FBSDKLoginKit" spec="8.0.0"/>
         <pod name="FBSDKShareKit" spec="8.0.0"/>
     </pods>
</podspec>
```

 - Then added ios platform and build.

But I got the following error:

```
    ** BUILD FAILED **


The following build commands failed:
        CompileC /Users/<USER>/Library/Developer/Xcode/DerivedData/<APP>/Build/Intermediates.noindex/<APP.build>/Debug-iphonesimulator/<APP.build>/Objects-normal/x86_64/FacebookConnectPlugin.o /Users/path/to/project/platforms/ios/<APP>/Plugins/cordova-plugin-facebook4/FacebookConnectPlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65
[ERROR] An error occurred while running subprocess cordova.
```


Any idea how can I update the iOS SDK?


I am using:
Cordova - 10.0.0
cordova-ios@^6.1.0

**Comment by rgustavsson** [comment]
I'll pay $500 to anyone that upgrades this plugin to the latest FB SDK within 3 weeks.

**Comment by orl99** [comment]
> I'll pay $500 to anyone that upgrades this plugin to the latest FB SDK within 3 weeks.

Is someone interested?

**Comment by rgustavsson** [comment]
@orl99 was that question to me of everyone else? :) No one has show interest yet :(

**Comment by orl99** [comment]
@rgustavsson I would like to add it to the plugging, but I am not an expert in that technology, at least I can try to do the integration and do a Pull request, @rgustavsson do you know some Java and objective-c?

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect`, which defaults to the most recent version of the Facebook SDK:

https://www.npmjs.com/package/cordova-plugin-facebook-connect
