### ISSUE TITLE
Cordova app closes after displaying Facebook login screen

### ISSUE THREAD

**Issue by arevoly** [jeduan/cordova-plugin-facebook4#879]
Bug description:

After using the login method, the Facebook login window pops up, I click "Continue as USER", and nothing happens, the remote debugger window in Chrome disconnects. 

I added the plugin correctly with APP_ID as it described in the documentation.
It worked earlier with previous Android platform (6.0.0) and cordova.plugin.facebook4 (4.2.1) versions, even I could make a post after a successful login.
The facebook developer profile is in development mode, and I provided with the correct hashes.

facebookConnectPlugin.login(["public_profile"], fbLoginSuccess,
					function loginError (error) {
						console.error(error)
					}
				);

Cordova Android 7.0.0 platform
cordova-plugin-facebook4 6.4.0 version

Thanks,
arevoly

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect.

It's hard to tell without more reproduction steps, and more detail on what your fbLoginSuccess function does, but your login call looks correct. If you use cordova-plugin-facebook-connect and still run into this issue, feel free to log a new issue there with more info.
