### ISSUE TITLE
Get invited friends Id in App Invites callback?

### ISSUE THREAD

**Issue by bboyjeans** [jeduan/cordova-plugin-facebook4#88]
Hi, is it possible to get invited friends' Ids in the callback, so that I can store them somewhere for later use? Currently it only returnes 'Completed' status in the callback.

**Comment by Hirbod** [comment]
Facebook changed it when I remember correctly. They don't provide it anymore

**Comment by bboyjeans** [comment]
@Hirbod  Ah that's a bit lame. Do you know by any chance since which SDK version it got removed?
