### ISSUE TITLE
On FB Dialog Login Screen

### ISSUE THREAD

**Issue by sunerandgarcia** [jeduan/cordova-plugin-facebook4#881]
When you press done button there is a dialogue box that comes up instead of logging in or cancelling the dialogue. Has anyone had something similar to this? 

[ApplicationLifecycle] UIWindows were created prior to initial application activation. This may result in incorrect visual appearance.

**Comment by tetkosimi** [comment]
I have similar behavior issues with the cordova-plugin-inappbrowser@4.0.0

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out the actively maintained fork `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect. I can't reproduce the issue you're describing.

**Comment by igloriousz** [comment]
> This plugin is deprecated. Check out the actively maintained fork `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect. I can't reproduce the issue you're describing.

+9999999
