### ISSUE TITLE
Error: Unable to merge dex 

### ISSUE THREAD

**Issue by ayubUOL** [jeduan/cordova-plugin-facebook4#884]
**While making android build I'm facing this error** 
Facebook plugin version is 6.4.0
Facebook SDK version 4.36

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

BUILD FAILED in 1m 2s
[ERROR] An error occurred while running subprocess cordova.

**Ionic Info**
Ionic:

   Ionic CLI          : 5.4.16 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.7

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 7.1.4
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 25 other plugins)

Utility:

   cordova-res (update available: 0.15.1) : 0.6.0
   native-run (update available: 1.0.0)   : 0.2.7

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v10.16.0 (/usr/local/bin/node)
   npm        : 6.9.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61

I tried 
> cordova clean android 

but didn't worked for me. I tried without specifying facebook SDK version but still facing same error.

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out the actively maintained fork `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect. I don't experience this Android build error with that plugin, but if you are still running into issues, feel free to open a new issue there.
