### ISSUE TITLE
Got error on facebook/index.js file on login

### ISSUE THREAD

**Issue by ahmedfarag2010** [jeduan/cordova-plugin-facebook4#888]
Just got this error after call the function
**Uncaught TypeError: Object(...) is not a function at index.js:465**

**Comment by noahcooper** [comment]
I'm not sure this error is actually related to this plugin. It does not expose any file named index.js. I'm guessing this is an Ionic issue. Perhaps this is your issue:

https://stackoverflow.com/questions/56076245/object-is-not-a-function-ionic-3-facebook-login

Either way, this plugin is deprecated. Going forward, check out https://www.npmjs.com/package/cordova-plugin-facebook-connect. (The Ionic wrapper has just been updated in https://github.com/ionic-team/ionic-native/pull/3603.)
