### ISSUE TITLE
Facebook Login Suddenly Fails on Oct 1st - Permission Error

### ISSUE THREAD

**Issue by Akz47** [jeduan/cordova-plugin-facebook4#889]
Facebook login suddenly started failing today (Oct 1st 2020).

When calling the facebookConnectPlugin.login, it keeps returning this error:
**"Facebook error: Caught exception: (#200) Missing Permissions"**

It has been working fine all the while, and our app is authorized for those permissions. This is the code used:

```
    facebookConnectPlugin.login(["email","public_profile","user_birthday","user_location"], 
        function(response) {
            // do something
        },
        function(err) {
            console.log(err);
        }
    );

```

We tried completely removing all the permissions, or just using a single one like "email", but the same error persists. The error happens on both iOS and Android. 

We are using Cordova 9.0, cordova-plugin-facebook4 6.4.0.

Please advise ASAP as users are not able to login to our apps since today. Thank you.

**Comment by ttthub** [comment]
Hi,
I can confirm my app is also failing, I am using "public_profile", "email", "user_friends" and we have approval for user_friends since a very long time. Will update here if we are able to find a workaround using other permissions.

**Comment by Akz47** [comment]
We have tried removing all the permissions, or using a single one like "email", but it still fails. I wonder if it is due to Facebook SDK / API changes.

**Comment by ttthub** [comment]
https://twitter.com/search?q=facebook%20login%20&src=typed_query&f=live

Its failing for a LOT of apps (maybe all of them). FB seems to have broken something.

**Comment by Akz47** [comment]
Thanks, that is very helpful knowing that it is FB that is completely screwed and not just our apps.

We have been repeatedly trying the login again, and it seems that it works some of the time and fails on others. I think it is due to their server outages.
