### ISSUE TITLE
How about a support for phonegap build?

### ISSUE THREAD

**Issue by thedarkman123** [jeduan/cordova-plugin-facebook4#89]
Is it now possible to add this plugin to the phonegap build repository since they use gradle builds now?

**Comment by jeduan** [comment]
Don't know, it's possible. Would you test it and report back results on a PR?

**Comment by MaicolBen** [comment]
@jeduan @thedarkman123 I checked and it works without the app installed, but with the app installed shows me this error: "User logged in as different Facebook user".

**Comment by Dineshrajaa** [comment]
http://phonegap.com/blog/2015/09/28/android-using-gradle
Since Phonegap build is supporting gradle kindly help us to configure this plugin in build service.

**Comment by jeduan** [comment]
@Dineshrajaa I don't support PG Build, if you manage to get it working please do contribute back.

**Comment by Dineshrajaa** [comment]
ok sure @jeduan will give it a try and thanks for the plugin :)

**Comment by MaicolBen** [comment]
@Dineshrajaa I can get it work, you have to add to the config.xml:
      
     <preference name="android-minSdkVersion" value="15" />
     <preference name="android-build-tool" value="gradle" />
     <gap:plugin name="cordova-plugin-facebook4" source="npm" version="1.4.0">
        <param name="APP_ID" value="1234" />
        <param name="APP_NAME" value="MyApp" />
     </gap:plugin>

**Comment by Dineshrajaa** [comment]
Thank you @MaicolBen :)
