### ISSUE TITLE
Facebook login is not redirecting back to app when you facebook app installed

### ISSUE THREAD

**Issue by RaghavCoddle** [jeduan/cordova-plugin-facebook4#890]
When I click on social login, it is redirecting to in app web and asking login with facebook App. But when I authenticate using facebook app again redirecting to same screen and its not navigating back to my app. 

I am stuck on this screen, again if click on login with facebook App same thing happens. I am not able to login with facebook when I have facebook native app installed. 
![Screenshot 2020-10-16 at 2 04 05 PM](https://user-images.githubusercontent.com/34889816/96235454-75d19280-0fb8-11eb-93f6-5fcfd6097c18.png)

**Comment by shide1989** [comment]
Same issue here.-> `"cordova-plugin-facebook4": "^6.4.0",`

**Comment by YkkJeff** [comment]
I have the same issue on my app... that's a real problem for our customers, I hope this will be fixed soon :(

**Comment by shide1989** [comment]
@RaghavCoddle did you find any solution yet ?

**Comment by shide1989** [comment]
@RaghavCoddle and for all those having the issue on iOS14/13, we seem to have found a solution :
add the following lines in your AppDelegate.swift :
```
import FBSDKCoreKit
...


    func application(_ application: UIApplication,
                     didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data ,
                     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        ...
        ApplicationDelegate.shared.application( application, didFinishLaunchingWithOptions: launchOptions )
        return true
...

    func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
        // Called when the app was launched with a url. Feel free to add additional processing here,
        // but if you want the App API to support tracking app url opens, make sure to keep this call
         ApplicationDelegate.shared.application( app, open: url, sourceApplication: options[UIApplication.OpenURLOptionsKey.sourceApplication] as? String, annotation: options[UIApplication.OpenURLOptionsKey.annotation] )
        return CAPBridge.handleOpenUrl(url, options)
    }
```

Reference : Step 5 from https://developers.facebook.com/docs/facebook-login/ios/


This should be mentionned in the README.md or elsewhere as a reference for those struggling on this @peterpeterparker @jeduan @Hirbod

**Comment by RaghavCoddle** [comment]
> @RaghavCoddle and for all those having the issue on iOS14/13, we seem to have found a solution :
> add the following lines in your AppDelegate.swift :
> 
> ```
> import FBSDKCoreKit
> ...
> 
> 
>     func application(_ application: UIApplication,
>                      didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data ,
>                      didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
>         ...
>         ApplicationDelegate.shared.application( application, didFinishLaunchingWithOptions: launchOptions )
>         return true
> ...
> 
>     func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
>         // Called when the app was launched with a url. Feel free to add additional processing here,
>         // but if you want the App API to support tracking app url opens, make sure to keep this call
>          ApplicationDelegate.shared.application( app, open: url, sourceApplication: options[UIApplication.OpenURLOptionsKey.sourceApplication] as? String, annotation: options[UIApplication.OpenURLOptionsKey.annotation] )
>         return CAPBridge.handleOpenUrl(url, options)
>     }
> ```
> 
> Reference : Step 5 from https://developers.facebook.com/docs/facebook-login/ios/
> 
> This should be mentionned in the iOS setup README.md (https://github.com/jeduan/cordova-plugin-facebook4/blob/master/docs/ios/README.md) or elsewhere as a reference for those struggling on this @peterpeterparker @jeduan @Hirbod

@shide1989 great. It's working for me.
