### ISSUE TITLE
unable to upgrade to FB SDK (iOS) 8.1.0

### ISSUE THREAD

**Issue by Zvika88** [jeduan/cordova-plugin-facebook4#892]
Trying to mitigate FB's warnings about out of date SDK , I tried updating the pod reference from the previous (working!) 5.7.0 to the latest 8.1.0 for FBSDKCoreKit, FBSDKLoginKit, FBSDKShareKit.

I am getting a bunch of errors in XCode when trying to build the app:

What needs to be done in order to update the SDK?
What is the latest supported SDK?

Thanks!

![Screen Shot 2020-11-10 at 2 56 12 AM](https://user-images.githubusercontent.com/6226058/98665573-b6df6d00-2300-11eb-9a8d-b26462a9202d.png)

**Comment by 6ewis** [comment]
@Zvika88 did you manage to fix it? were you able to update to the latest version?

**Comment by S-Asakoto** [comment]
Faced with the same problem, but reimporting FB SDK version 5.15.1 solved the problem. This seems to be due to that FB removed these classes as obsolete in version 6 onwards, while the plugin is still using these classes. Since the versions 6 to 8 published within just a year, the author could have not noticed that. (At least version 5.15.1 was published in Jan 2020)

**Comment by rgustavsson** [comment]
Obviously the latest supported SDK for this plugin is 5.X
It would be awesome if someone could manage to upgrade to the latest Facebook SDK. I might even pay you ;)

**Comment by rgustavsson** [comment]
I'll pay $500 to anyone that upgrades within 3 weeks.

**Comment by pellaras** [comment]
> 
> 
> I'll pay $500 to anyone that upgrades within 3 weeks.

@rgustavsson: Here you go: https://github.com/pellaras/cordova-plugin-facebook4

Please pay [here](https://www.redcross.org.cy/en/make-a-donation/donation-form). ;)

**Comment by rgustavsson** [comment]
@pellaras good news!
I'll test it asap :) May I ask for a clarification around the commented out code in the iOS upgrade? (FacebookConnectPlugin.m)
Do you know when "share_open_graph" is used/needed?

**Comment by pellaras** [comment]
Hi @rgustavsson, not sure, but seems to be a depreciated feature:
https://developers.facebook.com/community/threads/428042001393940/

xcode was complaining about that portion, and the facebook sdk change logs shows them as been [removed](https://github.com/facebook/facebook-ios-sdk/blob/master/CHANGELOG.md#600)

**Comment by rgustavsson** [comment]
@pellaras ah, thank you.
So we should basically make sure that:
- I test it
- Then we merge your fork into this repo since this repo is communicated everywhere.

May I ask if you use this plugin in any project?

**Comment by pellaras** [comment]
@rgustavsson 

This repo is no longer maintained, so merging it will prove challenging

Quite a few, but to be fair, mostly for analytics.

**Comment by rgustavsson** [comment]
@pellaras True!

@jeduan I'd be happy to take ownership so that this plugin stays up to date. It would be a pitty to work on different forks.

**Comment by daksamedia** [comment]
Hi @pellaras 

is this repo still under your maintain?
https://github.com/pellaras/cordova-plugin-facebook4

I see that repo updated 2 days ago.
I'm glad if you answer me.

Thank you

**Comment by rgustavsson** [comment]
@daksamedia please follow our discussion above, we're discussing ownership/maintenance. It would be stupid not to try to align this repo with the latest development

**Comment by daksamedia** [comment]
> @daksamedia please follow our discussion above, we're discussing ownership/maintenance. It would be stupid not to try to align this repo with the latest development

I see, I'd be happy if you or anyone else take this ownership / maintenance, 'cause this is one of important plugin in Cordova. Thank you for answering me.

**Comment by pellaras** [comment]
Hi @daksamedia, that's my fork and only has a few changes needed for the apps I am involved with.
I wouldn't say it's actively maintained.

**Comment by noahcooper** [comment]
FYI - I've created https://github.com/cordova-plugin-facebook-connect/cordova-plugin-facebook-connect and will be working on updating it to the most recent version of the Facebook SDK.

**Comment by rgustavsson** [comment]
Everyones going to have their own fork.. Why not collaborate??

**Comment by rgustavsson** [comment]
@jeduan seems to have abandoned the ship without wanting to transfer ownership 😞

**Comment by jeduan** [comment]
@rgustavsson friendly reminder that I don’t owe you anything.  Your comment comes off as extremely entitled. 
maintainer burnout from handling entitled GitHub posters is the main reason me and other folks have stopped working on this and other open source projects. 
Be better.

**Comment by rgustavsson** [comment]
@jeduan if you take the responsibility to own/maintain an open source repo then you also take the responsibility to answers requests - especially requests about helping out. I’ve tried to reach you here and via LinkedIn without any luck. I won’t apologize as I believe you can handle things better.

**Comment by jeduan** [comment]
@rgustavsson take that energy and put it in your own (open source or otherwise) projects.

**Comment by noahcooper** [comment]
This issue is fixed in the new plugin `cordova-plugin-facebook-connect`!

https://www.npmjs.com/package/cordova-plugin-facebook-connect
