### ISSUE TITLE
IOS facebook sdk 5.15.0 is deprecated

### ISSUE THREAD

**Issue by eidanfi** [jeduan/cordova-plugin-facebook4#893]
Hi, when i edit the FBSDKCoreKit, FBSDKLoginKit FBSDKShareKit version on plugin.xml, to newer version because current version is deprecated, the app not success build, How i can upgrade the IOS sdk through the plugin ?

![image](https://user-images.githubusercontent.com/18303572/107145400-de6ac380-6949-11eb-887a-129acfa907d8.png)

**Comment by eidanfi** [comment]
it was my mistake with the version

**Comment by reesz** [comment]
@eidanfi can you please share what your working solution was?
