### ISSUE TITLE
Failed to install 'cordova-plugin-facebook4': Error: pod: Command failed with exit code 1

### ISSUE THREAD

**Issue by Ashu-Akeo** [jeduan/cordova-plugin-facebook4#895]
**Describe the Bug of feature request**

Getting Error **"Failed to install 'cordova-plugin-facebook4': Error: pod: Command failed with exit code 1**" when running command **"cordova platform add ios"**

**Expected Behavior**

It should run.

**Plugin version, OS, devices, etc**

Please provide information about the plugin version, OS, devices etc. where you faced your issue
Plugin version = 6.4.0
OS = Mac Catalina 10.15.7
devices = iPhone 14.4

![image](https://user-images.githubusercontent.com/86477859/123432024-8e825580-d5e7-11eb-9023-95343fe0c961.png)

**Comment by AsoStrife** [comment]
I'm having the same issue. Did you solve?

**Comment by AsoStrife** [comment]
I think I solved using this: https://stackoverflow.com/questions/64901180/running-cocoapods-on-apple-silicon-m1/65334677#65334677

Just run: 

```
sudo arch -x86_64 gem install ffi
arch -x86_64 pod install
```

**Comment by noahcooper** [comment]
This plugin is deprecated. Check out the actively maintained `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect.
