### ISSUE TITLE
There was a problem logging you in

### ISSUE THREAD

**Issue by mabdelfattah** [jeduan/cordova-plugin-facebook4#91]
The app works fine in Android but not iOS, when I try to sign it opens the browser, I login to my FB, then I back to the app again but the plugin raise error "There was an problem logging you in"!

This is the returning response:

> fb1489932567959922://authorize/#state={"challenge":"9KKgFjEz7qmg2CoXgiT\/Wh2W5o8=","0_auth_logger_id":"7D8FB3CD-A356-422A-A565-2EF9E3163368","com.facebook.sdk_client_state":true,"3_method":1}&granted_scopes=user_friends,email,contact_email,publish_actions,public_profile&denied_scopes=&signed_request=REQUEST&access_token=TOKEN&expires_in=5181419&e2e={"init":1448364596451}

**Comment by mabdelfattah** [comment]
That happen because I more permissions in this release than the previous one, if I deleted the app, and re-installed it, everything works fine... But how can I handle this with the users who currently have the app? it is really hard to ask them to remove the app and re-install it!

**Comment by mabdelfattah** [comment]
I did a fix and it worked on my end, here's the pull request for it https://github.com/jeduan/cordova-plugin-facebook4/pull/92

**Comment by Hirbod** [comment]
I have the same problem, but I did not change the permissions @jeduan. I just upgraded from plugin version 1.3.1 to 1.4.1 and now, it opens SFSafariView, returns and spits something to the console, nut nothing happens anymore?

**Comment by Hirbod** [comment]
@jeduan after deleting the app, it works as intended, but this is a bug. I can't force my users to delete the app before they update. What can we do?
