### ISSUE TITLE
This app has no Android Key hashes configured.

### ISSUE THREAD

**Issue by nowitz** [jeduan/cordova-plugin-facebook4#93]
I have problem about login with facebook acount in my application. I read to Facebook Doc. And I did all step as Facebook Doc.

First in login with facebook acount in app - SUCCESSFUL ! (first connection, when the facebook account never Authorized application). I want to login again with my facebook acount. But not working !! And I took this Excepiton ! Please help me !

Exception : This app has no Android Key hashes configured.Configure your app key hashes at http:developers.facebook.com/apps/"APP ID"

**Comment by jeduan** [comment]
Configure your application correctly.

**Comment by porridj** [comment]
Hey up,
I'm having this trouble too, it's the creating the hash etc that I can't figure out, I used the keytool like everyone else said, but to no avail, if you could provide a link or something to explain how to set up the application properly that would be awesome, I've tried a number of things so far and none have worked, however I am new to all this so it's probably stuff that's obvious to someone. Any help welcomed! :D

**Comment by HasiniWijerathna** [comment]
If this occurs even after configuring the generated key hash in developer settings correctly just check the   "APP_ID" in installed cordova plugin in package.json file
