### ISSUE TITLE
Failed to execute the application (Android with cordova-plugin-facebook4 )

### ISSUE THREAD

**Issue by MarceMtz** [jeduan/cordova-plugin-facebook4#95]
Hi!
I tried to use the plugin provided for use with android. When building the project, add the plugin and build the project did not make any error. However, the run does not work any method. Try to import the project into eclipse to do a debug of the application on my phone, but when I import the project does not know me the library of facebook. But I do not see that somewhere the corresponding library is added.
Could you tell me if there are extra steps you need to perform?

**Comment by jeduan** [comment]
You should use Android Studio, not Eclipse which does not (that I know) support gradle, so that would be the reason for not knowing about Facebook. Usual problems with Android are not setting up key hashes/activity/bundle on Facebook Developer's page.

**Comment by jeduan** [comment]
This seems resolved, if not please reopen the issue
