### ISSUE TITLE
Android second LOGIN NO HASH CONFIGURED

### ISSUE THREAD

**Issue by balicekt** [jeduan/cordova-plugin-facebook4#96]
Hi, thanks for this awesome plugin. I'm using it some time. But today I made upgrade to last version and the guy from #93 is absolutely right. I have exactly the same problem iOS is working fine but Android is not. I made i video about this issue. You can see here where is the problem and absolutely don't understand why is this happening! 

More informations here: https://www.youtube.com/watch?v=FB0UwDM8RfM

Thanks for any comment!

**Comment by jeduan** [comment]
Wow, thanks for taking the time of making a video. Definitely baffling.
First, you did add your key hashes at the Facebook Developers page, right?
This question seems to suggest that this is a bug on Facebook's side when you have your hashes configured incorrectly. http://stackoverflow.com/a/31366704

**Comment by Hirbod** [comment]
I can confirm - this error is not caused by this plugin. I had the same problem some months ago, and the first login was fine, the 2nd not. At the end, it was the wrong hash-key. Fix it!

**Comment by balicekt** [comment]
After deeper research and thank you you comments a checked hash-keys in detail. This app is just in debug mode so I had debug key in debug key field on facebook but this debug key were missing in Settings -> Android -> Key Hashes and this made this baffling thing. So thank you your comments and I'm happy that I didn't get crazy :)

**Comment by Hirbod** [comment]
👍🏼

**Comment by vajidbwd** [comment]
Too much time taken for resolve this issue finally got solution follow the step
Step-1: Generate  SHA key 
Step-2: Now  SHA key convert into BASE64 , and converted string put on your facebook developer account application and save .
