### ISSUE TITLE
Lack of phonegap build support

### ISSUE THREAD

**Issue by ahlidap** [jeduan/cordova-plugin-facebook4#97]
As now PGB supports build with gradle, I think this can be viewed like an issue.
Many plugins (good ones) are now required to be built with gradle, and the old Facebook plugins on PGB simply don't support it.

Is this hard to implement?

**Comment by fredgalvao** [comment]
This plugin already supports gradle builds, as well as PGB. See [here](https://github.com/jeduan/cordova-plugin-facebook4/issues/89#issuecomment-160144611) for detailed (although standard) instructions if you're having problems.

**Comment by ahlidap** [comment]
Perfect!, thank you!
That info is missing on documentation, when clearly says PGB is not supported.

Thanks again.

**Comment by jeduan** [comment]
@ahlidap I'll take a PR
